Explorer/Assets/Scenes/DynamicSceneLoading.unity, Explorer/Assets/Scripts/Global/Containers.asmdef, Explorer/Assets/Scripts/Global/Dynamic/DynamicSceneLoader.cs, Explorer/Assets/Scripts/Global/Dynamic/RealmLauncher.cs, Explorer/Assets/Scripts/Global/Dynamic/RealmLauncher.cs.meta
Adds a very basic realm launcher
=> feat: realm launcher

Explorer/Assets/DCL/CharacterMotion/Systems/CalculateCharacterVelocitySystem.cs, Explorer/Assets/DCL/CharacterMotion/Systems/DropPlayerFromFreeCameraSystem.cs, Explorer/Assets/DCL/Input/UnityInputSystem/DCLInput.cs, Explorer/Assets/DCL/Input/UnityInputSystem/DCLInput.inputactions, Explorer/Assets/Scripts/CrdtEcsBridge/Engine/EngineAPIImplementation.cs, Explorer/Assets/Scripts/ECS/SceneLifeCycle/SceneFacade/Systems/LoadSceneSystemLogic.cs, Explorer/Assets/Scripts/ECS/Unity/PrimitiveRenderer/Systems/ReleaseOutdatedRenderingSystem.cs, Explorer/Assets/Scripts/Global/Dynamic/Plugins/InputPlugin.cs, Explorer/Assets/Scripts/SceneRunner/EmptyScene/EmptySceneData.cs, Explorer/Assets/Scripts/SceneRunner/Scene/ISceneContent.cs, Explorer/Assets/Scripts/SceneRunner/Scene/ISceneContent.cs.meta, Explorer/Assets/Scripts/SceneRunner/Scene/ISceneData.cs, Explorer/Assets/Scripts/SceneRunner/Scene/SceneData.cs, Explorer/Assets/Scripts/SceneRunner/Scene/SceneHashedContent.cs, Explorer/Assets/Scripts/SceneRunner/Scene/SceneHashedContent.cs.meta, Explorer/Assets/Scripts/SceneRunner/Scene/SceneNonHashedContent.cs, Explorer/Assets/Scripts/SceneRunner/Scene/SceneNonHashedContent.cs.meta, Explorer/Assets/Scripts/SceneRunner/Scene/StaticSceneMessages.cs, Explorer/Assets/Scripts/SceneRunner/Scene/StaticSceneMessages.cs.meta, Explorer/Assets/Scripts/SceneRunner/SceneFacade.cs, Explorer/Assets/Scripts/SceneRunner/SceneFactory.cs, Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/EngineApiWrapper.cs, Explorer/Assets/Scripts/SceneRuntime/ISceneRuntime.cs, Explorer/Assets/Scripts/SceneRuntime/SceneRuntimeImpl.cs, Explorer/Assets/StreamingAssets/Js/Modules/EngineApi.js
Closes #128 
* Added support for reading `main.crdt` file before launching the scene
* Its state then is propagated to the scene via `CrdtGetState`
=> feat: Add support for "main.crdt"

.gitattributes
Removes the listed file types from the auto resolve of merge conflicts
=> Fix: removed file types from auto resolve of merge conflicts

Explorer/Assets/Scripts/Global/Dynamic/DynamicSceneLoader.cs, Explorer/Assets/Scripts/Global/GameReports.cs, Explorer/Assets/Scripts/Global/GameReports.cs.meta, Explorer/Assets/Scripts/Global/Static/StaticSceneLauncher.cs, README.md
extract PrintGameIsDead into a separated class, remove code duplication
=> GameReports with PrintIsDead instead PrintGameIsDead inside launchers

Explorer/Assets/DCL/CharacterMotion/Settings/CharacterControllerSettings.asset, Explorer/Assets/DCL/CharacterMotion/Systems/FeetIKSystem.cs, Explorer/Assets/DCL/CharacterMotion/Systems/HandsIKSystem.cs, Explorer/Assets/DCL/CharacterMotion/Systems/HeadIKSystem.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/Builders/BuilderExtensions.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/Views/Assets/DebugUtilitiesStyle.uss, Explorer/Assets/Scripts/CrdtEcsBridge/Physics/PhysicsLayers.cs
=> Fix debug menu buttons & Introuduce toggles to the IK Systems

Explorer/Assets/Scripts/ECS/Prioritization/Settings/IRealmPartitionSettings.cs, Explorer/Assets/Scripts/ECS/Prioritization/Settings/RealmPartitionSettingsAsset.cs, Explorer/Assets/Scripts/ECS/SceneLifeCycle/IncreasingRadius/ResolveSceneStateByIncreasingRadiusSystem.cs, Explorer/Assets/Scripts/ECS/SceneLifeCycle/Tests/ResolveSceneStateByIncreasingRadiusSystemShould.cs
Changed unloading distance to be bound with maximum loading distance
=> Fix: unloading distance

Explorer/Assets/Scenes/DynamicSceneLoading.unity, Explorer/Assets/Scripts/Global/Dynamic/DynamicSceneLoaderSettings.asset, Explorer/Assets/StreamingAssets/Js/Init.js
- Introduce work around for missing "performance" object 
- Extend size of realms loader dropdown
=> Introduce MetadyneLabs & Add workaround for missing performance object

Explorer/Assets/DCL/PluginSystem/World/SceneUIPlugin.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Classes/TextFieldPlaceholder.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Classes/TextFieldPlaceholder.cs.meta, Explorer/Assets/DCL/SDKComponents/SceneUI/Components/UIInputComponent.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Components/UIInputComponent.cs.meta, Explorer/Assets/DCL/SDKComponents/SceneUI/Defaults/PBUiInput_Defaults.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Defaults/PBUiInput_Defaults.cs.meta, Explorer/Assets/DCL/SDKComponents/SceneUI/ScenesUIStyleSheet.uss, Explorer/Assets/DCL/SDKComponents/SceneUI/Systems/UIInput.meta, Explorer/Assets/DCL/SDKComponents/SceneUI/Systems/UIInput/UIInputInstantiationSystem.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Systems/UIInput/UIInputInstantiationSystem.cs.meta, Explorer/Assets/DCL/SDKComponents/SceneUI/Systems/UIInput/UIInputReleaseSystem.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Systems/UIInput/UIInputReleaseSystem.cs.meta, Explorer/Assets/DCL/SDKComponents/SceneUI/Tests/UIInputInstantiationSystemShould.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Tests/UIInputInstantiationSystemShould.cs.meta, Explorer/Assets/DCL/SDKComponents/SceneUI/Utils/UiElementUtils.cs, Explorer/Assets/Scripts/ECS/Unity/ColorComponent/ColorDefaults.cs, Explorer/Assets/Scripts/Global/ComponentsContainer.cs, Explorer/Assets/Scripts/ProtobufPartialClasses/IDirtyMarker.cs
- Implement **UIInput** SDK component.
- `UIInputInstantiationSystem`
- `UIInputReleaseSystem`
=> feat: UIInput component

Explorer/Assets/DCL/PluginSystem/Global/Global Plugins Settings.asset
for some reason type in Global Settings haven't been updated, here fix
=> fix Global Plugins Settings

Explorer/Assets/DCL/PluginSystem/World/SceneUIPlugin.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Classes/DCLDropdown.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Classes/DCLDropdown.cs.meta, Explorer/Assets/DCL/SDKComponents/SceneUI/Components/UIDropdownComponent.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Components/UIDropdownComponent.cs.meta, Explorer/Assets/DCL/SDKComponents/SceneUI/Defaults/PBUiDropdown_Defaults.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Defaults/PBUiDropdown_Defaults.cs.meta, Explorer/Assets/DCL/SDKComponents/SceneUI/ScenesUIStyleSheet.uss, Explorer/Assets/DCL/SDKComponents/SceneUI/Systems/UIDropdown.meta, Explorer/Assets/DCL/SDKComponents/SceneUI/Systems/UIDropdown/UIDropdownInstantiationSystem.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Systems/UIDropdown/UIDropdownInstantiationSystem.cs.meta, Explorer/Assets/DCL/SDKComponents/SceneUI/Systems/UIDropdown/UIDropdownReleaseSystem.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Systems/UIDropdown/UIDropdownReleaseSystem.cs.meta, Explorer/Assets/DCL/SDKComponents/SceneUI/Systems/UIInput/UIInputInstantiationSystem.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Systems/UIInput/UIInputReleaseSystem.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Systems/UIText/UITextInstantiationSystem.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Systems/UITransform/UITransformInstantiationSystem.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Tests/UIDropdownInstantiationSystemShould.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Tests/UIDropdownInstantiationSystemShould.cs.meta, Explorer/Assets/DCL/SDKComponents/SceneUI/Tests/UIInputInstantiationSystemShould.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Tests/UITextInstantiationSystemShould.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Tests/UITransformInstantiationSystemShould.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Utils/UiElementUtils.cs, Explorer/Assets/Scripts/Global/ComponentsContainer.cs, Explorer/Assets/Scripts/ProtobufPartialClasses/IDirtyMarker.cs
- Implement **UIDropdown** SDK component (without `UiDropdownResult`).
- Small fix in `UIInputReleaseSystem`.
- `UIDropdownInstantiationSystem`
- `UIDropdownReleaseSystem`
https://github.com/decentraland/unity-explorer/assets/64659061/71c06d28-7bb0-4496-b1a8-a16c0465eb1a
=> feat: UIDropdown SDK component

Explorer/Assets/DCL/ExplorePanel/Assets/PersistentExploreOpener.prefab, Explorer/Assets/Textures/Common/MenuIcn.png, Explorer/Assets/Textures/Common/MenuVerticalIcn.png, Explorer/Assets/Textures/Common/MenuVerticalIcn.png.meta
This PR was created to update the menu button.
=> style: menu button texture update

Explorer/.gitignore, Explorer/Assets/AddressableAssetsData/AssetGroups/Localization-Locales.asset
Added line to git ignore to remove lods
Removed localization for spanish and italian
=> Fixed Localization issues

Explorer/Assets/DCL/AvatarRendering/AvatarShape/Assets/AvatarBase.prefab, Explorer/Assets/DCL/Character/CharacterMotion/Settings/CharacterControllerSettings.asset, Explorer/Assets/DCL/Character/CharacterMotion/Settings/CharacterControllerSettings.cs, Explorer/Assets/DCL/Character/CharacterMotion/Settings/ICharacterControllerSettings.cs, Explorer/Assets/DCL/Character/CharacterMotion/Systems/FeetIKSystem.cs
Fixed leg IK Stiffnes when character is idle, knees are more relaxed now. 
Also disabled the IK Gizmos
https://github.com/decentraland/unity-explorer/assets/7646450/4c01962a-34a1-4d3f-a3f2-d2a19e066cde
https://github.com/decentraland/unity-explorer/assets/7646450/448c53e0-bc11-4804-9d79-b4c56b1ec8d9
Just stand idle :)
=> fix: IK leg positioning when idle

Explorer/Packages/manifest.json, Explorer/Packages/packages-lock.json
Adding https://github.com/brunomikoski/Animation-Sequencer for DoTween control via inspector
=> chore: add Animation Sequencer package

Explorer/Assets/Scenes/Main.unity, Explorer/Assets/Scripts/Global/Dynamic/InitialRealm.cs, Explorer/Assets/Scripts/Global/Dynamic/InitialRealm.cs.meta, Explorer/Assets/Scripts/Global/Dynamic/MainSceneLoader.cs, Explorer/Assets/Scripts/Utility/CustomPropertyDrawers.cs, Explorer/Assets/Scripts/Utility/CustomPropertyDrawers.cs.meta, Explorer/Assets/Scripts/Utility/Editor/EditorCustomPropertyDrawers.cs, Explorer/Assets/Scripts/Utility/Editor/EditorCustomPropertyDrawers.cs.meta
https://github.com/decentraland/unity-explorer/assets/7646450/31d3d836-d61e-4b79-ad99-f2d3847ffce0
=> feat: added easy setup options to go to sdk scenes

Explorer/Packages/manifest.json, Explorer/Packages/packages-lock.json
This PR was created to add the soft mask package, which enables gradual and semi-transparent masks by supporting alpha.
[Here](https://github.com/olegknyazev/SoftMask) is its Github repo.
=> chore: add soft mask package

.github/workflows/build-Windows-il2cpp.yml
- Action to auto download lod 3 assets into the build. For now, it relies on a google drive link
=> chore: auto download lod 3

.github/workflows/build-Windows-il2cpp.yml, .github/workflows/test.yml, Explorer/Packages/manifest.json, Explorer/Packages/packages-lock.json
Moved soft mask package to private repo
=> chore: update soft mask package

.github/workflows/pr-comment-artifact-url.yml
Fixes comment action for easiear QA
=> fix: comment action

Explorer/Assets/DCL/LOD/Settings/LODSettings.asset
Enables lods streaming by default
=> chore: lod streaming enabled by default

Explorer/Assets/DCL/ExplorePanel/Assets/ExplorePanelUI.prefab
Small fix for Explore Panel not allowing to use backpack.
Related to the animation to show it not playing because it could not find audio mixer
=> fix : explore panel

Explorer/Assets/DCL/Audio/AudioConfigs/Avatar_Jog_step.asset, Explorer/Assets/DCL/Audio/AudioConfigs/Avatar_Jump.asset, Explorer/Assets/DCL/Audio/AudioConfigs/Avatar_Jump_Jog.asset, Explorer/Assets/DCL/Audio/AudioConfigs/Avatar_Jump_Run.asset, Explorer/Assets/DCL/Audio/AudioConfigs/Avatar_Jump_Walk.asset, Explorer/Assets/DCL/Audio/AudioConfigs/Backpack_Emote_Click.asset, Explorer/Assets/DCL/Audio/AudioConfigs/Backpack_Emote_Hover.asset, Explorer/Assets/DCL/Audio/AudioConfigs/Backpack_Emote_UnEquip.asset, Explorer/Assets/DCL/Audio/AudioConfigs/Backpack_Hover_Item_Icon.asset, Explorer/Assets/DCL/Audio/AudioConfigs/Backpack_Wearable_Click.asset, Explorer/Assets/DCL/Audio/AudioConfigs/Backpack_Wearable_Hover.asset, Explorer/Assets/DCL/Audio/AudioConfigs/Backpack_Wearable_UnEquip.asset, Explorer/Assets/DCL/Audio/AudioConfigs/CharacterPreview_Hover.asset, Explorer/Assets/DCL/Audio/AudioConfigs/CharacterPreview_ZoomIn.asset, Explorer/Assets/DCL/Audio/AudioConfigs/CharacterPreview_ZoomOut.asset, Explorer/Assets/DCL/Audio/AudioConfigs/Generic_Tab_Selected .asset, Explorer/Assets/DCL/Audio/AudioConfigs/Menu_ExplorePanel_Open.asset, Explorer/Assets/DCL/Audio/AudioConfigs/Menu_LogIn_Background_Music.asset, Explorer/Assets/DCL/Audio/Prefabs/GeneralAudioMixer.mixer, Explorer/Assets/DCL/UI/Shaders/RadialWave.shadergraph
Updated Radial Shader to remove the error of the MainTex_
Redefined some sounds and master volume.
...
2. ...
=> Updated Radial shader and redefined sounds

.github/auto_assign_config.yml
=> chore: adding QA to auto_assign_config

Explorer/Assets/DCL/Landscape/TerrainGenerator.cs
bumped terrain cache version, it should trigger terrain regeneration
=> Chore: bumped terrain cache version

.github/workflows/test.yml, README.md
Applies this [workaround ](https://github.com/orgs/community/discussions/120966#discussioncomment-9211925)to fix tests
=> fix: Tests workaround regarding MS issue

Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/EmotePlayer.cs
Fixes [#694](https://github.com/decentraland/unity-explorer/issues/694)
Equip and play emotes that are affected by this issue.
=> fix: disabled unwanted renderers from Emotes

Explorer/Assets/DCL/CharacterTriggerArea/Components/CharacterTriggerAreaComponent.cs, Explorer/Assets/DCL/CharacterTriggerArea/Systems/CharacterTriggerAreaCleanupSystem.cs, Explorer/Assets/DCL/CharacterTriggerArea/Systems/CharacterTriggerAreaHandlerSystem.cs, Explorer/Assets/DCL/CharacterTriggerArea/Tests/EditMode/CharacterTriggerAreaCleanupSystemShould.cs, Explorer/Assets/DCL/CharacterTriggerArea/Tests/PlayMode/CharacterTriggerAreaHandlerSystemShould.cs, Explorer/Assets/DCL/CharacterTriggerArea/csc.rsp, Explorer/Assets/DCL/CharacterTriggerArea/csc.rsp.meta, Explorer/Assets/DCL/SDKComponents/AvatarModifierArea/Tests/AvatarModifierAreaHandlerSystemShould.cs
Fixes for object pool releasing
Testing
1. Go to Genesis Plaza
2. Go to 59_64
3. Scene works fine
=> fix pool releasing

Explorer/Assets/DCL/Character/CharacterPreview/CharacterPreviewControllerBase.cs
Fixes: #732
2. Verify avatar is much crisper
=> fix: Add AA and dynamic scaling to avatar preview

Explorer/Assets/DCL/Profiles/DataModels/ProfileJsonDto.cs, Explorer/Assets/DCL/Profiles/Repository/RealmProfileRepository.ProfileJsonRootDtoConverter.cs
Fixes #794 
2. Eyes, mouth & hair should be visible
=> fix: alpha value for skin, eyes & hair on new accounts

Explorer/Assets/DCL/Audio/AudioConfigs/Avatar_Fall_Long.asset, Explorer/Assets/DCL/Audio/AudioConfigs/Avatar_Fall_Short.asset, Explorer/Assets/DCL/Audio/AudioConfigs/Avatar_Jump_Jog.asset, Explorer/Assets/DCL/Audio/AudioConfigs/Avatar_Jump_Run.asset, Explorer/Assets/DCL/Audio/AudioConfigs/Avatar_Jump_Walk.asset, Explorer/Assets/DCL/Audio/AudioConfigs/Avatar_Land_Hard.asset, Explorer/Assets/DCL/Audio/AudioConfigs/Avatar_Land_Jog.asset, Explorer/Assets/DCL/Audio/AudioConfigs/Avatar_Land_Run.asset, Explorer/Assets/DCL/Audio/AudioConfigs/Avatar_Land_Walk.asset, Explorer/Assets/DCL/Audio/AudioConfigs/Avatar_Step_Jog.asset, Explorer/Assets/DCL/Audio/AudioConfigs/Avatar_Step_Run.asset, Explorer/Assets/DCL/Audio/AudioConfigs/Avatar_Step_Walk.asset, Explorer/Assets/DCL/Audio/AudioConfigs/Generic_Button_Close.asset, Explorer/Assets/DCL/Audio/AudioConfigs/Generic_Tab_Selected .asset, Explorer/Assets/DCL/Audio/AudioConfigs/Menu_LogIn_Background_Music.asset, Explorer/Assets/DCL/Audio/Sounds/Explorer Alpha 2024/Music - Builder.wav, Explorer/Assets/DCL/Audio/Sounds/Explorer Alpha 2024/Music - Builder.wav.meta, Explorer/Assets/DCL/Audio/Sounds/Explorer Alpha 2024/UI - Button Click 01.wav, Explorer/Assets/DCL/Audio/Sounds/Explorer Alpha 2024/UI - Button Click 01.wav.meta, Explorer/Assets/DCL/Audio/Sounds/Explorer Alpha 2024/UI - Button Hover 01.wav, Explorer/Assets/DCL/Audio/Sounds/Explorer Alpha 2024/UI - Button Hover 01.wav.meta, Explorer/Assets/DCL/Audio/Sounds/Explorer Alpha 2024/UI - Button Release 01.wav, Explorer/Assets/DCL/Audio/Sounds/Explorer Alpha 2024/UI - Button Release 01.wav.meta, Explorer/Assets/DCL/Audio/Sounds/Explorer Alpha 2024/UI - Cancel 01.wav, Explorer/Assets/DCL/Audio/Sounds/Explorer Alpha 2024/UI - Cancel 01.wav.meta
- Changed authentication music (removed "journey in the magic crystal cave" for something less gloomy)
- Increased the level of the avatar sounds +0.2
1. Open Decentraland and check the new music
2. The sounds of the avatar are a bit more evident now
3. Some other sounds has been changed (close chat, change sections on the menu)
=> chore: Changed music and sound tweaks

Explorer/Assets/DCL/Chat/MessageBus/MultiplayerChatMessagesBus.cs, Explorer/Assets/DCL/Minimap/MinimapController.cs, Explorer/Assets/DCL/Minimap/csc.rsp, Explorer/Assets/DCL/Minimap/csc.rsp.meta, Explorer/Assets/DCL/Multiplayer/Connections/Archipelago/Rooms/ArchipelagoIslandRoom.cs, Explorer/Assets/DCL/Multiplayer/Connections/Archipelago/Rooms/Fixed/FixedConnectiveRoom.cs, Explorer/Assets/DCL/Multiplayer/Connections/GateKeeper/Meta/LogMetaDataSource.cs, Explorer/Assets/DCL/Multiplayer/Connections/GateKeeper/Meta/MetaData.cs, Explorer/Assets/DCL/Multiplayer/Connections/GateKeeper/Meta/MetaDataSource.cs, Explorer/Assets/DCL/Multiplayer/Connections/GateKeeper/Rooms/GateKeeperSceneRoom.cs, Explorer/Assets/DCL/Multiplayer/Connections/Rooms/Connective/ConnectiveRoom.cs, Explorer/Assets/DCL/Navmap/FloatingPanelController.cs, Explorer/Assets/DCL/PlacesAPIService/IPlacesAPIClient.cs, Explorer/Assets/DCL/PlacesAPIService/IPlacesAPIService.cs, Explorer/Assets/DCL/PlacesAPIService/PlacesAPIClient.cs, Explorer/Assets/DCL/PlacesAPIService/PlacesAPIService.ActivePlaces.cs, Explorer/Assets/DCL/PlacesAPIService/PlacesAPIService.cs, Explorer/Assets/DCL/PlacesAPIService/csc.rsp, Explorer/Assets/DCL/PlacesAPIService/csc.rsp.meta, Explorer/Assets/DCL/TeleportPrompt/TeleportPromptController.cs, Explorer/Assets/DCL/TeleportPrompt/csc.rsp, Explorer/Assets/DCL/TeleportPrompt/csc.rsp.meta
More info in the issue https://github.com/decentraland/unity-explorer/issues/821
To test:
- teleport to -143,-1
- see that scene room is not connected in /debug
- teleport to 100,100
- see new scene room's sid
- teleport to 0,0
- see new scene room's sid
=> Fix Global chatting

Explorer/Assets/DCL/Character/CharacterCamera/Components/CameraInput.cs, Explorer/Assets/DCL/Character/CharacterCamera/Systems/ApplyCinemachineCameraInputSystem.cs, Explorer/Assets/DCL/Character/CharacterCamera/Systems/UpdateCameraInputSystem.cs, Explorer/Assets/DCL/Input/UnityInputSystem/DCLInput.cs, Explorer/Assets/DCL/Input/UnityInputSystem/DCLInput.inputactions
- Added vertical panning of the camera with Q and E (Pedestal movement)
- Added FOV control with Numpad +/- and mouse wheel.
- Added Slow mode toggle with Ctrl
- Gamepad Left Shoulder / Right Shoulder = FOV
- Gamepad D-pad UP / DOWN = Vertical panning
- Gamepad Left Trigger = Slow Down
1. Go to Free Camera (F11)
2. Change the FOV with the Numpad + / - 
3. Do vertical pan with Q/E
4. Slow down camera movement with Ctrl. 
=> feat: enhanced Free camera features

Explorer/Assets/DCL/Backpack/Assets/Animations/Avatar/AvatarAnimatorController.controller, Explorer/Assets/DCL/Backpack/Assets/Animations/Avatar/Deselected.anim, Explorer/Assets/DCL/Backpack/Assets/Animations/Avatar/Hover.anim, Explorer/Assets/DCL/Backpack/Assets/Animations/Avatar/Selected.anim, Explorer/Assets/DCL/Backpack/Assets/Animations/Avatar/Unhover.anim, Explorer/Assets/DCL/Backpack/Assets/Animations/Emotes/Deselected.anim, Explorer/Assets/DCL/Backpack/Assets/Animations/Emotes/Hover.anim, Explorer/Assets/DCL/Backpack/Assets/Animations/Emotes/Selected.anim, Explorer/Assets/DCL/Backpack/Assets/Animations/Emotes/Unhover.anim, Explorer/Assets/DCL/Backpack/Assets/Backpack.prefab, Explorer/Assets/DCL/ExplorePanel/Assets/ExplorePanelUI.prefab
Fix #895 
Fixes a weird behaviour of the emotes section button that was flickering
...
2. Go to the explore panel
3. Go to backpack
4. Switch between avatar and emotes and check that the emotes button doesn't break
=> Fixed animations for backpack sections

Explorer/Assets/DCL/Multiplayer/Connections/RoomHubs/IRoomHub.cs, Explorer/Assets/DCL/Multiplayer/Connections/RoomHubs/RoomHub.cs, Explorer/Assets/DCL/Multiplayer/Connections/Rooms/Connective/IConnectiveRoom.cs, Explorer/Assets/Scripts/Global/Dynamic/RealmNavigator.cs
=> Fix: cannot teleport to other realm if the scene room is not connected

Explorer/Assets/Scripts/ECS/StreamableLoading/AssetBundles/Editor/AssetBundleCacheClearMenu.cs
=> chore: add clear cache warning

Explorer/Assets/StreamingAssets/Js/Init.js
Attempts to stringify arguments
=> chore: stringify arguments so we avoid [Object object]

Explorer/Assets/DCL/Interaction/Systems/WritePointerEventResultsSystem.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportCategory.cs, Explorer/Assets/DCL/PluginSystem/Global/CharacterCameraPlugin.cs, Explorer/Assets/DCL/PluginSystem/World/CameraTransformPlugin.cs, Explorer/Assets/DCL/PluginSystem/World/CameraTransformPlugin.cs.meta, Explorer/Assets/DCL/SDKComponents/CameraTransform.meta, Explorer/Assets/DCL/SDKComponents/CameraTransform/Components.meta, Explorer/Assets/DCL/SDKComponents/CameraTransform/Components/SDKCameraComponent.cs, Explorer/Assets/DCL/SDKComponents/CameraTransform/Components/SDKCameraComponent.cs.meta, Explorer/Assets/DCL/SDKComponents/CameraTransform/Systems.meta, Explorer/Assets/DCL/SDKComponents/CameraTransform/Systems/SDKCameraTransformSystem.cs, Explorer/Assets/DCL/SDKComponents/CameraTransform/Systems/SDKCameraTransformSystem.cs.meta, Explorer/Assets/Scripts/Global/StaticContainer.cs
Fixes https://github.com/decentraland/unity-explorer/issues/900
Fixes https://github.com/decentraland/unity-explorer/issues/901
- `/world MetadyneLabs`
- Pick up the gun
- The gun should appear correctly on your screen
- Go and pick up the box with F, you should be able to pick it up and leave it at the device to open the door
- You should be able to finish the first level.
=> fix: cannot pick up objects in Metadyne

Explorer/Assets/DCL/AvatarRendering/Wearables/ECSThumbnailProvider.cs
=> Fix: test fix for emotes and backpack issues

Explorer/Assets/Scripts/Global/StaticContainer.cs
- `/world goerli`
- run around the scenes, no scene should be weirdly moving around you or being attached to the camera
=> disable: sdk camera plugin

Explorer/Assets/DCL/AvatarRendering/AvatarShape/Assets/Animations/Animator/CharacterAnimator.controller, Explorer/Assets/DCL/Character/CharacterMotion/Systems/InterpolateCharacterSystem.cs
Fixes https://github.com/decentraland/unity-explorer/issues/524
- `/goto 33.-11`
- go around the building and up the stairs
- character wont get stuck or in a falling loop when falling between the building and the last stair step 
=> fix: character being stuck on certain places

Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/SimpleFetchApiImplementation.cs
Missing part of https://github.com/decentraland/unity-explorer/pull/1053
=> fix: the fetch api module was not working correctly (II)

Explorer/Assets/DCL/Multiplayer/Connections/Messaging/Pipe/LogMessagePipe.cs, Explorer/Assets/DCL/Multiplayer/Connections/Systems/Debug/DebounceRoomDisplay.cs, Explorer/Assets/DCL/Multiplayer/Connections/Systems/Debug/DebounceRoomDisplay.cs.meta, Explorer/Assets/DCL/Multiplayer/Connections/Systems/DebugRoomsSystem.cs, Explorer/Assets/DCL/Multiplayer/Movement/Systems/PlayerMovementNetSendSystem.cs
Debounce for RoomDisplay
LogMessagePipe with caching
**How to test:**
A quick smoke test to ensure everything works as expected.
=> chore: reduce allocations livekit

Explorer/Assets/DCL/Minimap/MinimapController.cs, Explorer/Assets/Scripts/ECS/SceneLifeCycle/Realm/IRealmNavigator.cs, Explorer/Assets/Scripts/Global/Dynamic/ChatCommands/ChangeRealmChatCommand.cs, Explorer/Assets/Scripts/Global/Dynamic/RealmNavigator.cs
fix #889
Test steps are provided in the referenced issue [#889](https://github.com/decentraland/unity-explorer/issues/889)
=> Fix: check for not reloading same realm

Explorer/Assets/DCL/Ipfs/IpfsRealm.cs
Fixes #1057 
2. Check that you can also change wearables on peer.decentraland.org realm
=> fix: profile publish on worlds

Explorer/Assets/DCL/Backpack/AvatarSection/AvatarController.cs, Explorer/Assets/DCL/Backpack/BackpackGridController.cs
This PR reduces a bit the amount of requests made by the backpack, it shouldn't particularly affect the backpack.
...
2. Check the backpack and verify it works like before if not better
=> Fix: improved backpack by reducing requests amount

Explorer/Assets/DCL/AvatarRendering/Shaders/DCL_Toon/DCL_Toon.shader, Explorer/Assets/DCL/AvatarRendering/Shaders/DCL_Toon/DCL_ToonBodyDoubleShadeWithFeather.hlsl, Explorer/Assets/DCL/AvatarRendering/Shaders/DCL_Toon/DCL_ToonOutline.hlsl, Explorer/Assets/DCL/Rendering/Outline/OutlineDrawPass.cs, Explorer/Assets/Rendering/ForwardRenderer - Low.asset, Explorer/Assets/Rendering/ShaderVariants.shadervariants, Explorer/ProjectSettings/QualitySettings.asset
=> fix: avatar outline - false black renderering

Explorer/Assets/DCL/NameTags/NametagView.cs, Explorer/Assets/DCL/NameTags/Systems/NametagPlacementSystem.cs
Fix #1120 some minor improvements for nametags
...
It's a bit complex to test this because we would need many users connected to replicated some behaviours, to approve just verify that nametags and chat bubbles are working as previously
=> Fix: improved nametags lifecycle to avoid some visual bugs

Explorer/Assets/DCL/Multiplayer/Connections/Archipelago/SignFlow/LiveConnectionArchipelagoSignFlow.cs, Explorer/Assets/DCL/Multiplayer/Connections/Messaging/Pipe/MessagePipe.cs, Explorer/Assets/DCL/Multiplayer/Movement/Systems/MultiplayerMovementMessageBus.cs, Explorer/Assets/Scripts/ECS/SceneLifeCycle/Systems/ControlSceneUpdateLoopSystem.cs, Explorer/Assets/Scripts/ECS/StreamableLoading/AudioClips/AudioClipData.cs, Explorer/Assets/Scripts/Global/Dynamic/MainSceneLoader.cs, Explorer/Assets/Scripts/Global/Dynamic/RealmController.cs
Added some try/catch and proper error reporting while avoiding assertions and exceptions.
This fixes some memory leaks and potentially the crash when exiting the application
=> fix: proper project disposal

Explorer/Assets/DCL/AuthenticationScreenFlow/AuthenticationScreenController.cs, Explorer/Assets/DCL/AuthenticationScreenFlow/AuthenticationScreenFlow.asmdef, Explorer/Assets/DCL/AuthenticationScreenFlow/AuthenticationScreenView.cs, Explorer/Assets/DCL/Backpack/AvatarSection/AvatarController.cs, Explorer/Assets/DCL/Backpack/Backpack.asmdef, Explorer/Assets/DCL/Backpack/BackpackView.cs, Explorer/Assets/DCL/Backpack/EmotesSection/EmotesController.cs, Explorer/Assets/DCL/Character/CharacterMotion/Components/AnimationHashes.cs, Explorer/Assets/DCL/EmotesWheel/EmoteWheelSlotView.cs, Explorer/Assets/DCL/EmotesWheel/EmotesWheelView.cs, Explorer/Assets/DCL/ExplorePanel/ExplorePanel.asmdef, Explorer/Assets/DCL/ExplorePanel/PersistentExploreOpenerView.cs, Explorer/Assets/DCL/Minimap/Minimap.asmdef, Explorer/Assets/DCL/Minimap/MinimapController.cs, Explorer/Assets/DCL/Minimap/MinimapView.cs, Explorer/Assets/DCL/Navmap/FloatingPanelController.cs, Explorer/Assets/DCL/Navmap/FullSearchResultsView.cs, Explorer/Assets/DCL/Navmap/Navmap.asmdef, Explorer/Assets/DCL/Navmap/SatelliteController.cs, Explorer/Assets/DCL/Navmap/SearchResultPanelController.cs, Explorer/Assets/DCL/Navmap/SearchResultPanelView.cs, Explorer/Assets/DCL/Navmap/StreetViewController.cs, Explorer/Assets/DCL/UI/ButtonWithAnimationView.cs, Explorer/Assets/DCL/UI/SectionSelectorController.cs, Explorer/Assets/DCL/UI/TabSelectorView.cs, Explorer/Assets/DCL/UI/UI.asmdef
This PR improves the handling of some animators that were not properly disabled and cleans up the code
...
2. Check auth screen, explore panel and minimap animations
=> chore: improved animators performance and anim code cleanup

Explorer/Assets/DCL/StylizedSkybox/Materials/GenesisSkybox.mat, Explorer/Assets/DCL/StylizedSkybox/Prefabs/SkyboxController.prefab, Explorer/Assets/DCL/StylizedSkybox/Scripts/SkyboxController.cs, Explorer/Assets/DCL/StylizedSkybox/Shaders/GenesisSky.shadergraph
Updated indirect color and sky colors
Added animation clip to control cloud highlights intensity
...
2. ...
=> Updates in sky color and indirect lighting

Explorer/Assets/Scripts/SceneRuntime/ISceneRuntime.cs, Explorer/Assets/Scripts/SceneRuntime/SceneRuntimeImpl.cs
=> fix: fix engine api wrapper

Explorer/Assets/DCL/AvatarRendering/AvatarShape/Helpers/AvatarInstantiationPolymorphicBehaviour.cs, Explorer/Assets/DCL/AvatarRendering/Wearables/Helpers/Assets/WearableAssetsCache.cs
fix #1188 
disable newly equiped wearables renderers when switched in first person view
1. See related bug ticket for repro steps (#1188 )
=> Fix: equiped wearable in first person view

Explorer/Assets/DCL/Chat/ChatController.cs, Explorer/Assets/DCL/ExplorePanel/ExplorePanelController.cs, Explorer/Assets/DCL/Multiplayer/SDK/Systems/GlobalWorld/PlayerProfileDataPropagationSystem.cs, Explorer/Assets/Scripts/Utility/Arch.meta, Explorer/Assets/Scripts/Utility/Arch/ArchExtensions.cs, Explorer/Assets/Scripts/Utility/Arch/ArchExtensions.cs.meta
Fixes ECS exceptions that I had a chance to observe
=> Fix Arch exceptions

Explorer/Assets/DCL/ParcelsService/TeleportController.cs, Explorer/Assets/Scripts/CrdtEcsBridge/RestrictedActions/GlobalWorldActions.cs, Explorer/Assets/Scripts/CrdtEcsBridge/RestrictedActions/RestrictedActionsAPIImplementation.cs, Explorer/Assets/Scripts/Utility/Arch/ArchExtensions.cs
Teleport API action was executed off the main thread and adding to the ECS was secured (impossible to guarantee the added component is removed by the system before a similar API action is executed)
Fixes #1220
=> Fix: Secure Teleport Action execution

Explorer/ProjectSettings/ProjectSettings.asset
Seeing if this change fixes the stripping level problems
=> fix: revert stripping level changes for standalone build

.github/workflows/build-unitycloud.yml
=> chore: don't run unity cloud build on draft PR

Explorer/ProjectSettings/ProjectSettings.asset
=> fix: update stripping

Explorer/Assets/DCL/SceneLoadingScreens/SceneLoadingScreenController.cs
Fixes stucking in the loading screen, now this state is impossible during the manual tips switching with buttons
=> fix tips stucking

Explorer/Assets/Scripts/ECS/SceneLifeCycle/IncreasingRadius/LoadPointersByIncreasingRadiusSystem.cs, Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/SignedFetch/Messages/FlatFetchResponse.cs, Explorer/Assets/StreamingAssets/Js/Modules/FetchApi.js, Explorer/Assets/StreamingAssets/Js/Modules/SignedFetch.js
Based on #1236 fixed SignedFetch headers
Though the scene still does not work due to the usage of `Colyseus sdk`
=> Fix SignedFetch headers

Explorer/Assets/Scenes/Main.unity
Resets origin scene back to Genesis Plaza
2. See that you start in Genesis Plaza
=> fix: reset origin scene to genesis plaza

Explorer/Assets/DCL/PluginSystem/World/World Plugins Container.asset
=> fix: eye colour fix

.github/workflows/pr-comment-artifact-url.yml
Updates the comment action to show Unity Cloud Build
=> chore: Update comment action to show Unity Cloud Build

.github/workflows/pr-comment-artifact-url.yml
Fixes the url for the comment action
=> fix: comment action fix url

.github/workflows/build-Windows-il2cpp.yml
Stops GameCI flow from building automatically
=> chore: Remove auto generation of build by GameCI

.github/workflows/build-release-weekly.yml, .github/workflows/create-page-release-weekly.yml
With this fix, the github action of weekly release will get the correct artifact
=> fix: weekly release github action

Explorer/Assets/DCL/FeatureFlags/FeatureFlagsProviderExtensions.cs
Adds the hostname as program argument as it is necessary to provide the correct feature flag configuration either for zone or local development.
```
#!/bin/bash
./Decentraland.app --feature-flags-hostname localhost
```
=> feat: feature flag hostname program arg

Explorer/ProjectSettings/ProjectSettings.asset
Disables the unity logo on start of the application
2. One start you should not see the unity logo
=> chore: disable unity logo

Explorer/Assets/DCL/AvatarRendering/AvatarShape/Assets/AvatarBase.prefab, Explorer/Assets/DCL/AvatarRendering/AvatarShape/Tests/PlayMode/TestAssets/AvatarBase_TestAsset.prefab, Explorer/Assets/DCL/AvatarRendering/AvatarShape/UnityInterface/AvatarBase.cs, Explorer/Assets/DCL/SDKComponents/AvatarAttach/Systems/AvatarAttachHandlerSystem.cs, Explorer/Assets/DCL/SDKComponents/AvatarAttach/Tests/AvatarAttachHandlerSystemShould.cs
- Adds additional anchorpoints
- Adds name-tag anchorpoint using a fixed position stored in the avatar-base (note, this should eventually be dynamically updated based on the dynamic name tag height based on the current wearables, currently not implemented as the nametag also uses a fixed height)
Fixes #1135 
=> fix: anchor points

Explorer/Assets/DCL/AuthenticationScreenFlow/AuthenticationScreenController.cs, Explorer/Assets/DCL/PluginSystem/Global/Global Plugins Settings.asset, Explorer/Assets/DCL/PluginSystem/Global/Web3AuthenticationPlugin.cs
Fix #1355 
1. Log in and stay in Genesis Plaza.
2. Log out and return to the log in screen.
3. Check that Genesis Plaza music is off while the log in scren is open.
=> fix: Music of Genesis Plaza keeps playing on the log in screen

Explorer/Assets/DCL/SDKComponents/SceneUI/Systems/UIBackground/UIBackgroundInstantiationSystem.cs
Fix #973 
1. Go to genesis
2. /goto metadynelabs
3. Go to the UI options section
4. Select Home (door icon) --> Select Level
5. Click on the [next] arrow and observe the levels displayed and their corresponding images correctly.
=> fix: [Metadyne Labs] Levels Missing

.github/workflows/build-unitycloud.yml
Adds segment write key to the env vars of the build.
=> fix: add segment write key to build step

Explorer/Assets/Scripts/Global/Dynamic/BootstrapContainer.cs
force Debug Analytics everywhere, until we find how to fix it on CI
2. Verify it runs
=> Chore: disable Analytics

.github/workflows/build-Mac-il2cpp.yml
Unifies the Windows & Mac build scripts.
=> fix: mac il2cpp

Explorer/Assets/Editor/CloudBuild.cs, scripts/cloudbuild/build.py
=> fix: attempt to avoid new SHA for each build to ensure caching works.

Explorer/Assets/DCL/MapRenderer/MapLayers/Pins/PinMarker.cs
During deletion phase of mappins there could be some race conditions if there is interaction with the mappin on the map, this null propagation avoid the breaking of the flow in those scenarios
...
2. ...
=> Fix: fixed nullreference of map pin poolable behaviour

Explorer/Assets/DCL/MapRenderer/MapLayers/Pins/PinMarker.cs, Explorer/Assets/DCL/MapRenderer/MapLayers/Pins/PinMarkerController.cs, scripts/package.json
Fixes a bug in the assignment of texture to map pins
Updated protocol version
...
2. ...
=> Fix: fixed minor issue with map pins pooling

Explorer/Assets/Scripts/Global/Dynamic/ChatCommands/ChangeRealmChatCommand.cs
- extended change realm chat command with parcels coordinates
2. Use `/goto goerli 72,1` -> you should load Goerli realm near or at the `72,1` coordinates
3. Use `/world genesis 50,50` -> you should be loaded to Genesis City near to `50,50` parcel 
4. Verify normal commands like  `/goto olavra`,  `/world goerli` works as previously 
=> Chore: change realm command with parcels coordinates

Explorer/Assets/Scripts/Global/Dynamic/RealmLaunchSettings.cs, Explorer/Assets/Scripts/Global/Editor/RealmLaunchSettingsDrawer.cs
- changed string consts by `nameof`
1. Launch the editor
2. Choose localhost in the MainSceneLoader
3. it should work as usual
=> Fix: editor localhost development

scripts/cloudbuild/build.py
Hopefully handles the exception that is being thrown to avoid failing builds.
We dont test them we simply pray.
=> fix: retry if an exception occurs during the running of the build

Explorer/Assets/Editor/CloudBuild.cs
=> fix: if segment key doesn't exist, still build

Explorer/Assets/StreamingAssets/Js/Modules/FetchApi.js
Fixes #1518 
Fixes #1513 
Fixes #1514 
Fixes #1515 
1. Test dolls house & above
=> fix: add entries() functionality to fetchAPI

Explorer/Assets/DCL/InfiniteFloor/Floor.mat, Explorer/Assets/DCL/Landscape/Assets/Materials/Cliff.mat, Explorer/Assets/DCL/Landscape/Assets/Materials/Ground1.mat, Explorer/Assets/DCL/Roads/Data/RoadAssets/RoadRedesign/Bench.mat, Explorer/Assets/DCL/Roads/Data/RoadAssets/RoadRedesign/LampEmissive_mat.mat, Explorer/Assets/DCL/Roads/Data/RoadAssets/RoadRedesign/Lamp_mat.mat, Explorer/Assets/DCL/Roads/Data/RoadAssets/RoadRedesign/PotMiddleLarge.mat, Explorer/Assets/DCL/Roads/Data/RoadAssets/RoadRedesign/RoadPropsBlue.mat, Explorer/Assets/DCL/Roads/Data/RoadAssets/RoadRedesign/RoadPropsSoil.mat, Explorer/Assets/DCL/Roads/Data/RoadAssets/RoadRedesign/RoadPropsWhite.mat, Explorer/Assets/DCL/Roads/Data/RoadAssets/RoadRedesign/RoadTiles01.mat, Explorer/Assets/DCL/Roads/Data/RoadAssets/RoadRedesign/RoadTiles02.mat, Explorer/Assets/DCL/Roads/Data/RoadAssets/RoadRedesign/RoadTiles03.mat, Explorer/Assets/DCL/Roads/Data/RoadAssets/RoadRedesign/RoadTiles04.mat, Explorer/Assets/DCL/Roads/Data/RoadAssets/RoadRedesign/RoadTiles05.mat, Explorer/Assets/DCL/Roads/Data/RoadAssets/RoadRedesign/RoadTiles06.mat, Explorer/Assets/DCL/Roads/Data/RoadAssets/RoadRedesign/RoadTiles07.mat, Explorer/Assets/DCL/Roads/Data/RoadAssets/RoadRedesign/RoadTiles08.mat, Explorer/Assets/DCL/Roads/Data/RoadAssets/RoadRedesign/RoadTiles09.mat, Explorer/Assets/DCL/Roads/Data/RoadAssets/RoadRedesign/RoadTiles10.mat, Explorer/Assets/DCL/Roads/Data/RoadAssets/RoadRedesign/RoadTiles11.mat, Explorer/Assets/DCL/Roads/Data/RoadAssets/RoadRedesign/RoadTiles12.mat, Explorer/Assets/DCL/Roads/Data/RoadAssets/RoadRedesign/RoadTiles13.mat, Explorer/Assets/DCL/Roads/Data/RoadAssets/RoadRedesign/RoadTiles14.mat, Explorer/Assets/Scenes/Skybox/Floor.mat
fix: #1599
It just needs a test to make sure everything runs as per usual and things are as expected.
=> fix: instancing performance

Explorer/Assets/DCL/AvatarRendering/Emotes/Emote.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Tests.meta, Explorer/Assets/DCL/AvatarRendering/Emotes/Tests/DCL.Emotes.Tests.asmref, Explorer/Assets/DCL/AvatarRendering/Emotes/Tests/DCL.Emotes.Tests.asmref.meta, Explorer/Assets/DCL/AvatarRendering/Emotes/Tests/EmoteShould.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Tests/EmoteShould.cs.meta, Explorer/Assets/DCL/AvatarRendering/Wearables/Components/IAvatarAttachment.cs, Explorer/Assets/DCL/AvatarRendering/Wearables/Components/Wearable.cs, Explorer/Assets/DCL/AvatarRendering/Wearables/Tests/WearableShould.cs, Explorer/Assets/DCL/AvatarRendering/Wearables/Tests/WearableShould.cs.meta, Explorer/Assets/DCL/Passport/Modules/EquippedItems_PassportModuleController.cs
Changes how on-chain emotes are defined through its urn. In addition a refactor was made to improve the separation with the wearables.
=> fix: on-chain emotes definition & refactor of wearables

Explorer/Assets/DCL/Multiplayer/SDK/Systems/GlobalWorld/PlayerCRDTEntitiesHandlerSystem.cs, Explorer/Assets/DCL/Multiplayer/SDK/Tests/PlayerCRDTEntitiesHandlerSystemShould.cs
Reverts decentraland/unity-explorer#1639
=> Revert "fix: emote command subscription of the own player entity from the sdk"

.github/workflows/build-unitycloud.yml
Release action was being ignored.
...
2. ...
=> chore: fix cloud build when releasing

Explorer/Assets/DCL/Landscape/TerrainGenerator.cs
=> fix: verify grassRenderer is not null before calling render

Explorer/Assets/DCL/UI/Assets/ColorPicker.prefab
Fix #1707
Color picker color slider and actual body part color should be consistent after this change
...
1. Open backpack
2. Go to a category with color picker
3. Change the color slider
4. Check that the color picker color slider and body part color are consistent
=> Fix: fixed color picker color slider background

.github/workflows/build-release-weekly.yml
=> chore: disable weekly release

Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/Settings/CategorySeverityMatrix.cs
Caches the severity matrix to avoid the for loop every time a message is logged.
=> fix: cache severity matrix

.github/workflows/pr-comment-artifact-url.yml, Explorer/Assets/Scenes/Main.unity
- Disables by default lod and landscape in editor
- typo fix in the comment action
=> chore: minor editor cleanup

Explorer/Assets/DCL/Character/CharacterCamera/Settings/CinemachinePreset.cs, Explorer/Assets/DCL/Character/CharacterCamera/Systems/ApplyCinemachineCameraInputSystem.cs, Explorer/Assets/DCL/Character/CharacterCamera/Systems/csc.rsp, Explorer/Assets/DCL/Character/CharacterCamera/Systems/csc.rsp.meta, Explorer/Assets/DCL/Character/CharacterCamera/csc.rsp, Explorer/Assets/DCL/Character/CharacterCamera/csc.rsp.meta
Removed standby updates from virtual cameras. It improved performance in 3x times
2. Play happy path, ensure everything is fine about cameras
=> fix: camera performance

Explorer/Packages/packages-lock.json
Update of livekit version fixed this problem
...
2. Play happy path and check out that statuses for rooms work well in connection status panel
=> fix: always POOR connection quality, update livekit version

Explorer/Assets/DCL/Backpack/BackpackController.cs, Explorer/Assets/DCL/EmotesWheel/EmotesWheelController.cs, Explorer/Assets/DCL/PluginSystem/Global/BackpackSubPlugin.cs, Explorer/Assets/DCL/PluginSystem/Global/EmotePlugin.cs, Explorer/Assets/DCL/PluginSystem/Global/ExplorePanelPlugin.cs, Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
Fixes #1748 
2. The cursor should be unlocked when you open the backpack and/or the emote wheel
=> fix: unlock cursor on emote wheel and backpack

Explorer/Assets/DCL/ExplorePanel/Assets/ExplorePanelUI.prefab, Explorer/Assets/DCL/MapRenderer/Addressables/PinMarkerObject.prefab, Explorer/Assets/DCL/MapRenderer/MapLayers/Pins/PinMarker.cs, Explorer/Assets/DCL/MapRenderer/MapLayers/Pins/PinMarkerObject.cs, Explorer/Assets/DCL/Navmap/Assets/DestinationInfoElement.prefab, Explorer/Assets/DCL/Navmap/Assets/Navmap.prefab
Minor prefab changes and fixes for map pins
...
=> fix: minor fixes to map pins

Explorer/Assets/DCL/AvatarRendering/DemoScripts/Systems/InstantiateRandomAvatarsSystem.cs, Explorer/Assets/DCL/MapRenderer/Addressables/HotUserMarkerObject.prefab, Explorer/Assets/DCL/MapRenderer/ComponentsFactory/HotUsersMarkersInstaller.cs, Explorer/Assets/DCL/MapRenderer/ConsumerUtils/csc.rsp, Explorer/Assets/DCL/MapRenderer/ConsumerUtils/csc.rsp.meta, Explorer/Assets/DCL/MapRenderer/IMapRendererSettings.cs, Explorer/Assets/DCL/MapRenderer/MapLayers/UsersMarker/HotUserMarker.cs, Explorer/Assets/DCL/MapRenderer/MapLayers/UsersMarker/HotUserMarkerObject.cs, Explorer/Assets/DCL/MapRenderer/MapLayers/UsersMarker/UsersMarkersHotAreaController.cs, Explorer/Assets/DCL/PluginSystem/Global/MinimapPlugin.cs
The order of systems wasn't strictly determined, it might cause the error. Now it's determined and `RemovedTrackedPlayersPositionSystem` goes after `TrackPlayersPositionSystem`
...
2. Ask your buddy to join and leave the game multiple times, ensure the behaviour of minimap points is correct
=> fix: map avatar points

.github/workflows/build-release-weekly.yml, .github/workflows/build-unitycloud.yml
=> fix release build

.github/workflows/pr-closure.yml, scripts/cloudbuild/build.py
=> fix: added missing env for pr clean up workflow

scripts/cloudbuild/build.py
=> fix: deleting windows and mac targets on PR close

scripts/cloudbuild/build.py
=> fix: remove dots from name in build target request

.github/workflows/build-unitycloud.yml
=> fix: prebuild

scripts/cloudbuild/build.py
Unity cloud build does not support special characters in name of the build target.
This change adds validation to branch name, to avoid unity cloud build failing
=> chore: add validation for branch name to avoid special characters

.github/workflows/build-unitycloud.yml, scripts/cloudbuild/build.py
Added support for clean build from manual triggering of the unity cloud build workflow 
=> chore: support for clean build in unity cloud

.github/workflows/build-unitycloud.yml
Excludes symbols in tar process'
=> chore: exclude symbols in tar

Explorer/Assets/DCL/AvatarRendering/Emotes/Components/CharacterEmoteIntent.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/RemoteEmotesSystem.cs
Fixes remote emotes from being played
2. Get some friends
3. Play remote emotes
=> fix: remote emotes

Explorer/Assets/DCL/Navmap/Assets/FloatingPanel.prefab, Explorer/Assets/Textures/Common/NavigationIcon.png.meta
The floating panel was missing its navigation icon on the Start Navigation button, now its fixed.
=> fix: fixed missing navigation Icon on Floating Panel

Explorer/Assets/DCL/Audio/AudioConfigs/Avatar_AnimEvent_FootstepSlide.asset, Explorer/Assets/DCL/Audio/AudioConfigs/Avatar_AnimEvent_FootstepSlide.asset.meta, Explorer/Assets/DCL/Audio/AudioSettings/AvatarAudioSettings.asset
Footstep slide audio config was missing, so I added it :)
=> fix: missing footstep_slide audio

.github/workflows/build-unitycloud.yml
=> chore: extract errors from unity logs

Explorer/Assets/Scripts/Global/Dynamic/MainSceneLoader.cs
- Ensures that development builds are the same flow as release, for profiling and debugging
- A general smoke test will be just fine there should be no apparent changes from main.
=> fix: development build flow

Explorer/Assets/DCL/Multiplayer/SDK/Components/PlayerCRDTEntity.cs, Explorer/Assets/DCL/Multiplayer/SDK/Systems/GlobalWorld/PlayerProfileDataPropagationSystem.cs, Explorer/Assets/DCL/Multiplayer/SDK/Systems/GlobalWorld/PlayerTransformPropagationSystem.cs, Explorer/Assets/DCL/Multiplayer/SDK/Tests/PropagateTransformTest.cs, Explorer/Assets/DCL/PluginSystem/Global/MultiplayerPlugin.cs, Explorer/Assets/Scripts/CrdtEcsBridge/Components/Transform/SDKTransform.cs, Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
- Fixed logic execution when the scene is not assigned
- Changed `SDKTransform` instance creation to renting from the pool
=> Fix: transforms propagation outside scenes

Explorer/Assets/DCL/Landscape/Assets/Trees/Tree01/Trunk_LOD_NoWind.mat
Fixes #1884
- Check the tree trunks at a distance are no longer white.
=> fix: missing trunk texture

Explorer/Assets/DCL/Landscape/Assets/Materials/Ocean.mat
Changed the material for the ocean. Shibu will confirm that it's what's expected.
Testing will be basic performance check and make sure it looks different to the original.
=> feat: Ocean material change

Explorer/Packages/packages-lock.json
Just updating the Stylized Water 2 package, to test, just make sure the ocean looks right and that there's no obvious performance degradation.
=> fix: Ocean repo update

scripts/cloudbuild/build.py
=> fix: retry on invalid response code

.github/workflows/build-unitycloud.yml
=> chore: no need to show shader stats on compile failure

Explorer/Assets/DCL/Multiplayer/SDK/Systems/SceneWorld/WritePlayerTransformSystem.cs
=> Fix: Host Transform removal on Scene Leave

Explorer/Assets/DCL/Multiplayer/Connections/Archipelago/Rooms/ArchipelagoIslandRoom.cs
Fixes a validation in the livekit handshake operation.
2. Check that you can enter in world
3. Check that you can see other peers
=> fix: livekit handshake validation

.github/workflows/build-release-weekly.yml, .github/workflows/build-unitycloud.yml, .github/workflows/create-page-release-weekly.yml, .github/workflows/test.yml
=> chore: support for dev branch

.github/workflows/build-release-weekly.yml, .github/workflows/build-unitycloud.yml, .github/workflows/create-page-release-weekly.yml, .github/workflows/test.yml
=> chore: support for dev branch (#2285)

.github/workflows/build-release-weekly.yml, .github/workflows/build-unitycloud.yml, .github/workflows/create-page-release-weekly.yml, .github/workflows/test.yml
=> chore: support for dev branch (#2285) (#2361)

Explorer/Assets/DCL/LOD/Systems/LODContainer.cs, Explorer/Assets/DCL/Multiplayer/Profiles/Entities/RemoteEntities.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Optimization/Pools/ComponentPoolsRegistry.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Optimization/Pools/GameObjectPool.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Optimization/Pools/IComponentPoolsRegistry.cs, Explorer/Assets/DCL/PluginSystem/Global/AvatarPlugin.cs, Explorer/Assets/DCL/PluginSystem/Global/CharacterPreviewPlugin.cs, Explorer/Assets/DCL/PluginSystem/World/NFTShapePlugin.cs, Explorer/Assets/DCL/ResourcesUnloading/CacheCleaner.cs, Explorer/Assets/DCL/Roads/Pools/RoadAssetsPool.cs, Explorer/Assets/DCL/Roads/Systems/RoadPlugin.cs, Explorer/Assets/DCL/SDKComponents/MediaStream/Wrapper/MediaPlayerPluginWrapper.cs, Explorer/Assets/DCL/SDKComponents/NFTShape/Frames/Pool/FramesPool.cs
This reverts commit ef03086cabbc363e798e1fdd8b0039e6051f69aa.
=> Revert "chore: Tidy up hierarchy from loose pool elements etc (#2358)"

Explorer/Assets/DCL/PluginSystem/World/TextShapePlugin.cs, Explorer/Assets/DCL/SDKComponents/TextShape/Component/TextShapeComponent.cs, Explorer/Assets/DCL/SDKComponents/TextShape/Demo/DCL.TextShapeSystems.asmref, Explorer/Assets/DCL/SDKComponents/TextShape/Demo/DCL.TextShapeSystems.asmref.meta, Explorer/Assets/DCL/SDKComponents/TextShape/Demo/TextShapeDemoWorld.cs, Explorer/Assets/DCL/SDKComponents/TextShape/Demo/WarmUpSettingsTextShapeDemoWorld.cs, Explorer/Assets/DCL/SDKComponents/TextShape/System/DCL.TextShapeSystems.asmref, Explorer/Assets/DCL/SDKComponents/TextShape/System/DCL.TextShapeSystems.asmref.meta, Explorer/Assets/DCL/SDKComponents/TextShape/System/InstantiateTextShapeSystem.cs, Explorer/Assets/DCL/SDKComponents/TextShape/System/UpdateTextShapeSystem.cs, Explorer/Assets/DCL/SDKComponents/TextShape/System/VisibilityTextShapeSystem.cs, Explorer/Assets/Scripts/ECS/Unity/SceneBoundsChecker/CheckColliderBoundsSystem.cs, Explorer/Assets/Scripts/Utility/ParcelMathHelper.cs
Now TextMeshPro labels are hidden when they leave their scenes.
There are several scenarios that can be tested:
It is easier to test in Unity editor although.
2. Enable the Show scene bounds option in the Debug panel.
3. Move the avatar to the boundaries of the Genesis plaza.
4. Drag an object that has a text label, like the jukebox, near to the boundaries.
5. Slowly drag the object outside of the scene.
The label should hide when it is outside, and show when it enters again.
1. Copy the provided script into a local scene.
2. Wait for the label to touch the boundaries and move back.
https://github.com/user-attachments/assets/242c9e26-a691-4f47-b200-a733e72ddef9
```
export function main() {
const entity = engine.addEntity()
Transform.create(entity, { position: …
```
=> Text are not being affected when an object is outside bounds (#1904)

Explorer/Assets/DCL/SDKComponents/MediaStream/OpenMediaPromise.cs, Explorer/Assets/DCL/WebRequests/WebRequestControllerExtensions.cs, Explorer/Assets/Scripts/Global/Dynamic/RealmController.cs
=> chore: sync main to dev

.github/auto_assign_config.yml
=> chore: updated the auto assign config

Explorer/Assets/DCL/AvatarRendering/Loading/Components/IAvatarAttachment.cs, Explorer/Assets/DCL/AvatarRendering/Wearables/Helpers/WearablePolymorphicBehaviour.cs, Explorer/Assets/DCL/AvatarRendering/Wearables/Systems/FinalizeWearableLoadingSystem.cs, Explorer/Assets/DCL/CommunicationData/URLHelpers/URN.cs, Explorer/Assets/DCL/ResourcesUnloading/Tests/CacheCleanerIntegrationTests.cs
just removed some LINQ for optimizations
2. Smoke test that all things with wearables are working fine - like backpack and passport of others, some special wearables collections, wearables of other players, emotes
=> Chore: removed several LINQ

.github/workflows/pr-comment-artifact-url.yml
Fix the S3 artifact URL generation in the `Comment Artifact URL on PR` job.
=> fix: artifact url format generation

.github/workflows/pr-comment-artifact-url.yml
This PR updates the PR generated comment to use the bucket public URL instead of the bucket name
=> refactor: Use the bucket public url

Explorer/Assets/DCL/Landscape/TerrainGenerator.cs
see title 
check if [#2190](https://github.com/decentraland/unity-explorer/issues/2190) is fixed 
=> Chore: bumped cache version for landscape

Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/Systems/PerformanceAnalyticsSystem.cs
while working on optimization, this disables analytics temporarly
=> Chore: temporarly disable performance analytics

.github/workflows/build-unitycloud.yml
Fixing wrong build version on PR and dev branches
2. Check the version on loading screen
=> fix: wrong tag version on dev

Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandUrlsSource.cs
=> Fix: replace to -ea domain

Explorer/Assets/DCL/Input/Assets/Cursor.png.meta, Explorer/Assets/DCL/Input/Assets/CursorInteractive.png.meta, Explorer/Assets/DCL/Input/Assets/CursorSettings.asset
Adjusted the cursor sizes that I had increased in a previous PR and adjusted the settings as well so the hotspots are in correct position.
...
Just interact with the cursor, the size should be normal and the cursor should change from interactive to normal in the edges of things (easier to see with cubes or buttons, as characters have bigger colliders than the character itself).
Fixes #2595
=> Adjusted cursors sizes and settings

scripts/cloudbuild/build.py
=> fix: attempt to remove build id

.github/actions/version/action.yml
=> chore: fetch commit hash

.github/workflows/upload-build-epic-store.yml
This PR is adding a manual workflow to upload latest release to epic store.
This is closing https://github.com/decentraland/unity-explorer/issues/2639
=> chore: add workflow to automatically upload latest build to epic store

.github/workflows/build-unitycloud.yml, .github/workflows/s3-latest-release.yml
This PR generates a new `latest.json` file containing the github release version marked as the latest
=> chore: Create a latest.json file containing the latest github release version

.github/actions/version/action.yml, .github/workflows/build-release-main.yml, .github/workflows/build-unitycloud.yml
=> fix: use short version for release builds

Explorer/Assets/DCL/AuthenticationScreenFlow/Assets/AuthenticationScreen.prefab, Explorer/Assets/Editor/CloudBuild.cs
This fixes an issue with the PR that added the build data, It was not properly saving the changes to the asset...
=> fix: added asset saving to build data

Explorer/Assets/DCL/Clipboard.meta, Explorer/Assets/DCL/Clipboard/DCL.Clipboard.asmdef, Explorer/Assets/DCL/Clipboard/DCL.Clipboard.asmdef.meta, Explorer/Assets/DCL/Clipboard/ISystemClipboard.cs, Explorer/Assets/DCL/Clipboard/ISystemClipboard.cs.meta, Explorer/Assets/DCL/Clipboard/UnityClipboard.cs, Explorer/Assets/DCL/Clipboard/UnityClipboard.cs.meta, Explorer/Assets/DCL/Clipboard/csc.rsp, Explorer/Assets/DCL/Clipboard/csc.rsp.meta, Explorer/Assets/DCL/Navmap/Assets/EventEntry.prefab, Explorer/Assets/DCL/Navmap/Assets/PlacesAndEventsPanel.prefab, Explorer/Assets/DCL/Navmap/Assets/ShareContextMenu.prefab, Explorer/Assets/DCL/Navmap/Assets/ShareContextMenu.prefab.meta, Explorer/Assets/DCL/Navmap/EventElementView.cs, Explorer/Assets/DCL/Navmap/EventInfoPanelController.cs, Explorer/Assets/DCL/Navmap/EventInfoPanelView.cs, Explorer/Assets/DCL/Navmap/Navmap.asmdef, Explorer/Assets/DCL/Navmap/NavmapController.cs, Explorer/Assets/DCL/Navmap/PlaceInfoPanelController.cs, Explorer/Assets/DCL/Navmap/PlaceInfoPanelView.cs, Explorer/Assets/DCL/Navmap/PlacesAndEventsPanelView.cs, Explorer/Assets/DCL/Navmap/SharePlacesAndEventsContextMenuController.cs, Explorer/Assets/DCL/Navmap/SharePlacesAndEventsContextMenuController.cs.meta, Explorer/Assets/DCL/Navmap/SharePlacesAndEventsContextMenuView.cs, Explorer/Assets/DCL/Navmap/SharePlacesAndEventsContextMenuView.cs.meta, Explorer/Assets/DCL/PluginSystem/DCL.Plugins.asmdef, Explorer/Assets/DCL/PluginSystem/Global/ExplorePanelPlugin.cs, Explorer/Assets/DCL/UI/WarningNotificationView.cs, Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
Integrates a context menu to share an event or place. Allows to copy link and make a new post on twitter.
=> integration of share context menu for events and places

.github/workflows/s3-latest-release.yml
=> chore: add more debug for s3 upload workflow

Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/Sentry/SentryReportHandler.cs, Explorer/Assets/DCL/UserInAppInitializationFlow/DCL.UserInAppInitializationFlow.asmdef, Explorer/Assets/DCL/UserInAppInitializationFlow/RealUserInAppInitializationFlow.cs, Explorer/Assets/DCL/UserInAppInitializationFlow/StartupOperations/SentryDiagnosticStartupOperation.cs, Explorer/Assets/DCL/UserInAppInitializationFlow/StartupOperations/SentryDiagnosticStartupOperation.cs.meta, Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs, Explorer/Assets/Scripts/Global/Dynamic/MainSceneLoader.cs
- Introduces Realm information to Sentry so we can better diagnose issues.
2. Check happy path!
=> chore: add realm info to diagnostics

Explorer/Assets/DCL/Navmap/CategoryFilterController.cs, Explorer/Assets/DCL/Navmap/INavmapBus.cs, Explorer/Assets/DCL/Navmap/NavmapCommandBus.cs, Explorer/Assets/DCL/PluginSystem/Global/ExplorePanelPlugin.cs
Adds category filter event for navmap bus
=> feat: wired category filter even for navmap bus

Explorer/Assets/DCL/MapRenderer/MapLayers/Categories/CategoryControllers/CategoryMarkersController.cs, Explorer/Assets/DCL/MapRenderer/MapLayers/Favorites/FavoritesMarkerController.cs, Explorer/Assets/DCL/MapRenderer/MapLayers/PointsOfInterest/ScenesOfInterestMarkersController.cs
=> fix: minor clustering fixes

Explorer/Assets/DCL/MapRenderer/MapLayers/Favorites/FavoritesMarkerController.cs, Explorer/Assets/DCL/MapRenderer/MapLayers/SearchResults/SearchResultMarkersController.cs, Explorer/Assets/DCL/Navmap/Assets/PlacesAndEventsPanel.prefab, Explorer/Assets/DCL/Navmap/NavmapBus/INavmapBus.cs, Explorer/Assets/DCL/Navmap/NavmapBus/SharedNavmapBus.cs, Explorer/Assets/DCL/Navmap/NavmapBus/csc.rsp, Explorer/Assets/DCL/Navmap/NavmapBus/csc.rsp.meta, Explorer/Assets/DCL/Navmap/NavmapCommandBus.cs, Explorer/Assets/DCL/Navmap/NavmapSearchBarController.cs, Explorer/Assets/DCL/Navmap/PlaceInfoPanelController.cs, Explorer/Assets/DCL/Navmap/SearchForPlaceAndShowResultsCommand.cs, Explorer/Assets/DCL/Navmap/SearchResultPanelController.cs, Explorer/Assets/DCL/Navmap/SearchResultPanelView.cs, Explorer/Assets/DCL/PlacesAPIService/IPlacesAPIService.cs, Explorer/Assets/DCL/PlacesAPIService/PlacesAPIService.cs, Explorer/Assets/DCL/PluginSystem/Global/ExplorePanelPlugin.cs
Integrates the pagination into the search results.
Pages are set by a size of 50.
Refactor on how search parameters are passed.
Added search param context in the search results event, so it can be properly discriminated in the map layers later.
=> feat: implement pagination on places & refactor of search params

Explorer/Assets/DCL/Navmap/NavmapSearchBarController.cs
Allow sorting only on global search (all) and update the ui accordingly.
=> feat: map discoverability sorting reset

.github/actions/version/action.yml
=> fix: fixed version action

Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/CriticalLogsAnalyticsHandler.cs, Explorer/Assets/Scripts/Global/Dynamic/BootstrapContainer.cs
left only unhandled exceptions for analytics Error event
1. Just a smoke test should be fine
=> Chore: left only unhandled exceptions for analytics Error event

.github/workflows/on-delete-release.yml
This PR adds a Github Action to update the `latest.json` file when a release is deleted.
=> feat: Add GHA to update the latest.json when a release is deleted

Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/SignedFetch/Messages/FlatFetchResponse.cs, Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/SignedFetch/SignedFetchWrap.cs
Adds the correct error message when interacting with signed fetch
1. Test the scene from this [thread](https://decentralandteam.slack.com/archives/CFG8UQN68/p1733294091144959) and check that you have the correct error messages as expressed there
=> fix: error message for reward server

Explorer/Assets/DCL/SDKComponents/TextShape/Demo/DCL.TextShapeSystems.asmref.meta, Explorer/Assets/DCL/SDKComponents/TextShape/System/DCL.TextShapeSystems.asmref.meta, Explorer/Assets/Plugins/TexturesFuse/TexturesServerWrap/Playground/ASTCTexturesCompatability/ASTCTexturesCompatability.unity.meta, Explorer/Assets/Plugins/TexturesFuse/TexturesServerWrap/Playground/AdjustGamma/AdjustGammaTexturesPlayground.unity.meta
This change removes merge markers from some meta files that were committed with them.
This change does not affect the built game.
=> Fixed some broken meta files

Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
Uses the change realm chat command to unify the change of the realm when invoking ti through the restricted action
2. Follow the steps in this [thread](https://decentralandteam.slack.com/archives/C01QVR7TJK1/p1733505833067309). Try the change realm restricted action in Casa Roustan and in Gon's scene
=> fix: Change realm restricted action

Explorer/.gitignore, Explorer/Assets/AddressableAssetsData/OSX.meta, Explorer/Assets/AddressableAssetsData/OSX/addressables_content_state.bin, Explorer/Assets/Plugins/TexturesFuse/textures-server/ProcessHubExample.meta, Explorer/Assets/Plugins/TexturesFuse/textures-server/ProcessHubExample/CMakeLists.txt.meta, Explorer/Assets/Plugins/TexturesFuse/textures-server/ProcessHubExample/build.ps1.meta, Explorer/Assets/Plugins/TexturesFuse/textures-server/ProcessHubExample/deploy.ps1.meta, Explorer/Assets/Plugins/TexturesFuse/textures-server/ProcessHubExample/main.cpp.meta
Commits auto generated meta files to repo and ignore addressable content state bins. These are changes we get every time after clearing all changes (on Mac).
1. Clear all changes from git
2. Make sure no new files are created after running in editor
=> fix: add addressable content state to gitignore and commit meta files

Explorer/Assets/DCL/Multiplayer/Profiles/Tables/EntityParticipantTable.cs, Explorer/Assets/DCL/Multiplayer/Profiles/Tables/IReadOnlyEntityParticipantTable.cs
Code enhancement
1. Encapsulated Entry related operations to the struct and
2. Made entry immutable
2. Play happy path
=> Enhance: Immutable entry for IReadOnlyEntityParticipantTable

Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandUrl.cs, Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandUrlsSource.cs, Explorer/Assets/DCL/Friends.meta, Explorer/Assets/DCL/Friends/DCL.Friends.asmdef, Explorer/Assets/DCL/Friends/DCL.Friends.asmdef.meta, Explorer/Assets/DCL/Friends/DefaultFriendsEventBus.cs, Explorer/Assets/DCL/Friends/DefaultFriendsEventBus.cs.meta, Explorer/Assets/DCL/Friends/FriendRequest.cs, Explorer/Assets/DCL/Friends/FriendRequest.cs.meta, Explorer/Assets/DCL/Friends/IFriendsEventBus.cs, Explorer/Assets/DCL/Friends/IFriendsEventBus.cs.meta, Explorer/Assets/DCL/Friends/IFriendsService.cs, Explorer/Assets/DCL/Friends/IFriendsService.cs.meta, Explorer/Assets/DCL/Friends/RPCFriendsService.cs, Explorer/Assets/DCL/Friends/RPCFriendsService.cs.meta, Explorer/Assets/DCL/Friends/csc.rsp, Explorer/Assets/DCL/Friends/csc.rsp.meta, Explorer/Assets/DCL/PluginSystem/DCL.Plugins.asmdef, Explorer/Assets/DCL/PluginSystem/Global/FriendsPlugin.cs, Explorer/Assets/DCL/PluginSystem/Global/FriendsPlugin.cs.meta, Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
This is the base structure for the friends feature. It does not contain any implementation nor doesnt have any call from the real application flow.
2. Check that the startup flow runs as expected
=> feat: friends plugin, service & event bus interfaces

Explorer/Assets/DCL/Chat/ChatController.cs, Explorer/Assets/DCL/Input/Systems/UpdateCursorInputSystem.cs, Explorer/Assets/DCL/Input/UnityInputSystem/DCLInput.cs, Explorer/Assets/DCL/Input/UnityInputSystem/DCLInput.inputactions
Added 2 shortcuts for chat to enhance accessibility.
1. "T" - open chat
2. "/" - open chat with a slash for commands
2. Check shortcuts
3. Play happy path
=> Feat: chat shortcuts

Explorer/Assets/DCL/Multiplayer/Connections/Messaging/Hubs/MessagePipesHub.cs, Explorer/Assets/DCL/Multiplayer/Connections/Messaging/Throughput.meta, Explorer/Assets/DCL/Multiplayer/Connections/Messaging/Throughput/DataPipeExtensions.cs, Explorer/Assets/DCL/Multiplayer/Connections/Messaging/Throughput/DataPipeExtensions.cs.meta, Explorer/Assets/DCL/Multiplayer/Connections/Messaging/Throughput/IThroughputBuffer.cs, Explorer/Assets/DCL/Multiplayer/Connections/Messaging/Throughput/IThroughputBuffer.cs.meta, Explorer/Assets/DCL/Multiplayer/Connections/Messaging/Throughput/ThroughputBuffer.cs, Explorer/Assets/DCL/Multiplayer/Connections/Messaging/Throughput/ThroughputBuffer.cs.meta, Explorer/Assets/DCL/Multiplayer/Connections/Messaging/Throughput/ThroughputBufferBunch.cs, Explorer/Assets/DCL/Multiplayer/Connections/Messaging/Throughput/ThroughputBufferBunch.cs.meta, Explorer/Assets/DCL/Multiplayer/Connections/Messaging/Throughput/ThroughputMeasureDataPipe.cs, Explorer/Assets/DCL/Multiplayer/Connections/Messaging/Throughput/ThroughputMeasureDataPipe.cs.meta, Explorer/Assets/DCL/Multiplayer/Connections/Systems/DebugRoomsSystem.cs, Explorer/Assets/DCL/Multiplayer/Connections/Systems/DebugThroughputRoomsSystem.cs, Explorer/Assets/DCL/Multiplayer/Connections/Systems/DebugThroughputRoomsSystem.cs.meta, Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/Builders/IDebugContainerBuilder.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/DebugUtilitiesContainer.cs, Explorer/Assets/DCL/PluginSystem/Global/MultiplayerPlugin.cs, Explorer/Assets/Scripts/ECS/StreamableLoading/Cache/ISizedContent.cs, Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs, Explorer/Assets/Scripts/Utility/ByteSize.cs, Explorer/Assets/Scripts/Utility/ByteSize.cs.meta
Added a tab to the debug panel that allows to view livekit rooms throughput
2. Play happy path
3. Open debug panel, go to "Room: Throughput" tab and view the values
=> Feat: Throughput measure

.github/workflows/enforce-group-approvals.yml
Correct approval workflow
Setup ORG_ACCESS_TOKEN
Add error handling on fetch calls
2. ...
=> feat: correct approval workflow

.github/auto_assign_config.yml
Add missing users in auto assign config
=> chore: add missing users to github review group

Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/SignedFetch/SignedFetchWrap.cs
fixes: https://github.com/decentraland/unity-explorer/issues/3136
and any other scene that tries to use a DELETE method ( I do not know which! )
=> fix: add delete method to signed fetch.

Explorer/Assets/DCL/Chat/Assets/Chat.prefab, Explorer/Assets/DCL/Chat/Assets/ChatMessageViewerElement.prefab, Explorer/Assets/DCL/Chat/Assets/ChatMessageViewerElement.prefab.meta, Explorer/Assets/DCL/Chat/ChatController.cs, Explorer/Assets/DCL/Chat/ChatMessageViewerElement.cs, Explorer/Assets/DCL/Chat/ChatMessageViewerElement.cs.meta, Explorer/Assets/DCL/Chat/ChatView.cs
Some functionality of the ChatView has been moved to the new ChatMessageViewerElement script.
=> The scrollview of the chat has been converted into an independent UI element

Explorer/Assets/DCL/AvatarRendering/AvatarShape/Components/AvatarShapeComponent.cs
=> fix: Outline Rendering of weird meshes

Explorer/Assets/Scripts/ECS/StreamableLoading/Cache/Disk/Playgrounds/CacheTest.meta
This change commits the deletion of a meta file Unity keeps making. It was annoying me.
This change has no effect on the game or the editor. I would not bother testing.
2. Play normally
=> Unity keeps deleting this file

Explorer/Assets/Plugins/TexturesFuse/TexturesServerWrap/Playground/NormalMap/brick_wall2-diff-512.png.meta
This change fixes a broken meta file for a brick texture for a playground.
Nothing to test. The affected texture is not used in the game.
=> Fix broken meta file brick_wall2-diff-512.png.meta

Explorer/Assets/DCL/Character/CharacterCamera/Character Camera.prefab, Explorer/Assets/DCL/RealmNavigation/Container/RealmContainer.cs, Explorer/Assets/StreamingAssets/Js/Init.js
=> Sync release to dev

.github/PULL_REQUEST_TEMPLATE.md
This change updates the pull request template to match [what Aga posted on Slack](https://decentralandteam.slack.com/archives/C03G496L6NN/p1738841970016839) so that her instructions are not lost and forgotten.
1. [Read the new pull request template](https://raw.githubusercontent.com/decentraland/unity-explorer/65d041aa645e189e380985094361660f623b1744/.github/PULL_REQUEST_TEMPLATE.md)
2. Think if anything is unclear in it
=> Update the pull request template to match what Aga asked for

.github/workflows/build-unitycloud.yml
Only performs a unity cloud build when files change inside of ./Explorer.
No direct QA needed.
=> fix: only rebuild when explorer files change.

.github/workflows/test.yml
Avoids rerunning tests when something changes outside of Unity directory.
=> fix: update test.yml

Explorer/Packages/manifest.json
I am listing ClearScript as testable. By default non-local, non-embedded packages are excluded from unit tests.
Not applicable.
=> Include ClearScript in unit tests

Explorer/Assets/Plugins/TexturesFuse/Editor/TexturesFuseBuildProcess.cs
This change fixes an exception in a build script. Without it, the build process did not run to completion, which manifested itself as, among other things, git status pollution.
Play on Windows and pay attention to textures and game's performance. Visit an art gallery or something.
=> Fix an exception in Fuse build process

.github/workflows/enforce-group-approvals.yml
- correct proper exlusion of draft PRs on enforce-approvals
=> fix: correct proper exlusion of draft PRs on enforce-approvals

Explorer/Assets/DCL/PluginSystem/World/TexturesLoadingPlugin.cs, Explorer/Assets/Scripts/Global/Dynamic/MainSceneLoader.cs, Explorer/Assets/Scripts/Global/StaticContainer.cs
Disables cache for LSD
1. Load a local scene with a texture
2. Change the texture
3. Do a hot reload
4. See that the new texture has been replaced on the hot reload
=> fix: Disable disk cache on LSD

Explorer/Assets/DCL/RealmNavigation/Container/RealmNavigationContainer.cs.meta, Explorer/Assets/Protocol/DecentralandProtocol/LightSource.gen.cs.meta
This change fixes a couple broken meta files.
Do whatever minimal testing you feel like. This change has no impact on the game itself.
=> Fix meta files

Explorer/Packages/packages-lock.json
This change ha the game use the latest version of the ClearScript Unity package.
1. Visit complex scenes with lots of scripting
2. Look for scenes failing to load or run
=> Update ClearScript, switch Invoke to readonly ref struct scopes

Explorer/Assets/DCL/Audio/AudioMixerVolumesController.cs
Fixes https://github.com/decentraland/unity-explorer/issues/2038
Fixes https://github.com/decentraland/unity-explorer/issues/2994
=> fix: audio issue on first spawn

Explorer/Assets/DCL/Settings/Configuration/SettingsMenuConfiguration.asset
Changes texts on chat audio settings to respect designs
=> fix: Chat audio settings texts

Explorer/Assets/DCL/Chat/ChatMessageViewerElement.cs, Explorer/Assets/DCL/UI/InputSuggestions/ProfileInputSuggestionElement.prefab
Added check and warning when index for chat messages could be potentially faulty + fixed issue with masking on profile suggestions
For the first issue, we dont know xD 
For the second, get more than 5 Profile suggestions, now the frames should be properly masked.
=> fix: chat stuff

Explorer/Assets/DCL/Tests/Editor/DCL.EditMode.Tests.asmdef, Explorer/Assets/Scripts/SceneRuntime/Factory/Tests/JsCodeDiskSerializerShould.cs
This test was broken on my local environments (Mac and Windows both), fixed by the filling the buffer. Added extra coverage for the intermediate data validation.
1. NO QA
=> Fix: js code test

Explorer/Assets/DCL/NameTags/Systems/NametagPlacementSystem.cs
Fixes a null ref when profile is null
Do whatever Santi was doing xD
=> Fix for nametag issue with color

.gitmodules, Explorer/Assets/Scripts/Global/Dynamic/BootstrapContainer.cs, TexturesFuse/README.md
This removes old submodules from .gitmodules and adds links to our forks to the TexturesFuse readme.
1. Just a smoke test
=> Clean up submodules

Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportsHandlingSettingsDevelopment.asset, Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportsHandlingSettingsProduction.asset
Enables asserts & exception reports to sentry of the friends category.
Nothing important to check, just an overall roundup, as the changes do not modify any flow.
=> fix: enable sentry reports of friends category

Explorer/Assets/DCL/UI/Controls/ControlsPanel.prefab, Explorer/Assets/DCL/UI/Controls/Textures/Controls.png, Explorer/Assets/DCL/UI/Controls/Textures/Controls.png.meta
Fixes the size / compression of the controls overlay image.
fixes #3347
1. Open Explorer
2. Open Controls overlay and make sure it still works / looks ok.
=> fix: controls panel image compression / size

Explorer/Assets/DCL/AvatarRendering/Shaders/DCL_Toon/DCL_Toon.shader, Explorer/Assets/DCL/AvatarRendering/Shaders/DCL_Toon/DCL_ToonBodyDoubleShadeWithFeather.hlsl
Emission not so bright
load up player
see that avatar emission is about half of the super bright version
=> fix: emissive brightness

.github/workflows/enforce-group-approvals.yml
- Added support for new PR events (review_requested, review_request_removed, review.dismissed) to keep approval checks reactive and accurate
- Introduced filtering to exclude pending reviewers from approval checks, ensuring only completed approvals are considered
- Added a new step to detect previously failed runs of the same workflow for the current commit
- Automatically re-triggers the workflow if approvals are valid and a previous run failed
- Improved logging and output formatting for easier debugging and better visibility during workflow execution
=> fix: refine PR approval logic and add auto re-run

Explorer/Assets/DCL/Friends/RPCFriendsService.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportsHandlingSettingsDevelopment.asset, Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportsHandlingSettingsProduction.asset, Explorer/Assets/DCL/Profiles/ProfileThumbnailCache.cs
- Aligned Sentry matrix
- Disabled unnessecary rethrows of cancellation
- Play happy paths, no game code has changed.
=> fix: update report handling to include exceptions and assertions that we previously missed

Explorer/Assets/DCL/Infrastructure/Global/Dynamic/PortableExperiences/ECSPortableExperiencesController.cs
Just cherrypicked the fix from release branch
=> fix: killpx does bad things #3821

Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerSystem.cs
This change adds some profiling markers around MediaPlayer calls that I suspect can take a long time. MediaPlayerSystem shows up in the profiler a lot, and this is to narrow down the cause.
Visit a scene with video textures and see that they still work.
=> Add some profiling markers for MediaPlayer

.github/workflows/build-unitycloud.yml, .github/workflows/pr-comment-artifact-url.yml, Explorer/.gitignore
- add github event name code for "schedule"
- adjusted generic code from "gen" to "gn" for better future alignment
=> chore: add github event name code for schedule

README.md
Updates the required version in readme
=> chore: update version in the readme

Explorer/Assets/DCL/Friends/WebSocketRpcTransport.cs
This change duct tapes this Sentry issue: https://decentraland.sentry.io/issues/6416842773/
Test that friend requests can be sent and are received.
=> Duct tape object disposed exception in friends service

Explorer/Assets/DCL/Chat/Assets/Chat.prefab, Explorer/Assets/DCL/Chat/Assets/ChatTitlebarDefault.prefab, Explorer/Assets/DCL/Chat/Assets/VoiceChatOnCallTitlebar.prefab, Explorer/Assets/DCL/Chat/Assets/VoiceChatOnCallTitlebar.prefab.meta, Explorer/Assets/DCL/Chat/Assets/VoiceChatTitleBarsContainer.prefab, Explorer/Assets/DCL/Chat/Assets/VoiceChatTitleBarsContainer.prefab.meta
Because we want to avoid big conflicts with possible chat changes between communities and voice chat shapes, we applied a quick change in the chat prefab structure to allow future resize of the panel, as of now it won't have any visible changes
1. Launch DCL
2. Verify that the chat is working as before
=> chore: minor changes to chat to allow auto scaling of panel

Explorer/Assets/DCL/Communities/Communities.asmdef, Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesBrowserController.cs, Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesBrowserController.cs.meta, Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesBrowserView.cs, Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesBrowserView.cs.meta, Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs.meta, Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/CommunitiesBrowser.prefab, Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/CommunitiesBrowser.prefab.meta, Explorer/Assets/DCL/ExplorePanel/Assets/ExplorePanelUI.prefab, Explorer/Assets/DCL/ExplorePanel/ExplorePanel.asmdef, Explorer/Assets/DCL/ExplorePanel/ExplorePanelController.cs, Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs, Explorer/Assets/DCL/Input/UnityInputSystem/DCLInput.cs, Explorer/Assets/DCL/Input/UnityInputSystem/DCLInput.inputactions, Explorer/Assets/DCL/PluginSystem/DCL.Plugins.asmdef, Explorer/Assets/DCL/PluginSystem/Global/ExplorePanelPlugin.cs, Explorer/Assets/DCL/UI/ExploreSections.cs, Explorer/Assets/DCL/UI/SharedSpaceManager/SharedSpaceManagerImpl/SharedSpaceManager.cs
- New empty COMMNUNITIES section in the Explore Menu.
- [O] shortcut key implemented to directly open the section.
- Use of the Feature Flag to show/hide the section.
=> [Communities] New empty section in Explorer Menu

Explorer/Assets/DCL/Infrastructure/CrdtEcsBridge/JsModulesImplementation/ClientWebSocketApiImplementation.cs, Explorer/Assets/DCL/Infrastructure/SceneRuntime/Apis/Modules/WebSocket/IWebSocketApi.cs, Explorer/Assets/DCL/Infrastructure/SceneRuntime/Apis/Modules/WebSocket/WebSocketApiWrapper.cs
Fixes #4012 
Test according to the instructions in the attached ticket
=> Fix: WebSocket. Fix the size of the outgoing binary

Explorer/Assets/DCL/Settings/Settings/VoiceChatSettingsAsset.cs, Explorer/Assets/DCL/VoiceChat/VoiceChatHandler.cs
Adds different input detection to handle T as both a toggle key and push to talk key for voicechat interaction
1. First step
2. Second step
4. ...
=> chore: push to talk and continuos voice communication

Explorer/Assets/DCL/Audio/AudioMixerVolumesController.cs, Explorer/Assets/DCL/Audio/Prefabs/GeneralAudioMixer.mixer, Explorer/Assets/DCL/Settings/Configuration/SettingsMenuConfiguration.asset, Explorer/Assets/DCL/Settings/Configuration/SliderModuleBinding.cs, Explorer/Assets/DCL/Settings/ModuleControllers/VoiceChatVolumeSettingsController.cs, Explorer/Assets/DCL/Settings/ModuleControllers/VoiceChatVolumeSettingsController.cs.meta
Added voice chat volume slider in settings and mixer audio track for voice chat
=> feat: added voice chat volume settings and mixer track

Explorer/Assets/DCL/Infrastructure/ECS/SceneLifeCycle/ECSReloadScene.cs
Fixes reload scene
1. Do a `/reload` on any scene/world you can imagine
2. Try the hot reload in LSD
=> fix: reload scene

Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandUrl.cs, Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandUrlsSource.cs, Explorer/Assets/DCL/Communities/Communities.asmdef, Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesBrowserController.cs, Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesBrowserView.cs, Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunityResultCardView.cs, Explorer/Assets/DCL/Communities/CommunitiesBrowser/MyCommunityCardView.cs, Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/CommunityResultCard.prefab, Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/MyCommunityCard.prefab, Explorer/Assets/DCL/Communities/CommunitiesDataProvider/CommunitiesDataProvider.cs, Explorer/Assets/DCL/Communities/CommunitiesDataProvider/DTOs/CommunityMemberRole.cs, Explorer/Assets/DCL/Communities/CommunitiesDataProvider/DTOs/GetUserCommunitiesResponse.cs, Explorer/Assets/DCL/Communities/CommunitiesDataProvider/FakeCommunitiesDataProvider.cs, Explorer/Assets/DCL/Communities/CommunitiesDataProvider/ICommunitiesDataProvider.cs, Explorer/Assets/DCL/ExplorePanel/Assets/ExplorePanelUI.prefab, Explorer/Assets/DCL/ExplorePanel/ExplorePanelView.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportCategory.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportsHandlingSettingsDevelopment.asset, Explorer/Assets/DCL/PluginSystem/Global/ExplorePanelPlugin.cs
Fix #4316 
It integrates the `https://social-service-ea.decentraland.{ENV}/v1/communities`  endpoint in the Communities Browser.
1. Open the build pointing to `zone` -> `dclenv zone`.
2. Open the Communities Browser in the Explore Menu.
3. Check that you're receiving all the communities that are currently created in the `zone` database.
4. Test the browser overall: list of my communities, "View All My Communities" button, search bar, navigation between states...
**NOTE 1**: All the received data in the browser now is not fake but it comes from back-end 👍 
**NOTE 2**: The join community action is still fake.
=> [SHAPE-UP] Communities (GET Communities endpoint integration)

Explorer/Assets/Protocol/DecentralandProtocol/InputAction.gen.cs, Explorer/Assets/Protocol/DecentralandProtocol/PrimaryPointerInfo.gen.cs, Explorer/Assets/Protocol/DecentralandProtocol/RealmInfo.gen.cs, Explorer/Assets/Protocol/DecentralandProtocol/SocialServiceV2.gen.cs, scripts/package-lock.json, scripts/package.json
=> Updated protocol experimental branch and rebuilt classes

Explorer/Assets/DCL/Chat/Assets/Chat.prefab, Explorer/Assets/DCL/Chat/Assets/ChatTitleBarsContainer.prefab, Explorer/Assets/DCL/Chat/ChatController.cs, Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs, Explorer/Assets/DCL/PluginSystem/Global/VoiceChatPlugin.cs, Explorer/Assets/DCL/VoiceChat/CallButtonController.cs, Explorer/Assets/DCL/VoiceChat/DCL.VoiceChat.asmdef, Explorer/Assets/DCL/VoiceChat/VoiceChatController.cs, Explorer/Assets/DCL/VoiceChat/VoiceChatView.cs
1. First step
2. Second step
4. ...
=> some UI fixes from merge conflcits

.github/workflows/claude-pr-review.yml
Be more accurate with the claude prompt.
=> chore: update claude prompt

Explorer/Assets/DCL/SDKComponents/SceneUI/Utils/UiElementUtils.cs
Fixes the default opacity value for scene ui elements
=> fix: scene ui default opacity

Explorer/Assets/DCL/Communities/CommunitiesCard/CommunityFetchingControllerBase.cs, Explorer/Assets/DCL/Communities/CommunitiesCard/Events/EventListController.cs, Explorer/Assets/DCL/Communities/CommunitiesCard/Events/EventListView.cs, Explorer/Assets/DCL/Communities/CommunitiesCard/ICommunityFetchingView.cs, Explorer/Assets/DCL/Communities/CommunitiesCard/Members/MembersListController.cs, Explorer/Assets/DCL/Communities/CommunitiesCard/Members/MembersListView.cs, Explorer/Assets/DCL/Communities/CommunitiesCard/Places/PlacesSectionController.cs, Explorer/Assets/DCL/Communities/CommunitiesCard/Places/PlacesSectionView.cs
1. First step
2. Second step
4. ...
=> Fix: community fetching view data assignment

Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesBrowserController.cs, Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesBrowserView.cs, Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunityResultCardView.cs, Explorer/Assets/DCL/Communities/CommunitiesBrowser/MyCommunityCardView.cs, Explorer/Assets/DCL/Communities/CommunitiesDataProvider/CommunitiesDataProvider.cs, Explorer/Assets/DCL/Communities/CommunitiesFeatureAccess.cs, Explorer/Assets/DCL/Communities/CommunitiesUtility.cs, Explorer/Assets/DCL/Communities/CommunityCreation/CommunityCreationEditionController.cs, Explorer/Assets/DCL/Communities/CommunityCreation/CommunityCreationEditionView.cs, Explorer/Assets/DCL/Communities/CommunityCreation/CommunityPlaceTag.cs, Explorer/Assets/DCL/UI/ISpriteCache.cs, Explorer/Assets/DCL/UI/SpriteCache.cs
Fixes warnings related to nullable rules.
=> [SHAPE-UP] Communities (Community browser and wizard null fixes)

.github/workflows/build-profile-nightly.yml
Skip the nightly if no changes since the last nightly.
=> chore: skip the nightly if no changes since the last nightly.

Explorer/Assets/DCL/Multiplayer/Connections/Rooms/Connective/IConnectiveRoom.cs
Fixed typo in ToStringNonAlloc method
1. Happy path
=> fix: connection loop health typo

Explorer/Assets/DCL/SDKComponents/MediaStream/MultiMediaPlayer.cs, Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/InitializeVideoPlayerMaterialsSystem.cs
Fixes streaming scaling and moved logic to the REnum MediaPlayerComponent to streamline it.
=> fix: streaming scaling

Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs
Ignore deeplink runtime handling logic for LSD instances, part of solution for: https://github.com/decentraland/launcher-rust/issues/140
1. Test together with https://github.com/decentraland/launcher-rust/pull/141
=> feat: exclude lsd instances

.github/ISSUE_TEMPLATE/bug_report.md
1. First step
2. Second step
4. ...
=> chore: Update bug_report.md

Explorer/Assets/DCL/ExplorePanel/Assets/Animations/CommunitiesTab/Hover.anim, Explorer/Assets/DCL/ExplorePanel/Assets/Animations/CommunitiesTab/Unhover.anim
Fix #4902 
Edited the hover and unhover animations for the Communities button in order to make them faster.
=> fix: Communities button animation

Explorer/Assets/DCL/SDKComponents/LightSource/Prefab/LightSourceSettings.asset
Just tweaking some light settings so that it's easier to achieve similar results between different clients.
We can use the same [test scene](https://github.com/user-attachments/files/21601725/Lights.Testing.zip) we have been using so far, although nothing different is expected to happen, just lights are a bit less bright now.
=> chore: tweaked light settings

Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunityResultCardView.cs, Explorer/Assets/DCL/Communities/CommunitiesBrowser/ListenersCountView.cs, Explorer/Assets/DCL/Communities/CommunitiesBrowser/ListenersCountView.cs.meta, Explorer/Assets/DCL/Communities/CommunitiesBrowser/MyCommunityCardView.cs, Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/CommunityResultCard.prefab, Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/ListenersCounter.prefab, Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/ListenersCounter.prefab.meta, Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/MyCommunityCard.prefab
This PR adds some prefabs in the community and my community entries prefabs to avoid conflicts and allow easier integration of community voice chat changes
Simple smoke test of the communities browser that validates everything looks as before in the list "My Communities" and community browser
=> feat: prefab changes to community entries

Explorer/Assets/DCL/Chat/_Refactor/ChatTitleBar/ChatTitlebarPresenter.cs
Fixes multiple selections allowed in the chat channel context menu sound settings
1. Open chat channel context menu
2. Select one option
3. Select different option
4. Observe that you can select only one option
=> Fix context menu sounds setting for chat channel

.github/workflows/test.yml
For running tests with adddressables we need full image to run the editor tests
=> fix: using il2cpp windows target version for test.yml

Explorer/Packages/packages-lock.json
Updated Systems Visualiser Package to v1.1.0 which includes:
🟢 A simpler tree-view layout
🟢 Filter systems by name
🟢 Systems are highlighted by filter
🟢 Retain selection when clearing filters
🟢 See which systems are throttled
🟢 Collapse All/Expand All
1. Checkout Branch
2. Load Editor
3. Go to the menu Arch -> Systems
4. Enter play mode
5. Ensure filtering works & the tree is navigatable
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md …
=> chore: update visualiser package to v1.1.0

.github/workflows/test.yml
1. First step
2. Second step
4. ...
=> test: run on ubuntu-latest

Explorer/Packages/manifest.json, Explorer/Packages/packages-lock.json
Ensure the correct RenderFeature package is referenced.
=> hotfix: reference correct package

Explorer/Assets/DCL/Infrastructure/CRDT/CRDTFilter.cs, Explorer/Assets/DCL/Infrastructure/CRDT/CRDTFilter.cs.meta, Explorer/Assets/DCL/Infrastructure/CRDT/Protocol/CRDTMessageType.cs, Explorer/Assets/DCL/Infrastructure/CrdtEcsBridge/JsModulesImplementation/Communications/CommunicationsControllerAPIImplementationBase.cs, Explorer/Assets/DCL/Infrastructure/CrdtEcsBridge/JsModulesImplementation/Tests/CommunicationControllerAPIImplementationShould.cs, Explorer/Assets/DCL/Infrastructure/Utility/ByteUtils.cs
1. First step
2. Second step
4. ...
=> hotfix: filter

Explorer/Assets/Rendering/ForwardRenderer - High.asset, Explorer/Assets/Rendering/ForwardRenderer - Low.asset, Explorer/Assets/Rendering/ForwardRenderer - Medium.asset, Explorer/Packages/packages-lock.json, Explorer/ProjectSettings/GraphicsSettings.asset
Reverts decentraland/unity-explorer#5587
=> Revert "feat: skybox to cubemap render feature"

Explorer/Assets/DCL/VoiceChat/CommunityVoiceChatCallStatusServiceNull.cs, Explorer/Assets/DCL/VoiceChat/PrivateVoiceChatCallStatusServiceNull.cs, Explorer/Assets/link.xml
Fixes #5640
This PR sets a non-null value in the service-null implementation of the voice chat (private and communities) `CallId` and `Status`reactive property.
=> fix: communities not loading
