Explorer/Assets/Scripts/ECS/ComponentsPooling/Systems/ReleasePoolableComponentSystem.cs, Explorer/Assets/Scripts/SceneRunner/ECSWorld/ECSWorldFactory.cs
The `DestroyEntitySystem` was not being injected, causing objects that were already released on the pool to be released again.
=> Fix: inject destroy entity world

Explorer/Assets/Scripts/ECS/SceneLifeCycle/SceneFacade/Systems/LoadSceneSystemLogic.cs
Some scene definitions don't include a scene.json in their content array. Therefore, this stops some scenes from rendering altogether.
The metadata and the scene.json fetched should be, in theory, the same. So, in cases where the scene.json is not present, we can still work with the one that comes with the metadata.
IE: 
Alvaro's world (https://worlds-content-server.decentraland.org/contents/bafkreie5is3bddgjczpd2dx2xpdqxsenifppr4jmc36hbbae6rmcbr2hom), done in SDK7 , does not include a reference to scene.json in its content.  Without this PR change, this world does not work
=> fix: Load scene even if scene.json is not present in content

Explorer/Assets/Scenes/DynamicSceneLoading.unity, Explorer/Assets/Scripts/Global/Dynamic/DynamicSceneLoader.cs, Explorer/Assets/Scripts/Global/Dynamic/DynamicSceneLoaderSettings.asset, Explorer/Assets/Scripts/Global/Dynamic/DynamicSceneLoaderSettings.asset.meta, Explorer/Assets/Scripts/Global/Dynamic/DynamicSceneLoaderSettings.cs, Explorer/Assets/Scripts/Global/Dynamic/DynamicSceneLoaderSettings.cs.meta
This pull request introduces a scriptable object that contains settings from `DynamicSceneLoader`.
This makes it easier to change settings without need to update the actual scene, and makes merge conflict resolve easier.
This will also allow us to have different presets of configuration files if we need.
=> chore: add scriptable object for dynamic scene loader settings

Explorer/Assets/DCL/Backpack/BackpackSettings.cs, Explorer/Assets/DCL/PluginSystem/Global/ExplorePanelPlugin.cs, Explorer/Assets/Scenes/DynamicSceneLoading.unity
Changed reference type from scriptable object in `BackpackSettings` to `AssetReference` to avoid duplication of assets that are part of addressables.
Before:
After:
=> chore: moved backpack settings to use asset reference

Explorer/Assets/DCL/Minimap/Assets/Minimap.prefab, Explorer/Assets/DCL/Minimap/Assets/SideMenu.prefab, Explorer/Assets/DCL/Navmap/Assets/Navmap.prefab, Explorer/Assets/DCL/UI/Assets/Toggle.prefab
On one hand the mini map side menu
On the other hand, the POI tooltip inside the Nav Map's filters
=> style: polish mini map menu

Explorer/Assets/Scripts/ECS/Prioritization/DistanceBasedComparer.cs, Explorer/Assets/Scripts/ECS/SceneLifeCycle/IncreasingRadius/ResolveSceneStateByIncreasingRadiusSystem.cs, Explorer/Assets/Scripts/ECS/SceneLifeCycle/Tests/ResolveSceneStateByIncreasingRadiusSystemShould.cs, Explorer/Assets/Scripts/Utility/ParcelMathJobifiedHelper.cs
The problem with sorting performance starts to appear when `MaxLoadingDistanceInParcels` is big, for example `50`
**Before:**
**After:**
Job impact is hardly noticeable (the screenshot is taken in Deep Profiling) but throttling in frames can be quite high depending on the current load: 5-10 frames.
=> Jobify scenes sorting

Explorer/Assets/DCL/SkyBox/Rendering/DCL_RenderPass_GenerateSkyBox.cs
Star Buffer was leaking every frame
=> fix: Initialize Stars Buffer only once to prevent leaks

Explorer/Assets/AddressableAssetsData/AssetGroups/Localization-Locales.asset
We dont provide any content for italian and spanish languages. This is bringing some issues since we require loadings tips to be available, but it crashes if you have your system on spanish or italian.
=> fix: removed italian & spanish from localization settings

Explorer/Assets/DCL/Tests/Editor/ValidationTests.cs
Add validation test to check missing references in unity objects (static assets like prefabs or scriptable objects)
=> Chore: assets validation for missing refs

Explorer/Assets/DCL/SDKComponents/TextShape/Renderer/Factory/TextShapeRendererFactory.cs
I found a little bug with the direction of text in static demo worlds.
remove backward flipping fixed it.
=> chore: remove backward TextShape

Explorer/Assets/Scenes/Main.unity
You get stuck into the splash animation if you have a low frame-rate.
The fix consists to avoid skipping frames in the video player configuration.
1. Start the app with a low-end pc
2. Check that you always go through the splash screen and eventually into the authentication screen
=> fix: splash never ending animation

Explorer/Assets/DCL/Minimap/Assets/Minimap.prefab
Currently, some scene names overlap the divider line that separates it from the menu button in the mini map.
This PR reduce the width of the scene's name text box to fix that aesthetic issue which happens with large names only.
Example bellow
Open the client. Then go to a scene with a very large name and check that the text component on the mini map is not touching the divider line anymore.
=> style: reduce scene's name text box width in the mini map

Explorer/Assets/AddressableAssetsData/AssetGroups/Localization-Locales.asset, Explorer/Assets/AddressableAssetsData/Windows/addressables_content_state.bin.meta, Explorer/Assets/Locales/Localization Tables/SceneLoadingScreen.asset
It fixes an error during the initialization because the spanish (or italian) languages didn't have its localization tables configured. The issue happened only for OS configured in spanish or italian.
=> fix: remove spanish and italian languages

Explorer/Assets/DCL/AvatarRendering/DemoScripts/Systems/InstantiateRandomAvatarsSystem.cs
Updated random avatar instantiation system in order to use `CharacterTransform` instead of `TransformComponent`
For QA:
Enter the main realm and verify that the Intantiate avatar option in the debug panel works correctly
=> Fix: fixed random avatar instantiation debug option

Explorer/Assets/DCL/Backpack/BackpackCharacterPreviewController.cs, Explorer/Assets/DCL/Utilities/DisposableUtils.cs, Explorer/Assets/DCL/Utilities/DisposableUtils.cs.meta, Explorer/Assets/Scripts/ECS/SceneLifeCycle/SceneFacade/Systems/LoadEmptySceneSystemLogic.cs, Explorer/Assets/Scripts/ECS/SceneLifeCycle/Tests/LoadEmptySceneSystemShould.cs, Explorer/Assets/Scripts/Global/Dynamic/IRealmController.cs, Explorer/Assets/Scripts/Global/Dynamic/MainSceneLoader.cs, Explorer/Assets/Scripts/Global/Dynamic/RealmController.cs, Explorer/Assets/Scripts/SceneRunner/EmptyScene/EmptySceneFacade.cs, Explorer/Assets/Scripts/SceneRunner/Scene/ISceneFacade.cs, Explorer/Assets/Scripts/SceneRunner/SceneFacade.cs
* The destruction flow made sync as it can't be executed asynchronously in an understandable manner
* `SafeDispose` catches an exception and logs it with additional information
* All plugins and scenes now are disposed of with safety
Example of the log with the inner exception:
```
NullReferenceException: Object reference not set to an instance of an object
at DCL.CharacterPreview.CharacterPreviewController.Dispose () [0x00001] in D:\Decentraland\unity-explorer\Explorer\Assets\DCL\CharacterPreview\CharacterPreviewController.cs:42 
at DCL.CharacterPreview.BackpackCharacterPreviewController.Dispose () [0x000a5] in D:\Decentraland\unity-explorer\Explorer\Assets\DCL\Backpack\BackpackCharacterPreviewController.cs:76 
at DCL.Backpack.BackpackControler.Dispose () [0x00048] in …
```
=> fix: Introduce SafeDispose to make the destruction flow uninterruptible

Explorer/Assets/DCL/AuthenticationScreenFlow/Assets/AuthenticationScreen.prefab, Explorer/Assets/DCL/Character/CharacterPreview/Assets/CharacterPreviewCameraSettings_LoadingScreen.asset, Explorer/Assets/DCL/Character/CharacterPreview/CharacterPreviewCameraController.cs, Explorer/Assets/DCL/ExplorePanel/Assets/PersistentExploreOpener.prefab
- The zoom & panning has been enabled on authentication screen so you can properly preview avatars that get out of screen
- Prevent avatar preview from clipping on the top on authentication screen
- Reverted direction of rotation on avatar preview
- Explore menu icon moved next to the map
- Go through the authentication screen
- Check your avatar is correctly previewed with no clipping
- Check you can zoom in/out with scroll and pan the camera dragging right click button
- Jump into the world
- Check the explore menu button is working as expected (next to the minimap)
- Quit the application through the system menu by clicking on your avatar's capsule. The app should close correctly without any crashes
=> polishment: diverse ux improvements

Explorer/Assets/StreamingAssets/AssetBundles/Wearables/dcl/scene_ignore_windows, Explorer/Assets/StreamingAssets/AssetBundles/Wearables/dcl/scene_ignore_windows.meta
Before the fix:
After the fix:
Used profile:
`0x9dB59920d3776c2d8A3aA0CbD7b16d81FcAb0A2b`
=> fix: wearables not loading because of missing AB dependency

.github/workflows/build-Mac-il2cpp.yml, .github/workflows/build-Windows-il2cpp.yml, Explorer/Packages/packages-lock.json
- bump unity-builder version to 0.9 which removes step for importing required packages, that are not used on alpha
- bumped hash for grass shader package, this includes fix for this error `Asset Packages/decentraland.grassshader/package.json has no meta file, but it's in an immutable folder. The asset will be ignored.`
=> chore: update unity builder action

Explorer/Assets/DCL/Character/CharacterMotion/Systems/InterpolateCharacterSystem.cs
Sometimes, when we made a teleport (through the debug panel, the map or the `movePlayerTo` SDK action), the player got stuck in the current position and the teleport wasn't applied. This happened randomly, sometimes the telport worked and sometimes not.
1. Enter the world.
2. Try to teleport to any coords using the debug panel.
3. Notice the teleport is ALWAYS performed and not randomly as before.
=> fix: teleport sometimes fails

Explorer/Assets/DCL/Landscape/Config/Editor/TerrainGeneratorTestEditor.cs, Explorer/Assets/DCL/Landscape/Jobs/GenerateTreeInstancesJob.cs, Explorer/Assets/DCL/Landscape/Jobs/SetupRandomForParallelJobs.cs, Explorer/Assets/DCL/Landscape/Jobs/SetupRandomForParallelJobs.cs.meta, Explorer/Assets/DCL/Landscape/TerrainGenerator.cs, Explorer/Assets/DCL/Landscape/TerrainGeneratorTest.cs, Explorer/Assets/DCL/Landscape/Utils/TerrainGeneratorLocalCache.cs
Fixed trees & stones are not being deterministically placed at the same position on every client due to a race condition with `Random` usage in `IJobParallelFor` jobs.
The random is now being created for each chunk position using the seed and its index to be used during the parallel job, deterministically working for every seed.
=> fix: deterministic terrain generation

Explorer/Assets/DCL/AuthenticationScreenFlow/Assets/AuthenticationScreen.prefab, Explorer/Assets/DCL/SceneLoadingScreens/Assets/SceneLoadingScreen.prefab, Explorer/Assets/Textures/Authentication/Packed/DclLogotype.png, Explorer/Assets/Textures/Authentication/Packed/DclWordmark.png, Explorer/Assets/Textures/Authentication/Packed/DclWordmark.png.meta
The DCL logo has a brand new look. This PR was created to update the logo texture.
Collaterally, the `SceneLoadingScreen` and `AuthenticationScreen` prefabs were modified because the logo game object needed to be resized.
=> style: update Decentraland logo

Explorer/Assets/DCL/Ipfs/SceneMetadata.cs, Explorer/Assets/DCL/Ipfs/SpawnPointConverter.cs, Explorer/Assets/DCL/ParcelsService/TeleportController.cs
Fixes inability to teleport to the spawn point. E.g. `(-9, 91)` coordinate
=> fix: Each individual coordinate can be either an array or a plain value

Explorer/ProjectSettings/PackageManagerSettings.asset
Since [the commit](https://github.com/decentraland/unity-explorer/commit/ec5495c40662dc435b7b3f041c061e98f6075ee2) that adds the "Animation Sequencer" unity package in the unity project, I haven't been able to load the unity project at all (I use a macbook pro intel 2019).
It stays in the following frozen state forever:
Replicating the adding of the desired package from the previous commit to the one that added it, following [the package official instructions](https://github.com/brunomikoski/Animation-Sequencer#how-to-install) I saw that there was a "registry scope" step that modified the PackageManagerSettings file (`Explorer/ProjectSettings/PackageManagerSettings.asset`) and that change hadn't been pushed in [the original commit …
=> fix: missing scoped registry in package manager settings for animation sequencer package

Explorer/Assets/DCL/Landscape/Assets/DebugAssets/SatelliteView.shadergraph, Explorer/Assets/DCL/Landscape/Systems/LandscapeDebugSystem.cs, Explorer/Assets/DCL/StylizedSkybox/Prefabs/SkyboxController.prefab, Explorer/Assets/DCL/StylizedSkybox/Scripts/SkyboxController.cs
- Changed default values of landscape to 5000 chunk cull distance and LOD bias % to 180
- Changed floor satellite shader to be Lit, removed multiply of Fog
- Reduced Skybox speed to 1 hour cycle
- Skybox now sets up the fog to linear instead of exponential until we fix the Scene shader
- Default fog values goes from 200 -> 2500
=> chore: Armonized environment fog and floor shaders

Explorer/Assets/DCL/Web3/Authenticators/DappWeb3Authenticator.cs, Explorer/Assets/Scripts/Global/Dynamic/DynamicSceneLoaderSettings.asset, Explorer/Assets/Scripts/Global/Dynamic/DynamicSceneLoaderSettings.cs, Explorer/Assets/Scripts/Global/Dynamic/MainSceneLoader.cs
Sets the authentication urls to `org` which is currently prod. Allows to set a secondary development url for development builds.
1. Open the app and follow the authentication process
2. When redirected to the web browser to sign the request observe that your avatar has your wearables
3. Continue through the authentication process, everything should keep working as expected
=> fix: authentication urls & dApp avatar preview

Explorer/Assets/DCL/Character/CharacterPreview/CharacterPreviewAvatarContainer.cs, Explorer/Assets/DCL/Character/CharacterPreview/DCL.CharacterPreview.asmdef
As the title says, we are disabling PostProcessing for the CharacterPreview Standalone versions for Mac users, as it is not working correctly RN
=> Fix : Disabled post processing on camera on character preview only for Mac

Explorer/Assets/Scripts/CrdtEcsBridge/OutgoingMessages/OutgoingCRDTMessagesProvider.cs
When memory is calculated at `GetSerializationSyncBlock()` we should do it only for `PUT` or `APPEND` messages, since in other cases like `DELETE` the `pendingMessage.Message` is null.
I was getting the following behaviour on scene that called the `IECSToCRDTWriter.DeleteMessage()` method, effectively breaking scenes execution with the nullref:
https://github.com/decentraland/unity-explorer/assets/1031741/67b3d330-e282-4fb5-8527-aef6fd18ab36
=> fix: nullref on DELETE crdt messages

Explorer/Assets/DCL/MapRenderer/Addressables/Favorite.prefab, Explorer/Assets/DCL/MapRenderer/Addressables/SceneOfInterest.prefab, Explorer/Assets/DCL/Minimap/Assets/Minimap.prefab
This PR was created to add the tiles texture behind the mini map to fix the visible transparency when reaching the map limits. Also fixes the dynamic font size depending on the text lenght.
=> style: minimap and poi updates

Explorer/Assets/DCL/Chat/ChatController.cs, Explorer/Assets/DCL/EmojiPanel/EmojiSuggestionPanel.cs
Fixed issue when pressing an emoji with the mouse from the suggestion list broke the flow
...
2. In the chat use the suggestion panel
3. try to add emoji by pressing enter
4. try to add emoji by selecting with mouse
=> fix: panel closing on emoji suggestion press

Explorer/Assets/DCL/Chat/ChatController.cs, Explorer/Assets/DCL/EmojiPanel/EmojiPanelController.cs, Explorer/Assets/DCL/EmojiPanel/EmojiPanelView.cs
With this PR the emoji panel and the emoji suggestions panel can be closed by clicking anywhere
...
2. Open the emoji panel
3. Click anywhere to close it
4. Same for emoji suggestions panel
=> fix: fixed emoji panel and emoji suggestion panel closing when clicking elsewhere

Explorer/Assets/DCL/Quality/Quality Settings.asset, Explorer/ProjectSettings/QualitySettings.asset
Fix #691 
2. Change the quality preset to "Medium" from the Settnigs Menu.
3. Observe everything in the graphics looks as expected.
=> fix: Medium quality settings gives invisible terrain

Explorer/Assets/DCL/Minimap/Assets/Animations/MinimapAnimatorController.controller
This PR was created to re assigned the collapse missing transition from the mini map animator.
1- Open the client
2- Press the collapse button from the mini map to hide the map reference. Now you should see the animation working.
=> fix: collapse mini map animation

Explorer/Assets/DCL/ParcelsService/TeleportController.cs, Explorer/Assets/Scripts/Utility/ParcelMathHelper.cs
Fix #661 
2. Go to `-104,4`.
3. Check that your avatar is teleported ON the surface of the floor and not below.
=> fix: When teleporting to a high terrain, the spawn point appears to be under it

Explorer/Assets/DCL/Backpack/EmotesSection/BackpackEmoteGridController.cs, Explorer/Assets/DCL/PluginSystem/Global/Global Plugins Settings.asset
Fixes #650 
There was a wrong calculation of emotes pagination. The pagination should only skip embedded emotes list since the owned list is already filtered by page by the catalyst.
2. The more custom emotes the better. The problem comes because of the pagination
3. There should be 22 base emotes
=> fix: embedded emote pagination & added missing embedded emote

.github/workflows/build-Windows-il2cpp.yml, Explorer/Assets/DCL/LOD/Systems/LODContainer.cs, Explorer/Assets/DCL/LOD/Systems/LODPlugin.cs, Explorer/Assets/DCL/LOD/Systems/LODUtils.cs, Explorer/Assets/DCL/LOD/Systems/UpdateSceneLODInfoMockSystem.cs, Explorer/Assets/DCL/LOD/Systems/UpdateSceneLODInfoMockSystem.cs.meta, Explorer/Assets/DCL/LOD/Systems/UpdateSceneLODInfoSystem.cs, Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs, Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldParams.cs, Explorer/Assets/Scripts/Global/Dynamic/MainSceneLoader.cs
- Adds the Enable LOD toggle in Main scene. By default, is off. This will be enabled by default when not development build.
- Removes LOD_3 embedded files in build to avoid creating such big files
In Editor,
1. Try with and without the Enable LOD toggle. Walk around and check that behaviour is as expected. 
2. If you dont have lods and landscape enabled, the loading should be super fast
In Build,
1. Check that LODs load correctly
=> Chore: lod cleanup

Explorer/Assets/DCL/Landscape/TerrainFactory.cs, Explorer/Assets/DCL/Landscape/TerrainGenerator.cs, Explorer/Assets/DCL/Landscape/Utils/TerrainGenerationUtils.cs, Explorer/Assets/DCL/Landscape/Worlds/WorldTerrainGenerator.cs
Fixes https://github.com/decentraland/unity-explorer/issues/563
Spreads along frames the re-enabling of terrain to fix a bug with the ColormapRenderer
The loading screen should not get stuck at 92% for some seconds, instead, it should be spread out and the wait at 92% should be lower.
=> fix: large hiccup during loading, now its spread along the loading bar

Explorer/Assets/DCL/Character/CharacterPreview/CharacterPreviewController.cs
Fixes #622 
2. The avatar preview should be always visible either in the authentication screen or backpack
=> fix: show naked avatar when wearables are empty at character preview

Explorer/Assets/DCL/Landscape/Data/WorldsVairations/Noises/Bush01Noise_W.asset, Explorer/Assets/DCL/Landscape/Data/WorldsVairations/Noises/OakCNoise_W.asset, Explorer/Assets/DCL/Landscape/Worlds/WorldModel.cs, Explorer/Assets/DCL/Landscape/Worlds/WorldTerrainGenerator.cs
Changes this
into this
Also fixes all memory leaks caused by generating terrain in worlds.
- `/goto goerli`
- fly with F11
- check that trees are no longer in weird patterns
=> fix: weird tree generation and memory leaks

Explorer/Assets/Scripts/Utility/ParcelMathHelper.cs
This is the second part of https://github.com/decentraland/unity-explorer/pull/720
Fix #661 
2. Go to coordinates where the terrain is elevated (for example: `-104,4`, `-73,-85` or `-144,-106`).
3. Check that your avatar is teleported ON the surface of the floor and not below.
=> fix: When teleporting to a high terrain, the spawn point appears to be under it (part 2)

Explorer/Assets/DCL/Character/CharacterPreview/Assets/CharacterPreviewContainer.prefab, Explorer/Assets/DCL/Character/CharacterPreview/CharacterPreviewAvatarContainer.cs, Explorer/Assets/DCL/Character/CharacterPreview/CharacterPreviewControllerBase.cs, Explorer/Assets/DCL/Character/CharacterPreview/ICharacterPreviewFactory.cs, Explorer/Assets/Scenes/Main.unity
First we are fixing the issue of duplicated character previews on the backpack. So now it works as it should.
Before when switching between tabs on the backpack new character previews were spawned and was horrible :D
Second, the preview no longer receives global illumination, but has its own point light for itself.
Just go to the backpack and try switching tabs, closing and opening and any other hijinks that you can think of :)
For the light thing, it should be visible already on the auth screen, but also in the backpack :)
=> fix: Character Preview fixes

Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/UpdateEmoteInputSystem.cs, Explorer/Assets/DCL/Multiplayer/Emotes/MultiplayerEmotesMessageBus.cs
fixes EntityOrNull for Inbox in MultiplayerEmotesMessageBus, to avoid nullref exceptions
Go to multiple players tests, and see there are no errors about MultiplayerEmotesMessageBus in the console, emotes should play fine
=> fix self-replica

Explorer/Assets/DCL/Landscape/Config/LandscapeAsset.cs, Explorer/Assets/DCL/Landscape/Data/Trees/Birch.asset, Explorer/Assets/DCL/Landscape/Data/Trees/Bush01.asset, Explorer/Assets/DCL/Landscape/Data/Trees/Bush02.asset, Explorer/Assets/DCL/Landscape/Data/Trees/Oak.asset, Explorer/Assets/DCL/Landscape/Data/Trees/Oak2.asset, Explorer/Assets/DCL/Landscape/Data/Trees/Tree01.asset, Explorer/Assets/DCL/Landscape/Data/Trees/Tree02.asset, Explorer/Assets/DCL/Landscape/Data/Trees/Tree03.asset, Explorer/Assets/DCL/Landscape/Data/WorldsTerrainData.asset, Explorer/Assets/DCL/Landscape/Data/WorldsVairations/Bush01_W.asset, Explorer/Assets/DCL/Landscape/Data/WorldsVairations/Bush02_W.asset, Explorer/Assets/DCL/Landscape/Data/WorldsVairations/Noises/Bush02Noise_W.asset, Explorer/Assets/DCL/Landscape/Data/WorldsVairations/Noises/OakCNoise_W.asset, Explorer/Assets/DCL/Landscape/Data/WorldsVairations/Noises/StoneNoise03_W.asset, Explorer/Assets/DCL/Landscape/Data/WorldsVairations/Stone01_W.asset, Explorer/Assets/DCL/Landscape/Data/WorldsVairations/Stone02_W.asset, Explorer/Assets/DCL/Landscape/Data/WorldsVairations/Stone03_W.asset, Explorer/Assets/DCL/Landscape/Data/WorldsVairations/Tree01_W.asset, Explorer/Assets/DCL/Landscape/Data/WorldsVairations/Tree02_W.asset, Explorer/Assets/DCL/Landscape/Data/WorldsVairations/Tree03_W.asset, Explorer/Assets/DCL/Landscape/Jobs/GenerateTreeInstancesJob.cs, Explorer/Assets/DCL/Landscape/Jobs/InvalidateTreesJob.cs, Explorer/Assets/DCL/Landscape/Jobs/TreeRadiusPair.cs, Explorer/Assets/DCL/Landscape/Jobs/TreeRadiusPair.cs.meta, Explorer/Assets/DCL/Landscape/TerrainChunkDataGenerator.cs, Explorer/Assets/DCL/Landscape/TerrainGenerator.cs, Explorer/Assets/DCL/Landscape/TerrainGeneratorTest.cs, Explorer/Assets/Scenes/InfiniteTerrain.unity, Explorer/Packages/packages-lock.json
Solves [#692](https://github.com/decentraland/unity-explorer/issues/692)
- Fixed tree overlap
- Trees spawn with more different scales now, this enables putting smaller trees on smaller portions of terrain, so overall more trees should spawn on single empty parcels
🌲 fly around and check the trees :) 🌳 
=> fix: Added tree overlap again

Explorer/Assets/DCL/Interaction/Raycast/Components/HighlightComponent.cs, Explorer/Assets/DCL/Interaction/Systems/InteractionHighlightSystem.cs, Explorer/Assets/Scripts/ECS/StreamableLoading/Common/AssetPromise.cs, Explorer/Assets/Scripts/Global/Dynamic/MainSceneLoader.cs
Fixes [#703](https://github.com/decentraland/unity-explorer/issues/703)
Fixes #710 
- Removed assertion that was making some assets to not load randomly on the editor
- Fixed interaction highlight with GLTF's and also fixed a null reference caused by the same system
- Fixed the ability to start on a world from the MainSceneLoader
- `/world dclexperience`
- Hover your cursor over interactables, you have the twitter buttons, the bot and downside you have some other characters that can be interacted with.
- Characters can be interacted and have an outline
=> fix: interactions with GLTFs

Explorer/Assets/DCL/NameTags/NametagView.cs
Fixes issue #739 
...
2. send messages of different lengths
3. verify the chat bubble never cuts out any text
=> Fix #739 : fixed chat bubble message cutout on certain length

Explorer/Assets/DCL/Audio/AudioSettings/LandscapeAudioSystemSettings.asset
For some reason we had set that for each chunk we should have 9^2 audioSources for landscape sounds. Which was a bestiality. I reduced that number to 4^2 which on my tests seemed OK.
Just go to any terrain parcel and listen to the nature sounds. There should be way less audioSources and less noise coming from everywhere.
=> fix: too many landscape audioSources

Explorer/Assets/DCL/Interaction/PlayerOriginated/Components/PlayerOriginRaycastResult.cs, Explorer/Assets/DCL/Interaction/PlayerOriginated/Tests/InteractionInputUtilsShould.cs, Explorer/Assets/DCL/Interaction/PlayerOriginated/Tests/PlayerOriginatedRaycastSystemShould.cs, Explorer/Assets/DCL/Interaction/PlayerOriginated/Tests/ProcessPointerEventsSystemShould.cs, Explorer/Assets/DCL/Interaction/PlayerOriginated/Utility/InteractionInputUtils.cs, Explorer/Assets/DCL/Interaction/Systems/PlayerOriginatedRaycastSystem.cs, Explorer/Assets/DCL/Interaction/Systems/ProcessPointerEventsSystem.cs
Fixes #709 
Also did a slight refactor
- Go to `dclexperience` world
- Pan the camera near an interactable, while panning the intractability should be disabled
=> fix: player raycasting when panning camera

Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/EmotePlayer.cs
Fix the issue with newer asset bundles having 2 states for the same clip, this added a new entry to the clip list, making the logic that detects extended emotes not work properly.
- Equip and use non-embedded emotes with _no props_
- All other emotes should also work
=> fix: emotes again

Explorer/Assets/Scripts/Global/Dynamic/RealmNavigator.cs
Fixes https://github.com/decentraland/unity-explorer/issues/899
- use `/world MetadyneLabs`
- Our loading screen should be fast and does not get stuck at 100%
- The custom loading screen from the scene should appear
=> fix: loading screen timeouts at 30 seconds when changing realms

Explorer/Assets/Scripts/ECS/StreamableLoading/Common/Systems/AssetsLoadingUtility.cs
Added check for the internal exception and not only the exception when catching on the AssetLoadingUtility as it was masking intended cancellations as unexpected exceptions. 
I detected this issue happening when cancelling a wearable request, but it might have happened with other assets as well.
Go to the backpack and try to equip a wearable you haven't equipped in this session yet, before it finishes loading, quickly unequip it. Nothing should break. 
Next time you try to equip the same wearable, it will try to load again the wearable and after a lil while it should be loaded correctly.
Previously, doing these steps would result on the wearable to be replaced by the default one for the duration of the session.
See video here ->
https://github.com/decentraland/unity-explorer/issues/933
=> fix: issue when cancelling asset bundle loading

Explorer/Assets/DCL/Minimap/Assets/Minimap.prefab
Fix #978 
2. Check that the 3 points button doesn't appear in the Minimap anymore.
=> fix: Hide 3 dots menu from Minimap

Explorer/Assets/DCL/Navmap/Assets/Navmap.prefab
This PR was created to fix the issue #956 . As the nav bar will always be on top of every other UI I decided to move the tooltip to the right side of the info button instead of keeping it at the top.
2. Open the nav map pressing **M** or the mini map.
3. Click the filters dropdown and then the info button.
4. Check the tooltip is not being overlap by the nav bar anymore.
=> fix: map filters POI tooltip position

Explorer/Assets/DCL/Landscape/TerrainGenerator.cs, Explorer/Assets/DCL/Landscape/TerrainGeneratorTest.cs, Explorer/Assets/Scripts/Global/Dynamic/RealmNavigator.cs
Added the missing TerrainShown flag when doing the GenerateTerrain + renamed method to GenerateTerrainAndShow so its clear that it also shows it. In the future we might wanna extract the show so we dont have GenerateAndShow and just Show methods in the RealmNavigator
Previously there would be no "nature" sounds anywhere and the visual culling would not work. so every tree would be visible, even outside of players view cone.
Now it should work as expected.
=> fix: Terrain was not set as shown on first start

Explorer/Assets/DCL/Chat/ChatController.cs
Fix #858 avoid chat to detect input when explore panel is open
...
2. Chat
3. Open the explore panel
4. Verify you cannot chat
5. Close the explore panel
6. Verify you can chat correctly again
=> Fix: blocked chat input on explore panel open

Explorer/Assets/DCL/AvatarRendering/AvatarShape/Systems/AvatarLoaderSystem.cs, Explorer/Assets/DCL/Multiplayer/SDK/Systems/GlobalWorld/PlayerProfileDataPropagationSystem.cs, Explorer/Assets/DCL/Multiplayer/SDK/Tests/PlayerProfileDataPropagationSystemShould.cs, Explorer/Assets/DCL/PluginSystem/Global/ProfilePlugin.cs, Explorer/Assets/DCL/Profiles/Components/Profile.cs
The components `AvatarBase` and `AvatarEquippedData` stopped working recently, I found it's due to how we handle the `Profile.IsDirty`.
* `Profile` component `IsDirty` flag was being reset manually at `AvatarLoaderSystem`, now it's handled by the `ResetDirtyFlagSystem`.
* `Profile` component reference was being propagated as is into the current scene by `PlayerProfileDataPropagationSystem`, now it's being cloned whenever it changed and a different instance is used in the scene world (thus avoiding shared manipulation in different worlds, which was also a problem)
Please test that the backpack and wearables still work corretly with this branch
=> fix: AvatarBase and AvatarEquippedData by correcting Profile.IsDirty reset

Explorer/Assets/DCL/Minimap/MinimapController.cs, Explorer/Assets/DCL/PluginSystem/Global/MinimapPlugin.cs, Explorer/Assets/Scripts/ECS/SceneLifeCycle/Realm/IRealmNavigator.cs, Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs, Explorer/Assets/Scripts/Global/Dynamic/RealmNavigator.cs
Toggles the minimap if you teleport to a world that has the same spawn point as the coordinate you left from
1. Launch the explorer and DONT MOVE
2. Go to dclexperience
3. Go back to Genesis
4. Teleport a couple of times to check that the minimap toggles as expected
=> fix: toggle minimap when teleporting to same location

Explorer/Assets/Scripts/Global/Dynamic/RealmNavigator.cs
In the `RealmNavigator` refator we lost the porgress in the terrain. Now its back
2. Check that the load bar is not stuck in 28 while loading
=> fix: Bring back progress bar for landscape

Explorer/Assets/DCL/AuthenticationScreenFlow/AuthenticationScreenController.cs, Explorer/Assets/DCL/Backpack/AvatarSection/AvatarController.cs, Explorer/Assets/DCL/Backpack/Backpack.asmdef, Explorer/Assets/DCL/Backpack/BackpackController.cs, Explorer/Assets/DCL/Backpack/BackpackSearchController.cs, Explorer/Assets/DCL/PluginSystem/Global/BackpackSubPlugin.cs, Explorer/Assets/DCL/PluginSystem/Global/ExplorePanelPlugin.cs, Explorer/Assets/DCL/Profiles/Repository/RealmProfileRepository.cs
Fixes #976 
Also fixes a problem when the profile cannot be solved on the authentication flow.
2. Check that the shortcuts (I, M, Tab, B, etc) are restored as expected when going back to world or changing screens
=> fix: interfering shortcuts on search bar & null profile on authentication

Explorer/Assets/StreamingAssets/Js/Init.js
This reverts commit 46b7e62e32b95c45bc1ebb3419135b6c6f6eafb6. since it produced a lot of js errors in `Goerli` realm
=> Fix: revert "Stringify arguments so we avoid [Object object] (#1024)"

Explorer/Assets/StreamingAssets/Js/Init.js
The fetch js module was not receiving correctly its arguments and it was making all the POST requests from the scenes fail.
=> fix: the fetch api module was not working correctly

Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/CharacterEmoteSystem.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/RemoteEmotesSystem.cs, Explorer/Assets/DCL/Multiplayer/Emotes/IEmotesMessageBus.cs, Explorer/Assets/DCL/Multiplayer/Emotes/MultiplayerEmotesMessageBus.cs
Fixes https://github.com/decentraland/unity-explorer/issues/930
Since introducing the `RemoteEmoteIntention`, the system has been consuming the intent even before the Entity exists, so we need to save the intent until the entity exists.
- Ask a friend to trigger an NFT emote with a loop.
- Log in to the place where your friend is.
- When his avatar appears, you should see it doing the emote. 
=> fix: looping emotes not being re-played on startup

Explorer/Assets/DCL/LOD/Settings/ILODSettingsAsset.cs, Explorer/Assets/DCL/LOD/Settings/LODSettingsAsset.cs, Explorer/Assets/DCL/LOD/Systems/LODDebugToolsSystem.cs, Explorer/Assets/DCL/LOD/Systems/VisualSceneStateResolver.cs, Explorer/Assets/DCL/LOD/Tests/EditMode/ResolveVisualSceneStateSystemShould.cs, Explorer/Assets/DCL/LOD/Tests/EditMode/UpdateVisualSceneStateSystemShould.cs
Adds an SDK7 threshold to show LOD0 for SDK 7 scenes
2. Enable LOD Debugging
3. There is a unicorn scene in one of the corners of genesis plaza
4. When approaching, scene should change form green to yellow. Eventually, the scene dissapears and some floating cubes appear. This means that the real scene has loaded
=> chore: Add SDK7 lods threshold

Explorer/Assets/DCL/WebRequests/WebRequestHeadersInfo.cs, Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/SimpleFetchApiImplementation.cs
Small fix caused by using case sensitive comparison for the content-type of the Fetch requests
=> fix: fetch requests content type not being sent

Explorer/Assets/DCL/AvatarRendering/AvatarShape/ComputeShader/ComputeShaderSkinning.cs
Avoids https://github.com/decentraland/unity-explorer/issues/1126 but does not fix it.
This should not happen anymore
=> fix: handled a weird exception during avatar instantiation

Explorer/Assets/DCL/PerformanceAndDiagnostics/Optimization/Pools/GameObjectPool.cs, Explorer/Assets/Scripts/ECS/Unity/GLTFContainer/Asset/Cache/GltfContainerAssetsCache.cs
Fixes https://github.com/decentraland/unity-explorer/issues/1076
- After spawning go to a world like `/world kinerius`
- go back to Genesis with either `/goto 0,0` or pressing the minimap button
- Check that the texts on the boards have proper rotations
=> fix: pooling reposition

Explorer/Assets/DCL/Interaction/Systems/InteractionHighlightSystem.cs
Fixes #1077 
Fix applies for scenes that uses pointer events, like this:
```
PointerEvents.create(staticBase, {
pointerEvents: [
{
eventType: PointerEventType.PET_DOWN,
eventInfo: {
showFeedback: false
}
}
]
})
```
Which in the client eventually ends up in the highlighting feature. This was making the client crash for entities which do not have a `TransformComponent`. The fix just checks that the required components exists in the entity.
2. Check that the highlighting keeps working
=> fix: crash on scenes that uses pointer events and highlighting

Explorer/Assets/DCL/Character/CharacterMotion/Settings/CharacterControllerSettings.asset, Explorer/Assets/DCL/Character/CharacterMotion/Settings/CharacterControllerSettings.cs, Explorer/Assets/DCL/Character/CharacterMotion/Settings/ICharacterControllerSettings.cs, Explorer/Assets/DCL/Character/CharacterMotion/Systems/FeetIKSystem.cs
Added an offset to the Feet IK so the feet look more relaxed just like how they are with the Idle pose
Fixed offset that made the feet be over the ground level
Without IK:
Before with IK:
Now with IK:
- Just watch your feet
=> fix: feet ik offset

Explorer/Assets/DCL/SDKComponents/SceneUI/Systems/UITransform/UITransformParentingSystem.cs
Fixes #1089 
The UI system was performing parenting operations on entities that didnt have any `UITransformComponent`. The scene UI gets broken tho, but we avoid the client crash.
2. Check that the UI on other scenes keeps working
=> fix: scene ui parenting crash

Explorer/Assets/DCL/Roads/Data/RoadAssets/RoadRedesign/PotTree.prefab
Updated prefab `PotTree` to remove this warning:
```
BoxCollider does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "ROAD_ASSET_POOL/Crossroads_A(Clone)/*SCENEROOT*/Scene/PotTree"
```
...
2. Go the the roads
3. The warning should not be visible in the console in editor or the log file.
=> fix: removed negative size on box collider on the pot in the streets

Explorer/Assets/Scripts/Global/Dynamic/RealmNavigator.cs
Fixes this
The ring jobs was still running when changing realms. This PR avoid that by removing the `CameraSamplingData` while changing realms
2. Teleport back and forth between realms
=> fix: Ring job overcalculating

Explorer/Assets/DCL/Backpack/BackpackGridController.cs, Explorer/Assets/DCL/UI/PageSelector/PageSelectorController.cs
This issue fixes the backpack freeze that happened when clicking the page selector when the first page was not loaded.
To solve this the page selector now is visible only after we retrieve properly the total pages count.
...
2. Open the backpack
3. Verify that the page selector is not visible before the first page loads
4. Verify this also when applying the category filters
PS: Keep in mind that if we open the backpack when other stuff is loading as soon as we join in game the requests will take longer, if instead we wait a while and then open the backpack it will be faster
=> Fix: fixed backpack freeze

Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/RestrictedActionsApi/RestrictedActionsAPIWrapper.cs
Fix #677 
Fix #1149 
2. Go to the beam area in the cafe
3. Check that the countdown appears
4. Check that after the countdown your avatar is teleported to the upper place of the scene
=> fix: movePlayerTo restricted action does not work

Explorer/Assets/DCL/AvatarRendering/AvatarShape/Assets/EmbeddedEmotes/EmbeddedEmotes.asset
- Removed` hands_in_the_air emote` since it failed to be equipped and it was a duplicate of `handsinair`
- Check that you have only one version of `handsinair` and that you can equip it and use it (it has confetti! 🥳) 
=> fix: duplicated emote

Explorer/Assets/DCL/MapRenderer/MapLayers/PointsOfInterest/ScenesOfInterestMarkersController.cs
Found a weird exception, this fix should avoid the map not loading
- minimap should load
=> fix: exception with POIs

Explorer/Assets/DCL/PluginSystem/Global/Global Plugins Settings.asset
Removed an already deleted embed emote from a secondary list
- Emotes in the backpack should not take 30 seconds to load.
=> fix: emotes timeout when loading in the backpack

Explorer/Assets/DCL/Interaction/PlayerOriginated/Tests/WritePointerEventResultsSystemShould.cs, Explorer/Assets/DCL/Interaction/Systems/InteractionHighlightSystem.cs, Explorer/Assets/DCL/Interaction/Systems/WritePointerEventResultsSystem.cs, Explorer/Assets/DCL/PluginSystem/World/InteractionPlugin.cs
User interactions are being tracked and processed on scenes that are not the current scene, this consumes performance and may affect the "starting state" of a scene once the user reached that scene.
Added a simple current scene check on the system that writes into CRDT the user input values + the interactables highlighting system
There is a scene in **goerli-plaza 82,1** that has the following interactions:
* Re-spawn balls in the air when pressing E
* Highlight balls even at long distance
* Move balls by clicking them on close distance
Those interactions are working when triggered from outside the scene and that shouldn't be the case, here's a video displaying those 3 being triggered from outside the scene:
https://github.com/decentraland/unity-explorer/assets/1031741/cc295b8c-30ca-4150-b …
=> fix: interactions from outside scenes

Explorer/Assets/DCL/Minimap/Assets/Minimap.prefab, Explorer/Assets/DCL/Minimap/MinimapController.cs
Fix #1178 
2. Go to a world
3. Observe the minimap keeps the coordinates and, when you move through the place, the coords change
=> fix: put coordinates back into world minimap

Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/SignedFetch/SignedFetchWrap.cs, Explorer/Assets/StreamingAssets/Js/Modules/SignedFetch.js
This PR fixes the `signedFetch failed: the object has no method named 'SignedFetch' that matches the specific arguments` error successfully.
If this "breaks" the signed fetch functionality is not easy to confirm right now since we can't even find a working example of signedFetch with unity-renderer.
I'd suggest moving forward with this fix and revisiting the `signedFetch` functionality in the future.
=> fix: SignedFetch does not work

Explorer/Assets/DCL/MapRenderer/ComponentsFactory/MapRendererChunkComponentsFactory.cs, Explorer/Assets/DCL/Navmap/NavmapController.cs, Explorer/Assets/DCL/PluginSystem/Global/ExplorePanelPlugin.cs
Fix #1198 
If an error occurs at places API level when initialising the map it no longer breaks the full flow for the map.
...
2. Verify that minimap doesn't break
=> fix: errors in map init flow no longer breaks the full UI

Explorer/Assets/DCL/AvatarRendering/AvatarShape/Assets/Animator/CharacterAnimator.controller, Explorer/Assets/DCL/AvatarRendering/Emotes/Components/CharacterEmoteComponent.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/CharacterEmoteSystem.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/EmotePlayer.cs
Fixes https://github.com/decentraland/unity-explorer/issues/1034
Fixes https://github.com/decentraland/unity-explorer/issues/1196
Fixes https://github.com/decentraland/unity-explorer/issues/1194 and https://github.com/decentraland/unity-explorer/issues/791
- Use a looping emote with props
- Without canceling it, teleport to another location or switch realms
- Your character should spawn without doing any emote
- Amidst the chaos of users playing emotes and disappearing or teleporting around, all avatars should spawn and move without emote props that weren't properly returned to the pool. 
- Equip and play a looping emote that also has a looping audio clip
- The audio clip should keep playing forever
=> fix: emote not being cancelled properly / audio not looping

Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/SignedFetch/SignedFetchWrap.cs, Explorer/Assets/StreamingAssets/Js/Modules/SignedFetch.js
This is a complementary fix of https://github.com/decentraland/unity-explorer/pull/1186 that fixes the call to `SignedFetchWrap` when the params come empty from the JS side.
=> fix: SignedFetch does not work (II)

Explorer/Assets/DCL/AvatarRendering/Emotes/Helpers/MemoryEmotesCache.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/LoadEmotesByPointersSystem.cs, Explorer/Assets/DCL/AvatarRendering/Wearables/Components/Wearable.cs, Explorer/Assets/DCL/AvatarRendering/Wearables/Helpers/IWearableCatalog.cs, Explorer/Assets/DCL/AvatarRendering/Wearables/Helpers/WearableCatalog.cs, Explorer/Assets/DCL/AvatarRendering/Wearables/Systems/ResolveWearableByPointerSystem.cs, Explorer/Assets/DCL/Backpack/BackpackBus/BackpackBusController.cs, Explorer/Assets/DCL/Backpack/BackpackController.cs, Explorer/Assets/DCL/CommunicationData/URLHelpers/URN.cs, Explorer/Assets/DCL/Profiles/DataModels/ProfileJsonDto.cs
Third party wearables and emotes were not working due its urn structure.
TP do not include the tokenId and has 7 parts, so we must not shorten them. Example: `urn:decentraland:matic:collections-thirdparty:dolcegabbana-disco-drip:0x4bd77619a75c8eda181e3587339e7011da75bf0e:2a424e9c-c6fb-4783-99ed-63d260d90ed2`.
Also, some TPW wearable urns comes in UPPER CASE, but `entities/active` endpoint gets everything lowered provoking cache misses in the content. This change makes the urns case-insensitive.
Finally added some safe checks on resolving wearables so the avatars do not fail when a DTO is not resolved.
1. Equip a third party wearable and/or emote into your avatar
2. Check that works as expected
3. Go to the backpack, change some wearables, keeping the TPW
4. Check that the avatar is …
=> fix: third party wearables & emote urns and fixes on wearable resolving process

Explorer/Assets/DCL/Interaction/Raycast/Systems/ExecuteRaycastSystem.cs
Fixes:
https://github.com/decentraland/unity-explorer/issues/1080
Howdy dudes and dudettes, this little thing fixes an issue present when doing Raycasts that get the first hit. 
The issue was evident on the Advanced Range where an error triggered when shooting saying the SDK could not find an entity with a huge ID. This ID was -1 converted to uint.
Aaaand -1 is the default value given to the CRDTEntities in the ExecuteRaycastSystem xD
Basically, in TryGetQualifiedEntity we were overwritting the value of foundEntity with -1. Which normally would be OK if we didnt do it even when the raycast should be ignored xD
So we were first getting the Entity, overwritting the value of foundEntity (which when the entity did not qualify would be -1) and THEN checking if that hit should be considered or …
=> fix: Fixed issue with not found Entity when Raycasting

Explorer/Assets/DCL/PluginSystem/Editor/ContainerReference.cs, Explorer/Assets/DCL/PluginSystem/Editor/ContainerReference.cs.meta, Explorer/Assets/DCL/PluginSystem/Editor/PluginSettingsEditorWindow.cs, Explorer/Assets/DCL/PluginSystem/Editor/PluginSettingsEditorWindow.cs.meta, Explorer/Assets/DCL/PluginSystem/Editor/PluginsContainerEditor.cs, Explorer/Assets/DCL/PluginSystem/Global/Global Plugins Settings.asset, Explorer/Assets/DCL/PluginSystem/GlobalPluginSettingsContainer.cs, Explorer/Assets/DCL/PluginSystem/GlobalPluginSettingsContainer.cs.meta, Explorer/Assets/DCL/PluginSystem/World/World Plugins Container.asset, Explorer/Assets/DCL/PluginSystem/WorldPluginSettingsContainer.cs, Explorer/Assets/DCL/PluginSystem/WorldPluginSettingsContainer.cs.meta
1. Containers are now available from the menu:
2. Settings are now filtered by their scope, it's no longer possible to mix them
=> Improve Containers' Editor

.github/workflows/build-unitycloud.yml, scripts/cloudbuild/build.py
Download & print Unity cloud logs in GitHub actions regardless of the build result
=> Always report cloud logs

.github/workflows/create-page-release-weekly.yml
Adds if to avoid running tag and page creation if build fails
=> fix: Avoid tag and page creation if build fails

Explorer/Assets/DCL/SDKComponents/SceneUI/Utils/UiElementUtils.cs
fixes #1150
fixes #1265
Scenes constantly re-create the UI as part of the flow and there is no reason to reset the background.
=> fix: do not reset UI background  image and colour on creation

Explorer/Assets/DCL/SDKComponents/SceneUI/Utils/UiElementUtils.cs
fixes #1309 
Protocol doesn't appear to have a white-space wrapping option, default to normal instead of no-wrap to avoid the force of the no-wrap. I also think the scene is incorrectly trying to wrap the text itself, I've reached out to @nearnshaw
=> fix: default text wrapping

Explorer/Assets/DCL/SDKComponents/Animator/Systems/AnimationPlayerSystem.cs, Explorer/Assets/Scripts/ECS/Unity/CollidersUtility/EntityCollidersCacheExtensions.cs, Explorer/Assets/Scripts/ECS/Unity/GLTFContainer/Asset/Components/GltfContainerAsset.cs, Explorer/Assets/Scripts/ECS/Unity/GLTFContainer/Asset/Systems/CreateGltfAssetFromAssetBundleSystem.cs, Explorer/Assets/Scripts/ECS/Unity/GLTFContainer/Systems/ConfigureGltfContainerColliders.cs, Explorer/Assets/Scripts/ECS/Unity/GLTFContainer/Tests/CleanUpGltfContainerSystemShould.cs, Explorer/Assets/Scripts/ECS/Unity/GLTFContainer/Tests/FinalizeGltfContainerLoadingSystemShould.cs, Explorer/Assets/Scripts/ECS/Unity/GLTFContainer/Tests/ResetGltfContainerSystemShould.cs, Explorer/Assets/Scripts/ECS/Unity/SceneBoundsChecker/CheckColliderBoundsSystem.cs
Fixes #752 
Fixes the interaction with the dog of #1261 
Partially fixes the interaction of #1087 
Fixes the pointer interactions with objects in the SDK configured like [this](https://github.com/decentraland/sdk7-goerli-plaza/blob/5dde0e08f5e369200d04506d1978c419fea3f3ff/Shark-animation/src/index.ts#L53) by supporting colliders for `SkinnedMeshRenderer` (which was previously ignored).
In order to fix the shark, we need to make animations weighted by layer so the bite and the swim can be played simultaneously. Will do it in another pr so this one does not grow too much.
2. Check that the pointer interaction works
3. The bite animation will not work yet
4. Go around the scenes and check that the colliders and pointer interactions are still working as expected …
=> fix: skinned mesh renderer pointer interaction

Explorer/Assets/DCL/UserInAppInitializationFlow/RealUserInitializationFlowController.cs
Fixes #1331 
Removes the flash of land between login and loading screen
1. Login
2. Wait for the loading screen. No flash should appear
=> fix: remove land flash between login and loading screen

Explorer/Assets/DCL/SDKComponents/Animator/Systems/AnimationPlayerSystem.cs
Fixes #1376 
Fixes #1397 
Should also fix #1333 when the AB conversion is done on Metadyne (not yet done)
Depends on AB conversions from: https://github.com/decentraland/asset-bundle-converter/pull/100
The doors should stay at the last frame of its open animation when the state is `loop:false`. The new asset bundle converter avoids overriding bones when transitioning to `empty`, keeping the animation on its latest state.
Clear asset bundles cache.
If affects the animation system, so all animations should work as expected.
Some of the scenes from goerli plaza:
door-wearable-scanner (76,-5)
sliding-doors (79,-9)
man-dancing (76,-3)
skeleton-king (74,-9)
zombie-chaser (78,-1)
shark (73,-8)
birds-tree (76,-9)
scene-emotes-green-tiles (77,-7)
swap-avatar (75,-7)
avatar-emotes (80,-1) …
=> fix: doors

Explorer/Assets/DCL/SDKComponents/MediaStream/Components/MediaPlayerComponent.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Classes/DCLImage.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Components/UIBackgroundComponent.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Systems/UIBackground/UIBackgroundInstantiationSystem.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Systems/UIBackground/UIBackgroundReleaseSystem.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Utils/UiElementUtils.cs
fix #1384 
fix #1380
- removed reference from DCLImage on UIBackground disposal
- moved Releasing system to CleanUp ECS group
- minor clean-ups
Check steps in #1384 and in #1380
=> fix: clean up of UI background component

Explorer/Assets/Scenes/Main.unity
added missing/lost MapPin reference on EntryPoint GO in Main.unity
=> fix: missing map pin reference on EntryPoint GO in Main.unity

Explorer/Assets/Scripts/SceneRunner/ECSWorld/ECSWorldFactory.cs
fixes #1431 (crash)
It does not fix colliders' movement as there is a separate issue for that.
P.S. Adding components to the scene root has no effect - it's hard to say what content creators wanted to achieve 🤷
=> fix: a weird case when the component is added and later removed from the scene root

scripts/cloudbuild/build.py
If a build is tried again while unity cloud still has it running, it will attempt to cancel the build by obtaining the build ID first. Then retry up to 10 times with a 20 second delay between.
=> fix: auto cancel & retry build when pending

Explorer/Assets/DCL/Ipfs/DCL.Ipfs.asmdef, Explorer/Assets/DCL/Ipfs/SceneMetadata.cs, Explorer/Assets/DCL/Utilities/Json.meta, Explorer/Assets/DCL/Utilities/Json/IPreserveOriginalJson.cs, Explorer/Assets/DCL/Utilities/Json/IPreserveOriginalJson.cs.meta, Explorer/Assets/DCL/Utilities/Json/PreserveOriginalJson.cs, Explorer/Assets/DCL/Utilities/Json/PreserveOriginalJson.cs.meta, Explorer/Assets/DCL/Utilities/Json/PreserveOriginalJsonConverter.cs, Explorer/Assets/DCL/Utilities/Json/PreserveOriginalJsonConverter.cs.meta, Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/RuntimeImplementation.cs
Preserves the original json data for when the scene creator requests it they are able to add any additional fields they want.
Fixes #1235
Fixes #1289 
=> fix: preserve original json blob of the scenes

Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/SceneApiImplementation.cs
Previous implementation of retaining the original json blob missed this change.
Genesis plaza should work properly again.
=> fix: genesis plaza events boards 

Explorer/Assets/DCL/PluginSystem/World/AudioSourcesPlugin.cs, Explorer/Assets/DCL/PluginSystem/World/World Plugins Container.asset, Explorer/Assets/DCL/SDKComponents/AudioSources/Systems/UpdateAudioSourceSystem.cs, Explorer/Assets/Scripts/Global/StaticContainer.cs, Explorer/Assets/Scripts/Global/Tests/PlayMode/Integration Tests World Container.asset
Fix #1395 
The "World" channel volume of our `GeneralAudioMixer` was not working in the build. None of the scenes audios was being attended to the WORLD volumen in the Settings Menu.
Now it works correctly.
1. Go to the top side of Genesis Plaza.
2. Check that you hear the background music.
3. Go to the Settings Menu -> audio section.
4. Modify the WORLD SFX slider to set it as 0.
5. Notice that the genesis plaza background music is being affected.
6. Do the same test with the sound of the doors in the floor below when they open.
7. Do the same test with other scenes/worlds (for example MetadyneLabs) and check that the scene audio is attending the volume that we set in the Settings Menu.
=> fix: World channel volume does not work in the build

Explorer/Assets/DCL/PluginSystem/World/SceneUIPlugin.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Systems/UIFixPbPointerEventsSystem.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Systems/UIPointerEvents/UIPointerEventsSystem.cs
Introduces a system to modify the pointer filtering as it is not enforced as part of SDK we must inject it into our system manually.
fixes #1233 
fixes #1483
=> fix: force picking mode

Explorer/Assets/DCL/Backpack/BackpackBus/BackpackBusController.cs, Explorer/Assets/DCL/Backpack/BackpackBus/BackpackCommand.cs, Explorer/Assets/DCL/Backpack/BackpackBus/BackpackEventBus.cs, Explorer/Assets/DCL/Backpack/BackpackBus/IBackpackEventBus.cs, Explorer/Assets/DCL/Backpack/BackpackController.cs, Explorer/Assets/DCL/Backpack/BackpackEquipStatusController.cs, Explorer/Assets/DCL/Backpack/CharacterPreview/BackpackCharacterPreviewController.cs, Explorer/Assets/DCL/Backpack/EmotesSection/BackpackEmoteGridController.cs, Explorer/Assets/DCL/Backpack/EmotesSection/BackpackEmoteSlotsController.cs
Fix #1164 
2. Go to the Backpack -> Emotes section.
3. Equip an emote in a slot.
4. Check that the equipped emote is played in the avatar preview.
=> fix: Clicking on Equip a emote does not play it

Explorer/Assets/DCL/SDKComponents/Tween/Systems/TweenUpdaterSystem.cs, Explorer/Assets/Scripts/ECS/Unity/Transforms/Systems/UpdateTransformSystem.cs
New gate for the UpdateTransform caused issue on GPlaza carousel
- disabled systems gate, before we fix it on GPlaza carousel
2. Check the carousel on GPlaza works as expected
=> Fix: disabled systems gate (temporarily)

Explorer/Assets/DCL/SDKComponents/Animator/Systems/AnimationPlayerSystem.cs
Fixes #1465 
The AB converter sets the first clip in the animator to play as default, since it is required by the sdk definitions. The scene first asks to play another clip (not the default one). Eventually the scene finally decides to play the default clip, but it was already playing since it was never modified. So the trigger gets enabled and makes the execution play twice (after it finishes), although is set to loop:false
The fix consists on avoid triggering the animation if it is already playing, to avoid stacking the trigger.
2. The chest should play the open animation only once
3. Its worth to also check that other scenes keep working:
sliding-doors (79,-9)
manDancing (76,-3)
skeleton-king (74,-9)
zombie-chaser (78,-1)
shark (73,-8)
birds-tree (76,-9) …
=> fix: avoid stacking trigger if the animation is playing

.github/workflows/build-unitycloud.yml
**Changes:**
Remove 'labeled' from pull_request event types
Add pull_request_target event for 'force-build' label
Update prebuild job condition to handle pull_request_target
**Effects:**
Stops workflow triggers on every label change
Allows builds to be forced with 'force-build' label
Maintains existing build triggers for PR updates and pushes to main
Enables 'force-build' to work on fork PRs (via pull_request_target)
=> fix: prevent constant rebuild when label is changed

Explorer/Assets/Scripts/Global/Dynamic/Bootstraper.cs
Currently, when connecting to a local scene, the genesis city landscape is being rendered and many of those meshes can clip with the actual local scene space.
Example:
Dynamically disabled Landscape and LODs for Local Scene Development scenario.
=> chore: disable Landscape for local scene development

Explorer/Assets/Scripts/ECS/Unity/Materials/Systems/CreateMaterialSystemBase.cs, Explorer/Assets/Scripts/ECS/Unity/Materials/Systems/StartMaterialsLoadingSystem.cs
Continuation of #1555 
```
if (Equals(ref textureComponentValue, ref promise)
&& promise!.Value.TryGetResult(World!, out var texture))
{
// If data inside promise has not changed just reuse the same promise
// as creating and waiting for a new one can be expensive
promise = Promise.CreateFinalized(intention, texture);
}
```
This branch was unreachable as `ReleaseMaterial.TryAddAbortIntention(World, ref promise);` was called before leading to the invalidation of the promise.
- It led to re-creation of the promise every time the material was changed even if the texture was not
- It could be a major bottleneck if materials on the scene are frequently changed, e.g. their colors
**I completely reverted that logic**
**The real issue**
`TryGetTextureResult` was operating on `Nullable.Value` …
=> Fix: Handle Texture Promises on Materials properly

scripts/cloudbuild/build.py
* Successful builds are deleted thus we do not have a cache for the previous build stored
* Caching is causing various issues with the mac build.
* Disable caching - lets see how fast the build runs.
=> fix: do not use cache

Explorer/Assets/Scripts/Global/Dynamic/ChatCommands/ChangeRealmChatCommand.cs, Explorer/Assets/Scripts/Global/Dynamic/ChatCommands/GoToChatCommand.cs
Close #1562 
- extends REGEX equations to allow white spaces
2. Try different variations of commands with coordinates and different spaces between coordinates, like:
```
/goto 10,20
/goto -5 , -10
/goto -5,-10
```
3. same with `/goto-local`
4. as well for world command:
```
/world genesis 10,20
/goto goerli 77 ,-3
```
=> Chore: allow goto commands to have spaces for coordinates

Explorer/Assets/DCL/Multiplayer/SDK/Systems/GlobalWorld/PlayerCRDTEntitiesHandlerSystem.cs, Explorer/Assets/DCL/Multiplayer/SDK/Tests/PlayerCRDTEntitiesHandlerSystemShould.cs
Fixes #1523 
`PBAvatarEmoteCommand` was not being sent through crdt because it was lacking of required components: `PlayerSceneCRDTEntity` & `AvatarEmoteCommandComponent`.
The solution consists in processing the OWN player so the `PlayerSceneCRDTEntity` is added to the to the scene's entity with `CRDTEntity: SpecialEntitiesID.PLAYER_ENTITY`, since the scene code (js side) subscribes to this special entity id. The flow will finally end up sending the `PBAvatarEmoteCommand` here: https://github.com/decentraland/unity-explorer/blob/2fffa9e337798c8e6aadecc7363fd17582f6fb73/Explorer/Assets/DCL/Multiplayer/SDK/Systems/SceneWorld/WriteAvatarEmoteCommandSystem.cs#L49
Since the local `CharacterEmoteIntent` player is applied to the own global player entity here: …
=> fix: emote command subscription of the own player entity from the sdk

Explorer/Assets/DCL/Passport/PassportController.cs, Explorer/Assets/DCL/Passport/PassportProfileInfoController.cs, Explorer/Assets/DCL/PluginSystem/Global/PassportPlugin.cs
This PR fixes issue #1619
It removes a duplicated disposal flow of the passport controller and it improves the creation of passportProfileInfoController
...
2. Verify that the player passports are working as expected (no major changes have been applied)
=> Fix #1619 : fixed nullref on passport disposal

Explorer/Assets/DCL/Multiplayer/Movement/Systems/MultiplayerMovementMessageBus.cs, Explorer/Assets/DCL/Multiplayer/Profiles/BroadcastProfiles/ProfileBroadcast.cs, Explorer/Assets/Scripts/CrdtEcsBridge/JsModulesImplementation/Communications/CommunicationControllerHub.cs
Temporarily updates livekit to only use reliable packets.
=> fix: change to reliable packets only temporarily

Explorer/Assets/DCL/LOD/Components/SceneLODInfo.cs, Explorer/Assets/DCL/LOD/Components/SceneLODInfoUtils.cs, Explorer/Assets/DCL/LOD/Systems/CalculateLODBiasSystem.cs, Explorer/Assets/DCL/LOD/Systems/LODPlugin.cs, Explorer/Assets/DCL/LOD/Systems/RecalculateLODDistanceSystem.cs, Explorer/Assets/DCL/LOD/Systems/RecalculateLODDistanceSystem.cs.meta, Explorer/Assets/Scripts/ECS/Prioritization/Settings/IRealmPartitionSettings.cs, Explorer/Assets/Scripts/ECS/Prioritization/Settings/RealmPartitionSettingsAsset.cs, Explorer/Assets/Scripts/ECS/SceneLifeCycle/SceneFacade/SceneLODInfoExtensions.cs
1. Adds a system that allows to recalculate relative transition heights on all LODs when `MaxParcelLoadingDistance` changes
2. When scrolling the camera (not running) the fov also changed. This PR adjusts that scenario, so the `LODBias` is correctly calculated.
3. Potentially fixes #1660. If the `SceneLODInfo` has not been initialized, there is nothing to dispose or release to pool
On top of that, it makes a refactor to `SceneLODInfo`. Divides the  `RecalculateLODValues` into two methods, `SetupRenderers` and `SetupLODRelativeHeights`. In that way, I can now update the distances without modifying the renderers 
2. Walk around the worlds and see lods dither in/out. There should be no popping
3. Run around. LODS should dither in/out just the same
4. Same occurs when …
=> chore: LOD group recalculation on distance change

Explorer/Assets/AddressableAssetsData/AssetGroups/Materials.asset, Explorer/Assets/DCL/PluginSystem/World/MaterialWorldPlugin.cs, Explorer/Assets/DCL/PluginSystem/World/World Plugins Container.asset, Explorer/ProjectSettings/GraphicsSettings.asset
Moves shape materials from addressables to the build
Being in Addressables caused a problem with strobe-lights because shaders were not being compiled and _EMISSION hadn't been propagated to renderer
It fixes
https://github.com/decentraland/unity-explorer/issues/1497#issue-2425588098
#1582
#796
#1500
#1101
Follow the flow of the tickets
=> fix: strobe lights

Explorer/Assets/DCL/PluginSystem/World/AudioSourcesPlugin.cs, Explorer/Assets/DCL/SDKComponents/AudioSources/Systems/UpdateAudioSourceSystem.cs, Explorer/Assets/DCL/SDKComponents/AudioSources/Tests/UpdateAudioSourceSystemShould.cs
1. Makes the volume setter to 0 event based instead of checking it every frame. When a scene is changed, the audio sources volumes should go to 0
2. `frameTimeBudgetProvider.TrySpendBudget()` was pilling up and causing an overhead. Moved the conditional around, so its not the first thing to check
Goes from this
to this
1. Check audios are fine in Genesis Plaza or in other scene you know there are audios at
2. Go between scenes and check that you don't have invading sounds from other scenes
=> chore: UpdateAudioSourceSystem optimization 

Explorer/Assets/DCL/Landscape/Assets/Trees/Tree01/Tree01 Variant.prefab, Explorer/Assets/DCL/Landscape/Assets/Trees/Tree01/Tree01_Billboard_LOD3.mat, Explorer/Assets/DCL/Landscape/Assets/Trees/Tree01/Tree01_LOD0.mat, Explorer/Assets/DCL/Landscape/Assets/Trees/Tree01/Tree01_LOD_NoWind.mat, Explorer/Assets/DCL/Landscape/Assets/Trees/Tree01/Tree01_LOD_NoWind.mat.meta, Explorer/Assets/DCL/Landscape/Assets/Trees/Tree01/Trunk_LOD0.mat, Explorer/Assets/DCL/Landscape/Assets/Trees/Tree01/Trunk_LOD_NoWind.mat, Explorer/Assets/DCL/Landscape/Assets/Trees/Tree01/Trunk_LOD_NoWind.mat.meta, Explorer/Assets/DCL/Landscape/Assets/Trees/Tree02/Tree02 Variant.prefab, Explorer/Assets/DCL/Landscape/Assets/Trees/Tree02/Tree02_Billboard_LOD3.mat, Explorer/Assets/DCL/Landscape/Assets/Trees/Tree02/Tree02_LOD0.mat, Explorer/Assets/DCL/Landscape/Assets/Trees/Tree02/Tree02_LOD_NoWind.mat, Explorer/Assets/DCL/Landscape/Assets/Trees/Tree02/Tree02_LOD_NoWind.mat.meta, Explorer/Assets/DCL/Landscape/Assets/Trees/Tree02/Trunk_LOD0.mat, Explorer/Assets/DCL/Landscape/Assets/Trees/Tree02/Trunk_LOD_NoWind.mat, Explorer/Assets/DCL/Landscape/Assets/Trees/Tree02/Trunk_LOD_NoWind.mat.meta, Explorer/Assets/DCL/Landscape/Assets/Trees/Tree03/Tree03 Variant.prefab, Explorer/Assets/DCL/Landscape/Assets/Trees/Tree03/Tree03_Billboard_LOD3.mat, Explorer/Assets/DCL/Landscape/Assets/Trees/Tree03/Tree03_LOD0.mat, Explorer/Assets/DCL/Landscape/Assets/Trees/Tree03/Tree03_LOD_NoWind.mat, Explorer/Assets/DCL/Landscape/Assets/Trees/Tree03/Tree03_LOD_NoWind.mat.meta, Explorer/Assets/DCL/Landscape/Assets/Trees/Tree03/Trunk_LOD0.mat, Explorer/Assets/DCL/Landscape/Assets/Trees/Tree03/Trunk_LOD_NoWind.mat, Explorer/Assets/DCL/Landscape/Assets/Trees/Tree03/Trunk_LOD_NoWind.mat.meta
* All trees were previously casting shadows, even billboards
* The same for wind, it was affecting all trees (or rather the calculation was being ran) for trees in the distance.
Before:
After:
* Verify there are no obvious visual differences between the trees
* Verify the wind still works for the close trees
=> fix: disable shadow casting for very distant trees and disable wind for lod0+

Explorer/Assets/Textures/BackpackPanel/ItemRarityBackground/UniqueBackground.png
This PR fixes the unique background texture which had a different size compared with the rest of the rarities, making it look smaller and broken regarding the mask and the rest of the items. 
2. Explore your profile or someone else's profile with unique items (@NikkiFuego for eg)
3. Open the backpack and check that unique items are also fixed.
=> style: fix unique rarity background texture

Explorer/Assets/DCL/PluginSystem/World/TransformsPlugin.cs, Explorer/Assets/Scripts/ECS/Unity/Transforms/Systems/UpdateTransformSystem.cs
Fix #1757
This PR introduces a new transform as a parent to the scene root transform.
The reason is that creators have access to the scene root transform and can change the rotation and the position (it is something allowed by SDK on purpose), causing the scene to be in weird places in some cases, for example by changing the rotation of the scene the position was being set to 0,0,0.
With this PR we place the scene correctly on the client and then still allow creators to manually change the scene root position but in relation to the world space
...
2. Go to wilderness (-24, 92)
3. Verify that the scene is visible, unlike before
4. Check other sdk7 scenes
=> Fix: fixed scene placement by introducing a new scene transform parent

Explorer/Assets/DCL/Backpack/BackpackEquipStatusController.cs, Explorer/Assets/DCL/LOD/Components/SceneLODInfoDebug.cs, Explorer/Assets/DCL/Multiplayer/SDK/Systems/SceneWorld/CleanUpAvatarPropagationComponentsSystem.cs, Explorer/Assets/DCL/Multiplayer/SDK/Systems/SceneWorld/CleanUpAvatarPropagationComponentsSystem.cs.meta, Explorer/Assets/DCL/Multiplayer/SDK/Systems/SceneWorld/WriteAvatarEmoteCommandSystem.cs, Explorer/Assets/DCL/Multiplayer/SDK/Systems/SceneWorld/WriteSDKAvatarBaseSystem.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportHub.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Optimization/Pools/GameObjectPool.cs, Explorer/Assets/DCL/PluginSystem/Global/BackpackSubPlugin.cs, Explorer/Assets/DCL/PluginSystem/World/MultiplayerPlugin.cs, Explorer/Assets/Scripts/SceneRuntime/Apis/Modules/UserIdentityApi/UserIdentityApiWrapper.cs, Explorer/Assets/Scripts/SceneRuntime/Apis/UnityOpsApi.cs, Explorer/Assets/StreamingAssets/Js/Modules/UserIdentity.js
**Reason:**
During the resolution of `GetUserDataResponse` promise the stack is overflowed. I traced it down to the following:
```
System.StackOverflowException: The requested operation caused a stack overflow.
at (wrapper managed-to-native) System.Object.__icall_wrapper_ves_icall_array_new_specific(intptr,int)
at System.RuntimeType.GetFields_internal (System.String name, System.Reflection.BindingFlags bindingAttr, System.RuntimeType+MemberListType listType, System.RuntimeType reflectedType) [0x0002f] in <b11ba2a8fbf24f219f7cc98532a11304>:0 
at System.RuntimeType.GetFieldCandidates (System.String name, System.Reflection.BindingFlags bindingAttr, System.Boolean allowPrefixLookup) [0x0000f] in <b11ba2a8fbf24f219f7cc98532a11304>:0 
at System.RuntimeType.GetFields …
```
=> Fix: ClearScript `GetUserDataResponse` propagation

Explorer/Assets/DCL/PluginSystem/Global/InputPlugin.cs, Explorer/Assets/DCL/UI/MainUIContainer/MainUIController.cs, Explorer/Assets/DCL/UI/MainUIContainer/MainUi.asmdef, Explorer/Assets/Scripts/Global/Dynamic/Bootstraper.cs, Explorer/Assets/Scripts/Global/Dynamic/MainSceneLoader.cs, Explorer/Assets/Scripts/MVC/ControllerBase.cs
We were receiving some weird sentry errors related to showing or hiding views during game loading. Turns out that the shortcuts were enabled during loading, even before the world was initialized.
It meant players could try to open the explore panel at any point and it would trigger different errors depending on which shortcut was pressed.
So, I added a couple of lines to disable the shortcuts during initialization + added the shortcuts to the disabled inputs at start. 
Why? because we got 2 stages were inputs are registered. First before systems are started but after plugins are initialized (which is were the inputs are registered to open the explore panel, for example). So in that interval inputs are working (which is why we got the DisableShortcuts() method called before that in the …
=> fix: Implemented disabling shortcut input before game is loaded

Explorer/Assets/DCL/NameTags/Systems/NametagPlacementSystem.cs
It changes the order of execution of the system NametagPlacementSystem.
2. Move the avatar.
The name tag must not jitter.
=> Fix: Nametag is jittery and detaching from the avatar (#1664)

Explorer/Assets/Scripts/Global/AppArgs/ApplicationParametersParser.cs
The logic with editor flags was missed on merge in PR https://github.com/decentraland/unity-explorer/pull/1848 
`private static readonly HashSet<string> ALWAYS_IN_EDITOR = new ()`
Restore this behaviour for proper Debug Panel workflow
1. Only in editor
2. Debug panel shows full info
=> Fix: always in editor flags

Explorer/Assets/DCL/Landscape/SatelliteFloor.cs
The separation between the ground assets (roads) and the satellite view chunks has increased from 0.001 to 0.005 (satellite planes are now placed at Y=-0.005). It's the minimum distance to avoid Z-fighting.
It moves the satellite view planes down to avoid z-fighting.
2. Go to a high place, like the tower where avatars are spawned.
3. Look at the horizon and move the camera, pay attention to roads that are far from you, there should not be any visual glitch on them.
=> fix: Clipping Issue on Roads and Scenes from a Distance (#1790)

Explorer/Assets/DCL/MapRenderer/MapCameraController/IMapCameraController.cs, Explorer/Assets/DCL/MapRenderer/MapCameraController/MapCameraController.cs, Explorer/Assets/DCL/Navmap/NavmapController.cs, Explorer/Assets/DCL/Navmap/NavmapLocationController.cs, Explorer/Assets/DCL/UI/SectionSelectorController.cs
PR centers map on its activation
Follow the ticket: https://github.com/decentraland/unity-explorer/issues/1742
=> Fix: 1742 map centering

Explorer/Assets/DCL/Character/CharacterCamera/Systems/ApplyCinemachineCameraInputSystem.cs
Fixes free-camera feature for editor. The assignment of `isAllowed` field was lost on the previous merge
1. Launch editor
2. Press f11 and use free-camera
=> fix arg propagation

Explorer/Assets/DCL/AvatarRendering/AvatarShape/Components/AvatarShapeComponent.cs
After we introduced a visibility optimization, avatar's in backpack and passport stopped rendering. 
This PR fixes that
2. Go to the backpack, change wearables. The avatar should not dissapear
3. Check passports. Avatar should be there
=> fix: avatar invisible in backpack after changes

Explorer/Assets/Scripts/Global/AppArgs/ApplicationParametersParser.cs, Explorer/Assets/Scripts/Global/AppArgs/IAppArgs.cs, Explorer/Assets/Scripts/Global/AppArgs/Tests.meta, Explorer/Assets/Scripts/Global/AppArgs/Tests/AppArgs.Tests.asmref, Explorer/Assets/Scripts/Global/AppArgs/Tests/AppArgs.Tests.asmref.meta, Explorer/Assets/Scripts/Global/AppArgs/Tests/AppArgsTests.cs, Explorer/Assets/Scripts/Global/AppArgs/Tests/AppArgsTests.cs.meta
Args keys are presented without '--' prefix
...
2. Try with and without `--debug` flag 
=> fix: AppArgs test and debug flag

Explorer/Assets/DCL/Character/CharacterCamera/Systems/ApplyCinemachineCameraInputSystem.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/AnalyticsController.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/StaticCommonTraitsPlugin.cs, Explorer/Assets/Scripts/Global/AppArgs/ApplicationParametersParser.cs, Explorer/Assets/Scripts/Global/Dynamic/BootstrapContainer.cs
we want to have same session_id and anonymous_id in both Launcher and Explorer. I just forward them from application cmd arguments.
Note: we cannot override Sentis `anonymous_id `, thus we introduce new one
2. Verify it launches :)
=> Chore: launcher ids in Explorer analytics

.github/workflows/pr-closure.yml
Fixing workflow that is supposed to remove the target on unity cloud when the PR is closed
=> fix: cleaning up unity target on PR closure

.github/workflows/build-release-weekly.yml, .github/workflows/test.yml, scripts/cloudbuild/build.py
- For release build we would use new build target to avoid blocking the main
- Don't run test if not modifying anything from Explorer folder
=> chore: separate build target for release build

Explorer/Assets/DCL/Landscape/Jobs/UpdateBoundariesCullingJob.cs, Explorer/Assets/DCL/Landscape/Systems/LandscapeMiscCullingSystem.cs, Explorer/Assets/DCL/Landscape/Systems/LandscapeTerrainCullingSystem.cs, Explorer/Packages/manifest.json
Removes unnecessary unity entities dependency.
Before:
After:
- Ensure the landscape works as normal in genesis and worlds
- Performance is the same or better
=> fix: remove entities dependency

Explorer/Assets/DCL/NameTags/Assets/NametagObject.prefab, Explorer/Assets/Rendering/ForwardRenderer - High.asset, Explorer/Assets/Rendering/ForwardRenderer - Low.asset, Explorer/Assets/Rendering/ForwardRenderer - Medium.asset
Added the same renderer feature to each renderer, Render Objects, which forces all geometry in the UI layer to render after the Transparent queue. The NametagObject prefab now has the UI layer instead of Default.
It forces nametags to render after all transparent objects.
2. Go to the basketball court, next to the Genesis plaza (ro to any other place where there are objects with transparencies).
3. Name tags should appear over everything at any moment.
=> fix: Some assets on the environment overlaps the nametag (#1032)

.github/workflows/build-release-weekly.yml, scripts/cloudbuild/build.py
=> fix: release workflow

Explorer/Assets/DCL/SDKComponents/Animator/Systems/AnimationPlayerSystem.cs
Fixes #1557
2. Turrets should always start on its normal state when the level is restarted
=> fix: apply latest animation state before disabling animator on objects in scenes

Explorer/Assets/Scripts/ECS/Unity/SceneBoundsChecker/CheckColliderBoundsSystem.cs, Explorer/Assets/Scripts/ECS/Unity/SceneBoundsChecker/Tests/ColliderBoundsCheckerShould.cs
We observed that randomly an object with a PointerEvents component started with its collider disabled.
By debugging we discovered that since [a recent optimization introduced](https://github.com/decentraland/unity-explorer/pull/1759) that makes the`CheckColliderBoundsSystem` run only once, this problem came to light.
What is happening is that sometimes/randomly during [this line](https://github.com/decentraland/unity-explorer/blob/00a8d6a6c077fe9f25f07a2397ee67204edf21bf/Explorer/Assets/Scripts/ECS/Unity/SceneBoundsChecker/CheckColliderBoundsSystem.cs#L76) the `collider.bounds.max` and `collider.bounds.min` is not completely updated by Unity (it holds values at 0,0,0; probably needs an extra frame or more to finish updating it) so the SDK collider ends up disabled in the end. And with the …
=> fix: unreliable sdk colliders initialization

Explorer/Assets/DCL/PluginSystem/World/GltfContainerPlugin.cs, Explorer/Assets/Scripts/ECS/Unity/GLTFContainer/Systems/LoadGltfContainerSystem.cs, Explorer/Assets/Scripts/ECS/Unity/GLTFContainer/Tests/LoadGltfContainerSystemShould.cs
Fixes #1911 
Fixes #1910 
In the rat scape scene (metadynelabs's world) whenever you grab a Mirror Box, the GLTF container changes the collision layer. This update was not propagated into the colliders cache. The fix consists on updating the cache of colliders when the `PBGltfContainer` requests a reconfiguration, so the raycasts can be calculated properly with latest collider changes in the `ExecuteRaycastSystem`.
=> fix: outdated colliders cache on gltf reconfiguration

Explorer/Assets/DCL/AvatarRendering/AvatarShape/Tests/EditMode/AvatarLoaderSystemShould.cs, Explorer/Assets/Scripts/ECS/StreamableLoading/Common/AssetPromise.cs, Explorer/Assets/Scripts/ECS/StreamableLoading/Common/Components/StreamableLoadingResult.cs, Explorer/Assets/Scripts/ECS/StreamableLoading/Common/Components/StreamableLoadingState.cs, Explorer/Assets/Scripts/ECS/StreamableLoading/Common/Systems/LoadSystemBase.cs
Fixes #1791 
- When `ForgetLoading` was called it didn't lead to the entity deletion. Its rensobility was in `LoadSystemBase`. However, if the promise was not allowed by `DeferredLoadingSystem` that flow was not starting at all leading to entities leak with `OperationCancelledException`
- Now `ForgetLoading` removes the entity and the flow in `LoadSystemBase` handles removed entities safely
- Ensure loading and unloading of assets, scenes, worlds, models all work as expected.
=> Fix: Prevent AssetPromise leak on cancellation

Explorer/Assets/Scripts/Global/ComponentsContainer.cs, Explorer/Assets/Scripts/ProtobufPartialClasses/IDirtyMarker.cs
Register PBGltfContainerLoadingState as an output component so it's presence is optional in ECS
=> Register PBGltfContainerLoadingState

Explorer/Assets/DCL/AvatarRendering/AvatarShape/Rendering/TextureArray/TextureArrayConstants.cs
Reduce avatar allocation to be able to instantiate aprox 25 avatars (assuming 10 wearables per avatar)
BEFORE
AFTER 
2. Instantiate avatars using the debug tool and check everything is okay
=> chore: Agressively reduce avatar texture pre-allocation

Explorer/Assets/DCL/SDKComponents/CameraControl/CameraModeArea/Systems/CameraModeAreaHandlerSystem.cs, Explorer/Assets/DCL/SDKComponents/CameraControl/MainCamera/Systems/MainCameraSystem.cs
fix #2046 
- removed Throttling from the system that handles CameraMode
1. Check steps on the mentioned issue
2. It would be nice to re-check that nothing get broken with virtual cameras, so please run QA tests from [this PR](https://github.com/decentraland/unity-explorer/pull/1744)
=> Fix: Metadynelabs - First-Person Mode Not Enforced and Toggle Allowed

Explorer/Assets/Scripts/ECS/Unity/GLTFContainer/Asset/Systems/PrepareGltfAssetLoadingSystem.cs
During local scene development, when using the hot reload (scene reloads when any change in the sdk-side of the locally running scene is made) the 3D models are not updated whtn the scene is reloaded. So if the creator had changed the model, after the hot reload they still see the old verion.
Issue: https://github.com/decentraland/unity-explorer/issues/2082
Added local scene development check when using cache at gltfAsset preparation.
https://github.com/user-attachments/assets/5acb9c1e-1e63-4ec7-96eb-512b7c84a4af
=> fix: sdk hot reload models caching

Explorer/Assets/DCL/EmotesWheel/EmotesWheelController.cs
Fix #2047 
Changes the emote wheel input registration such that the keys are listened only after the menu opening and unregisters the inputs after closing preventing the possibility to fire an emote before the actual menu is properly shown.
2. Open the emote wheel and trigger an emote
3. Try to trigger an emote while the wheel is opening
4. Verify that B+num shortcut still works
5. Spamming B doesn't break the lifecycle of the wheel menu
=> fix: Emote wheel closure

Explorer/Assets/DCL/AuthenticationScreenFlow/AuthenticationScreenController.cs
This fixes the issue when logging out and then back in. IN short, the auth screen wouldnt close.
This really small tweak fixes it. Looks like we were not awaiting properly for the event.
Log into the game, then go to profile -> log out, then try to login again. Now the whole flow should work OK.
Fixes:
#1969 
#2006 
(they are the same issue reported twice 😁 )
=> fix: Authentication screen wont close

Explorer/Assets/DCL/MapRenderer/Addressables/MapPinMarkerObject.prefab, Explorer/Assets/DCL/Minimap/Assets/MinimapMapPinMarkerObject.prefab, Explorer/Assets/DCL/Navmap/Assets/DestinationInfoElement.prefab, Explorer/Assets/Textures/MapPins/MiniGamePin_DefaultIcon.png.meta
The icon was wrongly imported for some reason, so I fixed it and re-added it to the prefabs.
...
Just check the nav map after enabling the global px (/loadpx globalpx), the pin should show a joystick icon. The same icon should appear on the minimap when setting it as destination as well as in the bottom panel with the current destination in the navmap window.
=> fix: Missing icon on minigame map pins

Explorer/Assets/DCL/AvatarRendering/Emotes/Helpers/IEmoteStorage.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Helpers/MemoryEmotesStorage.cs, Explorer/Assets/DCL/Multiplayer/SDK/Tests/AvatarEmoteCommandPropagationSystemShould.cs, Explorer/Assets/DCL/PluginSystem/Global/EmotePlugin.cs, Explorer/Assets/DCL/Profiles/DataModels/Avatar.cs, Explorer/Assets/DCL/Profiles/Self/SelfProfile.cs
Fix #2124
- filled up emote wheel with default emotes
- See related ticket.
- Check that emote wheel for not new users didn't brake
=> fix: Empty Emote Wheel for new users 

Explorer/Assets/DCL/Notifications/Assets/BadgeNotification.prefab, Explorer/Assets/DCL/Passport/Prefabs/Badges/BadgeDetailCard_PassportField.prefab, Explorer/Assets/DCL/Passport/Prefabs/Badges/BadgeInfo_PassportSubView.prefab, Explorer/Assets/Textures/Common/BadgeNotificationContainer.png.meta, Explorer/Assets/Textures/Common/Rays.png.meta, Explorer/Assets/Textures/Passport/ProgressBarContainer.png.meta, Explorer/Assets/Textures/Passport/ProgressBarFill.png.meta
Fix #2121 
2. Trigger a badge reward (e.g., Citizen, Traveler).
3. Check that the push notification appears with all its sprites correctly.
2. Open your passport.
3. Go to Badges section.
4. Check that all the progress bars in the cards and in the detail view appears with its sprites correctly.
=> fix: Several missing sprites in Badges feature

Explorer/Assets/Scripts/ECS/StreamableLoading/AssetBundles/Editor/CompileSceneShader.cs, Explorer/ProjectSettings/GraphicsSettings.asset
Fix: #2043 #2009
Might not fix the #2009, because it's believed the back end server is down. But we can presume if it fixes the Bubble Shooter then it'll fix the other, because the time line of the bug lines up.
Merges 2 variant lists, adds them back into pre-loaded shaders, adds dynamic branching to texarray and makes other variant changes
=> fix: SceneShader variant merging and branching in TexArray

Explorer/Assets/DCL/Notifications/Assets/NotificationIcons.asset, Explorer/Assets/DCL/Notifications/NotificationsMenu/NotificationsMenuController.cs
Fix #2123 
Fixes the errors listed in the issue related to the arrived at destination location by ignoring internal notification in the notification panel (as per design)
...
* Launch the explorer.
* Set a destination on the map.
* Travel to the set destination --> this should trigger the arrival notification.
* Observe if the push notification for destination arrival appears.
* Check the notifications panel in the sidebar and see if previous notifications are cleared and if new ones are obscured behind the arrival notification.
=> Fix: arrived at destination notification bugfixes

.github/workflows/build-profile-nightly.yml
Automatically builds a build that can be profiled, once per day.
=> chore: introduce a nightly profileable build

Explorer/Assets/DCL/Settings/ModuleControllers/ResolutionSettingsController.cs
On my Mac, if I have a second monitor connected, I dont get any resolutions added because `Screen.resolutions` doesnt return 16:9 resolutions. Therefore, I get an `OutOfBounds` exception in `SetResolutionSettings()`.
This PR adds a default resolution for this scenario
2. Do happy path
=> fix: Add default resolution

Explorer/Assets/DCL/Audio/Avatar/AvatarAudioController.prefab, Explorer/Assets/DCL/Audio/Prefabs/LandscapeAudioSource.prefab, Explorer/Assets/DCL/Audio/Prefabs/MediaPlayer.prefab, Explorer/Assets/DCL/AvatarRendering/AvatarShape/Assets/EmoteAudioSource.prefab
I removed the doppler effect from all AudioSources.
...
Do sounds! try moving the camera close and far at the same time, there should be no audio distortion caused by the doppler effect.
=> fix: remove doppler from audiosources

Explorer/Assets/DCL/SDKComponents/SceneUI/Components/UITransformComponent.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Systems/UITransform/UITransformSortingSystem.cs
This fixes a null ref that was happening on the onboardingdcl scene sometimes, its basically just a null check before doing a sorting. Otherwise the user gets stuck with a white square in the middle of the screen.
=> fix: UI sibling sorting error

Explorer/Assets/DCL/LOD/Components/SceneLODInfo.cs, Explorer/Assets/DCL/LOD/Systems/InstantiateSceneLODInfoSystem.cs, Explorer/Assets/DCL/LOD/Systems/RecalculateLODDistanceSystem.cs
It makes LOD0 of "small" scenes to appear when the camera is farther than before. Scenes with 10 parcels or less are considered "small" (arbitrary value, depending on performance). The smaller the scene is (under 11 parcels), the larger the distance from which the LOD0 is visible with respect to its original value.
2. Go to -94,-96.
3. Walk around and see how LOD0 of the small scenes appear at farther distances.
Demo video:
https://github.com/user-attachments/assets/603f325d-990d-4c8c-9e9f-8d097ea6be20
The LOD ranges of the scene of the purple ground and the pink floating stone, at the end of the video, have changed like this:
FROM
TO
And performance has been affected this way (measured with PIX, in a build without the changes and another with them, walking like in …
=> fix: [QA] LOD Loads Only When Very Close to Scenes (#1728)

Explorer/Assets/DCL/AvatarRendering/AvatarShape/Helpers/AvatarMaterialPoolHandler.cs
On program exit, the disposal was throwing a NRE. This just stops that from occuring
This was the error before this PR
```
Trying to copy properties from null material.
#0 GetStacktrace(int)
#1 DebugStringToFile(DebugStringToFileData const&)
#2 MaterialScripting::CopyPropertiesFrom(Material*, Material*)
#3 Material_CUSTOM_CopyPropertiesFromMaterial(ScriptingBackendNativeObjectPtrOpaque*, ScriptingBackendNativeObjectPtrOpaque*)
#4 Action_1_Invoke_m5A038831CEB84A7E374FE59D43444412629F833F_ClosedInstInvoker(Action_1_t923A20D1D4F6B55B2ED5AE21B90F1A0CE0450D99*, void*, MethodInfo const*)
#5 ObjectPool_1_Release_m71F1CADB7AD9CC20BD824583A3675A4260965DB5_gshared
#6 AvatarMaterialPoolHandler_Release_mC6B2F1508B89DA6B310DDD7CC98E6F9DDD6E3978
#7 …
```
=> fix: Avoid null material copy on dispose

Explorer/Assets/DCL/NameTags/Systems/NametagPlacementSystem.cs, Explorer/Assets/DCL/PluginSystem/Global/AvatarPlugin.cs
Hides nametags until the avatar is ready
2. Get some friends. Connect one by one. Nametags should appear with avatar
3. Same works with the avatar debug tool. If you isntantiate avatars, they should appear when the avatar appears
=> fix: Nametag visibility

Explorer/Assets/DCL/AvatarRendering/AvatarShape/ComputeShader/AvatarMaterialConfiguration.cs
Fixes the avatar differences in emission, fixes the scene smoothness/roughness default value, and adds parallax to the scene shader.
Test the avatars, as the others will be verified by the art team.
=> fix: Avatar Emissions & Scene Smoothness and Parallax

Explorer/Assets/DCL/AvatarRendering/AvatarShape/Assets/AvatarBase.prefab, Explorer/Assets/DCL/AvatarRendering/AvatarShape/Systems/AvatarInstantiatorSystem.cs, Explorer/Assets/DCL/AvatarRendering/AvatarShape/UnityInterface/AvatarBase.cs
There was an overhead added by the `RigBuilder` on remote entities. I just disabled the component, since remote entities do not use IK, so they dont need it
It brings a slight improvement of about `1.41ms` in Median. Illsutrated here, this are 30 avatars in `olavra`. Left is with RigBuilder, Right is without
2. Get some friends. Do all the basic avatar related stuff (emotes, run, jump). They should look the same as in `main`
3. Check in the backpack that your avatar is fine
=> chore: Remove rig builder for remote entities

Explorer/Assets/DCL/Multiplayer/Profiles/Announcements/RemoteAnnouncement.cs, Explorer/Assets/DCL/Multiplayer/Profiles/RemoteProfiles/RemoteProfiles.cs
It reverts the "Avoid downloading the same remote profile multiple times" fix -> #2165 
=> fix-revert: Revert "Avoid downloading the same remote profile multiple times"

Explorer/Assets/Locales/Localization Tables/SceneLoadingDefaultTips_en.asset
Changed builder title to `Creator Hub` in the loading screen.
2. Hit until the loading screen
3. Change the pages until you see the Creator Hub title
=> fix: creator hub title in loading screen

Explorer/Assets/DCL/Landscape/Utils/TerrainGeneratorLocalCache.cs
Corrected the way we store and delete the local cache, since the new version was prone to failure when the `checksum` was not the one that was stored
1. Delete all local terrain files
2. Enter the client and see the terrain. Explore the borders as well
3. Reset the client and repeat step 2. You are looking to the cached terrain now, everything should be the same.
4. Get out and delete only the `terrain_cache_dictionaries` folder
5. Repeat step 2
6. Get out and delete the terrain cache file
7. Repeat step 2
8. Repeat one last time step 2 to see once again the cached terrain
=> fix: Terrain cache local handling

Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/Systems/BadgesHeightReachedSystem.cs
Avoid NRE from BadgesHeightReachedSystem when re-login
2. Enter the world
3. Logout the user
4. Login it again
5. Check the "Vertical Voyager" value in the Debug Panel works fine.
6. Check that everything else works as expected.
=> fix: Avoid NRE from BadgesHeightReachedSystem when re-login

Explorer/Assets/DCL/AvatarRendering/AvatarShape/ComputeShader/AvatarMaterialConfiguration.cs
Avatar emissions are brought back, but shouldn't cause areas to glow when they shouldn't and smoothness fix on scene shader, as recognised in the play test, where some things were super shiney and sparkly when they shouldn't be.
=> fix: Avatar Emissions brought back and roughness on scene fixed

Explorer/Assets/DCL/PluginSystem/DCL.Plugins.asmdef, Explorer/Assets/DCL/UserInAppInitializationFlow/DCL.UserInAppInitializationFlow.asmdef, Explorer/Assets/DCL/UserInAppInitializationFlow/RealFlowLoadingStatus.cs, Explorer/Assets/DCL/UserInAppInitializationFlow/RealUserInAppInitializationFlow.cs, Explorer/Assets/DCL/UserInAppInitializationFlow/StartupOperations/LoadGlobalPortableExperiencesStartupOperation.cs, Explorer/Assets/DCL/UserInAppInitializationFlow/StartupOperations/LoadGlobalPortableExperiencesStartupOperation.cs.meta, Explorer/Assets/Scripts/Global/Dynamic/BootstrapContainer.cs, Explorer/Assets/Scripts/Global/Dynamic/Bootstraper.cs, Explorer/Assets/Scripts/Global/Dynamic/DebugSettings.meta, Explorer/Assets/Scripts/Global/Dynamic/DebugSettings/DebugSettings.cs, Explorer/Assets/Scripts/Global/Dynamic/DebugSettings/DebugSettings.cs.meta, Explorer/Assets/Scripts/Global/Dynamic/DebugSettings/Global.Dynamic.DebugSettings.asmdef, Explorer/Assets/Scripts/Global/Dynamic/DebugSettings/Global.Dynamic.DebugSettings.asmdef.meta, Explorer/Assets/Scripts/Global/Dynamic/DebugSettings/IDebugSettings.cs, Explorer/Assets/Scripts/Global/Dynamic/DebugSettings/IDebugSettings.cs.meta, Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs, Explorer/Assets/Scripts/Global/Dynamic/MainSceneLoader.cs
After we added the onboarding experience to the game, the global PX should not load at the start regardless anymore, but only in those cases where we are not taking the user to the onboarding experience.
So we are checking the profile values for that and acting accordingly.
Also, converted the whole loading of these PX as part of the proper loading operations.
...
To test, start the game with a new user, you should be taken to the onboardingdcl world and not see the global px.
The following game starts should take you to Genesis and the global px should load after a short while. (if it is enabled in the feature flags - which it is right now)
Resolves #2163
=> Chore: add logic to load global PX as part of startup operations

Explorer/Assets/DCL/Character/CharacterMotion/Components/MovementInputComponent.cs, Explorer/Assets/DCL/Character/CharacterMotion/Systems/UpdateInputMovementSystem.cs, Explorer/Assets/DCL/Input/UnityInputSystem/DCLInput.cs, Explorer/Assets/DCL/Input/UnityInputSystem/DCLInput.inputactions
The feature has been removed from code and from the input system config.
Now the Caps lock key does not make the avatar walk.
2. Press Caps lock key.
The avatar does nothing.
=> fix: Avatar moving on its own when pressin CAPS (#1743)

Explorer/Assets/DCL/Passport/Modules/UserAdditionalFields_PassportSubModuleController.cs, Explorer/Assets/DCL/Passport/Modules/UserDetailedInfo_PassportModuleController.cs
Fix #2153 
1. Go to the Passport.
2. Change the date on Birth Date using the format `ddMMyyyy`.
3. Check that the date is saved correctly.
4. Change the date on Birth Date using the format `dd/MM/yyyy`.
5. Check that the date is saved correctly.
6. Change the date on Birth Date using an invalid date format, for example writting a normal text.
7. Chack that the Passport show you an error saying that the profile's saving has failed.
=> fix: Incorrect birthdate in the Profile when it is saved from the Passport

Explorer/Assets/DCL/SDKComponents/SceneUI/Classes/DCLImage.cs, Explorer/Assets/DCL/SDKComponents/SceneUI/Systems/UIBackground/UIBackgroundInstantiationSystem.cs
Fix #2141 
When we initiated a dialogue with any NPC, a white square briefly appeared in the dialogue box before the NPC's image loads correctly. This caused a visual glitch that appeared for a moment before the proper asset is displayed.
This was happening because the loading life-cycle of an image UI component consists on 2 steps: Firstly the component with an empty texture (white) is instantiated and, after this, we request the texture loading. This second step can take a bit of time, so during this time we would see a white box in the screen.
In order to solve this we simply hide the component's canvas at the beginning and, when the texture has been loaded, we show it back.
2. Initiate a dialogue with any NPC.
3. Check that the white box doesn't appear anymore. …
=> fix: Hide UI images until its texture is loaded

Explorer/Assets/DCL/Multiplayer/Profiles/Entities/Prefabs/RemoteAvatarCollider.prefab
Fixes #2204
The remote avatar colliders were way bigger than the current's player avatar. The collider has been reduced so the click area is accordingly set to the avatar's area.
1. Follow issue steps and check that the click area is correct
2. Check that you can always interact with the avatars as expected
=> fix: remote avatar click interaction

Explorer/Assets/DCL/Landscape/Utils/TerrainGeneratorLocalCache.cs
The file stream was not correctly disposed when trying to delete the file. This PR resorts the code as needed
2. Do the steps in this [PR](https://github.com/decentraland/unity-explorer/pull/2206)
=> fix: Terrain local cache still open when trying to delete

Explorer/Assets/DCL/Character/CharacterMotion/Animation/AvatarAnimationEventsHandler.cs
This was caused by checking the movement blend value, but when we jump/land in place, we have no blend value, so check's always false. So I removed the check when jumping or landing which makes sense.
Jump in place. You should hear the sounds both when you take off and when you land.
=> Fix: Jumping/Landing in place makes no sound

Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/Systems/MovementBadgesSystem.cs
Fix a NRE in happened in `MovementBadgesSystem`.
=> fix: NRE in MovementBadgesSystem

Explorer/Assets/DCL/AvatarRendering/Emotes/Components/Intents/GetEmotesByPointersIntention.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/Load/LoadSceneEmotesSystem.cs
Fixes #2296
Fixes #2276 
Fixes this exception which produces to not be able to see other avatars in-world:
```
TimeoutException: Emote intention timeout urn:decentraland:matic:collections-v2:0x0b472c2c04325a545a43370b54e93c87f3d5badf:2:210624583337114373395836055367340864637790190801098222508621955124,urn:decentraland:matic:collections-v2:0xef832a5183bf2e4099efed4c6ec981b7b41aa545:0:135,urn:decentraland:matic:collections-v2:0xa6c722476bdd17bf2adb65e96388345d83259f3b:0:537,urn:decentraland:matic:collections-v2:0xe2fa84a384fa86c29855dd3909874b3dbddc74bc:0:541,clap,money,kiss,headexplode,urn:decentraland:matic:collections-v2:0x0ae365f8acc27f2c95fc7d60cf49a74f3af21573:3:315936875005671560093754083051011296956685286201647333762932932770
UnityEngine.DebugLogHandler:LogException(Exception, …
```
=> fix: emote timeouts no longer prevent avatars from loading

Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/Play/EmotePlayer.cs
Fixes #2274 
Fixes cases on which the emotes are not correctly converted and contains no `Animator`. This was provoking a flood in the object hierarchy degrading the performance significantly.
1. Launch the explorer with `--self-force-emotes urn:decentraland:matic:collections-v2:0x7bdc37ff3e8dca2d69f01a3dc34f3ad82e2e1870:0`
2. Try playing that emote
3. The emote will not be played, but the client should not degrade its performance
4. Play any other emote. It should work as expected
=> fix: missing animator component on emotes

Explorer/Assets/DCL/Landscape/IContainParcel.cs, Explorer/Assets/DCL/Landscape/IContainParcel.cs.meta, Explorer/Assets/DCL/Landscape/TerrainGenerator.cs, Explorer/Assets/DCL/Landscape/Worlds/TerrainModel.cs, Explorer/Assets/DCL/Landscape/Worlds/WorldTerrainGenerator.cs, Explorer/Assets/DCL/PluginSystem/Global/LandscapePlugin.cs, Explorer/Assets/Scripts/ECS/SceneLifeCycle/Realm/IRealmNavigator.cs, Explorer/Assets/Scripts/Global/Dynamic/ChatCommands/ChangeRealmChatCommand.cs, Explorer/Assets/Scripts/Global/Dynamic/ChatCommands/GoToChatCommand.cs, Explorer/Assets/Scripts/Global/Dynamic/RealmNavigator.cs, Explorer/Assets/Scripts/Global/Dynamic/TeleportOperations/MoveToParcelInSameRealmTeleportOperation.cs, Explorer/Assets/Scripts/Utility/GenesisCityData.cs
fix #2254
Prevent user to teleport outside of bounds of Genesis or World, by checking if parcel is inside generated terrain parcels. Works only when Landscape is enabled.
2. `/goto 1000,1000` -> error message from the system in the chat
3. `/goto 50,50` -> you teleported
4. `/goto olavra`
5. `/goto-local 50,50` -> validate error message in chat
6. `/goto-local 5,5 `-> you teleported normally
7. `/goto 1,1000` -> error message
8. `/goto 100,1` -> you teleported back in Genesis
=> Fix: can teleport outside city

Explorer/Assets/DCL/Passport/Fields/EquippedItem_PassportFieldView.cs, Explorer/Assets/DCL/Passport/Modules/EquippedItems_PassportModuleController.cs
Fix #2239 
Hide BUY button for base equipped items in the Passport.
Follow STR described in the issue associated.
=> fix: Hide BUY button for base equipped items in the Passport

Explorer/Assets/DCL/BadgesAPIService/BadgesUtils.cs, Explorer/Assets/DCL/Passport/Fields/Badges/BadgeDetailCard_PassportFieldView.cs, Explorer/Assets/DCL/Passport/Modules/Badges/BadgeInfo_PassportModuleSubController.cs
Fix #2309 
The progress bar of all "not achieved" badges doesn't show the progress although the number is increasing.
2. Open your passport.
3. Observe that the progress bars of all yours "not achieved" badges is correctly updated: the steps number in the left side of the screen match with the length of the orange progress bar.
=> fix: Progress bar for not achieved badges is always empty

Explorer/Assets/DCL/Chat/ChatController.cs
If we received a chat message while the view wasnt ready (IE: the loading screen) we would get the follwoing NRE
```
NullReferenceException: Object reference not set to an instance of an object
DCL.Chat.ChatController.CreateChatEntry (DCL.Chat.ChatMessage chatMessage) (at Assets/DCL/Chat/ChatController.cs:473)
DCL.Chat.History.ChatHistory.AddMessage (DCL.Chat.ChatMessage message) (at Assets/DCL/Chat/History/ChatHistory.cs:31)
DCL.Chat.ChatController.OnMessageAdded (DCL.Chat.ChatMessage chatMessage) (at Assets/DCL/Chat/ChatController.cs:452)
DCL.PerformanceAndDiagnostics.Analytics.ChatMessagesBusAnalyticsDecorator.ReEmit (DCL.Chat.ChatMessage obj) (at Assets/DCL/PerformanceAndDiagnostics/Analytics/DecoratorBased/ChatMessagesBusAnalyticsDecorator.cs:29) …
```
=> fix: NRE on chat message

Explorer/Assets/Locales/Localization Tables/SceneLoadingDefaultImages Shared Data.asset, Explorer/Assets/Locales/Localization Tables/SceneLoadingDefaultImages_en.asset, Explorer/Assets/Locales/Localization Tables/SceneLoadingDefaultTips Shared Data.asset, Explorer/Assets/Locales/Localization Tables/SceneLoadingDefaultTips_en.asset
This PR was created to remove the builder tip and to update the `Decentraland editor` tip title for `Creator Hud` instead.
2. While in the loading screen, check the Builder tip has been successfully removed.
3. Check that the tip which contains the SDK image has the new `Creator Hud` title implemented.
=> style: update loading screen tips

Explorer/Assets/DCL/NameTags/NametagView.cs
Fixes #2270 
There was a miss-management of the cancellation token in the name tags animation process. The original `CancellationTokenSource.Token` was referenced on each case, instead of passing a `CancellationToken` through parameter. When the original source was disposed it provoked the described exception.
The solution consists on only referencing the `CancellationTokenSource` once, at the start of the process and pass the `CancellationToken` only to the pipeline. Additionally, when the `cts` is disposed a new instance is required, since it becomes unusable. A proper `OperationCancelledException` handling was implementer to reset the internal animation state.
2. Group up with another peer in the same place
3. Write in the chat
4. The chat bubbles over the …
=> fix: nametags cancellation token

Explorer/Assets/DCL/Chat/ChatCommandsHandler.cs, Explorer/Assets/DCL/Chat/ChatController.cs, Explorer/Assets/DCL/Chat/MessageBus/CommandsHandleChatMessageBus.cs, Explorer/Assets/DCL/Chat/MessageBus/IChatMessagesBus.cs, Explorer/Assets/DCL/Chat/MessageBus/IgnoreWithSymbolsChatMessageBus.cs, Explorer/Assets/DCL/Chat/MessageBus/MultiplayerChatMessagesBus.cs, Explorer/Assets/DCL/Chat/MessageBus/SelfResendChatMessageBus.cs, Explorer/Assets/DCL/Minimap/MinimapController.cs, Explorer/Assets/DCL/Navmap/FloatingPanelController.cs, Explorer/Assets/DCL/Navmap/NavmapController.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/DecoratorBased/ChatMessagesBusAnalyticsDecorator.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/DecoratorBased/IdentityAnalyticsDecorator.cs, Explorer/Assets/DCL/TeleportPrompt/TeleportPromptController.cs
All sent chat messages considered to be same on Analytics, so I added property to have possibility to filter chat commands on the backend
You cannot verify adjustment to analytics, but it would be good to check that these variations of /goto are working fine:
1. from JumpIn button on Navmap
2. from Back-to-Genesis on Minimap
3. from chat `/goto`
=> fix: count command chat messages

Explorer/Assets/DCL/MapRenderer/MapLayers/UsersMarker/UsersMarkersHotAreaController.cs
Fix #2310
Removes correctly the player markers of players that leave the game
...
2. Have some people around you
3. Check their red marker in the map works fine
4. Check that if they disconnect the red marker in the map/minimap disappears correctly
=> fix: removed player marker when user disconnects

Explorer/Assets/DCL/AvatarRendering/Thumbnails/Utils/LoadThumbnailsUtils.cs, Explorer/Assets/DCL/AvatarRendering/Wearables/Tests/ResolveWearableByPointerSystemShould.cs, Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandUrlsSource.cs, Explorer/Assets/Scripts/ECS/SceneLifeCycle/SceneFacade/Systems/LoadSceneSystemLogicBase.cs, Explorer/Assets/Scripts/ECS/StreamableLoading/AssetBundles/Tests/PrepareAssetBundleLoadingParametersSystemShould.cs, Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/GltFastDownloadProvider.cs, Explorer/Assets/Scripts/SceneRunner/Scene/SceneAbDto.cs, Explorer/Assets/Scripts/SceneRunner/Scene/SceneAssetBundleManifest.cs, Explorer/Assets/Scripts/SceneRunner/Scene/Tests/SceneAssetBundleManifestShould.cs
There's an issue with ABs and their dependencies. If I have an asset bundle which has external dependecies, and only the external dependecies change, leaving the origin asset bundle hash to remain the same, cache problems arouse. This tries to solve it by
- CDN Cache: Adds the entity hash to the ABs path if the version is greater than 25. 
- Unity Local Cache: Modifies how we use `Hash128`. We are now hashing the date as well, if we didn't, the local asset bundle cache will still return the old ones on a scene redeployment
As a result, each asset is going to be unique for every scene re-deploy
The downside is that assets will not persist during scene re-deployment. If a scene get redeployed, the local cache is invalid.
Requires this ABConverter …
=> feat: use entity hash for ABs

Explorer/Assets/DCL/NameTags/Systems/NametagPlacementSystem.cs
Fix #2321
With this PR if you arrive next to people that were chatting you won't see their previous messages in the chat bubble
...
2. With 1 client go far away from the second client
3. send a message
4. With the second client get close so that the nametag is visible
5. Verify that no old chat bubble is displayed
=> Fix: remove chat bubbles for late at party

Explorer/Assets/DCL/RewardPanel/Assets/RewardPanel.prefab, Explorer/Assets/DCL/UI/ConnectionStatusPanel/Assets/ConnectionStatus.prefab, Explorer/Assets/DCL/UI/MainUIContainer/MainUIContainer.prefab
This PR was created to change the connection button position, which after the latest quest design updates is now overlapping the mission button. Additionally, the reward screen copies were updated to establish a better connection with this as the reward of having completed the mission steps. 
2. Activate the portable experience writing in the chat the command `loadpx globalpx`. Once it loaded, check the mission button is next to the mini-map an that the connection on is now in the right top corner. Try to hide the sidebar to validate it is not messing with the x position of the button.
3. Complete all the task to earn the reward. Validate the title now says `Mission reward / New item unlocked!` and the button 'collect' instead of continue.
=> style: relocate connection button & update reward screen copy

Explorer/Assets/DCL/WebRequests/GenericDownloadHandlerUtils.cs
Fix #2271 
This PR removes the origin header that was wrongly introduced.
This has been removed to avoid the
`The header Origin is managed automatically, setting it may have no effect or result in unexpected behavior.`
Warning that was spammed for every get request.
This Warning was being sent because the header Origin is a Forbidden header name and cannot be manually changed
...
2. Do a smoke test of inventory, map, walking around and scene loading
=> fix: removed origin header from get requests

Explorer/Assets/DCL/Backpack/BackpackSlotsController.cs
Fix #2180 
Fix #1836 
When we did set a wearable (for example the skeleton legs) that hides another wearable (the shoes), if we did configure the hidden slot as "force render" and, after that, we unequipped it, the final status of the avatar kept with the 2 wearables visible: the wearable that hides another wearables (the skeleton legs) + the avatar's feet naked above the first wearable.
2. Open your backpack.
3. Choose a wearable that hides some other wearable (for example the skeleton legs).
4. Go to the hidden slot (in this case the "shoes" slot) and select any wearable.
5. Set the hidden slot as "force render" (clicking the red eye in the right-bottom side of the slot).
6. Check that the hidden wearable is now visible in the avatar preview.
7. Unequipp the …
=> fix: Reset "force renderer" when unequip a wearable slot

Explorer/Assets/DCL/Settings/Prefabs/Settings.prefab
Fix #2354 
Sometimes when we opened the Settings Menu, the container size was not being adapted to the total height of all the controllers loaded inside.
Remove unneeded Content Size Fitter components inside the Settings Menu. It fix the issue and, in addition, improves the performance of the UI.
Follow the STR described in the issue associated.
=> fix: Some settings menus cannot be seen properly when opening them

Explorer/Assets/DCL/RewardPanel/Assets/RewardPanel.prefab, Explorer/Assets/Textures/BackpackPanel/NFTDefaultIcon.png
The opacity of the background was not enough to enhance legibility. As you can see in the screenshot it was a bit chaotic.
This is the new version, with 98% opacity while the previous was 70%
2. Launch the quest writing in the chat `/loadpx globalpx`.
3. Complete all the task to win the reward and validate the new background transparency is there.
=> style: increase reward background opacity

Explorer/Assets/DCL/PluginSystem/World/MaterialWorldPlugin.cs
Fixes the issue of seeing released textures on new materials. Like these:
2. Go to 43,100
3. Go to -139,-28
4. Check that images don't have unrelated textures
=> fix: Reset material properties when returning to pool

Explorer/Assets/DCL/Character/CharacterPreview/CharacterPreviewControllerBase.cs, Explorer/Assets/DCL/Passport/PassportController.cs, Explorer/Assets/DCL/Passport/Prefabs/Badges/Badge3DPreviewCamera.prefab
Fix #2312 
Fix #2365 
This PR avoid, when the Badges section in the Passport is open, to have other preview cameras (like the avatar one) activated at the same time.
This was happening when we did open the Passport and open the Badges tab... both cameras, avatar and badge previews, were activated and this was provoking an important downgrade in terms of performance, especially for high resolutions like in Macs.
Another scenario where it was happening was when we did open the Backpack and then open the Passport from the top-right side of the Explorer Menu and then open the Badges section... 3 cameras were activated here: the Backpack's avatar preview, the Passport avatar preview and the Badges preview. This was also provoking important performance's donwgrades.
I was not personally able to …
=> fix: Keep de-activated other avatar previews while the Passport is open (probably avoid crashes/freezes)

Explorer/Assets/DCL/SDKComponents/MediaStream/OpenMediaPromise.cs, Explorer/Assets/DCL/WebRequests/WebRequestControllerExtensions.cs, Explorer/Assets/Scripts/Global/Dynamic/RealmController.cs
This fixes this issue #2333 .
What happens here is that our Media Player logic does a HEAD request to check if the resource is available. But in this case, the HEAD returns 404 even thou a GET request goes through perfectly.
So I added a check in case of receiving a 404 after a HEAD to make a GET. If the GET Fails, then we assume the resource IS in fact unavailable.
...
Just go to the Inn while there is a stream in process (otherwise you will just see the default image)
It should work normally and you should be able to see the stream.
=> fix: Added a GET request as fallback when HEAD request fails

Explorer/Assets/Scripts/ECS/Prioritization/Settings/RealmPartitionSettingsAsset.cs
There was a wrong min value calculation for max loading distance. It was incorrectly "hardcoded" to the min value
No need to do `Min` or `Clamp` on Get. Those are already done in Set
2. Set loading distance to 100
3. Check that you can see further than at least 20 parcels (you can fly around to get the idea)
=> fix: Correct max loading distance

Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/GltFastDownloadProvider.cs, Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/LoadGLTFSystem.cs
An Assets Loading Budget "Token" (max 50, defined in SO: GlobalPluginsSettings->StaticSettings->AssetsLoadingBudget) is assigned to every GLTF that wants to be loaded.
Since we didn't release that budget until the GLTF finished loading, when a scene with 50 or more GLTFs (that use external textures, thus needing an extra budget token for those) is loaded, the loading flow gets deadlocked, and all those asset promises are never finished (the loading screen goes away after timeout).
Moved the `AcquiredBudget` release to the correct place, **as soon as the GLTF file itself has been fetched, regardless of its dependencies**, just as we already do [for Asset Bundles as well](https://github.com/decentraland/unity-explorer/blob/7f466c89500a8499eede466d4b435026a618a260/Explorer/Assets/Scripts/ECS/ …
=> fix: 50 plus gltf entities scene not loading locally

Explorer/Assets/DCL/Passport/Fields/Badges/BadgeDetailCard_PassportFieldView.cs, Explorer/Assets/DCL/Passport/Modules/Badges/BadgeInfo_PassportModuleSubController.cs
Fix #2414 
Clamps the calculated badge progress to 0-100 in order to prevent the visual overflow that can happen due to backend errors
2. Open your profile
3. Browse the badges
4. Check that every progress bar doesn't overflow (even if the progress is above 100%, e.g. 9 steps of 2 total)
=> fix: prevent badges progress bar size overflow

Explorer/Assets/DCL/Backpack/Assets/ItemInfoPanel.prefab, Explorer/Assets/DCL/Navmap/Assets/FloatingPanel.prefab, Explorer/Assets/DCL/Navmap/Assets/Navmap.prefab, Explorer/Assets/DCL/Navmap/FloatingPanelController.cs, Explorer/Assets/DCL/Navmap/FloatingPanelView.cs, Explorer/Assets/DCL/Navmap/NavmapController.cs, Explorer/Assets/DCL/Navmap/NavmapZoomController.cs
Fix #2284 
Prevent the execution of the map zoom if the cursor is on top of the floating panel for the Jump In destination
2. Open the map
3. Scroll and check that map zooms in/out
4. Click on any point of the map
5. Hover with the mouse on the panel to Jump In
6. Scroll the mouse wheel and check that the map doesn't zooms in/out and only the modal does
7. Hover with the mouse in the map
8. Scroll the mouse wheel and check that the map zooms in/out
=> fix: prevent map zoom when floating panel is opened

Explorer/Assets/DCL/AvatarRendering/AvatarShape/Components/AvatarShapeComponent.cs, Explorer/Assets/DCL/AvatarRendering/AvatarShape/Systems/AvatarInstantiatorSystem.cs, Explorer/Assets/DCL/AvatarRendering/AvatarShape/Systems/AvatarLoaderSystem.cs, Explorer/Assets/DCL/AvatarRendering/AvatarShape/Tests/Instantiate/AvatarInstantiatorSystemShould.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Components/Intents/GetEmotesByPointersIntention.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Helpers/EcsEmoteProvider.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/FinalizeEmoteLoadingSystem.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/Load/LoadEmotesByPointersSystem.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/Load/LoadSceneEmotesSystem.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/Play/CharacterEmoteSystem.cs, Explorer/Assets/DCL/Character/CharacterPreview/CharacterPreviewController.cs, Explorer/Assets/DCL/PluginSystem/Global/EmotePlugin.cs
Fixes #2298
We do not request all the emotes of all the remote avatars anymore. Instead we request the emotes whenever they need to be played. For the **main player only** we keep requesting all of which are described in the `profile.emotes`.
This change should greatly reduce the amount of requests we make to the content server / asset bundles, specially when we are in places on which there is a lot people around. It should reduce the memory consumption and unlock many processes that were stuck due to budgeting.
2. Check that you can play all your emotes
3. Get in a group of people and start playing emotes
4. You should be able to see your emotes and the ones from the remote avatars too
5. Go to the backpack and change your emotes
6. Check that emotes play in the …
=> fix: emote lazy loading

Explorer/Assets/DCL/SDKComponents/TextShape/System/VisibilityTextShapeSystem.cs
Now the visibility is set to its original value when the TextShape leaves and enters the scene again, instead of setting it as visible. Now both things are always considered, the original visibility and the position with respect to the scene.
2. Jump to different worlds.
Check that only texts that should be visible really are, in Genesis plaza or other worlds.
=> fix: TextShapes are visible when they should not

Explorer/Assets/DCL/AvatarRendering/AvatarShape/Systems/AvatarShapeVisibilitySystem.cs
Right now when performance degrades a lot and therea re hiccups in the main thread, the main camera following (in first person camera) can't keep up with the main player position, thus getting outside the minimum camera distance range that hides the main avatar in first person mode.
Adjusted minimum camera distance for hiding the avatar by testing in a specific place where the problem is always reproducible.
Put the camera in first person mode, go to `51, 72` and move towards the center of the Art Week Plaza to reproduce the issue, as shown in the video:
https://github.com/user-attachments/assets/e4770549-3921-4d5c-b27a-3d5be82227d7
Do the same with the build from this PR and confirm that the problem doesn't happen anymore.
=> chore: adjust minimum camera distance for main avatar visibility

Explorer/Assets/DCL/Ipfs/IpfsRealm.cs, Explorer/Assets/DCL/WebRequests/CommonArguments.cs, Explorer/Assets/DCL/WebRequests/WebRequestController.cs
Fix #2382 
Introduces a retry delay for profile deployments requests
...
2. Change wearables in the backpack
3. Check that it works fine
=> fix: added retry await for profile deployment requests

Explorer/Assets/DCL/LOD/Settings/ILODSettingsAsset.cs, Explorer/Assets/DCL/LOD/Settings/LODSettingsAsset.cs, Explorer/Assets/DCL/LOD/Systems/UpdateVisualSceneStateSystem.cs, Explorer/Assets/DCL/LOD/Systems/VisualSceneStateResolver.cs, Explorer/Assets/DCL/LOD/Tests/EditMode/ResolveVisualSceneStateSystemShould.cs, Explorer/Assets/Scripts/ECS/SceneLifeCycle/Components/VisualSceneState.cs
Added a small time before we switch from a scene/scene promise to a LOD, reducing the visual glitches and reducing the edge cases caused by quickly panning around the camera.
Go to -150,0, zoom into 1st person view, then approach the lonely house at -150,-3 until it changes from LOD to Scene. Then zoom out. It should take about 5seconds until it turns into LOD again. If you zoom in, it will turn into a scene again.
This delay should work for all scenes allowing to pan the camera around and leave a scene and come back without it changing too quickly to LODs.
Please let me know if the time set is OK or if we need more time for the change to happen.
https://github.com/user-attachments/assets/a8cb663d-37d6-49f0-ac6d-8b21bdd174cc
=> fix: issues with quick transition between LOD - Scene - LOD - Scene

.github/workflows/build-unitycloud.yml, .github/workflows/pr-comment-artifact-url.yml
This PR adds a CI step to upload the builds to a S3 bucket, relying on S3 capabilities because github often rate-limited our downloads.
=> chore: Upload builds to S3 bucket

Explorer/Assets/DCL/AvatarRendering/AvatarShape/Systems/AvatarShapeVisibilitySystem.cs
Updated main avatar visibility toggle logic to run on first person cam instead of camera distance.
* Confirm that the main avatar is hidden when entering first person mode
* Confirm that the main avatar is NOT hidden when the THIRD PERSON camera gets close ot it (for example in genesis plaza if you make the camera slide through the floor when moving the mouse up, you make it get close to the main player)
* Confirm the problem shown in [the video from this other PR](https://github.com/decentraland/unity-explorer/pull/2468) is also not happening
=> chore: hide main avatar only on first person camera

Explorer/Assets/DCL/UserInAppInitializationFlow/StartupOperations/LoadGlobalPortableExperiencesStartupOperation.cs
At some point we had disabled the loading of the global pxs when users had to do the tutorial, but now the PX already implements hidding on worlds, so it isnt necessary + when users finish the tutorial they will get the quests from the px.
This addresses that.
...
Log in with a new user, you should be taken into the tutorial world and NOT see the UI from the portable experience.
When you finish the tutorial (or at least one of the steps), and go back to Genesis Plaza, you should see the UI from the global PX with the quests and whatnot.
Also the minimap pins from the portable experience should also be visible on the navmap (both in world and in genesis).
=> chore: global px will always be loaded

Explorer/Assets/DCL/Multiplayer/Connections/Archipelago/Rooms/ForkGlobalRealmRoom.cs
This PR uses a fake room for the scenes that have specified in the scene.json an adapter called 
`
"fixedAdapter": "offline:offline"
`
In this way we won't have an error in the connection that forces a connection retry
...
2. /goto onboardingdcl
3. verify that everything works fine
4. Go back to genesis
=> fix: added fake room for scenes with offline:offline adapter

Explorer/Assets/DCL/SDKComponents/AudioSources/AudioSourceExtensions.cs
Supports the `PBAudioSource.global` property: https://js-sdk-toolchain.pages.dev/interfaces/ECS.PBAudioSource#global
This feature allows creators to play sounds all over the scene without attaching the audio into the player entity transform.
An example on how to do it from the scene:
```
const clip = 'assets/audio/music/RAC - Genesis Plaza 1.mp3'
AudioSource.create(music, {
audioClipUrl: clip
})
Transform.create(music, { position: Vector3.Zero() })
AudioSource.getMutable(music).volume = 0.04
AudioSource.getMutable(music).loop = true
AudioSource.getMutable(music).playing = true
AudioSource.getMutable(music).global = true;
```
Actually im not aware of any scene using this feature since never worked in the old renderer.
Just go through any scene and check that the sounds works as expected. …
=> feat: add support for global sounds

Explorer/Assets/Scripts/ECS/SceneLifeCycle/Systems/GatherGltfAssetsSystem.cs
Fixes this:
```
NullReferenceException: Object reference not set to an instance of an object.
at UnityEngine.Pool.CollectionPool`2+<>c[TCollection,TItem].<.cctor>b__5_1 (TCollection l) [0x00000] in <00000000000000000000000000000000>:0 
at UnityEngine.Pool.ObjectPool`1[T].Release (T element) [0x00000] in <00000000000000000000000000000000>:0 
at ECS.SceneLifeCycle.Systems.GatherGltfAssetsSystem.Dispose () [0x00000] in <00000000000000000000000000000000>:0 
at Arch.SystemGroups.CustomGroupBase`1[T].DisposeInternal () [0x00000] in <00000000000000000000000000000000>:0 
at Arch.SystemGroups.SystemGroup.Dispose () [0x00000] in <00000000000000000000000000000000>:0 
```
A scene may be disposed before initialized. This handles that situation
2. Do some health checks …
=> fix: NRE for entities under observation

Explorer/Assets/DCL/ECS/GlobalPartitioning/GlobalDeferredLoadingSystem.cs, Explorer/Assets/Scripts/ECS/StreamableLoading/DeferredLoading/AssetsDeferredLoadingSystem.cs
Data types were using the old return type instead of the new `..Data`. This was harmless because the promise entity gets deleted after consumed. But, for whatever reason, it took longer to consume, they were unnecessarily queried.
Also, this is the consists way to do it.
2. Play happy path
=> chore: Replace data types in GlobalDeferredSystems

.github/workflows/build-release-main-page.yml
The weekly release page was building the page using `dev` which is default and not `main`
=> fix: weekly release page

Explorer/Assets/DCL/Chat/ChatController.cs, Explorer/Assets/DCL/EmojiPanel/EmojiPanelController.cs, Explorer/Assets/DCL/EmojiPanel/EmojiSearchController.cs
Fix #2527 (maybe also fixed #2477 )
Removes the input blocker management from the emoji panel as it's handled by the chat controller already
...
2. Search for an emoji in the chat.
3. Exit the emoji search using 'Esc', then the 'X' button, or by clicking outside the chat.
4. Try to move the avatar or use hotkeys like U, B, N, M, I.
=> Fix: avoid movement blocking to affect when closing emoji search

Explorer/Assets/DCL/Multiplayer/Movement/Interpolation.cs
additional check for zero vector
doesn't produces spikes anymore
just fast smoke test
=> Fix: zero lookAt rotation in multiplayer

Explorer/Assets/DCL/Chat/Assets/Chat.prefab, Explorer/Assets/DCL/Chat/Assets/ChatEntry.prefab, Explorer/Assets/DCL/Chat/Assets/ChatEntryOwn.prefab, Explorer/Assets/DCL/NameTags/Assets/NametagObject.prefab
This PR removes the possibility of using rich text in chat, chat bubble and chat entries
...
2. Chat with emojis
3. Try to chat with stuff like "We are <color = green>green</color> with envy"
4. Verify no strange text appears and all work fine
=> fix: removed rich text from chat

Explorer/Assets/DCL/SDKComponents/TextShape/TMPProSdkExtensions.cs
When the cached TextMeshPro instances were reused and the new outline width equaled zero, it tried to disable the outline shader keyword which does not exist in the shader (so the previous values related to outline stayed the same and were still used). Now it also resets the values of the related properties.
It resets the default values of the outline and shadow effects when they are not used.
1. Launch the explorer (Genesis)
2. Go to NicoE world.
Texts atop the buttons should be white without outline.
=> fix: The outline of text shapes is wrong when created

Explorer/Assets/DCL/Multiplayer/Connections/Archipelago/Rooms/ForkGlobalRealmRoom.cs, Explorer/Assets/DCL/Multiplayer/Connections/Rooms/Connective/IConnectiveRoom.cs
Changes how we consider the fake room. It returns as connected, so it can be used in the :offline:offline adapter
1. Open through  decentraland://?realm=onboardingdcl.dcl.eth as new user
2. Check that you get to the onboarding world
=> fix: Connect to fake room

Explorer/Assets/Scripts/ECS/StreamableLoading/GLTF/GltFastDownloadProvider.cs
During local scene development, some GLTFs may have external dependencies on a deept path than just the same folder as the GLTF. The `GLTFastDownloadProvider` wasn't contemplating that.
Corrected how the `GLTFastDownloadProvider` forms its download urls
1. Download [this test scene](https://github.com/user-attachments/files/17481231/gltf-deeper-external-deps-test.zip) and uncompress it somewhere
3. Confirm that the loading gets stuck at 88% or similar, and if the scene loads it's empty.
4. Close the Explorer that auto-opened. Leave the scene running in the console/terminal.
5. Download the build from this PR and connect it to the running scene using [the console …
=> fix: raw gltf external dependencies deeper path

Explorer/Assets/DCL/LOD/Systems/VisualSceneStateResolver.cs
When I added the new LOD change delay, I did a last minute change and missed a check that should have been done before dirtying the scene state. Which meant that if we moved and changed buckets, the scene would get re-dirtied and the timer would be reset, so unless we stood still or at a distance that didnt change buckets, the LOD would not be loaded again.
This is fixed now :)
...
https://github.com/user-attachments/assets/6107c9d0-131a-45e3-af06-327e0a3ba45c
RUN FOREST! RUN!
Spawn in Genesis Plaza and run away from it, after some seconds running it should switch from scene to LOD (its obvious because the scene has animations in the clouds and whatnot).
Same with any other scene (the smaller the scene, the closer the 5 seconds until they disappear will start counting)
It should work like …
=> fix: scenes not switching to LOD properly.

Explorer/Assets/DCL/LOD/Systems/VisualSceneStateResolver.cs
Scene were loading in distance, when the LOD should load. This happened when the scene was not initialized
2. .Go to 70,0 and walk to Genesis Plaza. Wait till it appear. It should first load the LOD, and when you get approx 2 parcels away, it should load the scene
=> fix: scene was loading in distance

Explorer/Assets/DCL/SDKComponents/MediaStream/MediaPlayerExtensions.cs, Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerSystem.cs
Fix #2588
This is an integration of the fix of https://github.com/decentraland/unity-explorer/issues/2294 to tackle a specific case 
...
2. Go to 0,83
3. Verify that master volume and world volume correctly modify the stream audio volume
=> fix: update audio for streams with no volume set

Explorer/Assets/DCL/Settings/ModuleControllers/ResolutionSettingsController.cs
Fix #2411 
Prevent the filtering of valid resolutions when the monitor is in vertical orientation (which flips the aspect ratio e.g: 16:9 -> 9:16)
You can check that the current live build suffers from the same problem as the one described in the linked issue on any monitor when it is in vertical orientation.
1. Make sure your monitor is in vertical orientation
2. Launch the explorer
3. Check that in the settings menu all the standard resolutions are there but with flipped aspect ratios
=> fix: support resolutions for vertical monitor orientation

Explorer/Assets/DCL/AvatarRendering/Emotes/Helpers/ApplicationParamsEmoteProvider.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Helpers/ApplicationParamsEmoteProvider.cs.meta, Explorer/Assets/DCL/AvatarRendering/Wearables/ApplicationParametersWearablesProvider.cs, Explorer/Assets/DCL/Backpack/CharacterPreview/BackpackCharacterPreviewController.cs, Explorer/Assets/DCL/Character/CharacterPreview/CharacterPreviewController.cs, Explorer/Assets/DCL/Character/CharacterPreview/CharacterPreviewControllerBase.cs, Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
Fixes #2536 
The root of the issue is that the avatar load process do not wait for the emotes to be loaded anymore since emotes lazy loading. This caused problems in the avatar preview.
The solution consists on waiting for the emote promise to be resolved before showing the avatar preview.
Additionally a new app param has been added to be able to preview emotes in the backpack:
```
--self-preview-emotes urn1,urn2
```
If you dont have any emote 2.0 (with props) you can launch the explorer with this command:
```
--self-preview-emotes urn:decentraland:matic:collections-v2:0x0ae365f8acc27f2c95fc7d60cf49a74f3af21573:4
```
2. Check that the authentication screen shows the avatar preview as expected
3. Open the backpack and follow the issue steps
4. Open other user …
=> fix: emotes spam stuck

Explorer/Assets/DCL/PluginSystem/World/TweenPlugin.cs, Explorer/Assets/DCL/SDKComponents/Tween/Components/CustomTweener/CustomTweener.cs, Explorer/Assets/DCL/SDKComponents/Tween/Components/CustomTweener/CustomTweenerImpl.cs, Explorer/Assets/DCL/SDKComponents/Tween/Components/CustomTweener/ICustomTweener.cs, Explorer/Assets/DCL/SDKComponents/Tween/Components/CustomTweener/TweenerPool.cs, Explorer/Assets/DCL/SDKComponents/Tween/Systems/TweenSDKComponentHelper.cs, Explorer/Assets/DCL/SDKComponents/Tween/Systems/TweenUpdaterSystem.cs, Explorer/Assets/DCL/SDKComponents/Tween/Tests/TweenUpdaterSystemShould.cs
**In the previous episode of Tweenage Ninja Turtles:**
We fixed how tweens were updating its values, making them update the SDK transform and letting the UpdateTransform system to take over and do the proper transform update.
BUT, this brought an unintended (or intended?) consequence, tween update frequency would depend on the update cycle of the scene. So if it either had low FPS because of throttling or because something heavy was going on in the scene, the tween would update slower than normal.
Apparently, this is not expected and tweens should be independent of the scene update cycle.
**In this episode:**
We fix that by updating the Transform along with the SDK transform... It is NOT the most elegant solution. I still believe the whole flow needs refactoring. And we need to discuss …
=> fix: tweens update with scene cycle

Explorer/Assets/DCL/PluginSystem/World/SceneUIPlugin.cs, Explorer/Assets/Scripts/Global/StaticContainer.cs
The system that hides UI when the shortcut is pressed did not have the proper reference to the scene UI root. Which it cannot have easily as the sceneUI plugin is init'ed in the StaticContainer.
The easy and clean solution is to just have a callback when the hideUI button is pressed to hide it.
...
Open the game, wait until the portable experience UI is shown and press the "U" key to hide the UI.
It should hide the PX UI as well.
=> Fix: HideUI shortcut must hide Scene UI

Explorer/Assets/Scripts/ECS/StreamableLoading/Common/AssetPromiseExtensions.cs
Adds the loading intention type that failed to get more information when this error appears:
```
Exception: The promise generated no result
DCL.Diagnostics.ReportHandlerBase:LogException(Exception, ReportData, Object)
DCL.Diagnostics.ReportHubLogger:LogException(Exception, ReportData, ReportHandler)
DCL.Diagnostics.ReportHub:LogException(Exception, ReportData, ReportHandler)
ECS.StreamableLoading.Common.Components.StreamableLoadingResult`1:.ctor(ReportData, Exception)
ECS.StreamableLoading.Common.AssetPromiseExtensions:SafeTryConsume(AssetPromise`2&, World, ReportData, StreamableLoadingResult`1&)
DCL.AvatarRendering.AvatarShape.Systems.AvatarInstantiatorSystem:InstantiateNewAvatar(Entity&, AvatarShapeComponent&, CharacterTransform&) …
```
=> chore: Add loading intention type on fail to get more info

Explorer/Assets/DCL/Landscape/TerrainGenerator.cs, Explorer/Assets/DCL/Landscape/TerrainGeneratorTest.cs, Explorer/Assets/DCL/Landscape/Utils/LandscapeParcelService.cs, Explorer/Assets/DCL/Landscape/Utils/TerrainGeneratorLocalCache.cs, Explorer/Assets/DCL/PluginSystem/Global/LandscapePlugin.cs, Explorer/Assets/Scripts/Global/Dynamic/BootstrapContainer.cs, Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
Adds support for zone terrain
1. Delete the terrain cache so you have a fresh start (Its in https://docs.unity3d.com/ScriptReference/Application-persistentDataPath.html)
2. Start the app normally and check that the terrain is fine (look around, check that no grass is in parcels, go to the sea and check its fine)
3. Start the app again but with the param `--dclenv zone`
4. Do the same terrain check. Go to `-68,-90` and check that its a valid scene and terrain does not invade it
5. Restart app again and check the terrain in regular world. Everything should be fine 
=> feat: support for zone terrain

Explorer/Assets/DCL/Passport/Prefabs/Badges/BadgeInfo_PassportSubView.prefab, Explorer/Assets/DCL/Passport/Prefabs/Badges/BadgeOverviewItem_PassportField.prefab
This PR was created to fix this issue #2450 and fix the line break from the counter when there is a badge that supports a ridiculous large number, as happens in the example attached bellow.
2. Open your profile card or others profile card to check that the tooltip, when hovering a badge with a large name, is not being masked anymore.
3. Then try to find someone who has unlocked the 'Walkabout Wanderer Bronze' badge. Validate that the counter next to the progress bar is not making a line break.
=> style: badges minor fixes

Explorer/Assets/DCL/MapRenderer/MapLayers/Atlas/SatelliteAtlas/SatelliteChunkController.cs
This PR fixed a bug in the suppress error for the satellite map chunks download, so that the client keeps working even if the map is not succesfully downloaded
...
2. Verify that it works correctly
3. If map is not visible the explorer should work anyway
=> fix: fixed suppress error in satellite map chunk download

Explorer/Assets/DCL/Interaction/Systems/ProcessPointerEventsSystem.cs, Explorer/Assets/Protocol/DecentralandProtocol/PointerEvents.gen.cs, scripts/package-lock.json, scripts/package.json
Currently scenes have no control over the automatic shader highlighting that happens on interractable objects (pointer event entities).
These are the possible pointer events feedback combinations that the scene can set today:
* Highlight ON + Hover Text ON
* Highlight ON + Hover Text OFF
These other states are not possible today:
* Highlight OFF + Hover Text OFF
* Highlight OFF + Hover Text ON
* Implemented support for new `showHighlight` property in the `PBPointerEvents` component, binding the highlight setup of entities to that property.
* Minor change on `showFeedback` usage to also avoid enabling the highlight if it's `false`, as the highlight is also **the feedback**
* Minor check to avoid enabling the `hoverText` if the component comes with that property with an empty string. Didn't …
=> feat: sdk pointer event toggle highlight

Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandEnvironment.cs, Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandUrlsSource.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/Builders/BuilderExtensions.cs, Explorer/Assets/Scripts/Global/Dynamic/ChatCommands/ChangeRealmChatCommand.cs, Explorer/Assets/Scripts/Global/Dynamic/ChatCommands/EnvironmentValidator.cs, Explorer/Assets/Scripts/Global/Dynamic/ChatCommands/EnvironmentValidator.cs.meta, Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs, Explorer/Assets/Scripts/Global/Dynamic/RealmController.cs, Explorer/Assets/Scripts/Global/Dynamic/RealmNavigatorDebugView.cs, Explorer/Assets/Scripts/Global/Dynamic/RealmNavigatorDebugView.cs.meta
`peer-testing.decentraland.org` is a new testing environment. 
- This environment allows creators who own land in the Ethereum blockchain to deploy content without deploying to the production (`org`) environment, therefore overriding the production content only on those parcels.
- The `un-overriden` parcels still show the production content
So, what this PR does
1. Adds support for `.today` environment. 
- It will connect to [peer-testing.decentraland.org/](http://peer-testing.decentraland.org/about) only since its the only valid test environment with comms configuration
- It will grab asset bundles from the `.today` environment
- All other URLs remains pointing to `.org`, since they should replicate the behaviour there
2. Introduces some rigidness for environments based on the `dclenv` …
=> feat: testing realms

Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/AnalyticsEvents.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/DCL.Analytics.asmdef, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/DecoratorBased/MVCManagerAnalyticsDecorator.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/EventBased/SupportAnalytics.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/EventBased/SupportAnalytics.cs.meta, Explorer/Assets/DCL/UI/Sidebar/SidebarController.cs
This PR add tracking event when users clicks on the help button. 
Closing #2728 
2. Click help button
3. The user should get redirected to the help page
=> chore: add open support tracking event

Explorer/Assets/DCL/SDKComponents/MediaStream/Components/MediaPlayerComponent.cs, Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/CreateMediaPlayerSystem.cs, Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/VideoEventsSystem.cs
Currently we are avoiding propagating a new state of the `VideoEvent` component to the scene when the `VideoState`doesn't change, but that is wrong because the `CurrentTime` property should still be propagated for the scene to use it (example: the video state keeps being "Playing" and we never update the video time again because the state doesn't change...).
Added tracking for last propagated video time and added that to the check in which we avoid propagating unnecessary video events to the scene.
1. Download [test scene](https://github.com/user-attachments/files/17660671/video-time-test.zip) and uncompress it somewhere
3. When the Explorer opens and finishes loading the scene, get in front of the …
=> fix: sdk video event time propagation

Explorer/Assets/DCL/FeatureFlags/FeatureFlagsStrings.cs, Explorer/Assets/DCL/SkyBox/Plugin/TimeOfDaySystem.cs, Explorer/Assets/DCL/StylizedSkybox/Scripts/Plugin/StylizedSkyboxPlugin.cs, Explorer/Assets/DCL/StylizedSkybox/Scripts/SkyboxController.cs, Explorer/Assets/DCL/StylizedSkybox/StylizedSkybox.asmdef, Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
Added a couple of settings that we read from the FF to handle the skybox.
For now its only the initial time and the speed, but in the future we can easily expand it to handle other settings we would wanna tweak remotely.
...
You can set the settings through here  (as long as you have the proper permissions xD) ->
https://features.decentraland.systems/#/features/variants/explorer-alfa-skybox-settings
Otherwise, the value I set right now is time of day 0 (midnight) and speed 300 (10 times faster than normal).
In the new settings <time> represents in seconds the hour of the day, 0 being 0:00:00 hs and 86400 being 23:59:59hs. 
<speed> represents how much we accelerate the clock, the default value is 30 (so one minute = 2 seconds), higher value means shorter days and viceversa. 1 represents …
=> feature: add feature flag to control skybox settings

Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandUrl.cs, Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandUrlsSource.cs, Explorer/Assets/DCL/MapRenderer/Addressables/MapRendererConfiguration.prefab, Explorer/Assets/DCL/MapRenderer/ComponentsFactory/MapRendererChunkComponentsFactory.cs, Explorer/Assets/DCL/MapRenderer/ComponentsFactory/MapRendererConfiguration.cs, Explorer/Assets/DCL/MapRenderer/MapLayers/Atlas/ParcelAtlas.meta, Explorer/Assets/DCL/MapRenderer/MapLayers/Atlas/ParcelAtlas/ParcelChunkAtlasController.cs, Explorer/Assets/DCL/MapRenderer/MapLayers/Atlas/ParcelAtlas/ParcelChunkAtlasController.cs.meta, Explorer/Assets/DCL/MapRenderer/MapLayers/Atlas/ParcelAtlas/ParcelChunkController.cs, Explorer/Assets/DCL/MapRenderer/MapLayers/Atlas/ParcelAtlas/ParcelChunkController.cs.meta, Explorer/Assets/DCL/MapRenderer/MapLayers/MapLayer.cs, Explorer/Assets/DCL/Navmap/Assets/FiltersContainer.prefab, Explorer/Assets/DCL/Navmap/Assets/Navmap.prefab, Explorer/Assets/DCL/Navmap/FilterPanel/NavmapFilterPanelView.cs, Explorer/Assets/DCL/Navmap/NavmapController.cs, Explorer/Assets/DCL/Navmap/SatelliteController.cs
This PR adds back the support for parcel view and map type switching in the navmap
...
2. Open the map
3. Open the filter view in bottom left
4. Switch between parcel view and satellite view 
=> feat: added parcel view and map type selector logic

.github/workflows/auto-sync-main-to-dev.yml, .github/workflows/create-release-branch.yml
The `repo-sync/pull-request` action is replaced with a direct call to gh pr create.
The GitHub CLI is actively supported, while `repo-sync/pull-request` has been already deprecated
=> fix: remove deprecated hub usage in workflows

Explorer/Assets/DCL/UserInAppInitializationFlow/RealUserInAppInitializationFlow.cs, Explorer/Assets/DCL/UserInAppInitializationFlow/StartupOperations/CheckOnboardingStartupOperation.cs
The issue users were experiencing was related to the Island that was not being reset when setting the new realm when loading into the onboarding world. This meant that new users that were redirected to that world, would be in the same island as genesis city users, seeing their chat and their avatars.
We were using just the `realmController.SetRealmAsync` but that only changed the realm data, but did not force a reset of the archipelago room. In the case of the onboarding world, it has no comms, so there should be no room connection, but we were keeping GC's one.
I changed this to use the TryChangeRealmAsync on the RealmNavigator, that properly goes through all the steps of stopping the current realm and switching it to a new one. Avoiding any other potential issue that could appear.
... …
=> fix: changed method to change realm when loading onboarding world

Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/VideoEventsSystem.cs
The problem was related to a mechanism to detect erroneous streams after no change in current time for more than 10 seconds. Now it checks that it was not manually paused previously and, if it was, then it plays normally.
There PR where the mechansim was originally implemented: https://github.com/decentraland/unity-explorer/pull/2563
1. Download this scene: https://github.com/decentraland-scenes/media-gallery-test and uncompress it somewhere
4. Close the Explorer that auto-opened. Leave the scene running in the console/terminal.
5. Download the build from this PR and connect it to the running scene using [the console command](https://github.com/decentraland/unity-explorer/wiki/How-to-connect-to-a-lo …
=> fix: Videos were freezing if paused more than 10 secs and played again

Explorer/Assets/DCL/AvatarRendering/AvatarShape/Helpers/AvatarInstantiationPolymorphicBehaviour.cs, Explorer/Assets/DCL/Minimap/MinimapController.cs
We still dont have 100% repro steps, but seems like on certain situations, a wearable with no ABs does not get replaced properly by the default wearables and so, when it gets to the AttachToAvatar code, it breaks, as the Asset is null.
This just adds a simple remediation with error logging to avoid breaking the game in this situation.
When we find a proper repro step, we can make a proper fix to the underlying issue.
+I also fixed a small totally unrelated null ref on the minimap that I was getting when quitting the game during the loading screen.
...
For now lets just do a smoke test. Once we get proper repro steps we will prepare a proper fix.
=> Fix: add remediation when a broken wearable doesnt gets replaced by default wearable.

Explorer/Assets/DCL/AvatarRendering/Loading/Assets/AttachmentAssetUtility.cs
Fixes #2789 
A wearable cannot contains animators or animation because that breaks the skinning. This PR cleans up the wearable to avoid the situation
Testing with https://decentraland.org/marketplace/contracts/0xd2bd1cadfe12ee9d37ff95912af7f8a97ae71ba0/tokens/128
2. Instantiate an avatar with urn `urn:decentraland:matic:collections-v2:0xd2bd1cadfe12ee9d37ff95912af7f8a97ae71ba0:0` (using the avatar creator debug)
3. Check that there are no giant feet, and the avatar has the slippers
4. Do several emotes and check that everything is okay
=> fix: Gigantic feat

Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/Builders/IDebugContainerBuilder.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/DebugUtilitiesContainer.cs, Explorer/Assets/Scripts/Global/Dynamic/RealmNavigatorDebugView.cs
Adds the realm debug tab to the regular debug menu
1. Launch the explorer no debug
2. Do `/debug'
3. Check that the realm tab is there
=>  chore: Adds realm debug tab to standard debug menu

Explorer/Assets/DCL/UserInAppInitializationFlow/DCL.UserInAppInitializationFlow.asmdef, Explorer/Assets/DCL/UserInAppInitializationFlow/RealUserInAppInitializationFlow.cs, Explorer/Assets/Scripts/ECS/SceneLifeCycle/Realm/IRealmNavigator.cs, Explorer/Assets/Scripts/Global/Dynamic/RealmNavigator.cs
I noticed that if we are on GP and we switch user, the scene is not properly reset. This causes the dispenser to block claiming for the following users if the first one already claimed it.
I just added a forceChangeRealm bool when calling the teleport to GP, so we do change realm (with all the associated processes) even if we are already there.
This fixes this issue and potentially other issues caused by this.
...
Log into GP with one user. Claim a wearable in the dispenser, you should get the message saying that the wearable is incoming and that it be sent to you soon. If you try again it will say you already claimed it.
Then, log out and change user. You will be teleported again to GP where you need to try to claim the wearable in the dispenser again. You will get the same message …
=> fix: switching user while on GP wont restart the scene properly

Explorer/Assets/DCL/ApplicationVersionGuard/ApplicationVersionGuard.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Helpers/ApplicationParamsEmoteProvider.cs, Explorer/Assets/DCL/AvatarRendering/Wearables/ApplicationParametersWearablesProvider.cs, Explorer/Assets/DCL/FeatureFlags/FeatureFlagsProviderExtensions.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/StaticCommonTraitsPlugin.cs, Explorer/Assets/DCL/PluginSystem/Global/MultiplayerMovementPlugin.cs, Explorer/Assets/DCL/UserInAppInitializationFlow/StartupOperations/CheckOnboardingStartupOperation.cs, Explorer/Assets/Scripts/Global/AppArgs/AppArgsFlags.cs, Explorer/Assets/Scripts/Global/AppArgs/AppArgsFlags.cs.meta, Explorer/Assets/Scripts/Global/AppArgs/ApplicationParametersParser.cs, Explorer/Assets/Scripts/Global/AppArgs/IAppArgs.cs, Explorer/Assets/Scripts/Global/Dynamic/BootstrapContainer.cs, Explorer/Assets/Scripts/Global/Dynamic/DynamicSceneLoaderSettings.cs, Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs, Explorer/Assets/Scripts/Global/Dynamic/MainSceneLoader.cs, Explorer/Assets/Scripts/Global/Dynamic/RealmLaunchSettings.cs
CLI app args flags were scattered through the code and sometime presented as "magic strings". Sometimes it leadedeven to duplication. I extracted it into one static class, so it is easier to see which params we have already and what can be used.
1. Launch the explorer with some command line arguments and verify it works as previously 
Examples: "`--debug`", "`--versionControl`" and "`--simulateVersion`"
=> Chore: centrilized app args flags 

Explorer/Assets/DCL/Character/CharacterCamera/CameraMode.cs, Explorer/Assets/DCL/Character/CharacterCamera/Character Camera.prefab
We found that in some scenes that did camera changes, having the Unknown as 0 in the CameraMode enum, broke the camera.
This removes it because best practices are for losers xDD
...
Got to any minigame with camera change like (-121,-59) and play it and then exit it, the camera should return to normal instead of sending you to the extratosphere :) 
Fixes: https://github.com/decentraland/unity-explorer/issues/2828
=> fix: Unknown camera mode Enum breaks scenes

Explorer/Assets/DCL/AvatarRendering/Thumbnails/Systems/ResolveAvatarAttachmentThumbnailSystem.cs
Long story short, I found that after doing some clicking around in the backpack when the wearables thumbnails havent finished loading yet, you could "lock" some wearables in a perpetual "loading" state, where the thumbnail would not load and you could also not preview them nor see the EQUIP/UNEQUIP button.
After a lot of digging, from our side the problem was that when requesting a cancellation of the loading in the `ResolveAvatarAttachmentThumbnailSystem `we would do this: `promise.TryForgetWithEntityIfCancelled` and that would remove the entity and whatnot BUT we would keep the `wearable.ThumbnailAssetResult` as not null. Which meant that when the thumbnail was requested again to the `ECSThumbnailProvider`, we would never go past this check `promiseAlreadyCreated = …
=> fix: wearables thumbnails stops loading after switching panels

Explorer/Assets/DCL/CommunicationData/URLHelpers/URLBuilder.cs, Explorer/Assets/DCL/EventsApi/HttpEventsApiService.cs, Explorer/Assets/DCL/Navmap/Assets/PlacesAndEventsPanel.prefab, Explorer/Assets/DCL/Navmap/EventInfoCardController.cs, Explorer/Assets/DCL/Navmap/EventInfoPanelController.cs, Explorer/Assets/DCL/Navmap/INavmapBus.cs, Explorer/Assets/DCL/Navmap/NavmapCommandBus.cs, Explorer/Assets/DCL/Navmap/NavmapSearchBarController.cs, Explorer/Assets/DCL/Navmap/PlaceInfoPanelController.cs, Explorer/Assets/DCL/Navmap/PlaceInfoPanelView.cs, Explorer/Assets/DCL/Navmap/PlacesAndEventsPanelController.cs, Explorer/Assets/DCL/Navmap/PlacesAndEventsPanelView.cs, Explorer/Assets/DCL/Navmap/SearchForPlaceAndShowResultsCommand.cs, Explorer/Assets/DCL/PlacesAPIService/IPlacesAPIClient.cs, Explorer/Assets/DCL/PlacesAPIService/IPlacesAPIService.cs, Explorer/Assets/DCL/PlacesAPIService/PlacesAPIClient.cs, Explorer/Assets/DCL/PlacesAPIService/PlacesAPIService.cs, Explorer/Assets/DCL/PluginSystem/Global/ExplorePanelPlugin.cs, Explorer/Assets/DCL/UI/TMP_Text_ClickeableLink.cs, Explorer/Assets/DCL/UI/TMP_Text_ClickeableLink.cs.meta, Explorer/Assets/DCL/UI/TextMeshProExtensions.cs, Explorer/Assets/DCL/UI/TextMeshProExtensions.cs.meta
- fix http request missing auth-chain for "set as interested" on an event 
- empty state on events tab
- add links to urls in the places & events descriptions
- fix http request for getting events of Genesis Plaza (more than parcel 255 parameters)
- disable/enable map zoom when the pointer enters/exits the side panel area
- make a clean search after the map is re-opened
=> feat: improvements and fixes on places and events panel

Explorer/Assets/DCL/Navmap/INavmapBus.cs, Explorer/Assets/DCL/Navmap/NavmapCommandBus.cs, Explorer/Assets/DCL/Navmap/SearchForPlaceAndShowResultsCommand.cs, Explorer/Assets/DCL/PluginSystem/Global/ExplorePanelPlugin.cs
Adds the possibility to hook you into an event everytime places are searched through the search bar in the side panel. This will allow to mark the parcels in the map.
=> feat: search places bus event

Explorer/Assets/Scripts/Global/Dynamic/PortableExperiences/ECSPortableExperiencesController.cs
SO, we were reusing the ServerAbout and it caused (when loading multiple PXs without delay) to sometimes load the wrong scenes for one of the PXs...
This is fixed now.
...
Open the client, it should load the PXs correctly and track the progress of the MF quests correctly as well.
=> fix: loading multiple pxs at start time issues

Explorer/Assets/DCL/AvatarRendering/Wearables/Components/Wearable.cs, Explorer/Assets/DCL/AvatarRendering/Wearables/Systems/FinalizeWearableLoadingSystem.cs
Wearable DTOs request were canceled if you clicked fast enough on the authentication screen, before they were resolved. 
Then, the loading screen was waiting for the avatar to be instantiated to continue. But the canceled wearable DTOs requests were never retriggered by anyone, therefore leaving an unresolvavble state for the `GetWearablesByPointersIntention`. No DTO, no way to move forward with that intention
This PR corrects that by checking if a DTO is not loading, and if not, then add it to the `missingPointers` list
2. Click as fast as you can before your avatar appears on the loading screen
3. You should never get stuck at 40%
4. Check general wearable loading (open backpack, close backpack before they load, press passports). Everything should go as expected …
=> fix: Stuck at 40% due to avatar unable to instantiate

Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/AnalyticsController.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/IAnalyticsController.cs, Explorer/Assets/Scripts/Global/Dynamic/BootstrapContainer.cs
We were doing initial identification in Analytics using just deviceId. However, cached wallet can be used without affecting Analytics events chain. 
Just a smoke test. Also try to clear cache and enter with no cached initial wallet.
=> Chore: initial analytics identification by cached wallet value 

Explorer/Assets/DCL/EventsApi/HttpEventsApiService.cs, Explorer/Assets/DCL/EventsApi/IEventsApiService.cs, Explorer/Assets/DCL/MapRenderer/Addressables/MapRendererConfiguration.prefab, Explorer/Assets/DCL/MapRenderer/ComponentsFactory/CategoryScenesMarkersInstaller.cs, Explorer/Assets/DCL/MapRenderer/ComponentsFactory/LiveEventsMarkersInstaller.cs, Explorer/Assets/DCL/MapRenderer/ComponentsFactory/LiveEventsMarkersInstaller.cs.meta, Explorer/Assets/DCL/MapRenderer/ComponentsFactory/MapRendererChunkComponentsFactory.cs, Explorer/Assets/DCL/MapRenderer/ComponentsFactory/MapRendererConfiguration.cs, Explorer/Assets/DCL/MapRenderer/ComponentsFactory/MapRendererDrawOrder.cs, Explorer/Assets/DCL/MapRenderer/MapLayerIconMapping.asset, Explorer/Assets/DCL/MapRenderer/MapLayers/LiveEvents.meta, Explorer/Assets/DCL/MapRenderer/MapLayers/LiveEvents/LiveEventsMarkersController.cs, Explorer/Assets/DCL/MapRenderer/MapLayers/LiveEvents/LiveEventsMarkersController.cs.meta, Explorer/Assets/DCL/MapRenderer/MapLayers/MapLayer.cs, Explorer/Assets/DCL/MapRenderer/MapRenderer.asmdef, Explorer/Assets/DCL/Minimap/MinimapController.cs, Explorer/Assets/DCL/Navmap/Assets/FiltersContainer.prefab, Explorer/Assets/DCL/Navmap/FilterPanel/NavmapFilterPanelView.cs, Explorer/Assets/DCL/Navmap/NavmapController.cs, Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs, Explorer/Assets/Scripts/Global/Dynamic/MapRendererContainer.cs
This PR adds a layer that contains all current live events, it refreshes every 5 minutes with a new request to the events endpoint
...
2. Open the map
3. Verify if there are any live events being displayed (check the events website if there are any live)
4. Check that toggling on and off the live events in the filters panel they are toggled on and off
=> Feat: live events map layer

.github/actions/version/action.yml, .github/workflows/build-unitycloud.yml
We have noticed that with build from PR the hash added to version in the build was not pointing to the correct one, make it hard for QA and devs to validate the fixes.
The issue occurs because GitHub Actions uses a merge commit when a workflow is triggered by a pull_request event. This merge commit is generated dynamically by GitHub to simulate what the branch would look like after merging into the base branch. As a result, the checkout step fetches and checks out this temporary merge commit instead of the exact commit from the source branch.
To fix it I had to override the checkout action, and also made changes in the get-version action to always use tags from main so we can easier test changes to workflows.
Check that the build version is matching with commit hash from last commit. …
=> fix: include correct commit hash in PR builds

Explorer/Assets/DCL/Roads/Data/RoadAssets/LongRoad/-51,-49.prefab, Explorer/Assets/DCL/Roads/Data/RoadAssets/LongRoad/-70,-1.prefab, Explorer/Assets/DCL/Roads/Settings/RoadData.asset
RoadData updated to change the rotation of the -51,-49 prefab from 270 to 90. Road prefab -70,-1 adapted so it connects with the other road forming a T. Two internal prefabs replaced with road prefabs of 1 corner.
2. Go to -51,-49.
3. Check that the road that connects that point with -51,-1 is there and is properly connected with the other road.
=> Missing street from (-51,-51) to (-51,-1) (#2578)

Explorer/Assets/DCL/MapRenderer/ComponentsFactory/CategoryScenesMarkersInstaller.cs, Explorer/Assets/DCL/MapRenderer/ComponentsFactory/MapRendererChunkComponentsFactory.cs, Explorer/Assets/DCL/MapRenderer/MapLayers/Categories/CategoryControllers/CategoryMarkersController.cs, Explorer/Assets/DCL/MapRenderer/MapLayers/SearchResults/SearchResultMarkersController.cs, Explorer/Assets/DCL/Navmap/Assets/Navmap.prefab, Explorer/Assets/DCL/Navmap/CategoryFilterController.cs, Explorer/Assets/DCL/Navmap/CategoryToggleView.cs, Explorer/Assets/DCL/Navmap/NavmapSearchBarController.cs
=> feat: align map with sidebar status

Explorer/Assets/DCL/MapRenderer/Addressables/AtlasChunk.prefab, Explorer/Assets/DCL/MapRenderer/MapLayers/Atlas/SatelliteAtlas/SatelliteChunkController.cs, Explorer/Assets/DCL/UI/Shaders/DCL_Sprite-Default.shader, Explorer/Assets/DCL/UI/Shaders/DCL_Sprite-Default.shader.meta, Explorer/Assets/DCL/UI/Shaders/DCL_UnitySprites.cginc, Explorer/Assets/DCL/UI/Shaders/DCL_UnitySprites.cginc.meta, Explorer/Assets/DCL/UI/Shaders/SpriteWithSaturation.mat, Explorer/Assets/DCL/UI/Shaders/SpriteWithSaturation.mat.meta
This PR introduces a shader that allows to change the saturation of the map chunks.
...
2. Open the map
3. Check that the satellite view is a bit washed out and not full saturation
=> feat: satellite atlas shader to decrease saturation

Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/VideoEventsSystem.cs
Currently the "video buffering/seeking" freeze check that propagates the ERROR video event is skipping the case it was originally implemented for: BUFFERING and SEEKING getting frozen for more than X seconds.
Removed wrongly placed checks for skipping the ERROR video event propagation for BUFFERING and SEEKING states (introduced at https://github.com/decentraland/unity-explorer/pull/2782).
As proof that the original fix from https://github.com/decentraland/unity-explorer/pull/2782 is still working as intended, the exact same test steps are provided below.
1. Download this scene: https://github.com/decentraland-scenes/media-gallery-test  (alternatively [this other scene](https://github.com/user-attachments/files/17948061/video_prioritization_scene.zip)) and uncompress it somewhere
2. Enter …
=> chore: correct video event error propagation on freeze check

Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/AnalyticsController.cs
So events can be send before `Identify`. Thus, moved Tracked system info after `Identify` and assure it won't happen
=> Fix: system info not being send

Explorer/Assets/DCL/FeatureFlags/FeatureFlagsStrings.cs, Explorer/Assets/DCL/PluginSystem/World/MediaPlayerPlugin.cs, Explorer/Assets/DCL/SDKComponents/MediaStream/DCL.MediaPlayer.asmdef, Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerPrioritizationSystem.cs, Explorer/Assets/DCL/SDKComponents/MediaStream/Wrapper/DCL.MediaPlayer.PluginWrapper.asmdef, Explorer/Assets/DCL/SDKComponents/MediaStream/Wrapper/MediaPlayerPluginWrapper.cs, Explorer/Assets/Scripts/Global/StaticContainer.cs
This change is related to this shape:
Until now, videos that were out of camera, too far from camera or looked too small on screen, where paused to save CPU. That behaviour has now changed as described below:
If the amount of videos in the scene is equal to or less than the maximum limit established for the current quality level, prioritization will not be applied, they all will keep playing even if they are not in camera or are too far. If there are more videos than the maximum, then a number of videos equal to the maximum will always be playing disregarding any priority or condition.
Added a new feature flag ("alfa-video-prioritization") so the entire video prioritization feature can be disabled from outside the application.
1. Download this scene: …
=> fix: Videos are paused whenever they are not in camera even when there are less videos than the maximum allowed

Explorer/Assets/DCL/SDKComponents/AvatarShape/Systems/AvatarShapeHandlerSystem.cs, Explorer/Assets/DCL/SDKComponents/DCL.SDKComponents.asmdef
Currently the SDK's AvatarShape component that allows the creation of NPCs is not supporting the triggering of emotes as described in t[he component's documentation](https://docs.decentraland.org/creator/development-guide/sdk7/npc-avatars/#animations).
Made minor change to start supporting the already existent emote field.
https://github.com/user-attachments/assets/dc0ccb17-b30b-4276-9fdf-3f37d98e9b0a
1. Download the build from this PR
2. Open the build connecting to the `pravus.dcl.eth`world by following the instructions from [the wiki](https://github.com/decentraland/unity-explorer/wiki/How-To#command-arguments-custompr-builds) according to your OS, adding `--realm pravus.dcl.eth`.
3. Confirm that the scene loads an AvatarShape that has your own wearables (maybe some wearable is not …
=> fix: sdk avatar shape emotes

Explorer/Assets/DCL/SDKComponents/MediaStream/Components/VideoStateByPriorityComponent.cs, Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerPrioritizationSystem.cs
Now when entering a scene that has a video that plays automatically at a given time, it does it correctly instead of starting at zero.
Additionally, sometimes when the scene contained a video that was shared by several meshes, it was not playing at all and now it does.
1. Download this scene: https://github.com/decentraland-scenes/dcl_music_fest_2024_stage 
4. Close the Explorer that auto-opened. Leave the scene running in the console/terminal.
5. Download the build from this PR and connect it to the running scene using [the console command](https://github.com/decentraland/unity-explorer/wiki/How-to-connect-to-a-local-scene-(Unity-Editor---Custom-Build---Latest-Released-Build)#connecting-a-custom-bu …
=> fix: Videos that play at a given time are starting at zero

Explorer/Assets/DCL/UI/Sidebar/SidebarUI.BottomLayout.prefab, Explorer/Assets/DCL/UI/Sidebar/SidebarUI.BottomLayout.prefab.meta, Explorer/Assets/DCL/UI/Sidebar/SidebarUI.UpperLayout.prefab, Explorer/Assets/DCL/UI/Sidebar/SidebarUI.UpperLayout.prefab.meta, Explorer/Assets/DCL/UI/Sidebar/SidebarUI.prefab
Separates layout into top and bottom layouts and moved screencapture button in the bottom one.
1. Launch the explorer with proper CLI argument
2. Verify that camera reel screencapture button is down on the sidebar (near to emotes button)
3. Verify this button is not presented if you run it without CLI args
=> Fix: camera-reel screencapture sidebar button being on top layout

Explorer/Assets/DCL/Minimap/MinimapController.cs, Explorer/Assets/DCL/PluginSystem/Global/MinimapPlugin.cs, Explorer/Assets/Scripts/ECS/SceneLifeCycle/Realm/IRealmController.cs, Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs, Explorer/Assets/Scripts/Global/Dynamic/Landscapes/Landscape.cs, Explorer/Assets/Scripts/Global/Dynamic/RealmController.cs, Explorer/Assets/Scripts/Global/Dynamic/RealmNavigator.cs
- Introduces the `LocalScene` realm type to bound certain results that required it, and it was not enough with worlds or genesis (ie: terrain generation)
2. Check that the terrain and minimap are correct
3. Teleport to a world
4. Check that the terrain and minimap are correct for the world
5. Teleport back to Genesis
6. Once again, check that the terrain and minimap are correct for Genesis
7. Launch the explorer with a local scene. Check that the scene loads, the minimap is gone and the terrain is correct
=> fix: LSD condition in RealmNavigator

Explorer/Assets/DCL/StylizedSkybox/Scripts/SkyboxController.cs
This change cleans up one of the "random modified files show up in Git" annoyances.
2. Look up :)
3. The game should run exactly the same as without this change
=> Don't modify the skybox material asset when animating the sky

Explorer/Assets/DCL/Character/CharacterMotion/Components/PlayerTeleportIntent.cs
TLDR: the first teleport intent to GP during loading was timing out after 30secs and breaking the loading process.
For now I just increased the time out time. 
The teleport also breaks when going to a world (or starting in a world) and coming back to GP.
...
Enter the game normally, you should appear in GP without problems.
Also, try teleporting to a world and going back to GP, there should be no failed teleport.
Other test that can be done is starting the game directly in a world and then going back to GP. GP should load correctly.
Fixes: https://github.com/decentraland/unity-explorer/issues/2975
=> fix: teleport timeout during loading

Explorer/Assets/DCL/Chat/ChatCommandsHandler.cs, Explorer/Assets/DCL/Chat/ChatController.cs, Explorer/Assets/DCL/Chat/Commands/IChatCommand.cs, Explorer/Assets/DCL/Chat/MessageBus/CommandsHandleChatMessageBus.cs, Explorer/Assets/DCL/Chat/MessageBus/IChatMessagesBus.cs, Explorer/Assets/Scripts/Global/Dynamic/ChatCommands/ChangeRealmChatCommand.cs, Explorer/Assets/Scripts/Global/Dynamic/ChatCommands/ClearChatCommand.cs, Explorer/Assets/Scripts/Global/Dynamic/ChatCommands/DebugPanelChatCommand.cs, Explorer/Assets/Scripts/Global/Dynamic/ChatCommands/GoToChatCommand.cs, Explorer/Assets/Scripts/Global/Dynamic/ChatCommands/HelpChatCommand.cs, Explorer/Assets/Scripts/Global/Dynamic/ChatCommands/HelpChatCommand.cs.meta, Explorer/Assets/Scripts/Global/Dynamic/ChatCommands/KillPortableExperienceChatCommand.cs, Explorer/Assets/Scripts/Global/Dynamic/ChatCommands/LoadPortableExperienceChatCommand.cs, Explorer/Assets/Scripts/Global/Dynamic/ChatCommands/ReloadSceneChatCommand.cs, Explorer/Assets/Scripts/Global/Dynamic/ChatCommands/ShowEntityInfoChatCommand.cs, Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
Adds a /help command with a small refactor to remove deferred command creation and simplify the code.
fix:#2567
2. Try executing /help and other commands
3. Check if command descriptions printed in /help are accurate.
=> feat: Add /help command

Explorer/Assets/DCL/SDKComponents/MediaStream/MediaPlayerExtensions.cs
It comes from here: https://github.com/decentraland/unity-explorer/issues/2880
It's just an extra prevention so the problem happens less often (currently we cannot reproduce it). It's not a definitive solution. It was already applied on Mac and now it has been extended to Windows builds.
It can't be reproduced. However, if you want to make sure it does not break existing things, you can do smoke testing like in this PR: https://github.com/decentraland/unity-explorer/pull/2955
=> Fix: Sometimes videos start at zero when the scene is loaded for the first time

Explorer/Assets/DCL/Chat/ChatController.cs, Explorer/Assets/DCL/InWorldCamera/InWorldCamera/Systems/ToggleInWorldCameraActivitySystem.cs, Explorer/Assets/DCL/Input/Component/InputMapComponent.cs, Explorer/Assets/DCL/Input/ECSInputBlock.cs, Explorer/Assets/DCL/Input/IInputBlock.cs, Explorer/Assets/DCL/Input/Systems/ApplyInputMapsSystem.cs, Explorer/Assets/DCL/SceneLoadingScreens/SceneLoadingScreenController.cs, Explorer/Assets/Scripts/Global/Dynamic/MainSceneLoader.cs
Stops the in-world-camera from spawning when using the chat or in the loading screen
1. Launch the explorer with in world camera feature on
2. Select the chat. Press C. The in world camera should not open
3. Deselect the chat. Press C. The world camera should open
4. Teleport anywhere. While loading screen is on, press C. The world camera should not open
5. When arriving to destination, press C. The camera should open
Try the regular input blocks as well (Shortcuts, Movement, Camera, FreeCamera, Emotes and EmotesWheel). They should all behave the same
=> fix: block camera input

Explorer/Assets/Plugins/TexturesFuse/TexturesServerWrap/Unzips/ITexturesFuse.cs
There is a problem with the compression speed on Windows for some users.
2. Play happy path, loading screen should take less than 1 minute as before the textures optimisation
=> Fix: disable compression for windows

Explorer/Assets/DCL/Editor/EntityBrowserWindow.cs.meta, Explorer/Assets/DCL/ExplorePanel/Assets/ExplorePanelUI.prefab, Explorer/Assets/DCL/InWorldCamera/CameraReelGallery/CameraReelGalleryController.cs, Explorer/Assets/DCL/Navmap/Assets/PlacesAndEventsPanel.prefab, Explorer/Assets/DCL/Navmap/Navmap.asmdef, Explorer/Assets/DCL/Navmap/PlaceInfoPanelController.cs, Explorer/Assets/DCL/Navmap/PlaceInfoPanelView.cs, Explorer/Assets/DCL/PluginSystem/Global/ExplorePanelPlugin.cs, Explorer/Assets/DCL/PluginSystem/Global/Global Plugins Settings.asset
Implements the place gallery into the appropriate navmap section, showing all public reels taken in a specific place.
1. Launch the explorer with all reels base urls pointing to `zone`
2. Open the navmap
3. Click on a parcel
4. Switch to the `PHOTOS` section
5. Click on any reels and verify it opens the photo detail view
=> Feat: camera reel - navmap integration

Explorer/Assets/DCL/PluginSystem/Global/Global Plugins Settings.asset
Change the share to x.com preconfigured message into using the tag to the official Decentraland X account
2. Open a reel
3. Click the share button and check that the preconfigured message now tags the Decentraland account
=> chore: camera-reel - change share to X message

Explorer/Assets/DCL/Minimap/MinimapController.cs
Fixes this [comment](https://github.com/decentraland/unity-explorer/issues/2974#issuecomment-2531904034)
2. Check that the minimap doesnt show a white image after the loading screen is gone
3. Teleport to a world. Check that the minimap changes to the world look correctly
4. Launch the explorer in a realm through `args`
5. Check that the minimap doesn't flash the genesis map after the loading screen is gone
6. Teleport to Genesis City. Check that the minimap is fine
7. Start with a new user. Check the same steps as in 5 and 6
=> fix: minimap flash

Explorer/Assets/DCL/AuthenticationScreenFlow/AuthenticationScreenController.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/AnalyticsConfiguration.asset, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/AnalyticsEvents.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/EventBased/AuthenticationScreenAnalytics.cs, Explorer/Assets/DCL/Web3/Authenticators/DappWeb3Authenticator.cs, Explorer/Assets/DCL/Web3/Authenticators/IWeb3VerifiedAuthenticator.cs
This adds analytics events from ticket #2964
2. Go through the login flow end ensure events are triggered.
=> feat: add analytics events for the login flow

Explorer/Assets/DCL/InWorldCamera/CameraReelGallery/CameraReelGalleryController.cs
Prevent the negative `beginVisible` index when scrolling against the scroll limit. This can happen when the scroll is so strong that no reel is visible due to the view going above/beyond the actual elements.
1. Launch the explorer with `debug` and `camera-reel` flags
2. Open the reel gallery
3. Scroll up or down intensively so that no reel is visible
4. Check that if you let go the scrolling, everything works as expected with no errors
=> fix: prevent negative index while scrolling against scroll limit in reel gallery

Explorer/Assets/DCL/InWorldCamera/CameraReelGallery/CameraReelGalleryController.cs, Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/CameraReelImagesMetadataRemoteDatabase.cs, Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/CameraReelRemoteStorageService.cs, Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/ICameraReelImagesMetadataDatabase.cs, Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/ICameraReelStorageService.cs, Explorer/Assets/DCL/InWorldCamera/InWorldCamera/Systems/InWorldCameraPlugin.cs, Explorer/Assets/DCL/InWorldCamera/InWorldCamera/Systems/ToggleInWorldCameraActivitySystem.cs, Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
Fix the empty state when the user's own passport doesn't contain any public reel.
It was working on other users passport because the get request was signed with a different wallet than the requested one, therefore the BE was correctly returning only the amount of public reels.
The problem on the user's passport was because the get request was signed with the same wallet as the requested one, returning all reels (public and private). If no reel was public, the grid was empty but the non-zero amount of reels wasn't triggering the empty state.
1. Launch the explorer with `debug` and `camera-reel` flags
2. Check that if you don't have any public reel, your reels passport section is correctly displaying the empty state (background + image + text saying that the list is empty)
3. Check that the …
=> fix: passport reels empty state not triggering for user own passport

Explorer/Assets/DCL/FeatureFlags/FeatureFlagsStrings.cs
Changed the camera-reel feature flag name to standard naming convention
2. Check that the camera reel features are enabled
=> fix: align camera reel feature flag name to standard

Explorer/Assets/DCL/SDKComponents/SceneUI/Systems/UICanvasInformation/UICanvasInformationSystem.cs
Before my previous changes the UICanvasInformationSystem was sending the PBUiCanvasInformation only during initialize, but once the scene started it would have PBUiCanvasInformation == null for some reason.
I thought it was because the CRDT was not working properly during initialize, but seems ti gets reset? I donno... we will look into it xD
For now, this fixes the issue by sending it both during initialize and again once the scene is ready :)
Please check with the onboarding scene as well as Rapture gallery (-88,-64) making sure both load and that the UI shows.
=> fix: UICanvasInformationSystem now sends canvas data twice

Explorer/Assets/DCL/Passport/PassportController.cs
Block camera reel inputs (`K` and `C`) while the passport is open
2. Open your passport
3. Edit some text
4. Check that by pressing either `K` or `C` no action is triggered and you can normally write text
=> fix: block camera reel input in passport

.github/workflows/enforce-group-approvals.yml
- Exclude auto-pr label on enforce approvals workflow
- Migrate logic to GitHub CLI for consistency purposes
- Add pull_request_review trigger only for dev branch
2. ...
=> chore: exclude some labels on enforce approvals workflow

Explorer/Assets/Scripts/ECS/StreamableLoading/AssetBundles/Tests/PrepareAssetBundleLoadingParametersSystemShould.cs, Explorer/Assets/Scripts/SceneRunner/Scene/SceneAssetBundleManifest.cs
#3096 had to be reverted since version cannot be ignored. If it does, we get error as following
Since Unity tries to load a new asset bundle with the same GUID, even if the asset version is different
Therefore, if two assets have different versions, they will be shared.
2. Do the happy path
=> fix: revert of #3096

Explorer/Assets/DCL/Character/CharacterCamera/Character Camera.prefab
Starts camera in third person mode instead of drone
1. Launch the explorer in worlds and GC
2. Check that the camera starts in third person mode
=> fix: Start camera in third person mode

Explorer/Assets/AddressableAssetsData/AssetGroups/UI.asset, Explorer/Assets/DCL/Input/UnityInputSystem/DCLInput.cs, Explorer/Assets/DCL/Input/UnityInputSystem/DCLInput.inputactions, Explorer/Assets/DCL/PluginSystem/Global/Global Plugins Settings.asset, Explorer/Assets/DCL/PluginSystem/Global/SidebarPlugin.cs, Explorer/Assets/DCL/UI/Controls.meta, Explorer/Assets/DCL/UI/Controls/ControlsPanel.prefab, Explorer/Assets/DCL/UI/Controls/ControlsPanel.prefab.meta, Explorer/Assets/DCL/UI/Controls/ControlsPanelController.cs, Explorer/Assets/DCL/UI/Controls/ControlsPanelController.cs.meta, Explorer/Assets/DCL/UI/Controls/ControlsPanelView.cs, Explorer/Assets/DCL/UI/Controls/ControlsPanelView.cs.meta, Explorer/Assets/DCL/UI/Controls/Textures.meta, Explorer/Assets/DCL/UI/Controls/Textures/Controls.png, Explorer/Assets/DCL/UI/Controls/Textures/Controls.png.meta, Explorer/Assets/DCL/UI/MainUIContainer/MainUIContainer.prefab, Explorer/Assets/DCL/UI/MainUIContainer/MainUIView.cs, Explorer/Assets/DCL/UI/Sidebar/SidebarController.cs, Explorer/Assets/DCL/UI/Sidebar/SidebarUI.UpperLayout.prefab, Explorer/Assets/DCL/UI/Sidebar/SidebarUI.prefab, Explorer/Assets/DCL/UI/Sidebar/SidebarView.cs, Explorer/Assets/DCL/UI/UI.asmdef, Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs, Explorer/Assets/Textures/Common/DecentralandLogoWhite.png, Explorer/Assets/Textures/Common/DecentralandLogoWhite.png.meta, Explorer/Assets/Textures/ExplorePanel/ControlsOff.png, Explorer/Assets/Textures/ExplorePanel/ControlsOff.png.meta, Explorer/Assets/Textures/ExplorePanel/ControlsOn.png, Explorer/Assets/Textures/ExplorePanel/ControlsOn.png.meta
This adds the Controls panel to the main sidebar and a new hotkey (H) to open it.
2. Open the controls panel from the sidebar
3. Open the controls panel with the shortcut (H)
=> feat: controls panel

Explorer/Assets/Scenes/Main.unity, Explorer/Assets/Scripts/Global/Dynamic/BootstrapContainer.cs, Explorer/Assets/Scripts/Global/Dynamic/DynamicSceneLoaderSettings.cs, Explorer/Assets/Scripts/Global/Dynamic/MainSceneLoader.cs
Moves the environment dropdown from an inner config to the EntryPoint
...
Just a quick smoke test that login works fine
=> chore: moved environment selection to EntryPoint

Explorer/Assets/DCL/InWorldCamera/PhotoDetail/Prefabs/PhotoDetailUI.prefab
This fixes overlapping buttons / text in galery details
Closes #3094 
2. Take some pictures
3. Open the gallary and click on a pic
4. Check sidebar details, they should not overlap (including when changing the size of the window)
=> fix: correctly anchor gallery details so they don't overlap

Explorer/Assets/DCL/MapRenderer/MapLayers/Categories/CategoryControllers/CategoryMarkersController.cs, Explorer/Assets/DCL/MapRenderer/MapLayers/Clusters/ClusterController.cs, Explorer/Assets/DCL/MapRenderer/MapLayers/IZoomScalingLayer.cs, Explorer/Assets/DCL/MapRenderer/MapLayers/LiveEvents/LiveEventsMarkersController.cs, Explorer/Assets/DCL/MapRenderer/MapLayers/Pins/PinMarkerController.cs, Explorer/Assets/DCL/MapRenderer/MapLayers/PlayerMarker/PlayerMarkerController.cs, Explorer/Assets/DCL/MapRenderer/MapLayers/PointsOfInterest/ScenesOfInterestMarkersController.cs, Explorer/Assets/DCL/MapRenderer/MapLayers/SearchResults/SearchResultMarkersController.cs, Explorer/Assets/DCL/MapRenderer/MapPath/MapPathController.cs, Explorer/Assets/DCL/MapRenderer/MapRenderer.cs
Fix #3101 
When we opened the fullscreen navmap and closed it, some icons were left with a wrong scale.
2. Open the fullscreen navmap.
3. Search Dollhouse and jump in there.
4. Check that the icons in the minimap have a correct size.
=> fix: Make the minimap icons reset its scale when the fullscreen map closes

Explorer/Assets/DCL/Navmap/PlaceInfoPanelController.cs
Fix #3106 
Before this fix, when we clicked multiple times any of the place's tabs when being on the map, we saw how the same content was being loaded several times without necessity and in some times, like clicking in the "PHOTOS" tab, the content was being loaded duplicated and generating several errors.
This fix avoid to load again the content of a tab that is already selected, thus solving 2 things:
- Unnecessary calls to the APIs.
- The duplicated issue described in #3106
2. Open the map.
3. Select a place (ideally the place has to have some photos published in its "PHOTOS" tab, for example: metagamimall).
4. Navigate through its tabs (Overview, Photos and Events) and check that it's working as expected. Specially clicking several times on PHOTOS and checking …
=> fix: Avoid to click in the same place map tab more than once

Explorer/Assets/DCL/InWorldCamera/ReelActions/ReelCommonActions.cs
Fix #3216 
When a user attempted to share a gallery picture from DCL to an X account, there was a lot of wrong characters on the text.
2. Go to your gallery.
3. Select the 3 dots of one picture.
4. Share on X.
5. Check that X opens and the text is correct.
=> fix: Wrong message when we try to share a photo in X

Explorer/Assets/DCL/Landscape/TerrainGenerator.cs
Forces a terrain cache generation
The shore should look just fine
2. Check in you cache that you now have the `terrain_cache_97_512_v10.data` file
=> fix: Force a terrain cache generation 

.github/workflows/build-unitycloud.yml
Before we only passed the `clean-build` flag when the label was added, on next run the label was not respected. 
With this change it will always check for the label and set `clean-build` properly
...
2. ...
=> fix: always check for clean build label

Explorer/Assets/Scripts/SceneRuntime/Factory/JsSource/CachedWebJsSources.cs
ignore local files for js sources in caching strategy since it doesn't make a sense to cache them on disk.
2. Play happy path
=> Chore: ignore file:// paths

Explorer/Assets/AddressableAssetsData/AssetGroups/Essentials.asset
I'm trying to cut down on the Git status pollution with this change. When entering play mode, Essentials.asset is modified to remove a reference to ReelGalleryContextMenuConfig, an asset that does not exist in the dev branch yet. I'm guessing a change to Essentials.asset was committed by mistake.
2. Test the photo reel gallery?
=> Remove a reference to an asset that does not exist

Explorer/Assets/DCL/Chat/Assets/ChatEntry.prefab, Explorer/Assets/DCL/Chat/Assets/ChatEntryOwn.prefab, Explorer/Assets/DCL/Chat/Assets/SystemChatEntry.prefab
Super Scroll View keeps modifying these prefabs whenever play mode is entered, and that is an annoyance. After reading its source code, I believe that these prefabs should be that way all along. This change commits that.
2. Test the chat UI. Send and receive messages, and whatever else.
=> Change the chat entry prefabs to how Super Scroll View wants them

Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/AnalyticsConfiguration.asset, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/AnalyticsController.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/AnalyticsEvents.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/CrashDetector.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/CrashDetector.cs.meta, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/IAnalyticsController.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/StaticCommonTraitsPlugin.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/Builders/IDebugContainerBuilder.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Profiling/ECS/DebugViewProfilingSystem.cs, Explorer/Assets/Scripts/Global/Dynamic/BootstrapContainer.cs
We now detect non-graceful exits of the application and report them as an analytics event.
2. Trigger a crash / kill it with task manager
3. Reopen explorer
4. Verify that a "crash" event was sent with the session ID of the previous run
=> feat: add crash detection analytics event

Explorer/Assets/DCL/ExplorePanel/ExplorePanelController.cs
This fixes #2918 where the Explore panel was not being opened correctly from Notifications, blocking input / reopening the panel after teleporting.
2. Open notifications panel
3. Click on a notification that redirects to backpack
4. Go to Map and teleport somewhere
5. Click on a notification again, explore panel should open instead of flashing and blocking input
=> fix: notification redirect freezing avatar

.github/workflows/build-unitycloud.yml, scripts/cloudbuild/build.py
Adding a global timeout in case the build hangs on Unity Cloud. Right now, there's no way to set this through the web interface. The timeout is currently set to 3 hours.
...
2. ...
=> chore: add global timeout for builds

Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/DynamicCommonTraitsPlugin.cs
Add `direct` parameter in context field for Segment Tracking. This tells segment to collect the IP of the request server-side.
...
2. Go to debugger tab in Explorer V2 source, check if IP's are being collected for events tracked in the explorer.
=> feat: add direct parameter to context object to collect ip's

Explorer/Assets/DCL/ExternalUrlPrompt/Assets/ExternalUrlPrompt.prefab
This PR updates the copies of the modal and add the missing animations on the buttons. Additionally, the checkmark container asset changed for a white squared instead of a transparent one.
Observe that the 'domain' text field has been remove leaving the link visible only. 
BEFORE
AFTER
2. To open the modal, click the 'Discord' or 'X' buttons located at the spawn point platform in Genesis Plaza. Validate the hover/press animation is working in both main buttons. 
3. Check the checkbox container has been updated with the correct white style.
=> style: update 'external URL' copies and add buttons animations

Explorer/Assets/DCL/InWorldCamera/CameraReelGallery/Assets/ThumbnailElement.prefab, Explorer/Assets/DCL/InWorldCamera/Textures/SquaredOutline.png, Explorer/Assets/DCL/InWorldCamera/Textures/SquaredOutline.png.meta
This PR was created to fix the hover animation of the photos: removes the scale on hover, erasing the issue of not seeing side of the outline when a photo is inside and next to mask edge (as happens in the Profile and in the Scene's Info Cards in the map). Also, replaces the texture which emulated an outline for a real outline. The final result is a neat hover animation which works in every context.
BEFORE
https://github.com/user-attachments/assets/105f4300-c4fa-4919-9ff4-f91635956f5d
Screenshots of the outline getting chopped in the map and profile card
AFTER
https://github.com/user-attachments/assets/7c7c5450-c2da-49bc-b8f4-98a22cb80a0d
2. Go to the gallery and hover any photo. Check the scale animation was removed and that the outline appears inside the photo …
=> style: fix photos hover animation

Explorer/Assets/Scripts/SceneRuntime/ModuleHub/SceneModuleHub.cs
We renamed all our modules some time ago, and so Protobuf could not find them anymore. Besides the eyesore in the log, it's a performance degradation because Protobuf then falls back to regular arrays. This change adds a special case for the modules Protobuf wants.
2. Play normally
3. The game should run at least as well as without this change
=> Let Protobuf use optimized JavaScript types

Explorer/Assets/DCL/Roads/Settings/RoadData.asset
fix #2419 
2. As the issue ticket describes, visit the next coords: `15,-135`, `58.-150`
3. And check that the missing roads appears.
**NOTE**: Take into account that it would be normal that these roads appear still empty in the map view. They will be updated there later, when we update the stellite view (this is a different process).
=> fix: Missing pieces of road in some locations

Explorer/Assets/DCL/InWorldCamera/CameraReelGallery/Assets/ThumbnailElement.prefab
Fixes the camera reel thumbnails not being interactable. Clicking on one now correctly opens the Photo Detail UI and you are also able to open the relative context menu containing actions related to the reel.
2. Open the camera reel
3. Check that the reels can now be clicked and the context menu can be opened as well
4. Do the same in the detail/photo section of a place in the map (no context menu is available there)
5. Do the same in the passport
=> fix: camera reel thumbnail element not being interactable (click and context menu button)

Explorer/Assets/Scripts/ECS/StreamableLoading/Cache/Disk/DiskCache.cs
There is an error with file access in disk cache
The real cause was that SetLastAccessTimeUtc fails when the file is being used. There is no mention in the [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.io.file.setlastaccesstimeutc?view=netcore-3.1) that It's not required on Mac but it is on Windows.
I put the scope to limit the FileStream and close it before the NotifyUsed call. It made the error gone in Editor on windows.
```
SlicedOwnedMemory<byte> data;
{
await using var stream = new FileStream(path, FileMode.Open, FileAccess.Read);
data = new SlicedOwnedMemory<byte>(MemoryPool<byte>.Shared!.Rent((int)stream.Length)!, (int)stream.Length);
int _ = await stream.ReadAsync(data.Memory, token);
}
diskCleanUp.NotifyUsed(fileName);
```
...
2. Play …
=> Fix: Scope Filestream

Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/SystemInfoUtils.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/SystemInfoUtils.cs.meta, Explorer/Assets/Scripts/Global/Dynamic/MainSceneLoader.cs, Explorer/Assets/Scripts/Global/Versioning/DCLVersion.cs
It prints full device information to Player.log
1. Run explorer
2. Verify that Player.log contains the device information
=> chore: print system information on startup.

Explorer/Assets/DCL/AvatarRendering/AvatarShape/Systems/AvatarShapeVisibilitySystem.cs, Explorer/Assets/DCL/Multiplayer/Connections/Messaging/Pipe/LogMessagePipe.cs
The lambda was capturing the log strings which are not compiled out at runtime. It got worse with an increasing number of players:
before:
after:
(dissapeared from profiler)
Secondly this frustrum calculation was allocating per frame:
before:
after:
No major changes to functionality, just play the happy paths.
1. Play Happy Paths
=> chore: fix remove lambda capture allocation

Explorer/Assets/DCL/Backpack/Assets/AvatarSlot.prefab, Explorer/Assets/DCL/Backpack/Assets/EmoteSlotContainer.prefab
In the backpack, when there is an empty slot we are displaying an icon which gives the sense of that the category is blocked. To fix that misleading empty visual message, this PR replaces the icon for a simple background.
BEFORE
AFTER
2. Go to the backpack, in the wearables section, and quit the item equipped on every category to check the icon is not visible anymore.
3. Go to the emotes section an repeat the instruction above.
=> style: update slot empty state

Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportsHandlingSettingsProduction.asset
We are polluting Sentry with errors in the form of 
`System.ArgumentException: GLTF source models/core_building/ not found in the content`
This doesn't add value to us, as they tend to be creator problems. Makes sense to remove this category from exception reporitng
Nothing to test
=> chore: remove GLTF container from exception reporting

Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
Disables the friends feature if local scene development is enabled since creators wont need it. This prevents any undesired error logging in the console.
1. Run the client in local scene development
2. Check that there are no errors in the console/logs because of friends
=> fix: disable friends on local scene development

Explorer/Assets/DCL/Notifications/NewNotification/Assets/NewNotificationPanel.prefab
Made the CanvasGroup on the new FriendsNotification to not block raycasts
Receive a friend request
Wait until you get the notification on top of the screen
Check that you can click it
Open the notifications panel from the side bar
Check that you can click any of the notifications
=> Fix: Notification panel issue

Explorer/Assets/DCL/NameTags/Systems/NametagPlacementSystem.cs
Fix #3144 
Fix #2108 
This PR set a max height limit for the avatars tagname, so regardless of the wrongly creation of the equipped wearable, the tagname is always gonna be placed as a maximum height of `4` meters.
We discovered that there are some wearables that have a bounding box wrongly set that makes our nametag be placed in a very far height, for example:
https://github.com/user-attachments/assets/d3f0c3c6-19a9-4de2-bd11-9a1b5a3e54e5
https://github.com/user-attachments/assets/7594612b-3ef5-4549-a808-355e1da3c295
None.
1. Open your backpack.
2. Equip the "Red Glasses" wearable.
3. Close the backpack.
4. Observe that your nametag doesn't disappear of the screen and its height is set to a maximum height of 4 meters.
5. Repeat the 1-4 steps but with the "Soccer Cleats" wearable.
These …
=> fix: Set a max height for nametags

Explorer/Assets/DCL/Friends/UI/FriendPanel/FriendsPanelController.cs, Explorer/Assets/DCL/Friends/UI/FriendPanel/PersistentFriendPanelOpenerController.cs, Explorer/Assets/DCL/Friends/UI/FriendPanel/Sections/Friends/FriendListSectionUtilities.cs, Explorer/Assets/DCL/Friends/UI/FriendPanel/Sections/Friends/FriendsSectionDoubleCollectionController.cs, Explorer/Assets/DCL/Friends/UI/FriendPanel/Sections/Requests/RequestsSectionController.cs, Explorer/Assets/DCL/Friends/UI/Requests/FriendRequestController.cs, Explorer/Assets/DCL/Friends/UI/Requests/FriendRequestParams.cs, Explorer/Assets/DCL/Passport/PassportController.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/AnalyticsConfiguration.asset, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/AnalyticsEvents.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/DecoratorBased/DCL.AnalyticsDecorators.asmdef, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/DecoratorBased/FriendServiceAnalyticsDecorator.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/DecoratorBased/FriendServiceAnalyticsDecorator.cs.meta, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/DecoratorBased/MVCManagerAnalyticsDecorator.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/EventBased/DCL.Analytics.EventBased.asmdef, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/EventBased/FriendsPanelAnalytics.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/EventBased/FriendsPanelAnalytics.cs.meta, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/EventBased/PassportAnalytics.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/EventBased/PersistentFriendPanelOpenerAnalytics.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/EventBased/PersistentFriendPanelOpenerAnalytics.cs.meta, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/Playgrounds/AnalyticsConfiguration Playground.asset, Explorer/Assets/DCL/PluginSystem/Global/FriendsPlugin.cs, Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
The initial PR for the Friends feature was missing minor details and analytics were skipped entirely. This PR addresses the request accepted splash screen and the analytics.
This PR introduces some of the missing stuff from the Friend feature such as:
1. Friends analytics
2. Missing friend request accepted splash screen if you interact from the shortcut buttons or the context menu
Launch the explorer with the following args:
1. `debug`
2. `friends`
1. Generate a friend request from another account with you as the target
2. Verify that accepting it triggers the splash screen in both the quick action button and the context menu
- Analytics cannot be tested as the corresponding feature flag for the Friends feature is not yet enabled …
=> feat: friends analytics and request accepted splash screen

Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/DecoratorBased/LoadingStatusAnalyticsDecorator.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/EventBased/AuthenticationScreenAnalytics.cs, Explorer/Assets/DCL/RealmNavigation/LoadingStatus.cs, Explorer/Assets/Scripts/Global/Dynamic/BootstrapAnalyticsDecorator.cs
Fixes initial loading analytics events:
Fixed order:
- 2 - dynamic container loaded -> 3 - dynamic container loaded
- 3 - feature flag initialized -> 2 - feature flag initialized
Fixed initial_loading events:
- 7.0.X has been removed
- 7.X are now ordered correctly and without gaps 7.0 - 7.8
None
1. Smoke test
2. Ensure initial_loading events are all in order (probably doesn't need QA approval)
=> fix: initial loading events

Explorer/Assets/Scripts/Utility/ParcelMathHelper.cs
Fix #1737 
In some scenes (like in "Meta GamiMall") the colliders that were too close to the scene bound limits (but inside them) were being deactivated.
This was happening due to the comparison between decimals that we were doing. Now, in order to apply a small margin to this comparison, we apply a rounding so we asure the we manage correctly these scenarios where a collider is too close to a bound limit.
None.
1. Go to Meta GamiMall (`145, 60`)
2. Board the Shuttle Pad and start the journey.
3. Check that the platform never loses its collider.
=> fix: Colliders too close to the scene limits (but inside them) were being deactivated

Explorer/Assets/DCL/Landscape/Assets/Trees/Tree01/Tree01 Variant.prefab, Explorer/Assets/DCL/Landscape/Assets/Trees/Tree02/Tree02 Variant.prefab, Explorer/Assets/DCL/Landscape/Assets/Trees/Tree03/Tree03 Variant.prefab
This PR removes the rigidbody component from the tree used by the terrain, in order to obtain some juicy sub-ms.
This has been done as rigidbodies are not needed on the trees and they just consume CPU power
This PR shouldn't have any impact, to test it just verify that the terrain and the trees are correctly rendered and that the wind effect is still working fine
=> Chore: removed rigidbodies from terrain trees

Explorer/Assets/DCL/Friends/UI/Prefabs/FriendsPanel.prefab, Explorer/Assets/DCL/Passport/Prefabs/Passport.prefab, Explorer/Assets/DCL/UI/GenericContextMenu/Prefabs/ButtonWithTextAndIcon.prefab, Explorer/Assets/DCL/UI/GenericContextMenu/Prefabs/UserProfile.prefab
PR to implement minor UI fixes
Remove top gap from friends panel list (both tabs: friends and requests)
Centre mutual friend string vertically with friends icons
User context menu
Make friends button less rounded and make paddings consistent with Figma file in name and address.
1. Launch Explorer
2. Open the friends panel and check the top gap between the tabs and the list has been removed in both tabs.
3. Then open someones context menu from any list and check the context menu updates are there.
4. Open someones profile card, with common friends, to check the string is now aligned properly.
=> style: polish friends UI

Explorer/Assets/DCL/Passport/Passport.asmdef, Explorer/Assets/DCL/Passport/PassportController.cs, Explorer/Assets/DCL/PluginSystem/Global/PassportPlugin.cs, Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
When merging the Friends shape branch, the passport mutual friends section slipped in as it is always enabled with default values (3 thumbnails and the text saying 16 mutual friends), regardless of the FF enable.
This PR ties the activation of the root gameobject of the passport mutual friend to the value of the Friends feature flag.
1. With the Friends feature disabled, open any passport different than yours and verify that the mutual friends section is not visible
2. With the Friends feature enabled, open any passport different than yours and verify that the mutual friends section is visible if you have in fact mutual friends with that person
- Keep in mind that mutual friends are represented by a max amount of thumbnails of 3, the text portion is actually describing how many you have …
=> fix: disable passport mutual friends if Friends FF is disabled

Explorer/Assets/DCL/Settings/Configuration/SettingsMenuConfiguration.asset, Explorer/Assets/DCL/Settings/ModuleControllers/MemoryLimitSettingController.cs
Our current minimum requirements is 16GB. It makes sense that our minimum settings is 16 as well
1. Check that the minimum ram that can be set through settings is 16. 
2. Check that with a fresh install, the default value is 16
3. Check that changing the numbers the memory limits is changed in the debug menu
=> fix: Increase the minimum memory limit in settings to go with our minimum requirements

Explorer/Assets/DCL/Landscape/Data/TerrainData.asset, Explorer/Assets/DCL/Landscape/TerrainFactory.cs, Explorer/Assets/DCL/Landscape/TerrainGenerator.cs, Explorer/Assets/DCL/Landscape/Worlds/TerrainModel.cs
Did someone say extra 375MB+ of memory? Yes!
This PR doubles the size of the chunks of terrain, minimising the memory footprint caused by two main things:
* Reduced by 3/4 the Terrain tree billboards Render Textures (that we might be able to remove in a separate PR entirely)
* Reduced by 3/4 the Terrain basemap and metallic map textures
Following some screenshots that prove the reduced memory allocations with no performance impact:
Memory snapshot before and after improvements:
Terrain tree billboards Render Textures before and after improvements:
Terrain basemap and metallic map textures before and after improvements:
Profile analyzer before and after:
To test this PR we just need a sanity check of the terrain
1. Enter genesis city
2. Walk around and verify the terrain is visible as …
=> Chore: increase terrain chunks size

Explorer/Assets/DCL/Friends/UI/FriendPanel/Sections/Friends/FriendListSectionUtilities.cs, Explorer/Assets/DCL/Friends/UI/FriendPanel/Sections/Friends/FriendSectionController.cs, Explorer/Assets/DCL/Friends/UI/FriendPanel/Sections/Friends/FriendsSectionDoubleCollectionController.cs, Explorer/Assets/DCL/Friends/UI/FriendPanel/Sections/Requests/RequestsSectionController.cs, Explorer/Assets/DCL/Passport/PassportController.cs, Explorer/Assets/DCL/UI/GenericContextMenu/Controls/Configs/GenericContextMenu.cs, Explorer/Assets/DCL/UI/GenericContextMenu/GenericContextMenuController.cs
Many use cases of the context menu need to be able to include/remove certain components based on runtime values that cannot be defined in the constructor. 
Instead of instantiating a new `GenericContextMenu` object every time to accomodate those cases, an `Enabled` bool value is introduced on every component in order to allow the user to create an instance once and then change this value to control how the context menu looks and which functionalities it exposes based on those runtime values.
The method `AddControl` of the class `GenericContextMenu` has a retro-compatible overload that wraps the instatiation of this new class type. This overload can also be applied to every use case where the user don't need to control the visibility of a certain context menu component.
This PR modifies …
=> Feat: generic context menu - enable on components

Explorer/Assets/DCL/PluginSystem/Global/StaticSettings.cs, Explorer/Assets/DCL/WebRequests/Analytics/WebRequestsContainer.cs, Explorer/Assets/DCL/WebRequests/BudgetedWebRequestController.cs, Explorer/Assets/DCL/WebRequests/WebRequestControllerExtensions.cs, Explorer/Assets/Scripts/Global/Dynamic/Bootstraper.cs, Explorer/Assets/Scripts/Global/Dynamic/MainSceneLoader.cs, Explorer/Assets/Scripts/Global/Tests/PlayMode/IntegrationTestsSuite.cs
Introduces a Scene Web Request Controller. 
This re-routes requests through a different controller, allowing to have a different and isolated budget from the core web request controller.
As an initial value, the scene web request controller have been set to 5. Any given scene cannot have more than 5 simultaneos web requests.
1. Two scenes are blowing up the web requests (`LaLigaLand (-150,64)` and `DCL 5 year birthday party (-137,52)` )
2. Teleport to both of those scenes. Probably the debug metric for `Scene Budget` will stay at 0; that's expected. But everything around you should load just fine
3. Teleport back to any scene. That metric should return to 5
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md) …
=> fix: Introduce scene web request controller

Explorer/Assets/Scripts/ECS/StreamableLoading/Cache/Disk/CacheDirectory.cs
This PR introduces Disk Cache versioning to allow full wipe of old cache when introducing major changes like partial loading and partial disk cache
=> fix: added disk cache versioning

Explorer/Assets/Scripts/SceneRuntime/Apis/JSTaskResolverResetable.cs
This change implements the unsafe API for JSTaskResolverResetable. This gets rid of allocations.
Visit complex scenes with lots of scripting.
=> Implement IV8HostObject for JSTaskResolverResetable

Explorer/Assets/DCL/NameTags/NametagView.cs, Explorer/Assets/DCL/Profiles/Self/SelfProfile.cs
Added a line on the SelfProfile that re-calculated the profile color when changing the profile.
Also found that we were assigning as OwnProfile the previous profile instead of the new one? So I changed that, but please correct me if im wrong with that xD just seemed odd that we were assigning back the previous profile...
* The issue triggered after changing wearables and teleporting back and forth. So try doing that xD
Teleport, change a wearable, wait until its changed, teleport again, etc. 
The nametag should remain with the correct color and all.
=> fix: own profile color doesnt get re-calculated when changing profile

Explorer/Assets/DCL/Chat/MessageBus/MultiplayerChatMessagesBus.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/DecoratorBased/ChatMessagesBusAnalyticsDecorator.cs, Explorer/Assets/DCL/UI/TextFormatter/HyperlinkTextFormatter.cs
…ed by some characters
The REGEX for websites used for hyperlink formatting expected at least 2 characters for the domain name, that has been reduced to a single character now. May god have mercy on our souls.
Also fixed a small issue with detecting mentions when the username was followed by a punctuation sign like !.,?
Try websites that have only one character in their domain like https://x.com or any other? also try links inside said domain, like links to specific users or posts inside x (lets just call it Twitter?)
=> fix: hyperlink detection for single character domain names

Explorer/Assets/DCL/NameTags/Systems/NametagPlacementSystem.cs, Explorer/Assets/DCL/Profiles/Components/Profile.cs, Explorer/Assets/DCL/Profiles/Self/SelfProfile.cs
Added a default color for the profile and a check for that color when setting the own nametag, in this case it will calculate the color if the color is the default.
Test that the own nametag has a visible name, particularly for new users. The color should remain constant after changing wearables or teleporting as well.
=> fix: username color shenanigans

Explorer/Assets/DCL/UI/InputSuggestions/InputSuggestionBox.prefab, Explorer/Assets/DCL/UI/InputSuggestions/InputSuggestionPanelView.cs
The margins on the asset were conflicting with the padding and it caused a slight visual issue.
Check that this doesnt happen:
Now margins on the top and bottom should be equal, both for emoticons and profile suggestions, also margins should remain correct when there are more than one suggestion.
Also fixed a small issue when selecting suggestions after deleting a letter, for example, write `:hel`, the helicopter will be selected, then delete `el` and type `e` again, the first suggestion on top should be selected and showing, instead of being in a random position.
=> fix: tweaks to suggestion box to correct missalignment

Explorer/Assets/DCL/Utilities/Extensions/StringExtensions.cs
Fix #3432
This Issue fixes a specific case of domain validation failure when handling video streams.
Video players were validating a domain and the function was breaking when the domain doesn't contain a / character after the domain, like: "https://lvpr.tv?v=9974hj8adxn8j21u". In this case the domain validation was breaking with a 
`ArgumentOutOfRangeException: Specified argument was out of the range of valid values.`
Blocking the scene from loading
1. Login in decentraland
2. Teleport to -116,-69
3. Verify that the loading doesn't get stuck and that the scene loads fine
Because this PR adds a specific validation verify in other scenes that video streams are working as before by comparing their execution to be the same between prod and this PR …
=> fix: fixed domain validation when no post domain SLASH char is provided

Explorer/Assets/Scenes/Main.unity
Brings back the loading logo before the authetication screen
See that the loading logo is visible while in Splash Screen
=> fix: bring back the loading logo

Explorer/Assets/DCL/Audio/Sounds/Explorer Alpha 2024/Ambience - Ocean.wav.meta, Explorer/Assets/DCL/Audio/Sounds/Explorer Alpha 2024/Ambience - Woods - Day - No Wind 01.wav.meta, Explorer/Assets/DCL/Audio/Sounds/Explorer Alpha 2024/Ambience - Woods - Day - No Wind 02.wav.meta, Explorer/Assets/DCL/Audio/Sounds/Explorer Alpha 2024/Ambience - Woods - Day - No Wind 03.wav.meta, Explorer/Assets/DCL/Audio/Sounds/Explorer Alpha 2024/Ambience - Woods - Night.wav.meta, Explorer/Assets/DCL/Audio/Sounds/Explorer Alpha 2024/Music - Authentication.wav.meta, Explorer/Assets/DCL/Audio/Sounds/Explorer Alpha 2024/Music - Builder.wav.meta
This change changes the built-in background music and ambience to be streamed from disk rather than loaded in memory. This will save us about 40 MB of RAM.
Listen to the background music for at least one full loop and listen for any cracks and pops.
=> Set music and ambience to be streamed from disk

Explorer/Assets/DCL/AvatarRendering/AvatarShape/Assets/Avatar_Facial_Features.mat, Explorer/Assets/DCL/AvatarRendering/AvatarShape/Assets/Avatar_Toon.mat, Explorer/Assets/DCL/AvatarRendering/AvatarShape/Components/AvatarCustomSkinningComponent.cs, Explorer/Assets/DCL/AvatarRendering/AvatarShape/ComputeShader/ComputeShaderConstants.cs, Explorer/Assets/DCL/AvatarRendering/AvatarShape/Systems/AvatarShapeVisibilitySystem.cs, Explorer/Assets/DCL/PluginSystem/Global/AvatarPlugin.cs
During the stress test, I found out that one of our most consuming system was `AvatarShapeVisibilitySystem`. When you have many avatars, you have to update the value of the fade distance for every material every frame
What this PR does is:
- Extract the `StartFadeDistance` value to `AvatarSettings`
- Set the value only where its under the `StartFadeDistance`. Any other value different than that, doesnt make sense to update
As a result, a gain of `1.53 ms` is visible when deep profiling on the example frames shown
1. Go to `olavra.dcl.eth` to avoid noise
2. Instanatiate 50 non network avatars
3. Check that dithering works fine for all of them and yourself
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md) …
=> chore: optimize avatar visibility shape system

Explorer/Assets/DCL/WebRequests/Texture/GetTextureWebRequest.cs
Currently only MacOS has runtime texture compression enabled for non-asset-bundle textures.
When in Local Scene Development, creators use raw textures and some of them may fail while TextureFuse library tries to compress them, in that scenario the texture is left as `null` instead of continue using the uncompressed texture as fallback.
Fixed our usage of TextureFuse compression to fallback to using the uncompressed texture when compresison fails.
Fixes https://github.com/decentraland/creator-hub/issues/499
Since runtime tex compression is only enabled for MacOS, **it only makes sense to test this PR on MacOS**.
1. Download [this test scene](https://github.com/user-attachments/files/19168072/light-memory-leak-test-main.zip) and uncomperss it somewhere
2. Enter the scene root folder and run …
=> fix: missing texturefuse compression failure fallback

Explorer/Assets/DCL/PerformanceAndDiagnostics/Optimization/ThreadSafePool/ThreadSafeObjectPool.cs
I've been getting weird Exceptions in HashNamings that uses ThreadSafePool for StringBuilder, after a research I found out that ThreadSafePool was not truly thread-safe because when `public PooledObject<T> Get(out T v)` is called the instance that PooledObject refers to is not thread-safe but is an underlying instance of `ExtendedObjectPool` which doesn't have any lock statement on its `Release()` implementation
Fixed by referring to the thread-safe object in `PooledObject`
```
NullReferenceException: Object reference not set to an instance of an object
ECS.StreamableLoading.Cache.Disk.HashNamings+<>c.<.cctor>b__2_1 (System.Text.StringBuilder sb) (at Assets/Scripts/ECS/StreamableLoading/Cache/Disk/HashNamings.cs:17)
UnityEngine.Pool.ObjectPool`1[T].Release (T element) (at …
```
=> fix: threadsafe pool

Explorer/Assets/DCL/Rendering/GPUInstancing/InstancingData/GPUInstancingMaterialsCache.cs, Explorer/Assets/DCL/Roads/Settings/IRoadSettingsAsset.cs, Explorer/Assets/DCL/Roads/Settings/RoadSettingsAsset.cs
In Editor material variants were creating errors for missing keywords. I added simple in-Editor workaround for that
1. Verify that roads, bushes and grass are rendered as on dev 
=> enable keywords on parent in editor

Explorer/Assets/DCL/AvatarRendering/AvatarShape/Assets/Avatar_Facial_Features.mat, Explorer/Assets/DCL/AvatarRendering/AvatarShape/Assets/Avatar_Toon.mat, Explorer/Assets/DCL/AvatarRendering/AvatarShape/Components/AvatarCachedVisibilityComponent.cs, Explorer/Assets/DCL/AvatarRendering/AvatarShape/Components/AvatarCustomSkinningComponent.cs, Explorer/Assets/DCL/AvatarRendering/AvatarShape/ComputeShader/ComputeShaderConstants.cs, Explorer/Assets/DCL/AvatarRendering/AvatarShape/Systems/AvatarShapeVisibilitySystem.cs, Explorer/Assets/DCL/PluginSystem/Global/AvatarPlugin.cs
When introducing this optimization, I introduced a bug which keeps transparency while doing abrupt changes (something that happened while teleport).
This improves the robustness of the solution through an enum, while keeping the performance optimization.
1. Teleport while having dithering. You should be opaque when getting to destination
2. Teleport transparent. You should be transparent when getting to the destination
3. Instantiate 50 avatars in `olavra.dcl.eth`. Check that dithering is fine
4. On a peer, change a wearable and see that transprency works as expected
=> fix: correct transparency while teleporting

Explorer/Assets/DCL/Chat/ChatController.cs, Explorer/Assets/DCL/Chat/ChatView.cs, Explorer/Assets/DCL/Chat/History/ChatChannel.cs
The padding messages were being considered as unread messages.
Additionally, now the conversation is set as read in the beginning.
The NEW line is now not shown when the messages are all visible and the line would be at the top.
1. Enter Decentraland.
2. Once you are in Genesis Plaza, there must not be any unread message.
=> Fix: 3 Unread Messages Badge Appears Randomly on App Start (#3570)

.github/workflows/enforce-group-approvals.yml
- remove `commented` state condition from if condition since it was causing to skip merge restrictions
=> fix: correct enforce-approvals conditions

Explorer/Assets/DCL/ApplicationVersionGuard/ApplicationVersionGuard.cs
This change implements shell execute for Windows and OSX so that we can launch the launcher from the game so that it can update the game. Fixes issue #3295.
Launch the game with the simulateVersion argument set to some old version and choose "update" when prompted.
=> Implement shell execute ourselves

Explorer/Assets/DCL/Friends/UI/Requests/FriendRequestController.cs, Explorer/Assets/DCL/PluginSystem/Global/FriendsPlugin.cs, Explorer/Assets/Scripts/Global/Dynamic/DynamicWorldContainer.cs
Adds the color name paired with the profile picture background at the friend request screen.
1. Send & receive friend requests
2. In all states, including the confirmation animation, check that the color name equals to the background color of the profile picture
=> fix: user color name at friend requests

.github/workflows/enforce-group-approvals.yml
- workflow will now trigger whenever commits are pushed to the PR branch (including when merging dev into it)
=> fix: update enforce-approvals trigger

Explorer/Assets/DCL/Passport/PassportController.cs
Fixes #3525 
According to specs, the interaction button of the profile component of the passport context menu should't allow to interact with the friendship status
This PR removes the button in the component in order to align the E@ to the specs
1. Launch the E@ and verify that the profile component of the Passport's context menu never (regardless the friendship status) has the button to interact with the friendship with that person
=> fix: align to specs profile component of passport's context menu

Explorer/Assets/DCL/Infrastructure/MVC/ViewDependencies/ViewDependencies.cs, Explorer/Assets/DCL/Infrastructure/MVC/ViewDependencies/csc.rsp, Explorer/Assets/DCL/Infrastructure/MVC/ViewDependencies/csc.rsp.meta, Explorer/Assets/DCL/Profiles/IProfileThumbnailCache.cs, Explorer/Assets/DCL/Profiles/ProfileThumbnailCache.cs, Explorer/Assets/DCL/UI/ImageView.cs, Explorer/Assets/DCL/UI/Profiles/ProfileElements/ProfilePictureView.cs, Explorer/Assets/DCL/UI/Profiles/ProfileElements/csc.rsp, Explorer/Assets/DCL/UI/Profiles/ProfileElements/csc.rsp.meta
Adds a fade transition when a profile picture is displayed.
You should see a fade transition on each profile picture if we need to download the thumbnail (not loaded in the cache).
You can check either through the friends feature, your own profile picture at the side bar, mutual friends at passport, chat.
=> feat: fade transition at profile pictures

Explorer/Assets/DCL/Infrastructure/ECS/SceneLifeCycle/ECSReloadScene.cs, Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs
Hot-reload is not working beyond the 1st reload.
Removed unneeded CacheCleaner usage that randomly breaks hot-reload. (introduced recently at https://github.com/decentraland/unity-explorer/pull/3595)
1. Download [this test scene](https://github.com/decentraland/sdk7-test-scenes/tree/main/scenes/54%2C-55-Testing-3d-models)
3. Close the Explorer that auto-opened. Leave the scene running in the console/terminal.
4. Download the build from this PR and connect it to the running scene using [the console command](https://github.com/decentraland/unity-explorer/wiki/How-to-connect-to-a-local-scene-(Unity-Editor---Custom-Build---Latest-Released-Build)#connecting-a-custom-build-to-the-scene) according to your …
=> fix: sdk local scene dev hot-reload

Explorer/Assets/DCL/SDKComponents/CameraControl/MainCamera/Systems/MainCameraSystem.cs
Fixes #3629
Camera locked scene restriction was being pushed even if the virtual camera wasn't enabled the first time causing its counter to stack => the icon on the minimap was "always" visible.
This PR pushes the restriction only when the virtual camera is actually enabled, making the notification aligned with the actual restrictions.
1. Launch the E@ and verify that no scene restriction icon is visible
2. Go to `eax.dcl.eth` and verify that the camera area correctly push the restrictions only when you are inside the camera more areas
3. Test Color pop/Minesweeper (and other games that block your camera) and verify that the listed restrictions are consistent and removed if you stop playing
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/maste …
=> fix: apply camera restriction on virtual camera apply only

Explorer/Assets/DCL/Web3/Identities/MemoryMappedFilePlayerPrefsIdentityProviderKeyStrategy.cs
Fixes [#3535 System.NullReferenceException: Object reference not set to an instance of an object.](https://github.com/decentraland/unity-explorer/issues/3535)
Prevents double dispose of MMF key.
1. Launch DCL normally
2. Jump into Genesis and play 2-3 mins
3. Force quit (alt+f4 or cmd+Q) 
4. Observe no error in the Player.log file that are related to MemoryMappedFilePlayerPrefsIdentityProviderKeyStrategy
- [+] Changes have been tested locally
=> Fix: prevent double dispose

Explorer/Assets/DCL/AvatarRendering/Wearables/Helpers/WearablePolymorphicBehaviour.cs
Fixes #3506 
When an equipped wearable fails to load with an exception, the system continuously tries to load it, stopping the whole avatar to be loaded.
This PR properly tests the load condition taking into account the fact that the wearable may have failed to be loaded for that avatar (in the issue case, it was a female only wearable that was being loaded onto a male avatar)
Use the `debug` arg to launch the E@
1. Using the debug panel, under "Profile: Avatar Shape", load the wallet `0xd8e554279131622199408a102ec62e237491acef`
2. Verify that the avatar loads (skipping the shoes that are for the wrong avatar shape) and is visible
3. Verify that no other unknown issue tied to wearables are introduced …
=> fix: account for failed wearable while loading avatar

Explorer/Assets/DCL/Infrastructure/ECS/SceneLifeCycle/ECSReloadScene.cs, Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs
Fixes Local Scene Development (AKA "Preview Mode") hot-reload that got broken with `v0.59`.
=> release: 2025-03-18-fix (#3632)

Explorer/Assets/DCL/UI/Profiles/ProfileElements/ProfilePictureView.cs
Fixes a major performance issue while spamming the chat.
Profile pictures for own chat messages were not working because the loading state was not correctly calculated. The chat system sets the profile picture many times in a row and this provokes to cancel the operation in between. We dont consider the load state anymore in the process. We just set the sprite if its already in the cache.
Spam messages in the chat. Check that you can see your own profile picture. Check that you don't have performance issues.
Check profile pictures in other places, like friends, sidebar, passport, etc.
=> fix: chat spam performance issue & own profile picture

Explorer/Assets/DCL/Friends/WebSocketRpcTransport.cs, Explorer/Assets/DCL/PluginSystem/Global/FriendsPlugin.cs
Changes consists on move all the friends subscriptions after the initial load is completed. At that point we are sure the user has a valid identity, so we can use it later when we try the connection with the friends server.
Try to login & logout with different accounts. Then check that all friends features are working, like friend & requests listing, send/receive/accept requests, etc..
=> fix: friends rpc connection with invalid identity

Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/AssetBundles/AssetBundleData.cs
Ensures we do not attempt to unload the AB if already null.
Fixes: https://github.com/decentraland/unity-explorer/issues/3641
- Run the game
- Close the game
- Check Player.log
- Ensure it doesn't have the following in (towards the end)
`NullReferenceException: Object reference not set to an instance of an object.
at ECS.StreamableLoading.AssetBundles.AssetBundleData.DestroyObject ()`
=> fix: verify AB is not null before attempting unload

Explorer/Assets/DCL/InWorldCamera/CameraReelGallery/Assets/OptionButton.prefab
PR created to fix the narrowed texture of the menu button used in the photos of the gallery.
2. Open the Gallery.
3. Hover any of the photos and validate the menu icon shows as expected.
=> style: fix menu button width

Explorer/Assets/DCL/Friends/UI/Prefabs/FriendRequest.prefab, Explorer/Assets/DCL/Notifications/Assets/FriendsNotification.prefab
This PR fixes the pivot point of the action buttons in the panels to `send a friend request` and `cancel a sent request`. As shown in the video, the buttons currently scale from the bottom corner instead of the center.
https://github.com/user-attachments/assets/818186eb-5a61-45b6-abf7-fa24bf6f7873
Also replaces de ProfilePicture UI component in the Friend notification, which was still using the deprecated in where the mask is not scaling proportionally with the size of the ellipse container.
1. Launch the client.
2. Try to send a friend request to anyone to open the prompt. Mouse hover both buttons and ensure the scale animation comes from the center. Then press `Send`.
3. Once the person accepts your request, check in the notification which appears on top of your screen (afterwards in …
=> style: fix buttons pivot on send & cancel friend request containers

Explorer/Assets/DCL/Friends/UI/Prefabs/BlockUserPrompt.prefab, Explorer/Assets/Textures/Common/LockGreen.png
This PR aligns the block/unblock prompt with the original design from [Figma](https://www.figma.com/design/2UQLtYTpDhBgaRafZJxj00/%F0%9F%97%BA%EF%B8%8F-Friends-%7C-Explorer-2.0-%7C-01%2F25?node-id=255-26025&t=3yqWiqNdZXggi9Ak-1). As shown in the screenshot, the body text box extends beyond the margin on both sides compared to the buttons breaking the guidelines. The 'floor light effect' behind the image is also missing.
This PR also fixes the pivot point of the action buttons. As shown in the video, the buttons currently scale from the bottom corner instead of the center.
https://github.com/user-attachments/assets/6998910c-7713-4aa3-82c7-58469136b479
1. Launch the client.
2. Attempt to block a friend from your friends list. Verify that the prompt’s body text box does not exceed the margin …
=> style: block user prompt UI polish

Explorer/Assets/DCL/FeatureFlags/FeatureFlagsStrings.cs
It renames the profile name editor feature flag so it includes the prefix `alfa`.
Check that you cannot edit your name from the passport (since the feature flag is disabled).
If you restart the client with `--debug --profile-name-editor` you should be able to edit your profile name.
=> fix: rename profile name editor feature flag name

Explorer/Assets/DCL/InWorldCamera/CameraReelGallery/CameraReelGallery.asmdef, Explorer/Assets/DCL/InWorldCamera/CameraReelGallery/CameraReelGalleryController.cs, Explorer/Assets/DCL/Navmap/Navmap.asmdef, Explorer/Assets/DCL/Navmap/SearchResultPanelController.cs, Explorer/Assets/DCL/UI/Utilities/ScrollRectExtensions.cs, Explorer/Assets/DCL/UI/Utilities/ScrollRectExtensions.cs.meta
Fixes #3588 
The scrolling speed of the scroll rect has a different feeling based on platform.
This PR sets a scrolling speed based on the current running platform.
1. Launch E@
2. Search for "games" in the navmap search bar
3. Verify that the scrolling speed of the results is acceptable
- I couldn't reproduce a slow scrolling speed in current version `0.60`, therefore the PR could be unnecessary
=> fix: navmap search result scroll speed

Explorer/Assets/DCL/InWorldCamera/InWorldCamera/Systems/ToggleInWorldCameraActivitySystem.cs
Fix #3360
When transitioning to InWorld Camera and then back, camera was not switching to previous mode and was going only to ThirdPerson or Drone mode (depending on distance).
- add caching for previous position and transition to it
check related bug-ticket and comments there
- Enable InWorld Camera from different camera modes - First Person, Third Person, Drone camera
- Verify that after switching back, it always goes to the mode from which you enabled InWorld Camera.
=> Fix:  Camera Reel | switching back to previous camera mode

Explorer/Assets/DCL/Infrastructure/Global/AppArgs/AppArgsFlags.cs, Explorer/Assets/DCL/Infrastructure/Global/AppArgs/IAppArgs.cs, Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/StaticCommonTraitsPlugin.cs, Explorer/Assets/DCL/UserInAppInitializationFlow/RealUserInAppInitializationFlow.cs
After [researching](https://github.com/decentraland/unity-explorer/pull/3668) which global plugins (unrelated to local scene dev) can be disabled to improve the Local Scene Development devexp, the LOD and LANDSCAPE-TERRAIN were identified as the only ones that actually bring some gains (in memory and performance, not initialization times).
* Disabled LOD plugin for LSD
* Implemented support for new flag to toggle Landscape plugin (`landscape-terrain-enabled`)
* Updated a couple of app args checks with new utility method
1. Download the build from this PR and open it normally, confirm that the terrain/landscape appears normally in Genesis City
2. Clone the [test scenes repo](https://github.com/decentraland/sdk7-test-scenes) and enter any of the scenes inside `/scenes/`
3. In the scene …
=> chore: landscape terrain toggling with app arg

Explorer/Assets/DCL/Friends/UserBlockingCache.cs, Explorer/Assets/DCL/Settings/Configuration/SettingsMenuConfiguration.asset
Fixes #3696
Remove the option to choose to show messages from blocked players.
Make `UserBlockingCache.HideChatMessages` always return true + remove the setting from the option menu through the scriptable object so that you cannot interact with it.
1. Block a user
2. Have that user send a chat message
3. Verify that you don't see their messages
4. Verify that you don't have any way to disable the option (aka show the message as blocked)
=> fix: remove option to show messages from blocked users

Explorer/Assets/DCL/Character/CharacterMotion/Systems/SDKAvatarShapesMotionSystem.cs, Explorer/Assets/DCL/Infrastructure/ECS/Unity/Transforms/ExposedTransformUtils.cs, Explorer/Assets/DCL/Infrastructure/Utility/ParcelMathHelper.cs, Explorer/Assets/DCL/Interaction/Utility/RaycastUtils.cs, Explorer/Assets/DCL/PluginSystem/World/AvatarShapePlugin.cs, Explorer/Assets/DCL/SDKComponents/AvatarShape/Systems/UpdateAvatarShapeInterpolateMovementSystem.cs
Currently when we auto-interpolate SDK Avatar Shapes after their SDK `Transform` is manipulated by the scene (instead of using the `Tween` component), we are not converting the scene-relative position to global.
Using `Tween` it works as expected because the `Tween` systems logic already takes care of the position conversions.
Issue: https://github.com/decentraland/unity-explorer/issues/3647
That's why for any scene that is not in 0,0 the avatar shape interpolates to a target position relative to 0,0 when it should be interpolating to a target position relative to the base parcel of the scene...
https://github.com/user-attachments/assets/51026a62-ba27-46f5-9207-1aafc264f5de
Added missing position conversion to global when reading SDKTransform for interpolation
1. Download the build from …
=> fix: sdk avatar shape transform interpolation not using global pos

Explorer/Assets/DCL/Utilities/TextureUtilities.cs
Marketplace builder collection wearables with textures above 1024x1024 resolution were breaking the preview due to the excessive TextureArray data allocation, since the AB Converter optimizes those textures capping them at 1k resolution.
Refactored raw gltf wearables textures patch to apply the same AB Converter patch on their resolution.
* To test this new feature you will need to create a collection in the wearables builder section of the marketplace at https://decentraland.org/builder/collections/
* Here I provide 2 test wearables that have to be loaded into the collection: [2048-res-tex-test-wearables.zip](https://github.com/user-attachments/files/19447509/2048-res-tex-test-wearables.zip)
* After you have a collection created in the marketplace builder section, copy its collection ID …
=> fix: unreleased wearables preview breaking with 2K texture resolution

Explorer/Assets/DCL/Chat/Assets/ChatMessageViewerElement.prefab, Explorer/Assets/DCL/Chat/Chat.asmdef, Explorer/Assets/DCL/Chat/ChatMessageViewerElement.cs, Explorer/Assets/DCL/UI/Utilities/ScrollRectExtensions.cs
Added scroll sensitivity change depending on platform for the Chat Scroll + added possibility to override default values in helper class.
Check that scrolling with the mouse wheel works correctly in the chat, both in Windows and Mac.
=> fix: Scroll speed in chat

Explorer/Assets/DCL/AvatarRendering/AvatarShape/Assets/Animator/CharacterAnimator.controller
Fixes #3631 
It also fixes problems on emote replication when there are several users on an area.
The issue was not the replication per-se, but the movement of the avatar. The current movement interpolation has problems and provokes small hiccups on the peers which makes them to cancel the current emote.
It is more evident when the peer is over a platform because they are not in sync and you can see how the user floats in the air executing the fall animation.
The fix consist on disable the transition in the animator from the emote to the movement and falling state. The only way the avatar will transition is by stopping the emote through the trigger, either `EmoteStop` and/or `EmoteLoop`, which we already handle in the animation system.
Play emotes and move, jump or fall. You should see …
=> fix: emotes platform replication

Explorer/Assets/DCL/AvatarRendering/AvatarShape/Rendering/TextureArray/TextureArrayContainerFactory.cs, Explorer/Assets/DCL/AvatarRendering/AvatarShape/Rendering/TextureArray/TextureArrayHandler.cs, Explorer/Assets/DCL/AvatarRendering/AvatarShape/Rendering/TextureArray/TextureArraySlotHandler.cs
Adds texture array naming for better debugging
1. Nothing in particular. Smoke test. This should not modify runtime code
=> chore: Add textures array for naming

Explorer/Assets/DCL/InWorldCamera/ReelActions/ReelCommonActions.cs
Fixes #3749
Move the camera reel download destination folder to OS Downloads folder
1. Take some screenshot using the in world camera
2. Open the gallery
3. Download some reel
4. Verify that they have been downloaded to the `Downloads` folder of you OS user folder
- Windows: `C:\users\your name\downloads`
- Mac: `/Users/your name/Downloads`
=> fix: move camera reel download folder to Downloads

Explorer/Assets/Textures/Common/Container24.png.meta
Fixes #3729 at least the masking problem in the client (the image propagation issue should be taken by platform team).
The fix consists on making the `Container24.png` read/write enabled.
Check that profile pictures works as expected. Places on which you can encounter them: chat, friends, passport, camera reel. You should not see any logs like this:
```
[WARN] SoftMasking Issue with Texture: Also, related to the profile picture, there is a warning in the logs about SoftMask not being able to read the texture for the profile image.
```
=> fix: log spam about profile picture masking

Explorer/Assets/DCL/MapRenderer/MapLayers/LiveEvents/LiveEventsMarkersController.cs, Explorer/Assets/DCL/MapRenderer/MapLayers/PointsOfInterest/ScenesOfInterestMarkersController.cs
This pr is related to https://github.com/decentraland/unity-explorer/pull/3608 but with a different approach.
Fixes #3403 
Also fixes exceptions like these when the identity is expired or non-existent:
```
InvalidOperationException: Identity is not found in the cache
```
Changes consist of postponing the load of the live events and points of interests when they are enabled by the map system. Previously it was being loaded during app start, at the creation of the containers provoking this kind of inconsistencies.
Check that the live events and point of interests works as expected, either in the map and minimap.
Try to logout and re-login checking everything keeps consistent in the map.
In the logs there shouldn't be any: `InvalidOperationException: Identity is not found in the cache`.
- …
=> fix: lazy load data of live events & pois

Explorer/Assets/DCL/AvatarRendering/Emotes/Emote.cs
Fix #3664
Avoids a rare possible null reference when accessing the isLooping metadata of emotes
1. Login with any account
2. Play different emotes, both looping and not looping
3. Verify they all work as expected
4. Verify emotes on other users also work as before
=> fix: added safe access to emote isLooping

Explorer/Assets/DCL/Interaction/Systems/InteractionHighlightSystem.cs
Fixes #3460
Add a check for the entity of the highlight component to test if it is still inside `World`, avoiding a subsequent `NRE` in `World.Has<>()`
1. Go to `1,101`
2. Play a solo game
3. Verify that it never freezes and you are able to finish the game
=> fix: disable highlight on entities that have been removed from the World

Explorer/Assets/DCL/Navmap/Assets/EventEntry.prefab, Explorer/Assets/DCL/Navmap/Assets/PlaceSearchEntry.prefab
This PR changes the squared aspect ratio of the results thumbnails which appear in the results panel of the map. 
2. Open the map and click any of the filter tags to view the results panel
3. Check the aspect ratio is not 1:1 anymore.
=> style: change thumbnails aspect ratio from 1:1 to 4:3 for map results cards

Explorer/Assets/DCL/UI/Profiles/Names/Assets/ProfileNameEditor.prefab, Explorer/Assets/DCL/UI/Profiles/Names/ProfileNameEditorController.cs, Explorer/Assets/DCL/UI/Profiles/Names/ProfileNameEditorView.cs, Explorer/Assets/DCL/UI/SystemMenu/SystemMenuController.cs
Fixes #3589
Also fixes a problem on the sorting order of the name editor.
Test the profile name editor. You can open it from your own passport. Test either with an account that has a claimed name and with an account that doesnt have any claimed name since the popup has different states for it. Check that you can save either a claimed name or a custom one. Observe that the loading state in the save button shows as expected.
=> fix: add loading state to profile name saving

Explorer/Assets/DCL/Profiles/ProfileThumbnailCache.cs
Fixes #3681
When a profile thumbnail fails to be downloaded (e.g. the backend is offline), every time the E@ needs it, it still tries to download it (causing error spam) every time.
For example if a message in the chat requires a thumbnail that failed, every new message causes the chat to be redrawn, sending a new request for the missing profile pic that will likely fail. This floods the log with exceptions for the failed download.
This PR introduces an exponential backoff on every thumbnail that fails. The first time, a new attempt is allowed after 30seconds (for all requests made in those 30 seconds, an empty image is returned), then 60, 90 and so on up to a maximum of 5 attempts. After those it is flagged as unsolvable and no attempts will be made. 
This means that for every failing …
=> fix: exponential backoff on thumbnail download error

Explorer/Assets/DCL/AvatarRendering/AvatarShape/ComputeShader/AvatarMaterialConfiguration.cs
This makes assigning facial features materials more exact so there's less of a chance that creators will run into the issue of facial features material being assigned incorrectly.
Previously if a mesh name contained "eyes, eyebrows, mouth", it would break. Now that's changed to "Mask_Eyes, Mask_Eyebrows, Mask_Mouth", which has to be the suffix (should only appear in our base models)
closes: #3249
1. Run the explorer
2. Equip the wearable
3. The head with the custom "cutesy texture" should be visible
- Make sure you don't have something else equipped that would hide the wearable helmet, as that is a separate issue
=> fix: be more specific when assigning facial feature materials

Explorer/Assets/DCL/ApplicationBlocklistGuard/BlockedScreenController.cs
This change adds a null check in BlockedScreenController.Dispose.
1. In Unity editor
2. Enter play mode
3. Exit play mode
4. See that no NullReferenceException occurs in BlockedScreenController.Dispose
=> Duct tape a null reference when exiting play mode

Explorer/Assets/DCL/InWorldCamera/CameraReelStorageService/CameraReelRemoteStorageService.cs, Explorer/Assets/DCL/InWorldCamera/InWorldCamera/Systems/InWorldCameraPlugin.cs, Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs
Fixes #3515 
Sometimes even though the user has plenty of space for camera reels, they cannot take screenshots because they are presented with the error of "storage full".
This PR addresses two edge cases that can cause this issue:
1. When looking at the public reels of another user using their passport, you could "inject" their status to yours. So, if they were "full", you would also be considered "full"
2. If upon startup of the E@ there wasn't any identity set (aka you needed to login) and you didn't go to your personal gallery before going to camera mode, you would get the "storage full" error message (this means: no identity set and as soon as you got into GP, you went into camera mode)
1. Verify that you get the "storage full" error message only if you have actually consumed all the …
=> Fix: in world camera storage full

Explorer/Assets/DCL/Audio/AudioMixerVolumesController.cs
Fixes an exception thrown during loading process:
```
NullReferenceException: Object reference not set to an instance of an object.
at DCL.Audio.AudioMixerVolumesController.UnmuteGroup (DCL.Audio.AudioMixerExposedParam groupParam) [0x00000] in <00000000000000000000000000000000>:0 
at DCL.SceneLoadingScreens.SceneLoadingScreenController.OnViewClose () [0x00000] in <00000000000000000000000000000000>:0 
at MVC.ControllerBase`2[TView,TInputData].HideViewAsync (System.Threading.CancellationToken ct) [0x00000] in <00000000000000000000000000000000>:0 
at Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskMethodBuilder.Start[TStateMachine] (TStateMachine& stateMachine) [0x00000] in <00000000000000000000000000000000>:0 
at MVC.ControllerBase`2[TView,TInputData].HideViewAsync …
```
=> fix: nre on audio group unmute

Explorer/Assets/DCL/Landscape/TerrainGenerator.cs, Explorer/Assets/DCL/RealmNavigation/TeleportController.cs
in Editor was broken due to the null Reference. I added a couple of null checks there. 
Original issue of hard coupling with `TeleportController` will be re-worked soon.
=> add null checks

Explorer/Assets/DCL/Infrastructure/Global/Dynamic/PortableExperiences/ECSPortableExperiencesController.cs
Removed a call to FinalizeWorldSystems from the UnloadPortableExperienceByEns method, as it was finalizing systems that should not be finalized. This was introduced at some point to cleanup MapPins, but seems to be not needed anymore. And is not doing what it should be doing.
Check that quest map pins are removed when you /killpx globalpx
=> fix: killpx does bad things

Explorer/Assets/DCL/InWorldCamera/InWorldCamera/UI/InWorldCameraController.cs
Fixes #3798 
When closing the in world camera view using its top right button, the whole UI disappears. This is caused because the panel controller was closing itself in the mvc system at the same time while the underlying system `ToggleInWorldCameraActivitySystem` was starting its closing process, skipping the normal flow.
This PR removes the button click as a condition for the controller to hide the view, letting the system `ToggleInWorldCameraActivitySystem` handle that.
1. Open the in world camera
2. Close it using the Esc/C shortcuts
3. Verify that all the UIs are still there and working properly as before
4. Open the in world camera
5. Close it using the X button on the top right (unlock the cursor first)
6. Same as .3
- Mention specific areas that …
=> fix: ui disappear when closing in world camera with button

Explorer/Assets/DCL/Infrastructure/ECS/SceneLifeCycle/ECSReloadScene.cs
The scene reload (or at least the hot-reload) breaks the scene and it never loads again.
Added missing entity alive check before `world.Has()`.
1. Download [this test scene](https://github.com/user-attachments/files/19582585/scene-reload-test.zip)
3. Close the Explorer that auto-opened. Leave the scene running in the console/terminal.
4. Download the build from this PR and connect it to the running scene using [the console command](https://github.com/decentraland/unity-explorer/wiki/How-to-connect-to-a-local-scene-(Unity-Editor---Custom-Build---Latest-Released-Build)#connecting-a-custom-build-to-the-scene) according to your OS
5. Once the scene loads, leave the Explorer running and in any text …
=> fix: scene reload missing entity alive check

Explorer/Assets/DCL/Interaction/Raycast/Systems/ExecuteRaycastSystem.cs, Explorer/Assets/DCL/Landscape/Assets/Bushes/Bush01/Bush01 Variant.prefab, Explorer/Assets/DCL/Landscape/Assets/Bushes/Bush02/Bush02 Variant.prefab, Explorer/Assets/DCL/Landscape/Assets/Props/Clifs/Cliff01.prefab, Explorer/Assets/DCL/Landscape/Assets/Props/Clifs/CliffCorner01.prefab, Explorer/Assets/DCL/Landscape/Assets/Rocks/Rock01/Rock01 Variant.prefab, Explorer/Assets/DCL/Landscape/Assets/Rocks/Rock02/Rock02 Variant.prefab, Explorer/Assets/DCL/Landscape/Assets/Rocks/Rock03/Rock03 Variant.prefab, Explorer/Assets/DCL/Landscape/Assets/Trees/Tree01/Tree01 Variant.prefab, Explorer/Assets/DCL/Landscape/Assets/Trees/Tree02/Tree02 Variant.prefab, Explorer/Assets/DCL/Landscape/Assets/Trees/Tree03/Tree03 Variant.prefab, Explorer/Assets/DCL/Landscape/TerrainFactory.cs
Fix https://github.com/decentraland/unity-explorer/issues/3818
- Brought terrain colliders back to `Default` layer
- removed Clamp maxDistance for Raycast
As in the mentioned bug-ticket
=> Fix: camera not colliding with terrain  

Explorer/Assets/DCL/Chat/ChatController.cs
Added a subscription to the key press event when the Chat controller is shown for the first time.
1. Enter Decentraland.
2. When everything loads, press Enter.
3. The input box of the chat should gain the focus.
=> Fix: Pressing Enter was not opening the chat for typing

Explorer/Assets/DCL/UI/MainUIContainer/MainUIContainer.prefab
The purpose of this PR is to move the friend's push notification from between the chat panel and mini-map to the bottom right corner.
2. Once the world loads check the friends notifications appears in their new position.
=> style: move the friend push notification to the right bottom corner

Explorer/Assets/DCL/InWorldCamera/CameraReelGallery/CameraReelGalleryController.cs, Explorer/Assets/DCL/InWorldCamera/CameraReelGallery/Components/ReelThumbnailController.cs, Explorer/Assets/DCL/InWorldCamera/PhotoDetail/PhotoDetailController.cs
Fixes #3829 
After memory profiling the E@ it was noticed that reels (both compressed and uncompressed versions) stayed in memory even if they were not used.
This PR explicitly destroys/remove references (in the case of pooled objects) of every reel related texture when they are no longer used.
1. Launch the E@
2. Verify that the reels work as before (in gallery, photo detail, users passports, navmpap places, etc)
=> fix: remove reel related texture from memory when not used

Explorer/Assets/DCL/SDKComponents/MediaStream/MediaPlayerCustomPool.cs, Explorer/Assets/DCL/SDKComponents/MediaStream/MediaPlayerUtils.cs, Explorer/Assets/DCL/SDKComponents/MediaStream/MediaPlayerUtils.cs.meta, Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/CleanUpMediaPlayerSystem.cs, Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerSystem.cs, Explorer/Assets/DCL/SDKComponents/MediaStream/Wrapper/MediaPlayerPluginWrapper.cs
- Correctly uses the media player pool when the URL changes. It now starts the cycle over
- Fixes [this ](https://decentraland.sentry.io/issues/6507381956/?project=4506075736047616&query=CleanUpMediaPlayer&referrer=issue-stream&sort=date&stream_index=0)raising Sentry issue
1. Use the change video LSD scene
2. Check that videos swap correctly and you here audio as well
=> fix: Reuse media player on url change

Explorer/Assets/DCL/AvatarRendering/AvatarShape/Assets/Animator/CharacterAnimator.controller
Cancel emote if the avatar is moving.
Previously we modified the avatar animator transitions so it doesn't consider the movement parameter anymore because peers were cancelling the emotes over time. The problem is that sometimes the avatar moves while emoting. The changes re-enables the transition but increasing the movement threshold.
Group together with other users. Play emotes. Emotes should not stop while standing still. Emotes should stop if the avatar moves. Also check steps/issue of this pr: https://github.com/decentraland/unity-explorer/pull/3714
=> fix: emotes while moving

Explorer/Assets/DCL/AvatarRendering/AvatarShape/Systems/AvatarCleanUpSystem.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/Play/CharacterEmoteSystem.cs, Explorer/Assets/DCL/Infrastructure/ECS/LifeCycle/Components/DeleteEntityIntention.cs, Explorer/Assets/DCL/Infrastructure/ECS/SceneLifeCycle/IncreasingRadius/ResolveSceneStateByIncreasingRadiusSystem.cs, Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs, Explorer/Assets/DCL/PluginSystem/Global/AvatarPlugin.cs
We got the following exception during the most recent stress test
```
MissingReferenceException: The object of type 'Animator' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
```
This reflects that an `avatarBase`, which has been returned to the pool and deleted by the `CacheCleaner`, is still persisting in ECS.
And Im unable to get to the very origin of this problem. One possibility could be that the defer deletion of the avatar causes a problem somewhere.
There isnt a reason to keep the performance budget on deletion, since it shouldnt be a super common operation. So, to remove one possible error, Im removing it on this PR
Took the opportunity as well to clarify why Scene entities require a …
=> fix: Remove avatar clean up defer deletion

Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Asset/Components/GltfContainerAsset.cs, Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Components/GltfContainerComponent.cs, Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Systems/ConfigureGltfContainerColliders.cs, Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Systems/LoadGltfContainerSystem.cs, Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Systems/ResetGltfContainerSystem.cs, Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Tests/LoadGltfContainerSystemShould.cs, Explorer/Assets/DCL/Infrastructure/ECS/Unity/SceneBoundsChecker/CheckColliderBoundsSystem.cs, Explorer/Assets/DCL/Infrastructure/ECS/Unity/SceneBoundsChecker/SDKCollider.cs, Explorer/Assets/DCL/Infrastructure/ECS/Unity/SceneBoundsChecker/Tests/ColliderBoundsCheckerShould.cs, Explorer/Assets/DCL/PluginSystem/World/GltfContainerPlugin.cs
Revert "fix: PBGltfContainer props update lost while GLTF is still loading (#3748)"
This reverts commit 9d077c9c1a35d35bb9e3349eb9923211c601a5e2.
Since apparently it brings problems on some MVFW scenes.
=> hotfix: 2025-04-08

Explorer/Assets/DCL/Infrastructure/SceneRuntime/Apis/Modules/FetchApi/LogSimpleFetchApi.cs
This change makes SimpleFetchApi task cancellation not an error.
Cause a web request made by a scene be interrupted and observe that no exception is logged. Maybe leaving a scene while it is performing a web request will do this.
=> SimpleFetchApi: Task cancellation is not an error

Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Asset/Components/GltfContainerAsset.cs, Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Components/GltfContainerComponent.cs, Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Systems/ConfigureGltfContainerColliders.cs, Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Systems/LoadGltfContainerSystem.cs, Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Systems/ResetGltfContainerSystem.cs, Explorer/Assets/DCL/Infrastructure/ECS/Unity/GLTFContainer/Tests/LoadGltfContainerSystemShould.cs, Explorer/Assets/DCL/Infrastructure/ECS/Unity/SceneBoundsChecker/CheckColliderBoundsSystem.cs, Explorer/Assets/DCL/Infrastructure/ECS/Unity/SceneBoundsChecker/SDKCollider.cs, Explorer/Assets/DCL/Infrastructure/ECS/Unity/SceneBoundsChecker/Tests/ColliderBoundsCheckerShould.cs, Explorer/Assets/DCL/PluginSystem/World/GltfContainerPlugin.cs
Related Issue: https://github.com/decentraland/unity-explorer/issues/3728
Recently implemented PR https://github.com/decentraland/unity-explorer/pull/3748 introduced a bug in which some scenes collider didn't enable correctly on scene initialization, so the original fix for instantiated GLTFContainer subsequent property updates had to be reverted.
* Re-added fix implemented at https://github.com/decentraland/unity-explorer/pull/3748
* Added 1-liner fix (from old https://github.com/decentraland/unity-explorer/pull/2718 PR) lost when implementing https://github.com/decentraland/unity-explorer/pull/3748 -> commit: https://github.com/decentraland/unity-explorer/pull/3881/commits/2b537b81d9089bad4d3dcd3733d6317c5ffe851a
1. Download the build from this PR and open it with the following …
=> fix: gltf collision layer update lost while loading (revisited)

Explorer/Assets/DCL/Chat/ChatMemberListView.cs, Explorer/Assets/DCL/ExplorePanel/Assets/ExplorePanelUI.prefab, Explorer/Assets/DCL/Friends/DCL.Friends.asmdef, Explorer/Assets/DCL/Friends/UI/FriendPanel/Sections/FriendPanelSectionController.cs, Explorer/Assets/DCL/Friends/UI/FriendPanel/Sections/FriendPanelSectionDoubleCollectionController.cs, Explorer/Assets/DCL/InWorldCamera/PhotoDetail/PhotoDetail.asmdef, Explorer/Assets/DCL/InWorldCamera/PhotoDetail/PhotoDetailInfoController.cs, Explorer/Assets/DCL/InWorldCamera/PhotoDetail/PhotoDetailInfoView.cs, Explorer/Assets/DCL/InWorldCamera/PhotoDetail/Prefabs/PhotoDetailUI.prefab, Explorer/Assets/DCL/Navmap/Assets/Navmap.prefab, Explorer/Assets/DCL/Navmap/Assets/PlacesAndEventsPanel.prefab, Explorer/Assets/DCL/Navmap/EventInfoPanelController.cs, Explorer/Assets/DCL/Navmap/EventInfoPanelView.cs, Explorer/Assets/DCL/Navmap/PlaceInfoPanelController.cs, Explorer/Assets/DCL/Notifications/Notifications.asmdef, Explorer/Assets/DCL/Notifications/NotificationsMenu/NotificationsMenuController.cs, Explorer/Assets/DCL/UI/DropdownView.cs, Explorer/Assets/DCL/UI/UI.asmdef
Fixes #3884
Every scroll rect had its own scrolling speed, making it inconsistent across the whole client.
This PR uses a common extension method on every scroll rect that we currently have to set a scrolling speed based on the platform the client is running, making the feel consistent across the whole client.
Check that the following scrollable sections are feeling consistent and are usable (not too fast, not too slow):
1. All 3 friend panel sections
2. Photo detail of a reel
3. Events, place info, search results panels in the navmap
4. Notifications menu
5. All settings dropdowns
6. Chat member list
- The goal is to normalize all scrolling speeds for all scroll rects. If you find one that I missed, please report it …
=> fix: uniform scroll rects scrolling speeds

.github/workflows/build-unitycloud.yml, Explorer/.gitignore
- switched from GITHUB_EVENT_NAME env var to github.event_name expression
- more reliable across different workflow contexts (e.g. workflow_call)
- simplifies the logic and avoids edge cases with env parsing
=> fix: improve github event handling

Explorer/Assets/DCL/Character/CharacterCamera/Character Camera.prefab, Explorer/Assets/DCL/Character/CharacterMotion/Systems/InterpolateCharacterSystem.cs, Explorer/Assets/DCL/Chat/Commands/DCL.Chat.Commands.asmdef, Explorer/Assets/DCL/Chat/Commands/ReloadSceneChatCommand.cs, Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Profiling/ECS/DebugViewProfilingSystem.cs
Fix #3389
- add temporal component during scene reload, so character interpolation system is not executed and player doesn't fall
See mentioned above bug-ticket
=> Fix: player fall on scene reload 

Explorer/Assets/Scenes/Main.unity, Explorer/Assets/Scenes/Splash.prefab, Explorer/Assets/Scenes/Splash.prefab.meta
Fix #3939
This PR fixes a missing reference to the animator controller for the splash screen, it also makes it as a prefab instead of a scene object to reduce possible issues in the future like this one
1. Launch dcl
2. Verify that the animated dcl logo appears in the initial loading
=> fix: bring back dcl logo in initial loading

Explorer/Assets/DCL/ApplicationVersionGuard/ApplicationVersionGuard.asmdef, Explorer/Assets/DCL/ApplicationVersionGuard/ApplicationVersionGuard.cs, Explorer/Assets/DCL/InWorldCamera/CameraReelGallery/CameraReelGalleryController.cs, Explorer/Assets/DCL/InWorldCamera/CameraReelToast/CameraReelToast.asmdef, Explorer/Assets/DCL/InWorldCamera/CameraReelToast/CameraReelToastMessage.cs, Explorer/Assets/DCL/InWorldCamera/CameraReelToast/DownloadNotificationView.cs, Explorer/Assets/DCL/InWorldCamera/CameraReelToast/DownloadNotificationView.cs.meta, Explorer/Assets/DCL/InWorldCamera/CameraReelToast/Prefabs/CameraReelToastMessage.prefab, Explorer/Assets/DCL/InWorldCamera/PhotoDetail/PhotoDetailController.cs, Explorer/Assets/DCL/InWorldCamera/ReelActions/ReelCommonActions.cs, Explorer/Assets/DCL/Infrastructure/Utility/PlatformUtils.cs, Explorer/Assets/DCL/PluginSystem/Global/Global Plugins Settings.asset
This change has the "photo downloaded" notification say where the photo was downloaded to, and clicking it will now open your file browser to that folder. This fixes #3534.
Save a photo and click the notification.
=> Show where photo was saved

Explorer/Assets/DCL/Profiles/ProfileBuilder.cs
The profile wasn’t being published when only the `forceRender` property of a wearable was changed.
This happened because forceRender was being passed by reference. When the `ProfileBuilder` copied the profile using `builder.From(profile)`, it also copied the reference to forceRender. Later, during the build process, forceRender was modified, which unintentionally changed the original profile too.
As a result, the system couldn’t detect any changes (since it thought both profiles were the same), so it skipped publishing the updated profile to Catalyst.
1. Go to the backpack and wear some wearables that hide other categories
2. Quit the backpack and save the profile
3. Restart the client
4. Open the backpack and only change the force render property on any hidden wearable
5. Quit the …
=> fix: publish force render on profiles

Explorer/Assets/DCL/Chat/Commands/ChatTeleporter.cs
Fixes #3933 
During teleport from chat dont add `.dcl.eth` if the realm is considered an ens name, like: `your.world.eth`.
Use the `/goto` command from the chat to teleport to different realms:
- `/goto olavra`
- `/goto coffee.daohq.dappcraft.eth`
- `/goto https://peer.decentraland.org`
- `/goto olavra.dcl.eth`
=> fix: support ens names on teleport from chat

Explorer/Assets/DCL/Minimap/Assets/Minimap.prefab, Explorer/Assets/DCL/Minimap/Assets/SceneRestrictionText.prefab, Explorer/Assets/DCL/SceneRestrictionBusController/SceneRestriction/Assets/SceneRestrictionsToast.prefab, Explorer/Assets/Textures/Common/TwinArrows.png
This PR was created to update the mini map warning icon, which indicates the scene is restricting some features.
[This](https://www.figma.com/design/PXdXYmnNUOiMjyj8SaNkkQ/%F0%9F%97%BA%EF%B8%8F-Mini-map-%7C-Explorer-2.0-%7C-10-24?node-id=1-1209&t=8YP2LC3B2LiW5elY-1) is the new look and feel of the icon and the tooltip.
1. Launch the Explorer.
2. Go to a scene where there is a feature restriction, as for example the MVFW runway when you enter the cinema mode.
3. Check the yellow warning icon in the mini map is now a white info icon. 
4. Click the icon to open the tooltip and check its title color is white instead of yellow, and that the bullet points text style are regular instead of semi-bold.
=> style: replace scene restriction warning icon for an info icon in the mini map

Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/Play/CharacterEmoteSystem.cs, Explorer/Assets/DCL/Multiplayer/Emotes/MultiplayerEmotesMessageBus.cs
Fixes #3745 
When a user is emoting and they got blocked, the blocking user is still able to see the emote props (if it had any).
This PR stops the remote emote for blocked players if they were emoting while the user blocked them. By doing so, the props disappear.
It also clears the `MultiplayerEmotesMessageBus.messageDeduplication` in order to be able to play a remote emote if the blocked user gets unblocked while emoting.
- This is easily tested if you can control 2 avatars A and B
1. Place A and B in the same place
2. Start a looping emote with props with both A and B
3. From A, block B
4. Verify that A can't see B and their emote props (the same applies from B to A)
5. From A, unblock B
6. Verify that A can see B and that shortly after, the emote starts playing as normal (the same …
=> fix: stop remote emote on player blocked

Explorer/Assets/DCL/Chat/Commands/LogsChatCommand.cs, Explorer/Assets/DCL/Chat/Commands/LogsChatCommand.cs.meta, Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs
This adds a /logs chat command that will open the logs folder. Depending on the platform / run type (build or editor) it opens one of these folders:
```
WindowsPlayer => @"file://%USERPROFILE%\AppData\LocalLow\Decentraland\Explorer\",
WindowsEditor => @"file://%LOCALAPPDATA%\Unity\Editor\",
OSXPlayer => "file://~/Library/Logs/Decentraland/Explorer/",
OSXEditor => "file://~/Library/Logs/Unity/",
```
Type in /logs and check if the right folder with the log file is opened on both platforms.
=> feat: add logs chat command

Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs, Explorer/Assets/DCL/Infrastructure/MVC/ViewDependencies/ViewDependencies.cs, Explorer/Assets/DCL/PluginSystem/Global/ExplorePanelPlugin.cs, Explorer/Assets/DCL/PluginSystem/Global/PassportPlugin.cs, Explorer/Assets/DCL/PluginSystem/Global/SidebarPlugin.cs, Explorer/Assets/DCL/Profiles/IProfileChangesBus.cs, Explorer/Assets/DCL/Profiles/IProfileChangesBus.cs.meta, Explorer/Assets/DCL/Profiles/ProfileChangesBusController.cs, Explorer/Assets/DCL/Profiles/ProfileChangesBusController.cs.meta, Explorer/Assets/DCL/UI/Profiles/Names/ProfileNameEditorController.cs, Explorer/Assets/DCL/UI/Profiles/ProfileElements/ProfileWidgetController.cs
Fixes #3776 
When a profile name change is performed, it is not reflected in the widgets (explore panel and sidebar) with the new name and color.
This PR creates a new `Action` in the name editor controller that is invoked when the profile is updated. Through the `ViewDependencies` object this is propagated to `ProfileWidgetController` so that it can update `ProfilePictureView` accordingly.
1. Follow the repro steps of the issue verifying that the widgets get updated (both in the explore panel and the sidebar)
=> fix: update profile widgets on profile name change

Explorer/Assets/StreamingAssets/Js/Modules/Runtime.js
Fixes #3048
Exports the `GetExplorerInformation` function so the client can return the unity values
1. Create a local test scene with a debug log of the new export. Something like 
```
console.log("LOG  " + (await getExplorerInformation({})).agent)
console.log("LOG  2 " + (await getExplorerInformation({})).platform)
```
You should see
```
LOG `unity-explorer`
LOG 2 `desktop`
```
=> feat: GetExplorerInformation export

Explorer/Assets/DCL/UI/Profiles/Names/Assets/ProfileNameEditor.prefab
Fix #3992 
Sets a maximum length in the name editor input box to limit the character name length to 15
1. Open 0.65
2. Go to your profile
3. Click on the pencil
4. Edit your name to non-unique username
5. Start writing different letters and verify the input stops at 15 characters
=> fix: fixed character name max characters in name editor

Explorer/Assets/DCL/Navmap/ScriptableObjects/MapCategoryIconMapping.asset
Fix #3869 
Added missing reference to crypto and music categories in navmap navigation
2. Open the map.
3. Click the categories 'Crypto' and 'Music' and verify that in the search section the icons appear correctly
=> fix: fixed missing category icon in map navigation

Explorer/Assets/DCL/Notifications/NotificationsMenu/NotificationsMenuController.cs
Fix #3925
Fixed the background of notifications of incoming rewards, before it was white, now it matches the rarity of the incoming item
1. Log in
2. Check the notifications
3. Verify that all notifications related to wearables display the background with the rarity color, unlike before that only white backgrounds were displayed
=> fix: fixed background of notifications for reward incoming

Explorer/Assets/DCL/Chat/ChatEntryMessageBubbleElement.cs
Fixes #3958
Due to `TMP_Text.GetPreferredValues()` some chat message backdrop entries appeared to be shorter than the message because of the calculation of the width in relation to the user name length.
This PR makes sure that the calculated width in always >= then the calculate username length so that no message will have the backdrop shorter then the username text, as seen in the issue.
1. Type messages of various lengths and characters (some letters need more width than others) and verify that no chat bubble appears cropped
- The issue can be replicated on a different branch by changing name into the unclaimed name `MommaCuddelz` and typing the message `love the fit crow` as shown in the issue. An even worse example is to type `iiiiiiiiiiiiiiiii`
- The issue can be replicated …
=> fix: make sure minimum chat bubbles width is name length to avoid cutoffs

Explorer/Assets/DCL/PerformanceAndDiagnostics/DebugUtilities/DebugUtilitiesContainer.cs
Fixes #4017
The "Current scene" debug section is only exposed if the full debug mode is enabled (running the E@ with `--debug` flag).
This PR enables the section in the normal debug panel (activated in-game with `/debug`).
1. Run the E@ normally
2. Verify that the "Current scene" section is present and working
=> fix: expose "current scene" in normal debug container

Explorer/Assets/DCL/Rendering/GPUInstancing/GPUInstancingService.cs
Fix #3871
Changed from isFocused check to willRender
See related bug ticket. 
Additionally compare with prod this behaviour:
1. Run app
2. Make application out of focus and fully covered by some other app or folder. 
3. Leave it like that for several minutes.
4. Bring DCL explorer application back to the focus
5. DCL explorer app should start running smooth, without big initial app switch freeze and/or crash
=> Fix: street assets disappear when explorer loses focus

Explorer/Assets/DCL/Landscape/Worlds/WorldTerrainGenerator.cs
Fixes the crash we had when the app (build) was exited.
fixes #3985
Removes the destroy call - it's not needed since this only runs on exit.
1. Launch Explorer
2. Wait for 10 minutes
3. Quit Explorer
4. There should be no crash popup on either platform.
=> fix: don't destroy terrain root go on dispose

Explorer/Assets/DCL/Chat/Commands/LogsChatCommand.cs
Fix opening the log folder in mac
1. In Mac, do `/logs` and confirm it opens the log folder
=> Fix: Mac logs

Explorer/Assets/DCL/Chat/MessageBus/CommandsHandleChatMessageBus.cs
Fix #3159 
It allows to put an space after a comma in a chat command. For example: `/goto 10, 10`.
Before this change, if we did put the coordinates with a space after the comma, we received the next error:
1. Type `/goto 10, 10` on the chat field (make sure you introduce a space after the comma)
2. Check that the teleport is done correctly.
3. Check that the rest of chat commands work correctly as before.
=> fix: allow space after a comma in the chat commands

Explorer/Assets/DCL/Backpack/Assets/Backpack.prefab, Explorer/Assets/DCL/Backpack/Backpack.asmdef, Explorer/Assets/DCL/Backpack/BackpackGridController.cs, Explorer/Assets/DCL/Backpack/BackpackGridView.cs, Explorer/Assets/DCL/Backpack/EmotesSection/BackpackEmoteGridController.cs, Explorer/Assets/DCL/PluginSystem/Global/BackpackSubPlugin.cs, Explorer/Assets/DCL/PluginSystem/Global/ExplorePanelPlugin.cs
Fix #3362 
When we did a search without matches or clicking an empty category in the backpack, the link to market place didn't exist to redirect the user to the marketplace webpage. Now it redirects to the marketplace.
1. Launch the client
2. Open the backpack and click an empty category. Then try to click the marketplace link.
3. Try to look for an item you don't have in your backpack. Try to click the marketplace link from the empty state message.
4. Check that the marketplace website opens.
=> fix: Marketplace button in Backpack  is not interactive

Explorer/Assets/DCL/Infrastructure/Global/Dynamic/RealmController.cs, Explorer/Assets/DCL/RealmNavigation/Container/RealmContainer.cs
Fix #2675 
Before this change, if an invalid realm app parameter was used, the application remained in a pre-authentication screen state forever:
Now, if this happens, we redirect the user to Genesis City.
1. Execute the build with a wrong `realm` parameter, for example: `decentraland://?realm=sadfsfds`.
2. Check that, instead of remaining in an infinite loading, the app redirects you to Genesis City (it's probably that it request you to authenticate your wallet before).
=> fix: Redirect to Genesis City if the app is initialized with a wrong realm

Explorer/Assets/DCL/MarketplaceCredits/Assets/Fields/MarketplaceCreditsTotalCreditsWidget.prefab, Explorer/Assets/DCL/MarketplaceCredits/Assets/Sections/MarketplaceCredits_ProgramEndedSection.prefab, Explorer/Assets/DCL/MarketplaceCredits/MarketplaceCreditsUtils.cs
PR created to update a couple of texts in the UI. 
**Fix 1**
- The `S` letter was removed from the word `Expires`.
**Fix 2**
- The final dates were added to the modal indicating that the program has closed. Before we weren't showing any.
2. Open the marketplace credits panel. If you have credits in your balance, check that the word `Expires` doesn't have the `S` at the end anymore.
3. Fix 2 won't be possible to text in the build as this requires the program to get closed, but can be confirmed by checking the prefab in Unity.
=> style: credits copy updates

Explorer/Assets/DCL/Notifications/Serialization/NotificationJsonDtoConverter.cs, Explorer/Assets/DCL/NotificationsBusController/NotificationTypes/NotificationType.cs, Explorer/Assets/DCL/NotificationsBusController/NotificationTypes/StreamingFeatureNotification.cs, Explorer/Assets/DCL/NotificationsBusController/NotificationTypes/StreamingFeatureNotification.cs.meta
Processes new notification types that came with `Streaming Feature`
1. Enter your scene
2. Start/Stop/Reset the streaming key to get corresponding notifications on the top of your screen
- Icon is not supported on backend side yet
- [+] Changes have been tested locally
=> feat: streaming feature notifications support

Explorer/Assets/DCL/SDKComponents/AudioSources/AudioSourceExtensions.cs, Explorer/Assets/DCL/SDKComponents/AudioSources/Systems/UpdateAudioSourceSystem.cs
Fixes #4043 
An example code that should modify the audio volume without stopping it:
```
import { AudioSource, engine, Entity, PBAudioSource, Transform } from "@dcl/sdk/ecs";
let currentMusic: Entity | undefined;
let prevMusic: Entity | undefined;
let music1: Entity | undefined;
let music2: Entity | undefined;
const music1Url = "assets/scene/Audio/any_audio.mp3";
const music2Url = "assets/scene/Audio/other_adio.mp3";
export function setup() {
music1 = engine.addEntity();
Transform.create(music1, {
position: { x: 0, y: 0, z: 0 }
});
AudioSource.create(music1, {
audioClipUrl: music1Url,
playing: false,
loop: true,
volume: 1,
global: true
});
music2 = engine.addEntity();
Transform.create(music2, {
position: { x: 0, y: 0, z: 0 }
});
AudioSource.create(music2, {
audioClipUrl: music2Url, …
```
=> fix: dont stop the audio source on sdk update

Explorer/Assets/DCL/AvatarRendering/Wearables/Components/Wearable.cs, Explorer/Assets/DCL/Passport/Modules/EquippedItems_PassportModuleController.cs
Fix #2619 
The profile card was not displaying all items that the avatar had equipped. Hidden categories by another wearable that were proactively turned on were not visible.
1. Open your backpack and equip any wearable that hides another one.
2. Make sure the hidden wearable is not marked as "forced to render" (bottom right icon in the wearable slot), I mean it should be set as hidden.
3. Close the backpack and wait for the new set of wearables are applied to your avatar.
4. Open you passport and check that all your visible wearables are included in the "EQUIPPED ITEMS" section. The wearable(s) that were hidden by another wearable(s) shouldn't appear.
5. Open your backpack again and set any of the hidden wearables as "dorced to render" (bottom right icon in the wearable slot), I mean it …
=> fix: Passport doesn't display all equipped items

Explorer/Assets/DCL/PluginSystem/World/AvatarShapePlugin.cs, Explorer/Assets/DCL/SDKComponents/AvatarShape/Systems/AvatarShapeHandlerSystem.cs, Explorer/Assets/DCL/SDKComponents/AvatarShape/Tests/AvatarShapeHandlerSystemShould.cs
Fixes #4050 
During scene loading, the scene is positioned at `MordorConstants.SCENE_MORDOR_POSITION`.
The solution consists in resetting the avatar’s local transform values to maintain correct avatar positioning, even considering the current scene’s offset. In addition, `CharacterInterpolationMovementComponent` is removed, because it updates the wrongly calculated global position on every frame.
This ensures the avatar no longer wanders into Mordor unexpectedly — because, as we all know, one does not simply interpolate into Mordor.
You need a scene that creates an `AvatarShape` on the startup. For example:
```
import { AvatarShape, Entity, Transform, engine } from "@dcl/sdk/ecs";
export function main() {
const npc = engine.addEntity();
Transform.create(npc, {
position: { x: 7.82, y: 0, …
```
=> fix: scene avatars initial relative positioning

Explorer/Assets/DCL/Navmap/FilterPanel/NavmapFilterPanelController.cs, Explorer/Assets/DCL/Navmap/FilterPanel/NavmapFilterPanelView.cs, Explorer/Assets/DCL/Navmap/NavmapController.cs, Explorer/Assets/DCL/Navmap/SatelliteController.cs
Fix #3262 
It makes the navmap keeps the last filters' selection (live events, POIs, Quests Mini Games, People, Sat/Parcel View) when we open it after being closed, instead of resetting them and leave the filter's controls un-synched.
1. Open the map.
2. Observe that it's showing all the layers that are activated in the LAYERS filter.
3. Change the filter deactivating some layers.
4. Close the map and re-open it.
5. Check that it's showing only the layers that are activated and not showing the deactivated ones.
=> fix: Keep active map layers when the map is closed and re-opened again

Explorer/Assets/DCL/Friends/UI/FriendPanel/FriendsPanelController.cs
The friends panel wasn't being closed appropriately to let the shared space manager know.
The panel is now forced to close when the jump in button is pressed.
1. Open the Friends panel. Chat hides.
2. Look for a friend that is online and click on the Jump In button for that user. Your avatar teleports.
3. After teleporting, the Friends panel should be hidden and the chat should be visible.
=> Fix: Chat | Disappears completely after using Jump In from Online Friends panel (#3843)

Explorer/Assets/DCL/MarketplaceCredits/MarketplaceCreditsMenuController.cs
Fix #4102 
Modify the link for the info button in the Marketplace Credits panel.
**NEW LINK**: https://decentraland.org/blog/announcements/marketplace-credits-earn-weekly-rewards-to-power-up-your-look
1. Open the MC panel.
2. Click on the info button by the main title.
3. Check that it redirects you to: https://decentraland.org/blog/announcements/marketplace-credits-earn-weekly-rewards-to-power-up-your-look
4. In the welcome screen (when you're not still registered in the Program), the LEARN MORE link must also redirects to the same link.
=> fix: Modify the link for Marketplace Credits feature info

Explorer/Assets/DCL/Navmap/NavmapController.cs
Fix #3263 
When we select any location in the map, an info card opens. If the map was closed and reopened, the card remained visible. This fix makes it to be closed the card when reopening the map.
1. Open the Map.
2. Select any Scene on the map.
3. The card opens in the right side of the sscreen.
4. Close the Map with the card still open.
5. Reopen the Map.
6. Check that the card is closed.
=> fix: The scene card reamins visible after re-opening the navmap

Explorer/Assets/DCL/UI/Skybox/SkyboxMenuController.cs
Fix #3193 
When we moved the skybox bar to its max range we saw `24:00`, when the correct thing would be to see `23:59`.
This PR fix it and now the range is from `00:00` to `23:59`.
1. Open the Explorer.
2. Open the skybox panel from the sidebar.
3. Move the bar to the end of the range (right side of the bar).
4. Check that it says 23:59 instead of 00:00.
=> fix: Make the max range of the skybox time slider is 23:59 instead of 24:00

Explorer/Assets/DCL/MapRenderer/Addressables/MapLayerCategoryIconMapping.asset
Fix #3124 
When we selected the 'Favorites' category in the map, the pins were displayed as the default location pins:
Now, with this fix we are showing the expected heart design:
1. Open the map.
2. Select the 'Favorites' category from the filters.
3. Check that the pin's icon showed for this category is correct (a heart instead of the generic place one).
=> fix: Set the correct icon for favorites pins in the navmap

Explorer/Assets/DCL/InWorldCamera/PhotoDetail/Prefabs/VisiblePersonEntry.prefab
Fixes #4104
Deactivates the `maskable` option from the spinner image so that the right shader is applied in order to show the animation.
1. Open the photo details of a reel
2. Open the wearable list of a person
3. Verify that the loading spinner is spinning
- In current version the spinner is not spinning
=> fix: photo detail wearable list loading spinner not spinning

Explorer/Assets/DCL/InWorldCamera/InWorldCamera/Playground/ScreenRecorderTester.cs, Explorer/Assets/DCL/InWorldCamera/InWorldCamera/ScreenRecorder.cs, Explorer/Assets/DCL/InWorldCamera/InWorldCamera/Systems/CaptureScreenshotSystem.cs, Explorer/Assets/DCL/InWorldCamera/InWorldCamera/Systems/InWorldCameraPlugin.cs, Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs
Fixes #3715. 
The crash occured in Mac when using low resolutions. This resorts the code to avoid it, while keeping the roads visible
1. Go to a scene with roads
2. Take screenshots on all avialable resolutions. You shouldnt get the crash
3. Download the screenshots. They should all be 1920x1080. Screenshots from higher resolutions should have crisper images
=> fix: crash when taking screenshots on low resolutions

Explorer/Assets/DCL/Navmap/EventInfoPanelController.cs, Explorer/Assets/DCL/Navmap/SharePlacesAndEventsContextMenuController.cs
This PR updates the format of shareable links generated by the client to align with the new standard.
Old format:
https://play.decentraland.org/?position=143%2C-77&realm=main
New format:
https://decentraland.org/jump/?position=-142%2C87
All shared links from the client should now:
Use the https://decentraland.org/jump/ base URL
Point to the new landing experience (see screenshot below)
Examples:
1. Open the client
2. Go to map
3. Click the share option
=> chore: updated sharing urls to new format

Explorer/Assets/DCL/SDKComponents/MediaStream/LivekitPlayer.cs
Fix for the issue described in this ticket https://github.com/decentraland/unity-explorer/issues/4076
1. Go to your streaming scene, I should not see any stream
2. Launch your stream from OBS after you reach the scene
3. The stream should appear on the screen normally
- [+] Changes have been tested locally
- [+] Performance impact has been considered
=> fix: retry fetch the stream

Explorer/Assets/DCL/Infrastructure/MVC/ControllerBase.cs
Fixes #4122 
Fixes an NRE on trying to hide the profile menu when closing the explore menu. This only happened if you didnt open the profile menu at any time.
We were missing a null check on the hide operation in the `ControllerBase`
Simply open the explore menu and close it. Everything should work as expected.
Do a smoke test on other UIs too.
=> fix: profile menu nre

Explorer/Assets/DCL/AuthenticationScreenFlow/AuthenticationScreenController.cs
Fixes #4159 
Changes consists on handling the `SignatureExpiredException` provoked by the user not signing the login request after 5 minutes.
Start the authentication flow. When it asks for wallet confirmation, wait more than 5 minutes until the timer expires. You should be redirected to start the auth flow again.
=> fix: handle of SignatureExpiredException

Explorer/Assets/DCL/Character/CharacterMotion/Components/StopCharacterMotion.cs, Explorer/Assets/DCL/Character/CharacterMotion/Components/StopCharacterMotion.cs.meta, Explorer/Assets/DCL/Character/CharacterMotion/Systems/InterpolateCharacterSystem.cs, Explorer/Assets/DCL/Chat/Commands/DCL.Chat.Commands.asmdef, Explorer/Assets/DCL/Chat/Commands/ReloadSceneChatCommand.cs, Explorer/Assets/DCL/Infrastructure/ECS/SceneLifeCycle/ECSReloadScene.cs, Explorer/Assets/DCL/Infrastructure/ECS/SceneLifeCycle/LocalSceneDevelopment/LocalSceneDevelopmentController.cs, Explorer/Assets/DCL/Infrastructure/ECS/SceneLifeCycle/Systems/GatherGltfAssetsSystem.cs, Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs
Fixes #3972 
The client was not freezing the character movement while the scene is reloaded due to a change in the Creator Hub, provoking the character to fall and then get stuck through the colliders.
The changes consists in adding a new `StopCharacterMotion` component into the player's entity at `LocalSceneDevelopmentController` which triggers the moment on which the Creator Hub request a hot-reload of the scene.
This was not enough, since `IReloadScene.TryReloadSceneAsync` was not waiting until the new scene was loaded as a whole, but instead it was only waiting until the old scene was disposed. Now the scene is considered "reloaded" until its state is `Running` and all the GLTF are loaded.
This changes will introduce more waiting time on any change in the scene, until the user can …
=> fix: character stuck on scene hot-reload at LSD mode

Explorer/Assets/DCL/UI/Profiles/ProfileElements/UserNameElementController.cs
Fixes #4161 
The exception occurs on the disposal of the main started from `MainSceneLoader`.
Removed the `warning.Hide` operation of the `UserNameElement` since seems to be unnecessary during application disposal.
Open the profile menu from the top left button of the side bar. Copy your wallet. Check that the toast shows as expected.
=> fix: nre on user name element disposal

Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandUrl.cs, Explorer/Assets/DCL/Browser/DecentralandUrls/DecentralandUrlsSource.cs, Explorer/Assets/DCL/MarketplaceCredits/Assets/Fields/MarketplaceCreditsCaptcha.prefab, Explorer/Assets/DCL/MarketplaceCredits/Assets/Fields/MarketplaceCreditsTotalCreditsWidget.prefab, Explorer/Assets/DCL/MarketplaceCredits/Assets/MarketplaceCreditsUnlockedPanel.prefab, Explorer/Assets/DCL/MarketplaceCredits/Assets/Sections/MarketplaceCredits_GoalsOfTheWeekSection.prefab, Explorer/Assets/DCL/MarketplaceCredits/Assets/Sections/MarketplaceCredits_ProgramEndedSection.prefab, Explorer/Assets/DCL/MarketplaceCredits/MarketplaceCreditsMenuController.cs, Explorer/Assets/DCL/MarketplaceCredits/MarketplaceCreditsUtils.cs, Explorer/Assets/DCL/MarketplaceCredits/Sections/MarketplaceCreditsGoalsOfTheWeekSubController.cs, Explorer/Assets/DCL/MarketplaceCredits/Sections/MarketplaceCreditsGoalsOfTheWeekSubView.cs, Explorer/Assets/DCL/MarketplaceCredits/Sections/MarketplaceCreditsProgramEndedSubController.cs, Explorer/Assets/DCL/MarketplaceCredits/Sections/MarketplaceCreditsWelcomeSubController.cs, Explorer/Assets/DCL/MarketplaceCreditsAPIService/ClaimCreditsResponse.cs, Explorer/Assets/DCL/MarketplaceCreditsAPIService/CreditsProgramProgressResponse.cs
Fix #4157 
- New UI screen for when all the credits have been emitted for the current week so the user will have to wait forn ext one.
- For the cases when, for any reason, we decide to pause the rewards program... instead of directly hiding the feature through the feature flag, we show a new UI screen indicating the user that it is paused.
- For the cases when the user has tried to solve the claiming credits captcha too many times, we will show a message indicating that the captcha is blocked so the user will need to wait 24h for trying again.
- Fix anchors in the Credits Rewards UI.
- Fix the alpha transparency of the rays in the Credits Rewards UI.
**NOTE**: The idea is to add these changes in the next release after **Marketplace Credits** feature has been put into production.
Please …
=> fix: [Marketplace Credits] Last minute security measures

Explorer/Assets/Locales/Localization Tables/SceneLoadingDefaultTips_en.asset
Fix #4196 
It updates the text "**COMING SOON**" by "**NOW LIVE!**" in the loading tip related to the Marketplace Credits feature.
1. Open the app.
2. Check that the tip "Marketplace Credits" in the loading screen's carrousel says "NOW LIVE!" instead of "COMING SOON".
=> fix: Update Marketplace Credits tip in the Loading Screen

Explorer/Assets/DCL/Chat/History/ChatHistorySerializer.cs, Explorer/Assets/DCL/Chat/History/ChatMessageFactory.cs, Explorer/Assets/DCL/Chat/History/DCL.Chat.History.asmdef, Explorer/Assets/DCL/Chat/History/csc.rsp, Explorer/Assets/DCL/Chat/History/csc.rsp.meta, Explorer/Assets/DCL/Chat/MessageBus/MultiplayerChatMessagesBus.cs, Explorer/Assets/DCL/Chat/MessageBus/SelfResendChatMessageBus.cs, Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs
Based on this pr: https://github.com/decentraland/unity-explorer/pull/4192
The approach has been updated to make chat message creation a synchronous function, ensuring immediate propagation and preserving the order of arrival.
In cases the profile is not in the cache, then the user name will be replaced by the `#userHash` being the last 4 numbers of the address.
You need to test chat messages in general. Either private conversations of nearby channel. Send and receive messages from different users. Check that you receive messages in the correct order. Also check that the username is always displayed correctly, and if by any case you receive just the #userHash, the next message should be fixed.
To check correct order of arrival, you can try spamming numbers: 1,2,3,4,5,...
Please review our …
=> fix: chat messages out of order

Explorer/Assets/DCL/Chat/ChatInputBoxElement.cs
Fixes #4183 
Previously, the input text was reset when the field was considered "deselected".
Clicking an emoji triggered this deselect event, causing the text to reset before the emoji was added.
This resulted in losing the previous input whenever an emoji was selected.
Now, the input text is preserved and no longer reset on deselection.
Add emojis in the chat. You should be able to add as many as you want, inside the character limit.
=> fix: add multiple emojis

Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/CreateMediaPlayerSystem.cs
Fixes #4181 
The client was considering the audio stream as global or spatial depending if the entity had a transform. Now that changed so we force all audio streams to be global.
We have an open discussion about how we can make audio streams configurable so they support both global and spatial. In the meantime we keep the behaviour as it was in the old client.
Download and run the scene attached into the issue. The audio stream should not change the volume depending on the distance to the player.
=> fix: global audio streams

.github/workflows/build-release-main-page.yml
When build-release-main-page.yml workflow fails, rerunning it creates a new tag, which  breaks the release process. To prevent this, we now check if the tag already exists before creating and pushing it.
=> fix: check if tag exists before adding a new one on create a release page workflow

Explorer/Assets/DCL/Chat/RPCChatPrivacyService.cs, Explorer/Assets/DCL/Friends/RPCFriendsService.cs, Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs, Explorer/Assets/DCL/PluginSystem/Global/ChatPlugin.cs, Explorer/Assets/DCL/PluginSystem/Global/FriendsPlugin.cs, Explorer/Assets/DCL/PluginSystem/Global/SocialServicesPlugin.cs, Explorer/Assets/DCL/SocialServices/RPCSocialServices.cs
This PR moves the initialization of the social service RPC in the dynamic world container and remove the object proxy that was previously used to pass it around.
This was a needed change to avoid the object proxy misuse and proper handling for the voice chat shape
1. Do a quick smoke test of friends functionality, it should all work as it used to before
=> chore: removed object proxy for social service rpc

Explorer/Assets/DCL/Backpack/BackpackEquipStatusController.cs, Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs, Explorer/Assets/DCL/Multiplayer/Profiles/BroadcastProfiles/EnsureSelfPublishedProfileBroadcast.cs, Explorer/Assets/DCL/PluginSystem/Global/BackpackSubPlugin.cs, Explorer/Assets/DCL/PluginSystem/Global/ExplorePanelPlugin.cs, Explorer/Assets/DCL/Profiles/Components/ProfileExtensions.cs, Explorer/Assets/DCL/Profiles/Components/ProfileExtensions.cs.meta, Explorer/Assets/DCL/Profiles/MemoryProfileRepository.cs, Explorer/Assets/DCL/Profiles/Repository/IProfileRepository.cs, Explorer/Assets/DCL/Profiles/Repository/LogProfileRepository.cs, Explorer/Assets/DCL/Profiles/Repository/RealmProfileRepository.cs, Explorer/Assets/DCL/Profiles/Self/ISelfProfile.cs, Explorer/Assets/DCL/Profiles/Self/Playground/SelfProfilePlayground.cs, Explorer/Assets/DCL/Profiles/Self/SelfProfile.cs, Explorer/Assets/DCL/UI/MainUIContainer/MainUIContainer.prefab, Explorer/Assets/DCL/UI/MainUIContainer/MainUIView.cs, Explorer/Assets/DCL/UI/Profiles/Names/InWorldSelfProfileDecorator.cs
Fixes #3984 
The issue was caused by a delay in saving the profile between closing the backpack and opening the emote wheel. During this gap, the profile data was outdated, resulting in outdated emotes being shown.
The solution updates the avatar’s in-world immediately, and performs a rollback if an error occurs, ensuring consistency with the catalyst.
Save the profile and open the wheel emote. You should always have your emotes updated.
=> fix: outdated avatar in-world

Explorer/Assets/DCL/Character/CharacterCamera/Character Camera.prefab
Brings back the nametags, since the camera layer was modified incorrectly
1. Check that the nametags are visible before and after pressing N
2. Walk around with other players and verify nametags
3. To confirm, check changing wearables (and maybe ask your friends the same) to see that you dont have the name udpate problem currently on dev
=> hotfix: name tag layer

Explorer/Assets/DCL/AvatarRendering/AvatarShape/Rendering/TextureArray/TextureArrayHandler.cs
This PR fixes road flicker and texture array size = 0 for scene LODs
1. Play
2. No road flicker and no "Texture is 2D array but arrayLength is 0 or less." and "UnityException: Failed to create 2D array texture because of invalid parameters." errors
=> fix: scene lod texture array zero size

Explorer/Assets/DCL/Chat/ChatConversationsToolbarView.cs
We thought that we fixed it, but we actually didnt. The component was null, so asking for the gameobejct was still giving a NRE.
1. Run at least 5 times DCL
2. Check that you dont get an exit crash
=> fix: NRE on exit for toolbar view

Explorer/Assets/DCL/NameTags/NametagView.cs, Explorer/Assets/DCL/NameTags/Systems/NametagPlacementSystem.cs
Brings back the correct usage of the verified icon
1. Get together some real users. Check that the verified icon is there for people with claimed names, and that it isnt for people without claimed names.
2. Instantiate some avatars from the debug panel. None of them should have a claimed named
3. Go to this location. Check that Skeeter does not have a verified icon
=> fix: bring back verified icon

Explorer/Assets/DCL/ApplicationVersionGuard/ApplicationVersionGuard.cs, Explorer/Assets/DCL/Browser/DecentralandUrls/IDecentralandUrlsSource.cs
This PR updates all launcher URLs to align with the release of the new launcher:
Windows and Apple Silicon Macs now use updated paths pointing to the new launcher.
Intel-based Macs continue to use the old launcher, as the new version does not support them.
If the launcher is not installed, the client will now default to a direct S3 bucket URL instead of the GitHub release page. This change improves download speed and consistency.
To trigger the popup us this command `".\Decentraland.exe" --simulateVersion 0.71.0-alpha`
- Launcher not installed → Clicking "Update now" should open a website with the correct download link for the user's platform.
- Launcher installed → Should open the launcher directly.
- Intel Mac → Should open the old launcher.
- Apple Silicon or Windows → Should open the …
=> fix: added support for new launcher in application version guard

Explorer/Assets/DCL/Chat/ChatConversationsToolbarView.cs, Explorer/Assets/DCL/Chat/ChatConversationsToolbarViewItem.cs
This PR fixed the issue If we received messages before we opened the chat we would not get DM indicator
1. Start Game 1 (Player 1) but don't open the chat, Start Game 2 (Player 2)
2. From Game 2 (Player 2) send direct message to Player 1
3. Notification is received in Game 1 in the chat panel that message is received
4. Open chat in Game 1
5. DM badge for Player 2 shows unread messages
=> fix: no dm indicator before we open the chat for the first time.

Explorer/Assets/DCL/ApplicationVersionGuard/ApplicationVersionGuard.cs, Explorer/Assets/DCL/Browser/DecentralandUrls/IDecentralandUrlsSource.cs, Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/AnalyticsConfiguration.asset, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/Playgrounds/AnalyticsConfiguration Playground.asset, Explorer/Assets/DCL/PluginSystem/Global/ChatPlugin.cs, Explorer/Assets/DCL/UI/MainUIContainer/MainUIController.cs
input missing after jump to player
When using the Jump In button from a friend's passport (accessed via the Friends tab), the chat panel disappears and the input box is not visible after teleporting.
NOTE: this is a workaround fix and here is the issue for the tech debt to be handled later:
https://github.com/decentraland/unity-explorer/pull/4317
This PR fixes missing chat input box after teleporting to friend
1. Play
2. Jump to friend through friend's passport
3. Observe that chat input box is there.
--
1. Play
2. Jump to friend through friend list
3. Observe that chat input box is there.
NOTE: this works for both teleport to parcel or load the world where friend is
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standa …
=> fix: input missing after jump to player

Explorer/Assets/DCL/Chat/ChatController.cs, Explorer/Assets/DCL/Chat/ChatView.cs, Explorer/Assets/DCL/Infrastructure/MVC/WindowsStackManager/WindowStackManager.cs
This PR refactors how the chat input’s Enter/Submit handler is registered and unregistered, ensuring that the chat only processes “Submit” events when it actually has focus. Previously, opening any other popup or screen could leave the chat’s handler active, causing unintended message submissions when players pressed Enter. Now, we explicitly unsubscribe before subscribing, and only attach the handler when the chat regains focus, preventing double registrations or stale subscriptions.
NOTE to developers:
- In WindowStackManager,  Blur() and Focus() are called inside PushPopup and PopPopup so that the chat can properly subscribe or unsubscribe from the OnSubmit event.
- To avoid redundant calls, we added guards around SubscribeToSubmitEvent() and UnsubscribeToSubmitEvent() so that each …
=> fix: prevent chat from capturing Enter when another screen’s input is submitted.

Explorer/Assets/DCL/Character/CharacterCamera/Character Camera.prefab
This reverts commit cbd34c960fbda9a2e72b279439798a5c240d4f36.
There has been reports of camera glitches around different areas of the world, specially on the onboarding scene and the falling tube at genesis plaza.
Test main scenes, camera should not move akwardly.
=> Revert "fix: 3rd person camera collider re-configuration (#4356)"

Explorer/Assets/DCL/AvatarRendering/Emotes/Components/Intents/GetEmotesByPointersIntention.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/FinalizeEmoteLoadingSystem.cs
Problem introduced recently by https://github.com/decentraland/unity-explorer/pull/3390 with Explorer `v0.72`.
When `GetEmotesByPointersIntention.Dispose()` is called we are now also [disposing of the CancellationTokenSource](https://github.com/decentraland/unity-explorer/blob/dev/Explorer/Assets/DCL/AvatarRendering/Emotes/Components/Intents/GetEmotesByPointersIntention.cs#L59~L60), the problem is that that token source is [shared among the related asset promises](https://github.com/decentraland/unity-explorer/blob/d5d7900ba2ae676964eccf856eed08c08bc483bb/Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/Load/LoadEmotesByPointersSystem.cs#L235).
So, when this sequence happens after the intention was disposed:
1. [FinalizeEmoteLoadingSystem:74](https://github.com/decentraland/unity-explore …
=> fix: emotes asset promise cancellation token disposed exception

Explorer/Assets/AddressableAssetsData/AssetGroups/Localization-Assets-English (en).asset, Explorer/Assets/DCL/SceneLoadingScreens/Textures/Smaller_Career_Quest_White.png, Explorer/Assets/DCL/SceneLoadingScreens/Textures/Smaller_Career_Quest_White.png.meta, Explorer/Assets/Locales/Localization Tables/SceneLoadingDefaultImages Shared Data.asset, Explorer/Assets/Locales/Localization Tables/SceneLoadingDefaultImages_en.asset, Explorer/Assets/Locales/Localization Tables/SceneLoadingDefaultTips Shared Data.asset, Explorer/Assets/Locales/Localization Tables/SceneLoadingDefaultTips_en.asset
Integrates the new loading screen for the Career Quest as designed here: https://www.figma.com/design/V9el6eF6PpxGrEAbO8Xgy4/Marketing-Brand-Images-DCL-2.0?node-id=2613-11&p=f
Start the app. Check that the loading screen images includes the new one, with title: Build your Future.
=> feat: integration of new career quest loading screen

Explorer/Assets/DCL/PluginSystem/World/MediaPlayerPlugin.cs, Explorer/Assets/DCL/PluginSystem/World/World Plugins Container.asset, Explorer/Assets/DCL/SDKComponents/AudioSources/Systems/UpdateAudioSourceSystem.cs, Explorer/Assets/DCL/SDKComponents/MediaStream/LivekitPlayer.cs, Explorer/Assets/DCL/SDKComponents/MediaStream/MediaPlayerExtensions.cs, Explorer/Assets/DCL/SDKComponents/MediaStream/MultiMediaPlayer.cs, Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/CreateMediaPlayerSystem.cs, Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerSystem.cs, Explorer/Assets/DCL/SDKComponents/MediaStream/Wrapper/MediaPlayerPluginWrapper.cs
This PR implements audio fade in/out for audio from LiveKit streams and MediaPlayer video/audio.
- extended logic to fade instead to set volume directly to the final value
Test on scenes with Video streams (like Game Night or `/goto 1,93`).
If possible, try to test it with the Live Streaming.
GIVEN player is on the SDK scene with Video stream or Live Stream
WHEN player step out of the scene by foot
THEN audio should slowly fade out (and not just be off/mute in one hit)
GIVEN player is near to the SDK scene with Video stream or Live Stream
WHEN player step in to the scene by foot
THEN audio should slowly fade in (and not just be on on full volume)
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md) before …
=> Feat: sdk scene video and streams fade in/out

Explorer/Assets/DCL/Character/CharacterMotion/Systems/TeleportCharacterSystem.cs
This is related to https://github.com/decentraland/unity-explorer/pull/4419
In case of load failure/cancelled we also restore the character collisions so we go back to the original state.
Teleport to different scenes. The character should collide normally within the scene.
=> fix: recover character collisions on load failure

Explorer/Assets/DCL/AvatarRendering/Emotes/Components/CharacterEmoteComponent.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/Play/CharacterEmoteSystem.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/Play/EmotePlayer.cs, Explorer/Assets/DCL/Infrastructure/CrdtEcsBridge/RestrictedActions/GlobalWorldActions.cs
Currently, sometimes when a scene emote that has props is played, the props may linger without being correctly disposed as displayed in https://github.com/decentraland/unity-explorer/issues/4405.
The bug is easily triggered by quickly triggering a scene emote with props while moving the avatar:
https://github.com/user-attachments/assets/ed49d76c-b35a-485c-a162-ee1e2e0a4253
Fixes Issue: https://github.com/decentraland/unity-explorer/issues/4405
* Corrected how `CharacterEmoteIntent` is updated in the entity when playing scene emotes
* Added a needed animator triggers cleanup when triggering play/stop of emotes to avoid observed conflicts of having both "EMOTE_STOP" and "EMOTE_RESET" triggers at the same time in the Animator...
1. Download the build from this PR
2. Enter the world …
=> fix: scene emote props sometimes not disposing

Explorer/Assets/DCL/AvatarRendering/Emotes/Helpers/MemoryEmotesStorage.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Tests/FinalizeEmoteLoadingSystemShould.cs, Explorer/Assets/DCL/AvatarRendering/Loading/IAvatarElementStorage.cs, Explorer/Assets/DCL/AvatarRendering/Wearables/Helpers/WearableStorage.cs, Explorer/Assets/DCL/Backpack/BackpackEquipStatusController.cs, Explorer/Assets/DCL/InWorldCamera/InWorldCamera/Playground/ScreenRecorderTester.cs, Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs, Explorer/Assets/DCL/Multiplayer/Connections/Demo/ArchipelagoFakeIdentityCache.cs, Explorer/Assets/DCL/Multiplayer/SDK/Tests/AvatarEmoteCommandPropagationSystemShould.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportsHandlingSettingsDevelopment.asset, Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportsHandlingSettingsProduction.asset, Explorer/Assets/DCL/Profiles/DataModels/ProfileJsonDto.cs, Explorer/Assets/DCL/Profiles/Self/ISelfProfile.cs, Explorer/Assets/DCL/Profiles/Self/Playground/SelfProfilePlayground.cs, Explorer/Assets/DCL/Profiles/Self/SelfProfile.cs, Explorer/Assets/DCL/Web3/Identities/IWeb3IdentityCache.cs, Explorer/Assets/DCL/Web3/Identities/LogWeb3IdentityCache.cs
Fixes #4413 
Three different problems were found in the process:
- If you rapidly logout after you update the profile from the backpack, you got an inconsistent profile state because it was invalid/cleared from the pool while the operation was being processed, provoking an internal exception.
- The `OwnProfile` of the `SelfProfile` needed to be invalidated on account switch, otherwise we might end up caching the profile from the previous account.
- The owned nft registry at the `WearableStorage` & `EmoteStorage` needed to be invalidated on account switch. We were trying to publish the owned `itemId` (last part of the urn chunks) of the wearable from the previous account if your new account had the same wearables.
Save the profile through the backpack. Change accounts. The avatar should …
=> fix: profile update fails on identity change

Explorer/Assets/Locales/Localization Tables/SceneLoadingDefaultTips_en.asset
Changes the game night loading screen text to:
```
Decentraland Game Night kicks off June 19 with 24 hours of fast, social, chaotic fun. Squad up or go solo in micro-games made for mayhem, from high-speed races to logic puzzles.
```
Check that the game night loading screen has the text fixed.
=> fix: game night loading screen text

Explorer/Assets/DCL/InWorldCamera/InWorldCamera/Playground/ScreenRecorderTester.cs, Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs, Explorer/Assets/DCL/Multiplayer/Connections/Demo/ArchipelagoFakeIdentityCache.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportsHandlingSettingsDevelopment.asset, Explorer/Assets/DCL/PerformanceAndDiagnostics/Diagnostics/ReportsHandling/ReportsHandlingSettingsProduction.asset, Explorer/Assets/DCL/Profiles/DataModels/ProfileJsonDto.cs, Explorer/Assets/DCL/Profiles/Self/Playground/SelfProfilePlayground.cs, Explorer/Assets/DCL/Profiles/Self/SelfProfile.cs, Explorer/Assets/DCL/Web3/Identities/IWeb3IdentityCache.cs, Explorer/Assets/DCL/Web3/Identities/LogWeb3IdentityCache.cs
Revert some changes introduced here: https://github.com/decentraland/unity-explorer/pull/4428
Logs were added for test purposes but we need to remove them.
Just do a smoke test, specially by saving the avatar. Nothing should be affected.
=> fix: remove logs during save profile process

Explorer/Assets/DCL/Passport/Prefabs/Passport.prefab, Explorer/Assets/Textures/Common/Container12FlareGradient.png.meta, Explorer/Assets/Textures/Common/CopyIcn.png
This PR was created to enhance the distinction between the [Add Friend] button and the [Block/Unblock] button on the profile card.
This issue became more noticeable with the upcoming Communities feature, where in the members list of a community, the [Add Friend] and [Block] buttons coexist in the same space, and the distinction between them, both in color and iconography, is barely visible.
BEFORE
AFTER
1. Launch the Explorer.
2. Open the profile card of a blocked user. Validate the blocked/unblock buttons style is the latest one.
=> style: update profile card block-unblock buttons 

Explorer/Assets/DCL/RealmNavigation/DCL.RealmNavigation.asmdef, Explorer/Assets/DCL/RealmNavigation/TeleportOperations/MoveToParcelInSameRealmTeleportOperation.cs, Explorer/Assets/DCL/RealmNavigation/TeleportOperations/TeleportToSpawnPointOperationBase.cs
Fixes #4470 & #1825 
The issue #1825 is a consequence of the scene not compiling at javascript level. Nothing we can do from the client, the creator needs to fix it.
The solution consists on stopping the propagation of `ScriptEngineException` generated by the load of the scene during the teleportation process. Now we teleport the player normally, even if the scene has compilation issues.
Teleport to -35,128 by typing `/goto` or setting the start position as an app arg `--position 35,-128`. Check that you are teleported correctly, even if the scene doesn't load.
Teleport to a world and then perform a `/goto -35,128`. You should be teleported to the location.
Please review our [Code Review Standards](https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md) …
=> fix: prevent javascript error propagation during teleport process

Explorer/Assets/DCL/Infrastructure/Global/Dynamic/MainSceneLoader.cs
This disables the version update check if the debug flag is present or the build is a development build.
Ensure version update is still triggered in a normal run, and not triggered when using the debug flag.
1. Launch explorer
2. Make sure version block is shown
3. Launch explorer with debug flag
4. Make sure version block is not shown
5. Launch explorer without debug flag but with skip-version-check
6. Make sure version block is not shown
=> fix: disable version update check when a debug flag is present

Explorer/Assets/DCL/Infrastructure/SceneRuntime/Apis/Modules/CommsApi/CommsApiWrap.cs, Explorer/Assets/DCL/Infrastructure/SceneRuntime/Apis/Modules/Players/PlayersWrap.cs, Explorer/Assets/DCL/Multiplayer/Connections/RoomHubs/RoomHub.cs, Explorer/Assets/DCL/Multiplayer/Profiles/RemoveIntentions/RemoveIntention.cs, Explorer/Assets/DCL/Multiplayer/Profiles/RemoveIntentions/ThreadSafeRemoveIntentions.cs, Explorer/Assets/DCL/SDKComponents/MediaStream/LivekitPlayer.cs
Fixes #3796 
The root of the problem seems to be the threading concurrency. The participant list gets modified by another thread while its being iterated, even tho we do have a mutex.
The changes introduces a thread lock on `root.Participants` during the iteration process. Does it fix the issue? Cant tell 100%, since i was not able to reproduce it. As an alternative solution i though about making a copy of the participant list, but we could also have the same issue while its being copied through every element.
Additionally a minor performance improvement has been made so the `RemoveIntention` can be properly compared in the `HashSet`.
Jump in world into crowded places. Check in the logs you don't have the exception. Check that players are disconnected properly.
Please review our [Code …
=> fix: participants collection modified while iterating

Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs, Explorer/Assets/DCL/MarketplaceCredits/MarketplaceCredits.asmdef, Explorer/Assets/DCL/MarketplaceCredits/MarketplaceCreditsMenuController.cs, Explorer/Assets/DCL/MarketplaceCredits/Sections/MarketplaceCreditsWelcomeSubController.cs, Explorer/Assets/DCL/PluginSystem/Global/MarketplaceCreditsPlugin.cs
Fix #4540 
In order to boost the users participation in the **Marketplace Credits** program and give it more visibility, this PR makes the main panel to be opened by default when the users that didn't start the program enter the world (without counting the tutorial stage).
1. Enter Decentraland with an already existing user (a wallet that already did the onboarding tutorial in the past) that never started the Marketplace Program.
2. Wait for the loading screen finishes.
3. Once your avatar appears in the world, check that the Marketplace Credits panel is opened automatically.
1. Enter Decentraland with an already existing user (a wallet that already did the onboarding tutorial in the past) that already started the Marketplace Program.
2. Wait for the loading screen finishes.
3. Once your …
=> hotfix: Open Marketplace Credits panel by default for users that didn't start the program

Explorer/Assets/Editor/CloudBuild.cs
Add csc.rsp generation for Unity Cloud Build warning suppression
This PR introduces a function to generate a `csc.rsp` file that suppresses specific compiler warnings during Unity Cloud Build processes. The file is only generated and used in cloud build environments to prevent build failures from non-critical warnings.
- Added `GenerateIgnoreWarningsFile()` function to create `csc.rsp` in Assets root
- Configured suppression for common nullable reference type warnings (8618, 8625, 8602, etc.)
- Included suppression for unused variable/field warnings (0649, 0414, 0168, 0219)
- Added error handling and logging for successful/failed file generation
Too many unnessecary Unity Cloud Build warnings can clutter our ability to diagnose any failures quickly, this was mainly introduced after we …
=> fix: ignore warnings in build only

Explorer/Assets/DCL/UI/ImageController.cs, Explorer/Assets/DCL/UI/ImageView.cs, Explorer/Assets/DCL/UI/SpriteCache.cs
Fixes #4603 
Fixes #4604 
This PR destroys all cached sprites contained by `SpriteCache` when `Clear` method is invoked in order to really free the memory (the instances of the sprites could be referenced by pooled/inactive objects).
It also adds a fade in animation on the `ImageView`/`ImageController` so that the previous contained image is hidden, while also improving the UX.
- launch the explorer in `zone` with the args `--dclenv zone`
1. Verify that all communities images are loading correctly
- community profile image
- events
- places
- event info panel
=> Shape: destroy cached sprite on clear and remove previous image while loading

.github/workflows/build-unitycloud.yml, scripts/cloudbuild/build.py
- Lowered the number of retry attempts in the workflow from three to two.
- Adjusted the retry logic so it now only kicks in when the script specifically exits with code 99, rather than retrying on any type of failure.
- Updated the Python script to use exit code 99 for certain HTTP-related errors, so those cases are the only ones that get retried automatically.
=> chore: adjust retry logic for unity build workflow

Explorer/Assets/DCL/Communities/CommunityCreation/CommunityCreationEditionView.cs, Explorer/Assets/DCL/Communities/CommunityCreation/Prefabs/CommunityCreationWizard.prefab
Fix #4655 
Pictures with transparent background can overlap the load image icon in community creation.
Follow the steps described here: https://github.com/decentraland/unity-explorer/issues/4655
=> [SHAPE-UP] Communities Fix (Pictures with transparent background can overlap the load image icon in community creation)

Explorer/Assets/DCL/Chat/ChatController.cs, Explorer/Assets/DCL/Chat/ChatControllerMemberListHelper.cs, Explorer/Assets/DCL/Chat/ChatUserStateUpdater.cs, Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesBrowserController.cs, Explorer/Assets/DCL/Communities/CommunitiesCard/CommunityCardController.cs, Explorer/Assets/DCL/Communities/CommunitiesCard/CommunityCardView.cs, Explorer/Assets/DCL/Communities/CommunitiesCard/Events/EventListController.cs, Explorer/Assets/DCL/Communities/CommunitiesCard/Members/MembersListController.cs, Explorer/Assets/DCL/Communities/CommunitiesCard/Members/MembersListView.cs, Explorer/Assets/DCL/Communities/CommunitiesCard/Places/PlacesSectionController.cs, Explorer/Assets/DCL/Communities/CommunitiesCard/Places/PlacesSectionView.cs, Explorer/Assets/DCL/Communities/CommunityCreation/CommunityCreationEditionController.cs
Fix #4643 
It manages, after each call to `SuppressToResultAsync`, the corresponding cancellation correctly.
- Check the Communities feature works as before.
- Specific test: Try to switch between the "Communities" tab and the "Map" one (like it's desceribed in https://github.com/decentraland/unity-explorer/issues/4643) and check that the communities load correctly and you don't see any error message.
=> [SHAPE-UP] Communities (Manage cancellations properly)

Explorer/Assets/DCL/SDKComponents/CameraControl/CameraModeArea/Systems/CameraModeAreaHandlerSystem.cs
Fixes #4346 
When the camera mode area was destroyed, it was considered as the played exited the area, but the player didn't enter in the first place.
The solution consists to only consider the player exit the area when it was active before.
Follow issue steps. Check the camera mode is not changed automatically while walking around the place.
=> fix: finalize area camera mode only if it was active before

Explorer/Assets/DCL/Communities/CommunityCreation/CommunityCreationEditionController.cs, Explorer/Assets/DCL/PluginSystem/Global/CommunitiesPlugin.cs
Fix #4587 
It makes the Community Profile Card opens right after we create the new community.
1. Create a new community.
2. Check that, right after the creation wizard closes, the community's profile card opens.
=> [SHAPE-UP] Communities (Open community card after creation)

.github/workflows/enforce-group-approvals.yml
This PR updates the `Enforce QA and DEV Approvals` workflow to allow skipping QA approval when the "no QA needed" label is applied to a pull request.
Changes:
- If the label "no QA needed" is present on the PR, QA approval is skipped.
- DEV approval is still always required.
This allows more flexibility for non-functional or low-risk PRs (e.g. documentation, CI changes) where QA review isn't necessary, reducing review overhead and allowing for faster merging.
=> chore: skip enforce approval when no QA needed label present

.github/workflows/enforce-group-approvals.yml
- Updated the "Enforce QA and DEV Approvals" workflow to better handle cases where multiple runs overlap
- The job now displays all runs for the current commit and checks how many are still in progress before retrying
- If it finds more than one run in progress for the same SHA, it skips triggering a rerun to avoid GitHub CLI errors
=> fix: address concurrent retry case for enforce-approvals workflow

Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunityResultCardView.cs, Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/CommunityResultCard.prefab, Explorer/Assets/DCL/Communities/CommunitiesFeatureAccess.cs, Explorer/Assets/DCL/FeatureFlags/FeatureFlagsStrings.cs
Fix #4716 
We have added a new Feature Flag (`alfa-communities-members-counter`) to show / hide the number of members of a community in the community browser.
1. Make sure the feature flag `alfa-communities-members-counter` is currently deactivated.
2. Open the build (in zone).
3. Open the Communities Browser.
4. Check that there is no members counter in any card.
5. Close the build.
6. Make sure the feature flag `alfa-communities-members-counter` is currently activated.
7. Open the build (in zone).
8. Open the Communities Browser.
9. Check that there is a members counter in each card.
=> [Communities Polishing] Show/Hide members counter in the Community Result Card (under new Feature Flag)

Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunityResultCardView.cs, Explorer/Assets/DCL/Communities/CommunitiesDataProvider/DTOs/GetUserCommunitiesResponse.cs
Rename "isVerified" by "hasClaimedName" in GetUserCommunitiesResponse DTO.
=> fix: [Communities Polishing] Rename "isVerified" by "hasClaimedName" in GetUserCommunitiesResponse DTO

Explorer/Assets/DCL/Minimap/Assets/Minimap.prefab, Explorer/Assets/DCL/Minimap/MinimapController.cs
This PR was created to solve the issues listed in [this](https://github.com/decentraland/unity-explorer/issues/4763) ticket, related to the recently added menu button within the mini map.
1. Launch the client.
2. Check that the container of the menu button matches with the collapse/expand button size.
3. Click the menu button, and validate the menu button container doesn't disappears in the different interactions with the button.
4. Once the menu is opened, validate its title says `Scene's Options` instead of `Minimap`. Disclaimer: our menus don't support titles, this is a temporary exception.
5. Check that the `Copy` icon has been replaced by a `Link` icon.
=> style: mini map menu

Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesBrowserView.cs, Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/CommunitiesBrowser.prefab, Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/CommunitiesBrowser_LeftSection.prefab, Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/CommunitiesBrowser_RightSection.prefab, Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/CommunityResultCard.prefab, Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/MyCommunityCard.prefab, Explorer/Assets/DCL/Communities/CommunitiesCard/CommunityCardController.cs, Explorer/Assets/DCL/Communities/CommunitiesCard/CommunityCardView.cs, Explorer/Assets/DCL/Communities/CommunitiesCard/Events/EventListView.cs, Explorer/Assets/DCL/Communities/CommunitiesCard/Members/MembersListView.cs, Explorer/Assets/DCL/Communities/CommunitiesCard/Places/PlacesSectionView.cs, Explorer/Assets/DCL/Communities/CommunitiesCard/Prefabs/CommunityCard.prefab, Explorer/Assets/DCL/Communities/CommunitiesCard/Prefabs/CommunityCardEvents.prefab, Explorer/Assets/DCL/Communities/CommunitiesCard/Prefabs/CommunityCardHeader.prefab, Explorer/Assets/DCL/Communities/CommunitiesCard/Prefabs/CommunityCardMembers.prefab, Explorer/Assets/DCL/Communities/CommunitiesCard/Prefabs/CommunityCardPlaces.prefab, Explorer/Assets/DCL/Communities/CommunitiesCard/Prefabs/EventItem.prefab, Explorer/Assets/DCL/ExplorePanel/Assets/ExplorePanelUI.prefab, Explorer/Assets/DCL/UI/Assets/ImageWithSkeletonAnimation.prefab, Explorer/Assets/DCL/UI/Assets/ImageWithSkeletonAnimation.prefab.meta, Explorer/Assets/DCL/UI/ImageController.cs, Explorer/Assets/DCL/UI/ImageView.cs, Explorer/Assets/DCL/UI/SkeletonLoadingView.cs, Explorer/Assets/DCL/UI/SkeletonLoadingView.cs.meta
Fixes #4585 
This PR introduces a new UI common script that lets you create skeleton loading animations by creating "skeleton" prefabs and animate their "bones".
This is applied throughout the whole communities UIs.
- connect to zone using the arg `--dclenv zone`
1. Open and fiddle around with all the communities UI to check the loading animations
=> Feat: community card skeleton loading

Explorer/Assets/DCL/SDKComponents/MediaStream/LivekitPlayer.cs, Explorer/Assets/DCL/SDKComponents/MediaStream/MediaPlayerExtensions.cs
Fixes #2294  #4759 
The volume was only changing on current scene if it was higher than the current set in the media player, but it was not considering if you lowered the volume through the settings.
The solution consists on removing the volume change conditions so it always applies to the given target volume.
Test the streaming volumes on mac and check that the settings applies.
=> fix: streaming volume change through settings on mac

Explorer/Assets/DCL/SDKComponents/SceneUI/Systems/UIFixPbPointerEventsSystem.cs
Fixes #4496 
For a reason i don't understand the issue was happening on build only.
If the `PBPointerEvents` was changing in runtime we were forcing the `PBUiTransform` to set the `pointerFilter: PointerFilterMode.PfmBlock` but we were not forcing the transform to re-update. The solution consists on setting the transform into `dirty:true` so the component is updated internally, applying the `pointerFilter` accordingly.
1. Download and run this scene: [button-pointer-filter.zip](https://github.com/user-attachments/files/21263175/button-pointer-filter.zip)
2. Open the developer console with key ` (left to number 1 key).
3. Click the button.
4. "Claim" log should appear whenever the button is enabled. The button is enabled and disabled every 3 seconds.
Ideally you should be able to verify …
=> fix: transform's pointer filter on pointer event changes

Explorer/Assets/DCL/Communities/CommunitiesCard/Prefabs/EventItem.prefab, Explorer/Assets/DCL/Communities/EventInfo/Prefabs/EventInfoPanel.prefab, Explorer/Assets/DCL/Communities/Textures/Gradient.png, Explorer/Assets/DCL/Communities/Textures/Gradient.png.meta
This PR updates the style of the `interested` and `share` buttons which appears in the events entries and event info panel. They used to had a white container with black content. Now they are a transparent white container with white content. This update has been done in order to make it match with the design guidelines of the explorer.
**NEW STYLE**
Connect to zone using the arg --dclenv zone
1. Launch the client.
2. Open the communities browser pressing `O`. Find and open the community 'Twin Peaks' which has events.
3. Hover the event entries. Check that the buttons have been updated.
4. Then click on any of the events entries to see their details. Check the buttons have been updated there too.
=> style: update interested button

Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/Play/CharacterEmoteSystem.cs
We had added an extra condition to avoid emotes looping during auth screen, but that also broke emotes looping in backpack.
Now that we removed looping emotes on auth screen, we can restore this logic.
Play any looping emote in the backpack. It should loop as expected.
=> Fix: Emotes not looping in backpack

Explorer/Assets/DCL/Infrastructure/Global/Dynamic/RealmLaunchSettings.cs, Explorer/Assets/DCL/Infrastructure/Global/Editor/RealmLaunchSettingsDrawer.cs
Adds a bool to be able to ignore the set of the start position via the feature flag in editor.
1. No QA required
=> fix: Ignore the position feature flag when in editor

.github/workflows/on-delete-release.yml, .github/workflows/s3-latest-release.yml
- used image amazon/aws-cli:latest was updated from Amazon Linux 2 to Amazon Linux 2023 , conflicting when trying to install curl
- curl install is not required anymore, so it was removed from all workflow steps
=> fix: remove manual curl install

Explorer/Assets/DCL/Communities/CommunitiesCard/Members/MembersListController.cs
This PR makes the clicking of a community member found in the member list, open the relative user passport.
- launch the explorer in zone using the arg `--dclenv zone`
1. Verify that clicking on a community member, opens their passport
=> feat: open user profile on community member entry click

Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/CommunitiesBrowser.prefab, Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/CommunitiesBrowser_RightSection.prefab, Explorer/Assets/DCL/Communities/CommunitiesCard/CommunityCardController.cs, Explorer/Assets/DCL/Communities/CommunitiesCard/Places/PlaceCardView.cs, Explorer/Assets/DCL/Communities/CommunitiesCard/Places/PlacesSectionController.cs, Explorer/Assets/DCL/Communities/CommunitiesCard/Places/PlacesSectionView.cs, Explorer/Assets/DCL/Communities/CommunitiesCard/Prefabs/CommunityCardEvents.prefab, Explorer/Assets/DCL/Communities/CommunitiesCard/Prefabs/CommunityCardPlaces.prefab, Explorer/Assets/DCL/Communities/CommunitiesCard/Prefabs/PlaceCard.prefab, Explorer/Assets/DCL/Communities/CommunityCreation/CommunityCreationEditionView.cs, Explorer/Assets/DCL/Communities/CommunityCreation/Prefabs/CreateOrEditCommunityPanel.prefab, Explorer/Assets/DCL/PluginSystem/Global/CommunitiesPlugin.cs, Explorer/Assets/DCL/UI/SkeletonLoadingView.cs
This PR fixes the community place card:
- subtext now contains the owner of the place
- the coordinates text no longer wraps
- added loading skeleton animation
- place thumbnail now adapts to the card
It also fixes the skeleton loading animation script because previously it was moving the UI elements in world coordinate rather than anchored positions leading to weird behaviours.
- launch the client in zone with the arg `--dclenv zone`
1. Open a community
2. Check that the place card thumbnail adapts to the card container
3. Check that it shows the scene owner
4. Check that the coordinates text never overflows/wraps
5. Verify that all skeleton animation behave as expected
WARNING: currently the events api have changed but the PR that addresses that is not yet merged: you will see errors …
=> Fix: community place thumbnails and loading animation

Explorer/Assets/DCL/ApplicationsGuards/ApplicationVersionGuard/ApplicationVersionGuard.cs, Explorer/Assets/DCL/Browser/DecentralandUrls/IDecentralandUrlsSource.cs
This PR updates the ApplicationVersionGuard to fetch the latest launcher version from the same source as launcher does instead of relying on the GitHub Releases API. This ensures consistency between the launcher and the client by using the same version source. 
To trigger the popup us this command ".\Decentraland.exe" --simulateVersion 0.71.0-alpha
There should not be any changes in the popup and it should show properly the version number.
=> fix: don't use github release page to check latest version

Explorer/Assets/DCL/Chat/Assets/Chat.prefab, Explorer/Assets/DCL/Friends/UI/Prefabs/FriendsPanel.prefab, Explorer/Assets/DCL/UI/MainUIContainer/MainUIContainer.prefab
This PR updates the friends and the chat panels in order to align them with the latest design updates. 
Changes where applied to the color/transparency of the background containers and the height of both panels.
Height is now 680px for both instead of 690 for friends and 640 for the chat. 
**BEFORE**
https://github.com/user-attachments/assets/dbe4c3f0-1518-488e-8572-3db276dd63fd
**AFTER**
https://github.com/user-attachments/assets/348c1e32-9236-4128-ba9e-1aaa807c8d3f
The chat toolbar is now transparent black instead of white.
Additionally, the title bar and the body containers of the friends panel are more transparent now making them match the with the chat. You may note the title bar of the chat is darker compared with friends in this PR, but that's okay as the update for the chat title …
=> style: update friends panel height

Explorer/Assets/DCL/Chat/ChatController.cs
It now checks that the current channel of the chat is a private conversation, before checking if a remote user is offline.
The bug: https://github.com/decentraland/unity-explorer/issues/4824
1. Enter DCL.
2. Click on the input box of the chat.
3. The input box must not show the mask that says that the user is offline.
4. Change to a conversation with a user that is offline. The mask shold appear.
5. Go to nearby again. The mask should disappear.
=> Fixed: Nearby chat appears with an offline warning (#4824)

Explorer/Assets/DCL/Communities/CommunitiesCard/Prefabs/CommunityCardEvents.prefab, Explorer/Assets/DCL/Communities/CommunitiesCard/Prefabs/CommunityCardMembers.prefab, Explorer/Assets/DCL/Communities/CommunitiesCard/Prefabs/CommunityCardPlaces.prefab
This PR fixes the scrolling parts of the community profile card: previously you could scroll up/down only while hovering elements. Now you can do that also while hovering on the background, making the scrolling experience "normal".
This is achieved by adding an empty transparent image inside the viewport of every scroll view.
1. Verify that you can scroll:
1. the member list
2. the place section
3. the photo section
4. the events section
all without hovering with the mouse on any scroll elements
- Both `org` and `zone` should have communities with enough elements in the scroll views
=> fix: fix scrolls in community card

Explorer/Assets/DCL/Communities/CommunitiesCard/Members/MembersListView.cs, Explorer/Assets/DCL/UI/GenericContextMenu/Controls/ControlsContainerView.cs, Explorer/Assets/DCL/UI/GenericContextMenu/GenericContextMenuController.cs, Explorer/Assets/DCL/UI/GenericContextMenu/Prefabs/ControlsContainer.prefab, Explorer/Assets/DCL/UI/GenericContextMenuParameter/GenericContextMenu.cs
This PR adds the support to show a border on the edge of the context menu container 
With the border:
Without the border:
- launch the client in zone with the arg `--dclenv zone`
1. Verify that context menus in general appear and work as before
2. Verify that the context menu on the member list of a community has the rim enabled and works as before
=> feat: add context menu container rim option

Explorer/Assets/DCL/Notifications/Assets/FriendsNotification.prefab, Explorer/Assets/DCL/UI/Communities/CommunityThumbnailView.prefab, Explorer/Assets/DCL/UI/Profiles/Assets/ProfilePictureView.prefab, Explorer/Assets/DCL/UI/Profiles/ProfileElements/ProfilePictureView.cs
This PR implements the skeleton loading animation in the `ProfilePictureView` prefab for the user thumbnail, hence propagating it everywhere.
This has been done for two main reasons:
1. it looks cooler and it was long due
2. the loading spinner (what was there before this PR) isn't maskable, therefore every floating hidden list containing profile picture views were rendering the spinners outside the boundaries as shown in the screenshot 
1. Just a smoke test confirming that profile pictures are working with the expected animation in all instances:
1. friend list
2. chat
3. communities
4. photo detail
5. passport (mutual friends)
6. friends notifications
7. ? (I may be missing other places)
- for testing in communities, you may want to connect to zone since there are many communities there …
=> feat: skeleton loading in profile picture view

Explorer/Assets/DCL/UI/Profiles/ProfileElements/ProfilePictureView.cs
Due to a race condition when the chat toolbar icons are initialized, the original color of its parts (image, background, etc.) used later when they are greyed out, were stored while the values were not correct.
Note: The bug happens randomly so you need to test it several times.
1. Open the chat (there should be several private conversations open, some of them offline).
2. Click on the icons of the toolbar. When clicking on each, the color of the background and the thumbnail should not change, and should be the expected one.
=> Fixed: When clicking on private chat toolbar icons their colors turn wrong

Explorer/Assets/DCL/Passport/Modules/Badges/BadgesDetails_PassportModuleController.cs, Explorer/Assets/DCL/Passport/PassportController.cs, Explorer/Assets/DCL/Passport/PassportView.cs, Explorer/Assets/DCL/Passport/Prefabs/Passport.prefab
Fix #3082 
Removed asynchronous code that was handling badge preview GameObject visibility causing the overlap of badges on top of avatar.
Cleaned up code in PassportView.cs that was handling passport sections visibility to prevent configuration problems.
Open passport and quickly switch between Badges tab and other tabs.
You should not see any overlapping betweeen the badge preview and avatar preview.
1. Open any passport
2. Switch to badges section and immediately switch to either overview or photos section
3. Verify that the badge preview and avatar preview do not appear together.
=> fix: Avoid badge and avatar overlap on passport

Explorer/Assets/DCL/AuthenticationScreenFlow/AuthenticationScreenCharacterPreviewController.cs, Explorer/Assets/DCL/Character/CharacterMotion/Components/HeadIKComponent.cs, Explorer/Assets/DCL/Character/CharacterMotion/Systems/HeadIKSystem.cs, Explorer/Assets/DCL/Character/CharacterPreview/CharacterPreviewController.cs, Explorer/Assets/DCL/PluginSystem/Global/CharacterMotionPlugin.cs
Fixes #4831 
The problem was the head IK. In the backpack, the avatar preview didnt have any head ik component and it was never initialized nor updated. By default has `weight:1`. This provoked a small offset in the avatar, which was noticeable on emotes with props.
The solution consists on adding the head IK component but only on backpack with `isEnabled:false`. This forces the ik to be updated with `weight:0`.
Check that the head IK works as expected:
- on authentication screen, check that the avatar's head follows the pointer.
- lock the mouse in-world and check that the avatar's head follows the target.
- open the backpack and check that the avatar's head does not follow the pointer. Also check that the emotes with props works correctly. …
=> fix: desync emotes with props on preview

Explorer/Assets/DCL/Prefs/FileDCLPlayerPrefs.cs
This fixes #4841, caused by saving the prefs at the same time that something was written to them, without locking.
All writes to userData are now locked, including the read while Saving, so we avoid changing the prefs while they are being serialized.
Verify that the game does not block / lag when the user changes their preferences / settings, and that everything is persisted as expected.
1. Login with a new account and verify it persists after relaunching explorer
2. Change settings (e.g. audio levels) and ensure they correctly persist.
=> fix: lock concurrent prefs writing

Explorer/Assets/DCL/Passport/PassportController.cs, Explorer/Assets/DCL/Passport/PassportView.cs
fix #4985 
Moved logic to handle character preview in PassportController.SetCharacterPreviewVisible, getting rid of the freezing and preventing reloading the preview when switching from PHOTOS to OVERVIEW (this was happening before).
Open the Passport and quickly switch to Badges section and then to either Overview or Photos. 
The avatar should always be animated and interactable when shown.
1. Open Passport
2. Switch to Badges section
3. Switch to Photos section
4. Make sure the avatar is animated and interactable
5. Repeat 1-2
6. Switch to Overview
7. Make sure the avatar is animated and interactable
=> fix: avatar freezes when switching tabs

Explorer/Assets/DCL/Chat/ChatController.cs, Explorer/Assets/DCL/Chat/ChatView.cs, Explorer/Assets/DCL/Chat/UserConnectivityInfoProvider.cs
It fixes this bug: https://github.com/decentraland/unity-explorer/issues/4990
The feature was not prepared for logging in an out, so several things were not being re-initialized when logging in again.
Additionally, another bug has been fixed: when a community conversation was hidden, incoming messages for that conversation were causing errors.
1. Log into DCL.
2. Check that you have some conversations in the toolbar (private and community's).
3. Log out.
4. Log in (with the same account).
5. Check that all conversations are there again.
=> Fixed: Logging in and out makes the community chats disappear (#4990)

Explorer/Assets/DCL/AvatarRendering/AvatarShape/Assets/Animator/CharacterAnimator.controller
Fixes #5047 
In the original issue, the test scene has the incorrect file naming for scene-emotes. They should end with `_emote.glb`.
Another problem: whenever a `PBAvatar` its instantiated with `expressionTriggerId: anims/scene_emote.glb` during local scene development mode, the emote was immediatelly cancelled because the updating of the animator state here: https://github.com/decentraland/unity-explorer/blob/b7246463cce5d9c4237937b944f4dc287e96474f/Explorer/Assets/DCL/Character/CharacterMotion/Systems/SDKAvatarShapesMotionSystem.cs#L137
`IsGrounded` param was initially `false` and then changed to `true` enabling the `Animator` again, and disabling the legacy `Animation` component on which the scene emote was running originally.
The solution consists on setting the `IsGrounded` param …
=> fix: instant cancel of scene emote on PBAvatar instantiation during local scene development

Explorer/Assets/DCL/Infrastructure/Global/Dynamic/BootstrapAnalyticsDecorator.cs, Explorer/Assets/DCL/Infrastructure/Global/Dynamic/Bootstraper.cs, Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs, Explorer/Assets/DCL/Infrastructure/Global/Dynamic/IBootstrap.cs, Explorer/Assets/DCL/Infrastructure/Global/Dynamic/MainSceneLoader.cs, Explorer/Assets/DCL/Input/Systems/UpdateShowHideUIInputSystem.cs, Explorer/Assets/DCL/PluginSystem/Global/InputPlugin.cs, Explorer/Assets/DCL/UI/WarningNotificationView.cs, Explorer/Assets/Scenes/Main.unity
Fixes #3456 
Adds a new canvas + notification prefab into the Main scene so it is not hidden by the hide UI feature.
The toast becomes visible when the user presses `U`.
Enter in-world. Press `U`. Check that the toast is shown. The toast should be hidden after 3 seconds or if you press `U` again.
=> feat: toast that restores the ui visibility

Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs, Explorer/Assets/DCL/Notifications/NotificationsMenu/NotificationsMenuController.cs, Explorer/Assets/DCL/PluginSystem/Global/NotificationPlugin.cs
Fixes #4903 
We are polling notifications over time, but it was continued even if we changed identity. Since it is a signed fetch, it was provoking an unauthorized error, by trying to use the old identity.
These changes cancel the polling whenever we clear identity. When we change it, we restart the polling.
Additionally the request to get the most recent notifications has been improved. It is now subscribed to the identity change event making it more consistent.
Start normally, enter the world and check you can see notifications in the side bar.
Logout and change the account. Enter world and check that you can see notifications in the side bar.
Also check that you can keep receiving notifications normally. …
=> fix: cancel notification polling on changing identity

Explorer/Assets/DCL/Character/CharacterMotion/Systems/TeleportPositionCalculationSystem.cs, Explorer/Assets/DCL/Infrastructure/ECS/SceneLifeCycle/TeleportUtils.cs, Explorer/Assets/DCL/MapRenderer/MapLayers/Categories/CategoryControllers/CategoryMarkersController.cs, Explorer/Assets/DCL/Navmap/INavmapCommand.cs, Explorer/Assets/DCL/Navmap/NavmapBus/INavmapBus.cs, Explorer/Assets/DCL/Navmap/NavmapBus/SharedNavmapBus.cs, Explorer/Assets/DCL/Navmap/NavmapCommandBus.cs, Explorer/Assets/DCL/Navmap/NavmapController.cs, Explorer/Assets/DCL/Navmap/PlaceInfoPanelController.cs, Explorer/Assets/DCL/Navmap/ShowPlaceInfoCommand.cs, Explorer/Assets/DCL/PluginSystem/Global/ExplorePanelPlugin.cs, Explorer/Assets/DCL/RealmNavigation/TeleportController.cs
Fixes #4302 
Check for the `Long Road` scene title to keep the original teleport coordinates.
Additionally the navmap passes the clicked coordinates to the places panel, so it can properly teleport if the destination is a road.
Teleport to any road. Spawn point should be the designed coordinates.
=> fix: keep roads teleport position

Explorer/Assets/DCL/Infrastructure/MVC/Manager/MVCManager.cs
Fix #4997 
Replaced foreach loop with inverse for loop, this ensures the correct order is followed when hiding popup views and prevents InvalidOperationException when iterating and a (parent) view asynchronously closes another (child) view.
Before, when opening a FullScreen window we iterated over the popup controllers hiding their views asynchronously.
This could lead to a InvalidOperationException during the loop because a view might close another view asynchronously when closing itself.
Also, this now works as intended, if a new fullscreen window is opened (i.e. Communities) all popups get closed correctly.
- Verify that pressing TAB when a community panel and/or context menu is open correctly closes the underlying UI but interaction with the panel / context menu is still possible.
- …
=> fix: User cannot interact with communities after TAB is pressed

Explorer/Assets/DCL/UI/Assets/UserNameElement.prefab
Fix [#4830](https://github.com/decentraland/unity-explorer/issues/4830)
Fixed user name copied toast not being displayed, by changing toast canvas drawing order
Check if upon coping the name toast is displayed in player and avatar's profiles
=> fix: user name copy not displaying toast

Explorer/Assets/DCL/MarketplaceCredits/Sections/MarketplaceCreditsWelcomeSubController.cs
Fixes #5158 
The issue was caused by a race condition between the "open" and "close" operations. The "open" operation asynchronously disables user input when it completes, while the "close" operation enables input again. If the "close" operation is triggered while the asynchronous "open" operation is still in progress, the late completion of the "open" flow could incorrectly disable user input even though the UI is already hidden. 
The solution involves canceling the operation responsible for fetching the program registration information when the UI is closed. This ensures that the "open" flow cannot disable user input once the UI has been closed, preventing scenarios where the avatar would become immobile due to disabled input.
1. Open the client with an account that is not registered …
=> fix: input blocked after closing the marketplace credits popup

Explorer/Assets/DCL/Communities/CommunitiesCard/Events/EventListItemView.cs
Fixes #5154 
This PR disables the activation of the counter of the amount of people interested in a given event of a community event in the community passport.
The prefab and logic are still present (as the whole community feature requirements are often changing), only the activation logic has been modified.
1. This can be also tested by checking already existing community events
2. Follow the steps described in the issue (if you go this route, you may want to test in `zone` since new events need approval)
- Can be tested in both `org` and `zone`
=> fix: disable event interested counter in community card

Explorer/Assets/DCL/AuthenticationScreenFlow/AuthenticationScreenController.cs, Explorer/Assets/DCL/Backpack/BackpackController.cs, Explorer/Assets/DCL/Character/CharacterPreview/CharacterPreviewControllerBase.cs, Explorer/Assets/DCL/Passport/PassportController.cs
Fixes #5182 
Changes add a new method `OnBeforeShow` to the avatar preview, that setups the view as loading and its called before the profile starts loading. This prevents the avatar's raw render image to be displayed with empty data.
Open the friends panel, and click on your friends. Check that the passport is open and you don't see a white rectangle.
=> fix: passport white rectangle while profile is loading

Explorer/Assets/DCL/AvatarRendering/Emotes/Components/Intents/GetEmotesByPointersIntention.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Components/Intents/GetSceneEmoteFromLocalSceneIntention.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Components/Intents/GetSceneEmoteFromRealmIntention.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Components/Intents/IEmoteAssetIntention.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Components/Intents/LoadTimeout.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/Load/LoadEmotesByPointersSystem.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/Load/LoadSceneEmotesSystem.cs, Explorer/Assets/DCL/AvatarRendering/Emotes/Systems/Play/CharacterEmoteSystem.cs, Explorer/Assets/DCL/Infrastructure/CrdtEcsBridge/RestrictedActions/GlobalWorldActions.cs, Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs, Explorer/Assets/DCL/PluginSystem/Global/EmotePlugin.cs
Fixes #5201 
Two main problems were found:
- The emote load intention was incorrectly created: the scene emote goes through the standard propagation process, including the multiplayer systems. When reaching the peer, since the emote was missing in the cache, the data was requested though pointers, which was never solved. The changes now identifies if the emote is from a scene and then make the load intention accordingly.
- The intention timeout was not working: the processing of the elapsed time was getting lost due to a temporal reference issue, thus the original reference was not getting impacted.
**TODO note**: local scene development mode is still missing this fix and will probably not work yet, at least if you are testing it with different machines. It is problematic to solve, …
=> fix: scene emote propagation

Explorer/Assets/DCL/PerformanceAndDiagnostics/Profiling/ECS/DebugViewProfilingSystem.cs
Fix #4891
When the app is not in focus the debug menu FPS metric will not update and will resume when back in focus.
Verify that when switching focus to another app, the FPS metric on the debug menu will stop updating and verify that when switching back to the app the fps metrics will resume updating
1. Open the app
2. Enable the debug menu with /debug and scroll down so the FPS metrics are visible
3. Move the cursor outside the app and select another app
4. Verify that the FPS metrics stop updating and display the last values
5. Move the cursor back to the app and select it 
6. Verify that the FPS metrics resume updating
7. Make sure to verify that this works on either Fullscreen and Windowed modes …
=> fix: adjust debug console FPS metric when E@ is out of focus

Explorer/Assets/DCL/Communities/CommunitiesCard/Members/MembersListView.cs, Explorer/Assets/DCL/Passport/PassportController.cs, Explorer/Assets/DCL/UI/Communities/CommunityChatConversationContextMenuSettings.asset, Explorer/Assets/DCL/UI/GenericContextMenu/Controllers/Communities/CommunityInvitationContextMenuButtonHandler.cs, Explorer/Assets/DCL/UI/GenericContextMenu/Controllers/GenericUserProfileContextMenuController.cs
It applies different offsets and paddings to the invitation to community submenus.
It fixes this bug: #5258 
You need a user that is owner/moderator of only 1 community.
1. Open a private conversation in the chat.
2. Open the context menu by clicking on the titlebar.
3. Open the Invite to Community option.
4. The submenu should have the expected height, as well as correct paddings.
1. Open the passport of another user.
2. Open the context menu by clicking on button at the top-right corner.
3. Open the Invite to Community option.
4. The submenu should have the expected height, as well as correct paddings.
1. Open a community that is not yours.
2. Open the context menu by clicking on the button of a member in the list.
3. Open the Invite to Community option.
4. The submenu should have the …
=> Fix: Context menu is way to big when there's only one community appearing

Explorer/Assets/DCL/UI/MainUIContainer/MainUIContainer.prefab, Explorer/Assets/DCL/UI/Sidebar/SidebarUI.BottomLayout.prefab, Explorer/Assets/DCL/UI/Sidebar/SkyboxWidget.prefab
fix [#4575](https://github.com/decentraland/unity-explorer/issues/4575)
Before:
Now:
Fixed skybox widget being misaligned on mac by setting correct anchors
Check if skybox widget is aligned correctly on mac with different resolutions.
=> fix: skybox widget misaligned on mac

Explorer/Assets/DCL/Notifications/Assets/SystemNotification.prefab
Fix #5294 
The warning message was not being adapted horizontally correctly.
Follow the STR in https://github.com/decentraland/unity-explorer/issues/5294
=> fix: Communities | Warning size message does not fit into the warning container

Explorer/Assets/DCL/AvatarRendering/Wearables/ApplicationParametersWearablesProvider.cs, Explorer/Assets/DCL/Backpack/EmotesSection/BackpackEmoteGridController.cs
Currently when curators test unreleased builder wearables, to be able to test those unreleased wearables and emotes with different bodyshapes they have to close and re-open the app because **default wearable/emotes don't appear in the Explorer** in that scenario.
Also currently they are unable to test wearables with the default emotes or in combination with other default wearables, as we are only showing the target collection elements in the backpack.
Issue: https://github.com/decentraland/unity-explorer/issues/5288
Refactored to consume all the available wearables for the user, to be shown in the backpack along with the target collection elements.
* To test this new feature you will need to create a collection in the wearables builder section of the marketplace at …
=> chore: builder wearables preview also show all wearables

Explorer/Assets/DCL/AssetsProvision/Contextual/ContextualImage.cs, Explorer/Assets/DCL/PluginSystem/Global/SidebarPlugin.cs, Explorer/Assets/DCL/UI/Controls/ControlsPanel.prefab, Explorer/Assets/DCL/UI/Controls/ControlsPanelController.cs, Explorer/Assets/DCL/UI/SharedSpaceManager/ISharedSpaceManager.cs, Explorer/Assets/DCL/UI/SharedSpaceManager/PanelsSharingSpace.cs, Explorer/Assets/DCL/UI/SharedSpaceManager/SharedSpaceManagerImpl/SharedSpaceManager.cs, Explorer/Assets/DCL/UI/Sidebar/SidebarController.cs
Fix [#4852](https://github.com/decentraland/unity-explorer/issues/4852)
Fixed overlap between the mouse and key controls and emote wheel by re-implementing that panel as IControllerInSharedSpace. 
Also fixed white box shown in space of controls image for a frame, by adding unloaded and loaded color for `ContextualImage`.
Panel in question for reference:
Check Controls panel with both its icon from side bar, and its shortcut `H`, and how it interacts with other panels. 
**Should hide:**
**Should NOT hide** (being shown on top of them):
This panel will not open from Passport panel.
=> fix: overlap between the mouse and key controls and emote wheel

Explorer/Assets/DCL/UI/SharedSpaceManager/SharedSpaceManagerImpl/SharedSpaceManager.cs
fix [#5337](https://github.com/decentraland/unity-explorer/issues/5337)
Fixed chat messages not being send, by returning old `SharedSpaceManager's` panels hiding, which I missed in last PR
=> fix: enter doesnt send chat message

Explorer/Assets/link.xml
Builder emote DTO code was being stripped; and we dont want this. This PR stops that from happening
1. Make sure the unreleased/builder emotes can be played, following the test steps from this other [PR](https://github.com/decentraland/unity-explorer/pull/5309)
=> fix: unwanted stripping of builder emote code

Explorer/Assets/DCL/Infrastructure/CrdtEcsBridge/JsModulesImplementation/Communications/SceneCommunicationPipe.cs, Explorer/Assets/DCL/Infrastructure/Global/Dynamic/DynamicWorldContainer.cs, Explorer/Assets/DCL/Multiplayer/Connections/Demo/GateKeeperRoomPlayground.cs, Explorer/Assets/DCL/Multiplayer/Connections/Demo/LocalSceneDevelopmentPlayground.cs, Explorer/Assets/DCL/Multiplayer/Connections/GateKeeper/Meta/ConstSceneRoomMetaDataSource.cs, Explorer/Assets/DCL/Multiplayer/Connections/GateKeeper/Meta/MetaData.cs, Explorer/Assets/DCL/Multiplayer/Connections/GateKeeper/Meta/SceneRoomMetaDataSource.cs, Explorer/Assets/DCL/Multiplayer/Connections/GateKeeper/Rooms/GateKeeperSceneRoom.cs, Explorer/Assets/DCL/Multiplayer/Connections/GateKeeper/Rooms/IGateKeeperSceneRoom.cs, Explorer/Assets/DCL/Multiplayer/Connections/Systems/Debug/DebugWidgetGateKeeperRoomDisplay.cs, Explorer/Assets/DCL/Multiplayer/Profiles/Poses/RemoteMetadata.cs
Fixes #5320
- We started to load LiveKit rooms in parallel with other start-up operations
- At the moment when the scene room has connected the scene object has not loaded yet leading to `scenesCache.TryGetByParcel(meta.Parcel, out connectedScene);` return `null` and set `ConnectedScene = null`. It's resolved only once when the connection string changes, preserving `null` until the player leaves the scene (changes the connection string)
- `IGateKeeperSceneRoom.IsSceneConnected`, thus, returns `false`
- It's accessed by `WriteRealmInfoSystem` which propagates `PBRealmInfo` to the JS scene only **once** when the corresponding data changes.
- The data doesn't change until `IslandSId` or `IsSceneConnected` changes
- On the JavaScript Side there is most likely reliance on the realm readiness …
=> Unbind GateKeeperSceneRoom from SceneCache

Explorer/Assets/DCL/PluginSystem/World/MediaPlayerPlugin.cs, Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/CreateMediaPlayerSystem.cs, Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerSystem.cs, Explorer/Assets/DCL/SDKComponents/MediaStream/Wrapper/MediaPlayerPluginWrapper.cs, Explorer/Packages/packages-lock.json
Fixes #4682 and #5266
Toggles the state of a livekit stream to control how we restart it.
We will lose the crossfade of the audio; since the livekit disconection flow is triggered as soon as we leave the scene, currently there is no way to ensure for how long the stream will be alive.
1. Go to `-133,-42` with a stream on. Check that if you leave the scene, see a room change, and re-enter; the stream works as expected withtout the glitching sound. 
=> fix: toggle stream on scene changed

Explorer/Assets/DCL/NotificationsBusController/NotificationTypes/CommunityDeletedContenViolationNotification.cs, Explorer/Assets/DCL/NotificationsBusController/NotificationTypes/CommunityDeletedNotification.cs, Explorer/Assets/DCL/NotificationsBusController/NotificationTypes/CommunityEventCreatedNotification.cs, Explorer/Assets/DCL/NotificationsBusController/NotificationTypes/CommunityRenamedNotification.cs, Explorer/Assets/DCL/NotificationsBusController/NotificationTypes/CommunityUserBannedNotification.cs, Explorer/Assets/DCL/NotificationsBusController/NotificationTypes/CommunityUserInvitedNotification.cs, Explorer/Assets/DCL/NotificationsBusController/NotificationTypes/CommunityUserRemovedNotification.cs, Explorer/Assets/DCL/NotificationsBusController/NotificationTypes/CommunityUserRequestToJoinAcceptedNotification.cs
Fixes #5390 
This PR modifies the text of the community notification in order to remove the square brackets surrounding the community names.
1. Open the app
2. Verify that all notifications related to community no longer have square brackets surrounding the community name
- This applies to new notification and old notification as well
=> fix: remove square brackets from community notification text

Explorer/Assets/DCL/Communities/CommunityCreation/CommunityCreationEditionController.cs, Explorer/Assets/DCL/Communities/CommunityCreation/CommunityCreationEditionView.cs
Fixes #5362 
This PR adds a clause to the construction of the moderation modal, preventing the reading of null data (avoids NRE). On top of that, it adds the checks of whitespace-only for the community name and description before submitting it for review. This is done to reflect the backend constraints: both name and description must have a non-null/empty values.
1. Follow the steps described in the linked issue and verify that you are no longer able to create a community with empty name/description
- If for some reason you are able to skip all the checks, the moderation modal should now be able to handle the case without exceptions
=> fix: prevent creation of community with no name/description and avoid NRE

Explorer/Assets/DCL/Backpack/Assets/Animations/Empty.anim, Explorer/Assets/DCL/Communities/CommunitiesBrowser/Animations/Empty.anim, Explorer/Assets/DCL/InWorldCamera/CameraReelGallery/Assets/Animations/Empty.anim, Explorer/Assets/DCL/Navmap/Assets/Animations/Navmap/Empty.anim, Explorer/Assets/DCL/Settings/Animations/Empty.anim
fix [#5336](https://github.com/decentraland/unity-explorer/issues/5336)
Fixed CanvasGroup keeping alpha value while spamming panel's shortcuts. This was happening because unity's animator locks values even if one particular state doesnt use it at all. 
So when we were spamming panels opening and closing animations, and it was interrupted in the middle, value stayed mid transition. I have fixed it, by adding default alpha value to Empty state.
Fixed it for all Explorer panels.
- Spam `O` and `M` keys. Panels should be fully visible, there should not be any darker overlay when fully opened.
- Check normal Explore panels opening.
=> fix: switching between communities and navmap glitches

Explorer/Assets/DCL/AvatarRendering/Wearables/Systems/Load/LoadWearablesByParamSystem.cs, Explorer/Assets/DCL/AvatarRendering/Wearables/Systems/Load/LoadWearablesDTOByPointersSystem.cs, Explorer/Assets/DCL/ECS/GlobalPartitioning/GlobalDeferredLoadingSystem.cs, Explorer/Assets/DCL/Infrastructure/ECS/Groups/LoadGlobalSystemGroup.cs, Explorer/Assets/DCL/Infrastructure/ECS/Groups/LoadGlobalSystemGroup.cs.meta, Explorer/Assets/DCL/Infrastructure/ECS/SceneLifeCycle/Debug/Systems/AbortSceneLoadingDebugSystem.cs, Explorer/Assets/DCL/Infrastructure/ECS/SceneLifeCycle/SceneDefinition/Systems/LoadSceneDefinitionListSystem.cs, Explorer/Assets/DCL/Infrastructure/ECS/SceneLifeCycle/SceneDefinition/Systems/LoadSceneDefinitionSystem.cs, Explorer/Assets/DCL/Infrastructure/ECS/SceneLifeCycle/SceneFacade/Systems/LoadSceneSystem.cs, Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/AssetBundles/LoadAssetBundleManifestSystem.cs, Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/AssetBundles/LoadGlobalAssetBundleSystem.cs, Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/AssetBundles/PrepareAssetBundleLoadingParametersSystem.cs, Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/AssetBundles/PrepareGlobalAssetBundleLoadingParametersSystem.cs, Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/DeferredLoading/AssetsDeferredLoadingSystem.cs, Explorer/Assets/DCL/Infrastructure/ECS/StreamableLoading/Textures/LoadGlobalTextureSystem.cs
The code generation that set up system ordering is not working properly. Therefore, we had a rrace condition between 
`PrepareGlobalAssetBundleLoadingSystem`
'GlobalDeferredSystem`
`LoadAssetBundleSystem`
That disorder can cause wearables not to load
To fix this, I packed the global systems in risks into a single group, therefore securing the order.
Just in case, I also resorted the world one, to secure the same order
System order in Global World
System order in Scene World
A smoke test of assets loading. So, everything
=> hotfix: Asset Bundle System Ordering

Explorer/Assets/DCL/UI/Sidebar/SidebarController.cs
Fixes #5468
This PR prevent the chat folding when any section of the explore panel is opened using the sidebar buttons.
1. Follow the steps described in the linked issue and verify that now it behaves as expected
=> fix: prevent chat folding when clicking sidebar button

Explorer/Assets/DCL/VoiceChat/Assets/CommunityVoiceChat/InCallHeader.prefab, Explorer/Assets/DCL/VoiceChat/Assets/CommunityVoiceChatSearch.prefab
This branch updates de color animation of the collapse/expand button and roundness of its container.
It also fixes the titles of the people's panel that were updated. Now `Request to speak` is `Requested to speak`, while `Listeners` is `Online`.
**AFTER**
https://github.com/user-attachments/assets/7f6fabff-675f-47fb-8740-0f16c9fe8f7d
2. Start a voice stream from any of the communities you moderate or own
3. Once the voice chat panel is opened, check the button is more rounded than before, arrows a bit smaller and the highlight color is not a strong as before.
4. Then press the people button in the title bar. Once the panel is opened, check the titles are updated.
=> style: update voice chat collapse/expand button animation and people's panel titles

Explorer/Assets/DCL/Chat/Commands/ReloadSceneChatCommand.cs, Explorer/Assets/DCL/Infrastructure/ECS/SceneLifeCycle/IScenesCache.cs, Explorer/Assets/DCL/Infrastructure/ECS/SceneLifeCycle/Systems/UpdateCurrentSceneSystem.cs, Explorer/Assets/DCL/Infrastructure/Global/Dynamic/PortableExperiences/ECSPortableExperiencesController.cs, Explorer/Assets/DCL/Infrastructure/Global/StaticContainer.cs, Explorer/Assets/DCL/Minimap/MinimapController.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Analytics/Systems/PlayerParcelChangedAnalyticsSystem.cs, Explorer/Assets/DCL/PerformanceAndDiagnostics/Profiling/ECS/UpdateProfilerSystem.cs, Explorer/Assets/DCL/SkyBox/SDKComponentState.cs, Explorer/Assets/DCL/SkyBox/SceneMetadataState.cs
I was this years old when I found out that when you change 60k lines of code in a PR, you can introduce bugs xD
So, the issue detected by Pravs and Juani is the following:
> Hey guys with Juani Molteni we just noticed, testing something unrelated, that basic interactions like pointer events are not working on scenes when you first teleport to them:
> Easiest example -> running [this test scene](https://github.com/decentraland/sdk7-test-scenes/tree/main/scenes/73%2C-8-animator-tests-shark) locally, as soon as you enter the scene directly, you can see that the shark is no longer clickable nor does its green outline for the hover feedback appear (attached video).
> If you walk out of the scene and re-enter it starts working as expected.
> Potentially this can be affecting any other features …
=> fix: Current scene is not updated properly after teleporting

Explorer/Assets/DCL/InWorldCamera/InWorldCamera/InWorldCameraComponents.cs, Explorer/Assets/DCL/InWorldCamera/InWorldCamera/Settings/InWorldCameraMovementSettings.cs, Explorer/Assets/DCL/InWorldCamera/InWorldCamera/Systems/EmitInWorldCameraInputSystem.cs, Explorer/Assets/DCL/InWorldCamera/InWorldCamera/Systems/MoveInWorldCameraSystem.cs, Explorer/Assets/DCL/Input/UnityInputSystem/DCLInput.cs, Explorer/Assets/DCL/Input/UnityInputSystem/DCLInput.inputactions
Fix #5232 
Implemented ctrl action to slow down camera movement. 
[Shift] doubles the speed, configured value for [Ctrl] halves the speed.
1. Open the camera [C].
2. Move the camera using the controls.
3. Hold [Shift] – observe the speed increases.
4. Hold [Ctrl] – observe that the speed does decrease.
- Multipliers are added independently so when holding both keys both multipliers are applied.
=> fix: camera ctrl does not slow movement

Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateMediaPlayerSystem.cs, Explorer/Assets/DCL/Settings/ModuleControllers/MasterVolumeSettingsController.cs, Explorer/Assets/DCL/Settings/ModuleControllers/WorldSoundsVolumeSettingsController.cs
Fixes #2294 
The volume control was disabled on windows. Fix removes any platform dependency on volume control.
Start explorer on windows.
Check video streams on different scenes, including live-stream. Volume should work correctly.
=> fix: enable stream volume control on windows

Explorer/Assets/DCL/Chat/Assets/Chat2.prefab, Explorer/Assets/DCL/VoiceChat/Assets/CommunityVoiceChat/InCallHeader.prefab, Explorer/Assets/DCL/VoiceChat/Assets/CommunityVoiceChat/PeopleButton.prefab, Explorer/Assets/DCL/VoiceChat/Assets/CommunityVoiceChat/PeopleButton.prefab.meta, Explorer/Assets/DCL/VoiceChat/Assets/CommunityVoiceChatInCallTitlebar.prefab, Explorer/Assets/DCL/VoiceChat/Assets/CommunityVoiceChatTitleBarsContainer.prefab, Explorer/Assets/DCL/VoiceChat/CommunityVoiceChat/CommunityVoiceChatController.cs, Explorer/Assets/DCL/VoiceChat/CommunityVoiceChat/CommunityVoiceChatInCallController.cs, Explorer/Assets/DCL/VoiceChat/CommunityVoiceChat/CommunityVoiceChatInCallView.cs, Explorer/Assets/DCL/VoiceChat/CommunityVoiceChat/CommunityVoiceChatSearchController.cs, Explorer/Assets/DCL/VoiceChat/Textures/HandIcon.png, Explorer/Assets/DCL/VoiceChat/Textures/HandIcon.png.meta
Fix #5504
This PR fixes all the inconsistencies in speakers/listeners count in community voice chat panel.
It also adds a small tooltip with the number of raised hand players in the people section as in the below pic:
this tooltip appears only if at least 1 user has his hand raised
1. Launch the client with --debug and --voice-chat
2. Start a voice stream
3. Check that the speakers count and listeners count update correctly based on connected people
4. Check that if someone raises the hand when in the main community voice chat panel the people button has a tooltip stating how many players raised their hand …
=> fix: fixed player count and added raise hand tooltip in people button in cvc

Explorer/Assets/DCL/Infrastructure/ECS/Unity/Textures/Components/VideoTextureConsumer.cs, Explorer/Assets/DCL/SDKComponents/MediaStream/Systems/UpdateVideoMaterialTextureScaleSystem.cs, Explorer/Assets/DCL/SDKComponents/MediaStream/Wrapper/MediaPlayerPluginWrapper.cs
As it is right now, we have a race condition where we can be setting the texture scale to a renderer which is gonna get its material replaced.
Since material creation is budgeted, this condition is quite possible in low frame rate condition
This PRs resorts the systems and budgets `UpdateScleVideoTextureSystem`; so it respects the same behaviour as the material creations
This is mainly a Windows test. Doesnt hurt to do it in Mac too
1. Test in Windows Art Week. Check that the video in the visitor center (`-139,-86`) is not flipped
2. Try out a stream (let me know and I can see to set one up). Check that its not flipped
3. Check the videos in Prom and Career Center. Once again, check that they are not flipped …
=> fix: check material state before setting the the texture scale

Explorer/Assets/DCL/WebRequests/Analytics/Plugin/ShowWebRequestsAnalyticsSystem.cs
Added explicit notification popup if CDP failed to launch
1. Uninstall Creator Hub
2. Try open CDP from Client
3. Observe error popup
4. Don't close the Client
5. Install Creator Hub
6. Try open CDP from Client again
7. CDP opens successfully
=> chore: CDP notifications on launch error

Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/CommunitiesBrowser_RightSection_MainView.prefab, Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/CommunitiesBrowser_RightSection_StreamingCommunitiesView.prefab
Fix #5391  
This PR changes the visual positioning of the voice streaming now section in the communities browser to follow properly the figma design
1. Launch the client with --debug and --voice-chat
2. Start a community voice stream
3. Go to the communities browser and verify that the "voice streaming now" title is properly alligned like the following screenshot
=> fix: allignement of voice streaming now title in community browser

Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesBrowserController.cs, Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesBrowserFilteredCommunitiesPresenter.cs, Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesBrowserMainRightSectionPresenter.cs, Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesBrowserMyCommunitiesPresenter.cs, Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesBrowserRightSectionMainView.cs, Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunityResultCardView.cs, Explorer/Assets/DCL/Communities/CommunitiesBrowser/FilteredCommunitiesView.cs, Explorer/Assets/DCL/Communities/CommunitiesBrowser/MyCommunitiesView.cs, Explorer/Assets/DCL/Communities/CommunitiesBrowser/MyCommunityCardView.cs, Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/CommunityResultCard.prefab, Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/MyCommunityCard.prefab, Explorer/Assets/DCL/Communities/CommunitiesBrowser/Prefabs/StreamingCommunityResultCard.prefab, Explorer/Assets/DCL/Communities/CommunitiesBrowser/StreamingCommunitiesView.cs, Explorer/Assets/DCL/Communities/CommunitiesBrowser/StreamingCommunityResultCardView.cs
Fix #5448
This PR introduces the listening label in community cards in the communities browser when you are already connected to a stream and check that panel, like in the following screenshot:
1. Open the client with --debug and --voice-chat
2. Start a community voice chat
3. Go to the community panel
4. Verify that, like in the screenshot above, the card of the community you are currently talking in has the listening icon or listening text
=> fix: added listening status in community browser when already connected to a cvc

Explorer/Assets/DCL/Communities/CommunitiesDataProvider/DTOs/GetCommunityResponse.cs, Explorer/Assets/DCL/Communities/CommunitiesDataProvider/DTOs/GetUserCommunitiesResponse.cs, Explorer/Assets/DCL/Communities/CommunitiesDataProvider/DTOs/VoiceChatStatusJsonConverter.cs, Explorer/Assets/DCL/Communities/CommunitiesDataProvider/DTOs/VoiceChatStatusJsonConverter.cs.meta
Fix #5546 
This PR is needed due to a change in BE, when a community is private and we are not part of it the voice chat status is sent to null, this was breaking serialization, this has been fixed by handling the null as a non active voice chat status in serialization.
1. Launch both clients with --debug and --voice-chat in .zone environment
2. With the user inside the private community start a community voice chat
3. With the other user go to the community browser and verify that in the list of communities you don't see the streaming status of the private community you are not part of
=> fix: handle null voice chat status in communities response

Explorer/Assets/DCL/Communities/CommunitiesBrowser/CommunitiesInvitesAndRequestsView.cs
Fix #5661 
Avoids displaying the listening indicator in the communities under invites and requests
1. Launch the client with --debug and --voice-chat
2. Go to the communities tab
3. Go to invites and requests
4. Verify that the communities results do not show the listening indicator
=> fix: avoid showing listening header in invites and request communities

scripts/cloudbuild/build.py
When making a new PR, we have been creating a new target on unity cloud which meant we had to reimport whole library.
With this change, for new builds we will share the cache from development target. 
This way we can reduce the first build from around 1h30 minutes to 30-40 minutes depending on the changes.
=> chore: using dev cache for new target

Explorer/Assets/DCL/Chat/ChatEntryUsernameElement.cs, Explorer/Assets/DCL/Chat/ChatEntryView.cs, Explorer/Assets/DCL/Chat/History/ChatMessageFactory.cs, Explorer/Assets/DCL/Chat/_Refactor/ChatCommands/CreateMessageViewModelCommand.cs, Explorer/Assets/DCL/Chat/_Refactor/ChatViewModels/ChatMessageViewModel.cs, Explorer/Assets/DCL/UI/Profiles/ProfileElements/ProfileOptionalBasicInfo.cs, Explorer/Assets/DCL/UI/Profiles/ProfileElements/ProfileOptionalBasicInfo.cs.meta
Fixes #4353
Fixes #5076 
Fixes #5555 
This PR expands what the `ChatMessageViewModel` carries with some basic profile information. Now when a chat message is displayed and the profile is not in the cache, a placeholder string is displayed in the sender name, so that when the profile is actually fetched, both the thumbnail and claimed name (or wallet address) are correctly retroactively updated (during this loading, the message entry is not interactable: no context menu).
This prevents having chat messages rendered in a "broken" state as described in the lined issues.
This can be further improved by using livekit participant metadata like in voice chat, but its implementation is a big rabbit hole and it also could be done in such a way that could modify how we approach Profiles in general, …
=> fix: handle missing profile on chat message
